signalfx/splunk-otel-collector

- go.mod
- pkg/extension/smartagentextension/go.mod
- pkg/receiver/smartagentreceiver/go.mod
Bump version references to inter-project modules (i.e. v0.83.0).  Note: this is for cosmetic reasons primarily, because of the `go.mod` "rewrite" directives that rewrite any reference to these modules to be relative to the current directory.
> Bump all inter-module references to latest version (v0.83.0)

- tests/go.mod
- tests/testutils/telemetry/common.go
- tests/testutils/telemetry/logs.go
- tests/testutils/telemetry/logs_test.go
- tests/testutils/telemetry/metrics.go
- tests/testutils/telemetry/metrics_test.go
- tests/testutils/telemetry/pdata_common.go
- tests/testutils/telemetry/testdata/logs/expected-logs.yaml
- tests/testutils/telemetry/testdata/logs/resource-logs.yaml
- tests/testutils/telemetry/testdata/metrics/expected-metrics.yaml
- tests/testutils/telemetry/testdata/metrics/resource-metrics.yaml
These changes add support for using the testutils directives for nested attributes, which are currently limited to root level maps. They will be necessary to vet entity events that embed endpoint information in an `otel.entity.attributes` log record attribute.
> testutils: add nested directive expansion to logs and metrics

- .github/workflows/chef-test.yml
- deployments/chef/kitchen.windows.yml
- deployments/chef/kitchen.yml
- deployments/chef/test/integration/custom_vars/inspec/custom_vars_spec.rb
- deployments/chef/test/integration/custom_vars/serverspec/spec_helper.rb
- deployments/chef/test/integration/default/inspec/default_spec.rb
- deployments/chef/test/integration/default/serverspec/spec_helper.rb
- deployments/chef/test/integration/with_custom_dotnet_instrumentation/inspec/with_custom_dotnet_instrumentation_spec.rb
- deployments/chef/test/integration/with_default_dotnet_instrumentation/inspec/with_default_dotnet_instrumentation_spec.rb
- deployments/chef/test/integration/with_instrumentation/inspec/with_instrumentation_spec.rb
- deployments/chef/test/integration/with_instrumentation/serverspec/spec_helper.rb
- deployments/chef/test/windows/Dockerfile.windows-2019
- deployments/chef/test/windows/Dockerfile.windows-2022
- deployments/chef/test/windows/spec_helper.rb
Convert chef tests from serverspec to inspec.
Follow-up to https://github.com/signalfx/splunk-otel-collector/pull/3606#issuecomment-1711945223.
> Fix chef tests

- deployments/ansible/roles/collector/tasks/win_fluentd_install.yml
- deployments/chef/attributes/default.rb
- deployments/puppet/manifests/init.pp
- deployments/puppet/manifests/params.pp
- internal/buildscripts/packaging/choco/splunk-otel-collector/tools/fluentd.ps1
- internal/buildscripts/packaging/installer/install.ps1
Changed fluentd url to download directly from https://s3.amazonaws.com/packages.treasuredata.com for windows, instead of being redirected from https://packages.treasuredata.com.
https://packages.treasuredata.com was recently updated to TLS 1.3, which is unsupported on [Windows 2012](https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-).
> Update fluentd url for windows

- internal/buildscripts/packaging/installer/install.sh
- internal/buildscripts/packaging/tests/installer_test.py
- Always include the `splunk.zc.method=splunk-otel-auto-instrumentation-<version>` resource attribute in `/usr/lib/splunk-instrumentation/instrumentation.conf` if installing with auto-instrumentation
- Enhance output for usage, info, and warnings
- Update installer script test
> Add splunk.zc.method attribute to linux installer script

- internal/buildscripts/packaging/installer/install.ps1
- internal/buildscripts/packaging/installer/install.sh
Add warnings regarding the change of default value from `0.0.0.0` to `127.0.0.1` in installers.
This logs a message when the value of the listen interface is set to `0.0.0.0` during installation, on Linux and Windows, in preparation of incoming changes to installer default values.
> Add warnings regarding the change of default value from 0.0.0.0 to 127.0.0.1 in installers

- examples/prometheusexec-migration/Dockerfile
The `prometheusexec` receiver was removed in 0.83.0, which breaks the ["pre-migration" example](https://github.com/signalfx/splunk-otel-collector/blob/main/examples/prometheusexec-migration/README.md?plain=1#L6).
> Revert "Bump signalfx/splunk-otel-collector (#3600)"

- .gitlab-ci.yml
- internal/signalfx-agent/bundle/scripts/build.sh
- No need to export local cache in gitlab
- Ensure local cache is exported and saved if there are changes in github
> Update bundle caching in CI to save time and disk space

- .github/workflows/win-package-test.yml
- internal/buildscripts/packaging/installer/install.ps1
- tests/zeroconfig/windows/testdata/resource_traces/aspnetcore.yaml
- tests/zeroconfig/windows/testdata/resource_traces/aspnetfx.yaml
Set `HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\SIGNALFX_GLOBAL_TAGS` with `splunk.zc.method:signalfx-dotnet-tracing-<version>` when installing `with_dotnet_instrumentation`.
> Include splunk.zc.method attribute for windows installer script

- pkg/extension/smartagentextension/README.md
Current urls are failing lychee test: https://github.com/signalfx/splunk-otel-collector/actions/runs/6314653816
Not sure if these new urls are the best replacements.
> Update SA extension links

- .github/workflows/lychee.yml
- .lychee.toml
Don't fail the lychee job for references in the changelog.
> Exclude pulsarexporter from link checker

- .github/workflows/darwin-test.yml
Also, remove the `macos-11-arm64` runner from the job to unblock PRs since it is currently inaccessible.
> Use macos-13 amd64 and arm64 runners

- deployments/ansible/README.md
- deployments/ansible/roles/collector/README.md
- deployments/ansible/roles/collector/tasks/linux_install.yml
- deployments/ansible/roles/collector/templates/splunk-otel-collector.conf.j2
This patch is adding the ability to pass splunk_hec_token so that logs can be ingested into Splunk Cloud.
> Allow passing splunk_hec_token for log ingestion into Splunk Cloud to work.

- README.md
Fixing 2 links which points to a broken Ansible-Galaxy page.
before:
after:
nothing
see Pictures
Nothing
> Update 2 link to Ansible-Galaxy

- go.mod
- go.sum
For twistlock PRISMA-2023-0046, supposedly fixed in https://github.com/go-resty/resty/commit/ad31b9fcf1193265a136269da03559a30884efb5
> Update github.com/go-resty/resty/v2 to v2.9.1

- CHANGELOG.md
- docs/getting-started/linux-installer.md
- internal/buildscripts/packaging/installer/install.sh
- internal/buildscripts/packaging/tests/images/deb/Dockerfile.debian-bookworm
- internal/buildscripts/packaging/tests/installer_test.py
These changes add debian 12 to the installer allowlist and packaging tests.
> Add debian 12 support to installer

- internal/signalfx-agent/pkg/core/config/config.go
- internal/signalfx-agent/pkg/core/config/config_test.go
- internal/signalfx-agent/pkg/core/config/writer.go
- internal/signalfx-agent/pkg/utils/strings.go
The `initialize` methods are not called, removing them as well as dependent methods.
> remove initialize methods on Config and WriterConfig, as well as its dependent methods

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
This adds the loadbalancingexporter to the Splunk distribution.
**Link to Splunk idea:** https://ideas.splunk.com/ideas/SFXIMMID-I-553
> Add loadbalancingexporter to distro

- .github/workflows/cla.yml
Adds a CLA action to run for any new PR to make sure we identify and request CLA signature ahead of contributions from others. This rollout is a general rollout across splunk and signalfx repositories.
> Add CLA action

- go.mod
- go.sum
See https://github.com/signalfx/splunk-otel-collector/actions/runs/6590014412/job/17905738050#step:3:29
This fixes exposure to GHSA-fr2g-9hjm-wr23. Note that this vulnerability is not exploitable with our program as we don't expose this functionality.
> Fix nats-server vulnerability

- cmd/otelcol/config/collector/config.d.linux/receivers/oracledb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/oracledb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/oracledb.discovery.yaml.tmpl
- tests/receivers/oracledb/bundled_test.go
- tests/receivers/oracledb/testdata/resource_metrics/bundled.yaml
Discovery bundled testing for oracle was relying on an `endpoint` definition. We can remove this to better test discovery
> Oracledb discovery tweaks (remove static endpoint)

- .github/workflows/cla.yml
Add the bot account used to open and manage PRs to the allowlist associated with the CLA.
> add srv-gh-o11y-gdi to allowlist

- internal/signalfx-agent/pkg/core/common/httpclient/http_test.go
- internal/signalfx-agent/pkg/core/config/config_test.go
- internal/signalfx-agent/pkg/core/config/filters_test.go
- internal/signalfx-agent/pkg/core/config/sources/vault/auth/gcp.go
- internal/signalfx-agent/pkg/core/dpfilters/filter.go
- internal/signalfx-agent/pkg/core/propfilters/filter_test.go
- internal/signalfx-agent/pkg/monitors/cloudfoundry/conversion.go
- internal/signalfx-agent/pkg/monitors/helpers_test.go
- internal/signalfx-agent/pkg/monitors/postgresql/monitor.go
- internal/signalfx-agent/pkg/monitors/processlist/processlist_linux_test.go
- internal/signalfx-agent/pkg/monitors/prometheusexporter/conversion.go
- internal/signalfx-agent/pkg/monitors/subproc/core.go
- internal/signalfx-agent/pkg/monitors/telegraf/common/emitter/emitter.go
- internal/signalfx-agent/pkg/monitors/types/output.go
- internal/signalfx-agent/pkg/monitors/vsphere/service/inventory_test.go
- internal/signalfx-agent/pkg/monitors/vsphere/service/multi_perf_fetcher_test.go
- internal/signalfx-agent/pkg/monitors/vsphere/service/util_test.go
- internal/signalfx-agent/pkg/utils/filter/filter.go
- internal/signalfx-agent/pkg/utils/filter/filter_test.go
- internal/signalfx-agent/pkg/utils/filter/overridable_test.go
- First PR for the easy lint updates to support bumping the golangci-lint version.
- A second PR will come out with less easy updates that will be needed which will involve updating prometheus exporter code.
> Simple lint fixes to help support newer version of  github.com/golangci/golangci-lint in /internal/tools

- internal/buildscripts/packaging/installer/install.sh
From https://github.com/signalfx/splunk-otel-collector/pull/3841#discussion_r1370858777
We should not exit on usage output directly, but in the calling script so we can exit 1.
> do not exit in usage, so exit 1 can trigger

- instrumentation/packaging/fpm/rpm/build.sh
- internal/buildscripts/packaging/fpm/rpm/build.sh
Currently, the rpm packages built and released to our test repos in artifactory from the `main` branch have `~post` appended to the version. However, the `~` in the version forces the sorting to be lower than previously released packages with the same base version, i.e. `0.86.0~post` < `0.86.0`. Use `_post` instead to enforce the correct sorting order for test packages.
> Use underscore for rpm test packages

- .github/workflows/build-and-test.yml
- .github/workflows/darwin-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/win-package-test.yml
Fixes a typo in the filename used in github workflows.
> fix makefile path typo in github workflows

- cmd/otelcol/config/collector/ecs_ec2_config.yaml
- cmd/otelcol/config/collector/fargate_config.yaml
otlp metric receiver was never incorporated, likely as an oversight.
> add otlp receiver to ecs metric pipelines

- README.md
- cmd/otelcol/config/collector/logs_config_linux.yaml
Adds a new example configuration file for the collector, this one specifically for collecting logs on Linux hosts.
> Example configuration for logs on Linux.

- Makefile.Common
Change Makefile so `make binaries-windows_amd64` runs clean on Windows. This is the same fix done on contrib to avoid errors while running `make` on Windows.
N/A
**Testing:**
- Ran it locally (only validated the target `binaries-windows_amd64`.
N/A
> Run make binaries-windows_amd64 clean on Windows

- tests/testutils/telemetry/common.go
- tests/testutils/telemetry/common_test.go
These changes add invalid re2 attribute key names to the panic to make invalid patterns easier to find.
**Testing:**
Added missing unit tests for happy and error path.
> testutils: log attr key for re2 compilation failure

- CHANGELOG.md
- internal/buildscripts/packaging/installer/install.sh
Since the new `libsplunk.so` will no longer generate the service name (the instrumentation agents will handle it) or the `splunk.linux-autoinstr.executions` metric, the `--[no-]generate-service-name` and `--[enable|disable]-telemetry` options will no longer be applicable.
> Mark old instrumentation options as deprecated in installer script usage

- CHANGELOG.md
- docs/getting-started/linux-installer.md
- internal/buildscripts/packaging/installer/install.sh
Instead of using flags per language, condense the instrumentation SDK selection using a `--with[out]-instrumentation-sdk` flag.
> Change installer flag to use `--with[out]-instrumentation-sdk`

- tests/general/discoverymode/k8s_observer_discovery_test.go
- tests/receivers/discovery/k8s_observer_test.go
- tests/receivers/smartagent/collectd-mysql/bundled_test.go
- tests/receivers/smartagent/postgresql/bundled_test.go
- tests/testutils/kubeutils/kind_cluster.go
- tests/testutils/kubeutils/kind_cluster_integration_test.go
These changes add a `kubectl delete -f` helper to the kind cluster, relocating the previous `cluster.Delete()` to `cluster.Teardown()`
**Testing:**
Add testutils integration and update existing.
> testutils: update cluster.Delete() for manifests

- CHANGELOG.md
- pkg/receiver/smartagentreceiver/receiver.go
- pkg/receiver/smartagentreceiver/receiver_test.go
These changes make sure that `JAVA_HOME` is only set in the smart agent receiver if currently unset. This breaking change will avoid the scenario where the jmx receiver's target java version isn't configurable otherwise.
Since this is a bug fix I haven't documented more than a changelog entry but appreciate suggestions.
> Respect JAVA_HOME in smartagent receiver

- tests/general/discoverymode/k8s_observer_discovery_test.go
- tests/receivers/discovery/k8s_observer_test.go
- tests/receivers/smartagent/collectd-mysql/bundled_test.go
- tests/receivers/smartagent/postgresql/bundled_test.go
- tests/testutils/kubeutils/manifests/cluster_role_binding.go
- tests/testutils/kubeutils/manifests/cluster_role_binding_test.go
- tests/testutils/kubeutils/manifests/cluster_role_test.go
- tests/testutils/kubeutils/manifests/config_map_test.go
- tests/testutils/kubeutils/manifests/deployment.go
- tests/testutils/kubeutils/manifests/deployment_test.go
- tests/testutils/kubeutils/manifests/manifest.go
- tests/testutils/kubeutils/manifests/manifest_test.go
- tests/testutils/kubeutils/manifests/namespace.go
- tests/testutils/kubeutils/manifests/namespace_test.go
- tests/testutils/kubeutils/manifests/service.go
- tests/testutils/kubeutils/manifests/service_account.go
- tests/testutils/kubeutils/manifests/service_account_test.go
- tests/testutils/kubeutils/manifests/service_test.go
These changes add deployment, service, and namespace manifest helpers while also moving validation error checks to the `Render()` method. They also add a new `RenderAll()` helper to avoid boilerplate for creating multiple resources.
> testutils: add more manifest types and rendering improvements

- internal/confmapprovider/discovery/README.md
- internal/confmapprovider/discovery/discoverer.go
- tests/general/discoverymode/host_observer_discovery_test.go
- tests/general/discoverymode/testdata/host-observer-config.d/receivers/internal-prometheus.discovery.yaml
- tests/receivers/smartagent/postgresql/bundled_test.go
Adding option for arbitrary env var to authenticate for dbs on discovery mode
**Link to Splunk idea:** 
> Support confmap providers in discovery config

- instrumentation/Makefile
- instrumentation/tests/java/test.sh
- instrumentation/tests/nodejs/test.sh
Fix for `WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested` when running `make tests`.
> Fix instrumentation tests for arm64

- tests/general/discoverymode/k8s_observer_discovery_test.go
- tests/receivers/discovery/k8s_observer_test.go
- tests/receivers/smartagent/collectd-mysql/bundled_test.go
- tests/receivers/smartagent/postgresql/bundled_test.go
- tests/testutils/kubeutils/kind_cluster.go
These changes add a new kind cluster method to avoid boilerplate in finding running pods. They also make sure that all the expected control plane pods are running before returning from `cluster.Create()` to avoid race conditions when evaluating telemetry from the control plane.
> testutils: add cluster.WaitForPods()

- .gitlab-ci.yml
Combine the deb/rpm release and metadata signing jobs to help reduce the time that the apt/yum artifactory repos are unsigned.
> Combine deb/rpm release gitlab jobs

- deployments/cloudfoundry/bosh/DEVELOPMENT.md
- deployments/cloudfoundry/bosh/jobs/splunk-otel-collector/spec
- deployments/cloudfoundry/bosh/jobs/splunk-otel-collector/templates/splunk-otel-collector.conf.erb
- deployments/cloudfoundry/tile/tile.yml
The NO_PROXY environment variable was previously not being set properly by the Tanzu Tile configuration option. This was because the input variable's name was being automatically converted from otel_proxy_no to otel_proxy_false internally, but the variable setting logic was still checking otel_proxy_no. Change name to otel_proxy_exclusions to avoid this.
Manually tested both the BOSH job and Tanzu Tile to ensure changes work properly.
Added some more
> [Tanzu Tile] Fix proxy exclusions bug

- deployments/salt/README.md
- deployments/salt/splunk-otel-collector/auto_instrumentation.sls
- internal/buildscripts/packaging/tests/deployments/salt/salt_test.py
- Support new java config for `splunk-otel-auto-instrumentation` v0.87.0
- Support auto instrumentation for systemd
- Add the `splunk.zc.method=splunk-otel-auto-instrumentation-<version>[-systemd]` resource attribute
- Add tests for default and custom options, for both the preload and systemd methods
- TODO: Add node.js support
> salt: Support new zero config

- CHANGELOG.md
Updates changelog with all relevant updates to the Splunk, Contrib, and Core distributions of the OpenTelemetry Collector.
Release is blocked by #3921
> Prepare release v0.88.0

- instrumentation/tests/java/Dockerfile
Remove a line that was not needed and had a typo, and remove an empty Makefile.
> fix some cruft in the java zero-config tests

- tests/helm/helm_test.go
The incompatible `opencensus.resourcetype` disabling rule was removed in 0.87.0 release so we can use default values.
> helm test: remove cleared clusterReceiver rattrs

- deployments/cloudfoundry/tile/DEVELOPMENT.md
In PR #3902 I changed the variable name from otel_proxy_no to otel_proxy_exclusions. This change updates a documentation reference to point to the proper variable name.
> [chore] Update documentation example with proper variable name

- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
**Description:**  Adds support for the [mongodb](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mongodbreceiver) receiver from the [opentelemetry contrib repo](https://github.com/open-telemetry/opentelemetry-collector-contrib). 
**Testing:** components_test.go has been updated to reflect these changes
**Documentation:** components.md has been updated to show the new component
> added mongodb receiver from collector contrib

- internal/signalfx-agent/pkg/monitors/processlist/processlist_windows.go
- internal/signalfx-agent/pkg/monitors/processlist/processlist_windows_test.go
The duration to compute the "Status" of Windows processes is the bottle neck of the `processlist` monitor on Windows. This change delegates the evaluation of the thread status to the WMI query reducing the amount of data marshalled back to golang. On my dev box this reduced memory and cpu usage, the duration was reduced to about 30% of the original code.
N/A
**Testing:**
Updated the tests.
N/A
> Reduce CPU usage to get process "Status" on Windows

- internal/signalfx-agent/pkg/monitors/collectd/marathon/marathon.go
Marathon is no longer maintained ; this plugin will eventually be removed at a later date.
This PR adds a warning log when the monitor starts to warn users that this plugin is now deprecated.
> Deprecate marathon

- internal/signalfx-agent/bundle/collectd-plugins.yaml
Remove the collectd-mesos plugin, as it is not registered as a monitor nor used by another monitor.
> remove mesos collectd dependency

- .github/workflows/ansible.yml
- deployments/ansible/CHANGELOG.md
- deployments/ansible/galaxy.yml
- deployments/ansible/molecule/with_instrumentation/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_custom/Dockerfile.j2
- deployments/ansible/molecule/with_instrumentation_preload_custom/converge.yml
- deployments/ansible/molecule/with_instrumentation_preload_custom/molecule.yml
- deployments/ansible/molecule/with_instrumentation_preload_custom/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_default/Dockerfile.j2
- deployments/ansible/molecule/with_instrumentation_preload_default/converge.yml
- deployments/ansible/molecule/with_instrumentation_preload_default/molecule.yml
- deployments/ansible/molecule/with_instrumentation_preload_default/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_custom/Dockerfile.j2
- deployments/ansible/molecule/with_instrumentation_systemd_custom/converge.yml
- deployments/ansible/molecule/with_instrumentation_systemd_custom/molecule.yml
- deployments/ansible/molecule/with_instrumentation_systemd_custom/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_default/Dockerfile.j2
- deployments/ansible/molecule/with_instrumentation_systemd_default/converge.yml
- deployments/ansible/molecule/with_instrumentation_systemd_default/molecule.yml
- deployments/ansible/molecule/with_instrumentation_systemd_default/verify.yml
- deployments/ansible/roles/collector/README.md
- deployments/ansible/roles/collector/defaults/main.yml
- deployments/ansible/roles/collector/tasks/linux_auto_instrumentation.yml
- deployments/ansible/roles/collector/tasks/linux_install.yml
- deployments/ansible/roles/collector/tasks/win_install_dotnet_auto_instrumentation.yml
- deployments/ansible/roles/collector/templates/00-splunk-otel-auto-instrumentation.conf.j2
- deployments/ansible/roles/collector/templates/java.conf.j2
- deployments/ansible/roles/collector/templates/ld_so_preload.j2
- See `deployments/ansible/CHANGELOG.md` for changes
- Add the `splunk.zc.method=splunk-otel-auto-instrumentation-<version>[-systemd]` resource attribute
- Add tests for default and custom options, for both the preload and systemd methods
- TODO: Add node.js support
> ansible: Support new zero config

- cmd/translatesfx/README.md
- cmd/translatesfx/doc.go
- cmd/translatesfx/main.go
- cmd/translatesfx/translatesfx/doc.go
Add a notice statement when executing translatesfx and a few deprecation notices on the translatesfx tooling to indicate that it is now deprecated and will eventually be removed.
> mark translatesfx as deprecated

- CHANGELOG.md
- cmd/otelcol/Dockerfile.windows
- cmd/otelcol/main_windows.go
- cmd/otelcol/main_windows_test.go
Fix run as a service detection on Windows. Instead of trying to detect if it is a service or not, for which both `svc.IsAnInteractiveSession()` and `svc.IsWindowsService()` are somehow broken, try to run as a Windows service, if it fails fallback to run as an interactive process. This will add a small cost, which on my machine is under 5 microseconds, to startup in the interactive mode compared to using the `NO_WINDOWS_SERVICE` environment variable. While this value seems fine for startup I'm keeping the `NO_WINDOWS_SERVICE` option instead of deprecating it (it doesn't seem worth the trouble of deprecating it).
N/A
**Testing:**
Added benchmark to measure the cost of trying to start as a service (notice that when running as a service there is no …
> Fix run as service detection

- instrumentation/tests/java/test.sh
- instrumentation/tests/nodejs/test.sh
Continuation of #4000 - somehow pushes are ignored if using rebase.
> Fix use of grep -v

- internal/signalfx-agent/pkg/monitors/collectd/cpu/cpu.go
Officially deprecate the `collect/cpu` plugin in favor of the `cpu` monitor. The `collectd/cpu` plugin will be removed in a future release of the collector.
The `collectd/cpu` plugin was originally marked as deprecated in Jan 2020 with https://github.com/signalfx/signalfx-agent/pull/1147.
> deprecate collect/cpu explicitly

- .github/workflows/auto-instrumentation.yml
- CHANGELOG.md
- docs/getting-started/linux-installer.md
- docs/getting-started/linux-manual.md
- instrumentation/README.md
- instrumentation/packaging/fpm/etc/splunk/zeroconfig/node.conf
- instrumentation/packaging/fpm/examples/systemd/00-splunk-otel-auto-instrumentation.conf
- internal/buildscripts/packaging/installer/install.sh
- internal/buildscripts/packaging/tests/installer_test.py
- internal/buildscripts/packaging/tests/instrumentation/instrumentation_test.py
- internal/buildscripts/packaging/tests/instrumentation/libsplunk-node-test.conf
- Update `NODE_OPTIONS` to `-r /usr/lib/splunk-instrumentation/splunk-otel-js/node_modules/@splunk/otel/instrument` in the ZC config files
- Update installer script to install `splunk-otel-js` with `cd /usr/lib/splunk-instrumentation/splunk-otel-js && npm install` instead of `--global`
- Replace the `--npm-command` installer script option with `--npm-path`
- Update docs and tests
> Update installation prefix for splunk-otel-js

- cmd/migratecheckpoint/log_library.go
- cmd/migratecheckpoint/main.go
**Description:** Migrating offsets from SCK to SCK-Otel doesn't work. This is because of incorrect keys we use to populate the boltdb cache. 
The proper keys should be
`file_input.knownFiles`, `journald_input.lastReadCursor`
But we prepend `$.` to them and it causes log replication. 
Refer [scoped persister](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.88.0/pkg/stanza/operator/persister.go#L30-L38) for the current format.
~~**Note: I'm currently in the process of testing this on my Mac. I'd appreciate you're review on this by then**~~
Testing: Manually tested it on SCK and SCK-OTeL with locally built image
> fix: use proper key formating as per stanza persister

- CHANGELOG.md
> v0.91.0 changelog

- cmd/otelcol/config/collector/agent_config.yaml
- cmd/otelcol/config/collector/gateway_config.yaml
- tests/general/default_config_test.go
These changes update two endpoints (one in both the agent and gateway configs) to source the `SPLUNK_LISTEN_INTERFACE` env var. They should resolve issues associated with listening on non-default addresses like missing internal metrics issues on the gateway. 
**Testing:**
Updated the existing cases* to exercise the env var flow for three conditions including the default, "all interfaces", and an additional loopback ip.
> source SPLUNK_LISTEN_INTERFACE on all host endpoints

- internal/signalfx-agent/bundle/Dockerfile
Fixes agent bundle builds due to expired gpg key for the mysql apt repo.
> Update mysql repo gpg key

- internal/buildscripts/packaging/installer/install.sh
- internal/buildscripts/packaging/tests/installer_test.py
Also, create the `node_modules` subdir under `/usr/lib/splunk-instrumentation/splunk-otel-js` since some npm versions/configurations require it for local installs.
> linux installer script: use --global=false for npm

- internal/receiver/lightprometheusreceiver/scraper.go
Add capture of start timestamp to metrics expressed by the lightprometheusreceiver.
**Testing:**
Can add tests once https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29718 is implemented.
> add start timestamps

- internal/configconverter/loglevel_to_verbosity.go
- internal/configconverter/loglevel_to_verbosity_test.go
- internal/configconverter/testdata/logging_loglevel-after.yaml
- internal/configconverter/testdata/logging_loglevel.yaml
- internal/settings/settings.go
- internal/settings/settings_test.go
Add a converter that takes loglevel and translates it over to verbosity.
> Convert loglevel to verbosity on logging exporter

- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
Adds the AWS s3 exporter to the Splunk distribution
https://ideas.splunk.com/ideas/SFXIMMID-I-389
https://ideas.splunk.com/ideas/SFXIMMID-I-548
> Add AWS s3 exporter

- .gitlab-ci.yml
- deployments/puppet/Dockerfile
Fixes https://github.com/signalfx/splunk-otel-collector/actions/runs/7242168501/job/20136916554?pr=4086
> Fix bundler gem install, specify version explicitly

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/ecs/ecs.go
- internal/signalfx-agent/pkg/monitors/ecs/ecs_test.go
- internal/signalfx-agent/pkg/neotest/output.go
These changes add a `dimensionToUpdate` config field to the ecs-metadata monitor to allow configuring dimension updates on either the `container_name` and `container_id` dimension. Since container_name's can be long lived, perpetuating entities to update becomes unnecessary and setting to the more ephemeral `container_id` is preferable. ~~My plan is to update the default value to `container_id` in a subsequent release but can understand wanting to here instead.~~
edit: updated to sync on `container_id` by default, w/ bw-compatibility option w/ new config field.
> ecs-metadata: support `dimensionToUpdate` config field 

- internal/signalfx-agent/bundle/java/jmx/src/main/java/com/signalfx/agent/SignalFxMonitorRunner.java
- internal/signalfx-agent/bundle/java/jmx/src/main/java/com/signalfx/agent/jmx/Client.java
- internal/signalfx-agent/bundle/java/jmx/src/main/java/com/signalfx/agent/jmx/GroovyRunner.java
- internal/signalfx-agent/bundle/java/jmx/src/main/java/com/signalfx/agent/jmx/JMXMonitor.java
Following best practices, marking loggers as final.
> make loggers final

- internal/signalfx-agent/bundle/java/jmx/src/main/java/com/signalfx/agent/SignalFxMonitorRunner.java
Remove a `return;` statement and a method, `runDebug()`, which is not used.
> remove code outside of execution path

- internal/settings/settings.go
- internal/settings/settings_test.go
- tests/general/validate_test.go
These changes allow the `validate` core service command argument that isn't possible without manual intervention per https://github.com/signalfx/splunk-otel-collector/pull/2343.
resolves https://github.com/signalfx/splunk-otel-collector/issues/4173
> support core service validate command

- CHANGELOG.md
Prepping changelog. Depending on the state of https://github.com/signalfx/splunk-otel-collector/pull/4176 as a fix we may need to wait for 0.93.0.
> Release 0.92.0

- deployments/ansible/roles/collector/tasks/main.yml
**Description:** ansible: fix the assert call on ansible 2.16.1 and 2.14.2
https://docs.ansible.com/ansible-core/2.16/porting_guides/porting_guide_core_2.16.html#playbook
fix error "Conditional is marked as unsafe, and cannot be evaluated." when `splunk_access_token` come from an untrusted source (like a lookup).
**Testing:** none
**Documentation:** none
> fix "Conditional is marked as unsafe, and cannot be evaluated."

- .golangci.yml
- internal/exporter/httpsinkexporter/doc.go
- internal/exporter/httpsinkexporter/factory.go
- internal/exporter/httpsinkexporter/httpsink_exporter.go
httpsinkexporter is used for testing in our SDKs, but it should not be used by customers. It is no longer developed and will be kept around as deprecated until such time it is no longer used, and will then be removed.
> Deprecate httpsinkexporter

- .lychee.toml
- deployments/cloudfoundry/bosh/README.md
- deployments/cloudfoundry/buildpack/README.md
- deployments/cloudfoundry/tile/DEVELOPMENT.md
- deployments/cloudfoundry/tile/README.md
`docs.pivotal.io` used to redirect to `docs.vmware.com`, but has been fully taken down. This PR updates references to point to the same documents that are hosted on docs.vmware.com instead.
> [chore] Fix dead links in CloudFoundry deployment

- internal/signalfx-agent/pkg/monitors/aspdotnet/metadata.yaml
- internal/signalfx-agent/pkg/monitors/dotnet/metadata.yaml
Add deprecation notice to .NET related SmartAgent monitors. The instrumentation for .NET provides the same metrics with names matching the OTel conventions and also work on platforms other than Windows.
https://splunk.atlassian.net/browse/OTL-2452
**Testing:**
N/A
Follow-up ticket https://splunk.atlassian.net/browse/OTL-2453
> Add deprecation notice to dotnet monitors

- internal/signalfx-agent/pkg/monitors/aspdotnet/aspdotnet_windows.go
- internal/signalfx-agent/pkg/monitors/dotnet/dotnet_windows.go
Log a deprecation notice to .NET related SmartAgent monitors. The instrumentation for .NET provides the same metrics with names matching the OTel conventions and also work on platforms other than Windows.
https://splunk.atlassian.net/browse/OTL-2452
**Testing:**
N/A
#4226
https://github.com/splunk/private-o11y-docs/pull/1699
Follow-up ticket https://splunk.atlassian.net/browse/OTL-2453
> Log a deprecation notice as warning for asptnet and dotnet monitors

- .github/workflows/ansible.yml
Only test Ansible versions that didn't reach EOL per https://endoflife.date/ansible
https://splunk.atlassian.net/browse/OTL-2462
**Testing:**
N/A
N/A
> Don't test unsupported Ansible versions

- .github/workflows/ansible.yml
- deployments/ansible/molecule/config/docker.yml
- deployments/ansible/molecule/config/vagrant.yml
- deployments/ansible/molecule/config/windows.yml
- deployments/ansible/molecule/custom_vars/converge.yml
- deployments/ansible/molecule/custom_vars/windows-converge.yml
- deployments/ansible/molecule/default/converge.yml
- deployments/ansible/molecule/default/windows-converge.yml
- deployments/ansible/molecule/with_instrumentation/converge.yml
- deployments/ansible/molecule/with_instrumentation/windows-converge.yml
- deployments/ansible/molecule/with_instrumentation_preload_custom/converge.yml
- deployments/ansible/molecule/with_instrumentation_preload_default/converge.yml
- deployments/ansible/molecule/with_instrumentation_systemd_custom/converge.yml
- deployments/ansible/molecule/with_instrumentation_systemd_default/converge.yml
Update tools used in Ansible tests, the main target being `molecule-vagrant` that was archived one year ago.
The new tools complained about the role "collector" not being found, [error message](https://github.com/pjanotti/splunk-otel-collector/actions/runs/7746705618/job/21125532013#step:6:119):
```terminal
ERROR! the role 'collector' was not found in /home/runner/work/splunk-otel-collector/splunk-otel-collector/deployments/ansible/molecule/custom_vars/roles:/home/runner/.cache/molecule/ansible/custom_vars/roles:/home/runner/work/splunk-otel-collector/splunk-otel-collector/deployments:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/runner/work/splunk-otel-collector/splunk-otel-collector/deployments/ansible/molecule/custom_vars
The error …
```
> Update Ansible test tools

- deployments/chef/Gemfile
The scheduled Chef job reported a consistent failure running `make rake-spec`. This is due to a change in the rspec gem published on 02/04/24, see https://rubygems.org/gems/rspec/versions/3.13.0. Errors:
https://github.com/pjanotti/splunk-otel-collector/actions/runs/7792487517/job/21250575903#step:4:1
```terminal
docker run \
--rm \
splunk-otel-collector-chef-dev \
rake spec
An error occurred while loading ./spec/unit/recipes/default_spec.rb. - Did you mean?
rspec ./spec/shared_examples.rb
Failure/Error: require 'chefspec'
LoadError:
cannot load such file -- rspec/matchers/expecteds_for_multiple_diffs
No examples found.
Finished in 0.00006 seconds (files took 0.[60](https://github.com/pjanotti/splunk-otel-collector/actions/runs/7792487517/job/21250575903#step:4:61)03 …
```
> Fix Chef lint workflow

- .gitlab-ci.yml
YAML anchors must be defined before their use.
> fix yaml anchor

- CHANGELOG.md
- cmd/otelcol/config/collector/agent_config.yaml
- cmd/otelcol/config/collector/ecs_ec2_config.yaml
- cmd/otelcol/config/collector/fargate_config.yaml
- cmd/otelcol/config/collector/full_config_linux.yaml
- cmd/otelcol/config/collector/gateway_config.yaml
- cmd/otelcol/config/collector/otlp_config_linux.yaml
- cmd/otelcol/config/collector/upstream_agent_config.yaml
- tests/installation/testdata/systemd/prometheus-internal.yaml
- tests/receivers/prometheus/testdata/internal_metrics_config.yaml
The batch processor metrics are not being used in any default dashboards but signicantly contribute towards metric timeseries created on the backend.
> Stop sending metrics reported by batch processor

- internal/configconverter/disable_excessive_internal_metrics.go
- internal/configconverter/disable_excessive_internal_metrics_test.go
- internal/configconverter/testdata/disable_excessive_internal_metrics/all_metric_relabel_configs_are_present.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/different_job.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/metric_relabel_configs_with_batch_drop_action_input.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/metric_relabel_configs_with_batch_drop_action_output.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/metric_relabel_configs_with_other_actions_input.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/metric_relabel_configs_with_other_actions_output.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/new_input.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/no_metric_relabel_configs_set_input.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/no_metric_relabel_configs_set_output.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/no_prom_receiver.yaml
- internal/configconverter/testdata/disable_excessive_internal_metrics/no_scrape_configs.yaml
- internal/settings/settings.go
- internal/settings/settings_test.go
0.93.0 version add a significant amount of internal metrics upstream. We want disable them on the prometheus receiver level until it's handled upstream.
> Add a converter to disable excessive internal metrics

- .semgrepignore
Ignore semgrep warnings related to pem files used for testing or part of the build
> Ignore semgrep warnings related to pem files

- .gitlab-ci.yml
Instead of using jq, prefer using a Powershell native function to extract the `os.version` label from the Windows images.
I have tested this manually on a Windows Powershell session to make sure it renders properly.
> Remove usage of jq in Windows script, use fixed versions

- .gitlab-ci.yml
This changes the way we tag the latest tag.
In the past, we'd use `docker tag` to create an alias, but we're now creating a manifest list itself pointing to images.
To tag a manifest, you need to use a different approach. I used [this SO post](https://stackoverflow.com/questions/48363572/how-to-add-tag-alias-on-docker-hub-without-pulling-an-image) and tried locally, and it almost worked except I can't push to quay.io.
> Build a manifest of the latest tag

- .gitlab-ci.yml
* Make sure the multiarch release runs after both docker images are built and pushed
* No need to pull images, we can create manifests by downloading the sha256 signatures from the registry (tested on a Windows machine)
* Remove the use of a docker buildx command as the gitlab worker doesn't have the right version. Build the manifest for each tag and push separately.
> Create manifest separately for latest as well

- .gitlab-ci.yml
`docker inspect` requires the image to be locally present. We have to add a line to pull the image beforehand.
Remove the need to set dependencies on the windows multiarch image as well since it is now running in its own stage.
> Pull the image before inspect its digest

- .gitlab-ci.yml
This avoids amending successive individual tags to the latest image, which will otherwise add more and more tags over time.
> use latest tags as amended tags for the windows multi-arch latest manifest

- .lychee.toml
Lychee workflow `[.github/workflows/lychee.yml](https://github.com/signalfx/splunk-otel-collector/actions/workflows/lychee.yml)` is broken https://github.com/signalfx/splunk-otel-collector/actions/runs/8056560876#summary-22005858584
> Exclude 1 link from lychee validation

- .github/workflows/win-package-test.yml
- CHANGELOG.md
- internal/buildscripts/packaging/installer/install.ps1
- tests/zeroconfig/windows/README.md
- tests/zeroconfig/windows/testdata/resource_traces/aspnetcore.yaml
- tests/zeroconfig/windows/testdata/resource_traces/aspnetfx.yaml
Change the Windows install script to install the [Splunk Distribution of OpenTelemetry .NET](https://docs.splunk.com/observability/en/gdi/get-data-in/application/otel-dotnet/get-started.html#instrument-net-applications-for-splunk-observability-cloud-opentelemetry)
instead of the [SignalFx Instrumentation for .NET](https://docs.splunk.com/observability/en/gdi/get-data-in/application/otel-dotnet/sfx/sfx-instrumentation.html#signalfx-instrumentation-for-net-deprecated)
when the parameter `-with_dotnet_instrumentation` is set to `$true`
N/A
**Testing:**
Local and CI validation on fork.
Pending: update install script documentation.
> Windows script to install Splunk distro for .NET instead of SFx.NET

- .github/workflows/puppet-test.yml
- .github/workflows/win-installer-script-test.yml
- .github/workflows/win-package-test.yml
- .github/workflows/windows-test.yml
Windows 2022 and 2019 are similar enough, at the level of the artifacts for this repo, that running on Windows 2019 tests doesn't provide much, if any, value and expose CI runs to [known issues with golang on Windows 2019](https://github.com/golang/go/issues/25965#issuecomment-1623741828), the common `go: CreateFile C:\Users\RUNNER~1\AppData\Local\Temp\go-build1611004282\b2864\settings.test.exe: Access is denied.`
Notice that both OTel collector core and contrib also don't run tests on Windows 2019, both use `windows-latest` only.
I'm opting to keep the GH action matrices so when a new Windows is released we can for a short of period of time run tests on both versions.
**Link to Jira:**
https://splunk.atlassian.net/browse/OTL-2618
**Testing:**
N/A
N/A
> Remove windows-2019 from test matrix

- .gitlab-ci.yml
CVE Scan is succeeding in GitHub, but there seems to be a `snyk` issue we're running into in GitLab. Working on resolving in the background.
> Skip cve scan in release for now

- .gitlab-ci.yml
This removes the whole job for now, we still have GitHub vulnerability scans.
> Remove cve-scan GitLab job for now

- .github/workflows/auto-instrumentation.yml
- .github/workflows/build-and-test.yml
- .github/workflows/chef-test.yml
- .github/workflows/darwin-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/tanzu-tile.yml
- .github/workflows/vuln-scans.yml
- .github/workflows/win-package-test.yml
Get rid of GH action warnings about actions using node 16, see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
The CLA assistant still doesn't have a node20 version and it is the last one remaining with this warning.
N/A
**Testing:**
N/A
N/A
> Update some actions to versions using node20

- .github/workflows/win-package-test.yml
The MSI is not being tested directly: there is always a "script" (install.ps1, choco, or a mass deployment) using it. This results in a test gap for the MSI directly. This PR adds a test that uses the MSI without any "scripts"
https://splunk.atlassian.net/browse/OTL-2627
**Testing:**
GH CI
N/A
> Test MSI without any "scripts"

- .github/workflows/vuln-scans.yml
We're hitting a lot of failures due to not authenticating for snyk scans. We're running too many, which is not allowed in their free tier. Once we get a proper account up and running we'll re-enable, which is why I'm leaving them commented out instead of removing.
> [CI/CD] Disable Snyk vulnerability scanner until we can properly authenticate

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
Enabling Cumulative to Delta processor which would allow for converting cumulative monotonic metrics to delta metrics.
**Link to Splunk idea:**  https://ideas.splunk.com/ideas/SFXIMMID-I-599
- Has been tested with a splunk-otel-collector helm chart (w/ a custom-built image) deployed in an EKS cluster, with the "cumulativetodelta" processor enabled in the processors config, and the processor added to the "metrics" pipeline like so: 
```
metrics:
processors:
- memory_limiter
- cumulativetodelta
- k8sattributes/metrics
- batch
- resourcedetection
- resource
``` 
We have confirmed that the metrics values that used to be ever-increasing monotonic numbers have become …
> Enable Cumulative to Delta Processor

- internal/configconverter/config_server.go
This adds this header as a masked value in the effective configuration.
> Add X-SF-Token header to the configuration masked keys

- .github/workflows/integration-test.yml
- tests/receivers/smartagent/collectd-tomcat/tomcat_test.go
Attempt to use Github to run docker containers for us rather than having us run it every time.
> Move integration test image to a service container

- internal/signalfx-agent/pkg/core/config/config.go
Remove configuration section that have no need to exist anymore as part of the smart agent receiver.
> Remove deprecated config fields

- .github/workflows/darwin-test.yml
As per https://endoflife.date/macos and https://github.com/actions/runner-images, we can drop support for Darwin 11 and add support for Darwin 14.
> Remove darwin 11 from test suite, add darwin 14

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
The `spanmetrics` processor was deleted from upstream, we should delete as well.
> Remove spanmetrics processor

- tests/receivers/jmxreceiver/jmxreceiver_test.go
This container was moved to github actions services and there is no need to build it directly.
> Remove the need to build and run cassandra as container

- tests/receivers/lightprometheus/testdata/resource_metrics/basic_auth_metrics.yaml
We had to change to port 8001 to fix a conflict, but I forgot to change the fixtures to match.
> use port 8001 to match running prometheus instance

- tests/receivers/jmxreceiver/jmxreceiver_test.go
- tests/receivers/smartagent/collectd-couchbase/testdata/resource_metrics/all.yaml
> skip jmxreceiver and fixed couchbase receiver

- internal/buildscripts/packaging/installer/install.ps1
**Description:** Added support for offline installs to the Windows Installer Script.  Its common for windows servers in the DMZ to have outbound access blocked which prevents the current script from working.  The current script does support an offline MSI but it does NOT support an offline .net auto instrumentation file.  This change adds that capability.
**Link to Splunk idea:** There is no idea for this, but this is something we see in field sales all the time.  Support tosses this issue back to the SAs/SEs so I lets just fix the root cause.
**Testing:** Ran the script multiple times with various options in my Home Lab using Win Server 2012R2 with powershell 5.1.  I believe it needs more testing, but my home lab resources are limited.  Hopefully the QA team can put it through the paces. …
> Windows Installer Script - Add support for offline installs

- README.md
- internal/configconverter/remove_memory_ballast_key.go
**Description:** Adding upgrade section for  memory_ballast changes.
> Adding upgrade section for memory_ballast

- CHANGELOG.md
This is a work in progress as we have yet to adopt contrib 0.97.0.
> Prepare changelog for 0.97.0

- .gitlab/update-otel-deps.sh
This commit checks for an OTEL_VERSION set to main. If so, it sets explicitly both core and contrib to the latest commit on each repository. It uses `go mod edit` instead of `go get`, which seems to fail to find the latest commit on some of the packages.
> use go mod edit when updating to latest main

- Makefile
To build arm docker images locally with docker-otelcol
> [Makefile] Allow overriding ARCH env var

- internal/confmapprovider/discovery/discoverer.go
- internal/confmapprovider/discovery/properties/property.go
- internal/confmapprovider/discovery/properties/property_test.go
To avoid collector crashes. We don't control the input in most of the cases
> [discovery] Don't use component.MustNewIDWithName

- docs/getting-started/linux-installer.md
- internal/signalfx-agent/bundle/python/sfxmonitor/__main__.py
- pkg/extension/smartagentextension/README.md
- pkg/receiver/smartagentreceiver/README.md
Remove mention of SignalFx when possible, inline docs from the signalfx agent repository, link to docs rather than an empty repository docs page.
> sanitize docs

- cmd/otelcol/config/collector/ecs_ec2_config.yaml
- cmd/otelcol/config/collector/fargate_config.yaml
Explicitly set port 443 on grpc endpoints to make sure they are considered valid by gRPC framework
> Cleanup configurations to use port 443

- cmd/otelcol/config/collector/agent_config.yaml
- tests/general/default_config_test.go
Remove an exporter that is not being used. Having one point for switching to gateway seems more convenient.
> Update default config to have only one otlp exporter

- .github/workflows/win-package-test.yml
Setting up 1.21.5 is taking about 9 to 15 minutes, let's try to use the default, currently 1.21.8, since this only runs an integration test. 
Update: @atoulme just upgraded go version to 1.21.9, but, it seems reasonable to live this one with whatever is the default version on the runner.
> Go 1.21.5 setup on Windows is taking too long, use default

- .github/workflows/scripts/win-test-services.ps1
- .github/workflows/win-package-test.yml
- internal/buildscripts/packaging/msi/splunk-otel-collector.wxs
This was reported as confusing during Office hours and makes sense: the user sees the files there and thinks that those are the ones being used by the collector. Now the install only leaves the ProgramData ones.
**Testing:**
Manual validation.
N/A
> MSI: delete config files from install dir

- .github/workflows/scripts/win-test-support-bundle.ps1
- docker/kong/Dockerfile
- internal/buildscripts/packaging/msi/splunk-support-bundle.ps1
Although the information itself is reported via the effective configuration this change adds a dedicated file showing what is set on the registry. It also adds a helper to set/modify a single environment variable at the service scope.
**Testing:**
Manual local testing.
Internal to the script.
> Add service environment helpers to the Windows support bundle

- CHANGELOG.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
This adds the SQL Server receiver to the Splunk distribution of the OpenTelemetry Collector.
> Add new component: SQL Server receiver

- deployments/ansible/molecule/custom_vars/windows-verify.yml
- deployments/ansible/molecule/default/windows-verify.yml
- deployments/ansible/molecule/with_instrumentation/windows-verify.yml
The addition of environment variable `SPLUNK_MEMORY_TOTAL_MIB=256` exposed a bug on the test code: 256 is converted to an integer and the string concatenation fails.
This came from the scheduled run of Ansible tests:
https://github.com/signalfx/splunk-otel-collector/actions/runs/8639527708/job/23686002963#step:8:1585
```
TASK [Verify splunk-otel-collector service env vars] ***************************
fatal: [2016]: FAILED! => {"msg": "The conditional check '(item.key + '=' + item.value) in collector_env.value' failed. The error was: Unexpected templating type error occurred on ({% if (item.key + '=' + item.value) in collector_env.value %} True {% else %} False {% endif %}): can only concatenate str (not \"int\") to str. can only concatenate str (not \"int\") to str"}
```
> [ktlo] Fix Ansible tests on Windows

- CHANGELOG.md
- go.mod
- internal/common/discovery/discovery.go
- internal/confmapprovider/discovery/discoverer.go
- internal/receiver/discoveryreceiver/README.md
- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
- internal/receiver/discoveryreceiver/statement_evaluator.go
- internal/receiver/discoveryreceiver/statement_evaluator_test.go
- internal/receiver/discoveryreceiver/statussources/statements.go
- internal/receiver/discoveryreceiver/statussources/statements_test.go
- tests/receivers/discovery/testdata/host_observer_simple_prometheus_config.yaml
- tests/receivers/discovery/testdata/resource_logs/host_observer_simple_prometheus_statuses.yaml
This change updates the schema of the logs emitted by the discovery receiver to represent entity events. No information is dropped, but it was reshuffled to adopt for the new schema:
- Entity ID is made of one key/value pair moved from `discovery.endpoint.id` resource attribute
- All other resource attributes are moved to the entity state event attributes
- Log body was moved to the `discovery.event.message` entity state attribute
The Discovery config provider is updated to use the entity events.
The keys used in the entity ID and entity attributes are not finalized and are expected to be changed in the following PRs.
> [discovery] Apply entity events schema the discovery receiver logs

- internal/configconverter/otlp_histogram_attr.go
- internal/configconverter/otlp_histogram_attr_test.go
- internal/configconverter/testdata/otlp_histograms_attr/send_otlp_histrograms_disabled.yaml
- internal/configconverter/testdata/otlp_histograms_attr/send_otlp_histrograms_disabled_expected.yaml
- internal/configconverter/testdata/otlp_histograms_attr/send_otlp_histrograms_disabled_no_exp.yaml
- internal/configconverter/testdata/otlp_histograms_attr/send_otlp_histrograms_disabled_no_exp_expected.yaml
- internal/configconverter/testdata/otlp_histograms_attr/send_otlp_histrograms_enabled.yaml
- internal/configconverter/testdata/otlp_histograms_attr/send_otlp_histrograms_enabled_expected.yaml
- internal/configconverter/testdata/otlp_histograms_attr/send_otlp_histrograms_enabled_no_telemetry.yaml
- internal/configconverter/testdata/otlp_histograms_attr/send_otlp_histrograms_enabled_no_telemetry_expected.yaml
- internal/settings/settings.go
- internal/settings/settings_test.go
Adds the resource attribute `splunk_otlp_histograms: true` to the `service::telemetry::resource` if the collector detects any in use signalfx metrics exporter with the flag `send_otlp_histograms` enabled.
Added tests
> add splunk_otlp_histograms resource attr

- .github/workflows/integration-test.yml
Since the remote `quay.io/splunko11ytest` images may not be up-to-date with the changes in their respective `docker/<service>` directory, always build the images in CI using the remote images as cache (currently takes ~1m30s to build all images).
> Build images for integration tests

- internal/buildscripts/packaging/tests/deployments/puppet/images/rpm/Dockerfile.centos-8
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.centos-8
The `centos:8` image is deprecated. Use `quay.io/centos/centos:stream8` instead.
> Use centos:stream8 image for puppet and salt tests

- go.mod
- internal/receiver/discoveryreceiver/README.md
- internal/receiver/discoveryreceiver/config.go
- internal/receiver/discoveryreceiver/config_test.go
- internal/receiver/discoveryreceiver/correlation.go
- internal/receiver/discoveryreceiver/correlation_test.go
- internal/receiver/discoveryreceiver/endpoint_tracker.go
- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
- internal/receiver/discoveryreceiver/evaluator_test.go
- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
- internal/receiver/discoveryreceiver/rule.go
- internal/receiver/discoveryreceiver/rule_test.go
- internal/receiver/discoveryreceiver/statement_evaluator.go
- internal/receiver/discoveryreceiver/statement_evaluator_test.go
- internal/receiver/discoveryreceiver/testdata/config.yaml
- internal/receiver/discoveryreceiver/testdata/conflicting_rules.yaml
- internal/receiver/discoveryreceiver/testdata/invalid_status_types.yaml
- internal/receiver/discoveryreceiver/testdata/missing_match_status.yaml
- internal/receiver/discoveryreceiver/testdata/missing_status.yaml
- internal/receiver/discoveryreceiver/testdata/missing_status_metrics_and_statements.yaml
- internal/receiver/discoveryreceiver/testdata/multiple_status_match_types.yaml
- internal/receiver/discoveryreceiver/testdata/reserved_receiver_creator.yaml
- internal/receiver/discoveryreceiver/testdata/reserved_receiver_name.yaml
- internal/receiver/discoveryreceiver/testdata/reserved_receiver_name_with_endpoint.yaml
This way, we can start tracking target endpoints in the correlation store and emit entity events on regular basis.
Also, this requires limiting discovered endpoint to only one receiver. If an overlapping rule is found in multiple receivers, that endpoint will be ignored with a warning. If we keep allowing multiple receivers per endpoint, it'll be unclear how to track successful discovery of endpoint/service because different receivers may provide conflicting results.
This change required pulling code from the receivercreator, which will be reused once the discovery receiver is upstreamed.
> [receiver/discovery] Track only endpoints matching a receiver rule

- deployments/ansible/roles/collector/defaults/main.yml
- deployments/ansible/roles/collector/tasks/otel_win_install.yml
- deployments/ansible/roles/collector/tasks/win_install.yml
Leverage the latest MSI capabilities so we don't rely on custom Ansible code to install the collector on Windows. At this point if the user wants to install only the collector on Windows they can directly use https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_package_module.html
**Testing:** CI
This change is not noticeable to end users, they can keep using the same settings that they used before.
> Use latest MSI capabilities instead of custom code in Ansible

- internal/receiver/discoveryreceiver/correlation.go
- internal/receiver/discoveryreceiver/correlation_test.go
- internal/receiver/discoveryreceiver/endpoint_tracker.go
- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
- internal/receiver/discoveryreceiver/evaluator_test.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
- internal/receiver/discoveryreceiver/statement_evaluator_test.go
Clearly separate state and delete entities. There is no need to keep the changed/added state from the observer. This will later help to enhance the endpoint storage to maintain more data about discovery states.
No functional changes.
> [receiver/discovery] Refactor the endpoint tracker to remove states

- CHANGELOG.md
- internal/receiver/discoveryreceiver/config_test.go
- internal/receiver/discoveryreceiver/endpoint_tracker.go
- internal/receiver/discoveryreceiver/testdata/config.yaml
- tests/receivers/discovery/testdata/host_observer_endpoints_config.yaml
Only the entity tracker will be responsible for emitting entity events. So we want to avoid sending entity state events for any observed endpoints. We need to send events only for those that we have defined discovery rules.
> [receiver/discovery] Emit entity events only for matching receivers

- internal/receiver/discoveryreceiver/correlation.go
Otherwise, both lock and unlock are defferred
> [receiver/discovery] Fix attributes locking mechanism

- internal/receiver/discoveryreceiver/config.go
- internal/receiver/discoveryreceiver/config_test.go
- internal/receiver/discoveryreceiver/evaluator.go
- internal/receiver/discoveryreceiver/evaluator_test.go
- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/receiver.go
- internal/receiver/discoveryreceiver/statement_evaluator.go
This change removes the complicated logic of passing the encoded config by metrics receivers as part of a resource attribute and intercepting it in the discovery receiver. Instead, we compute the embedded config on the fly for every emitted entity. In the short run, this hits the performance of the discovery receiver, but once we move the `metric.match` and `statement.match` discovery events to entity states in the following PRs, it won't be an issue.
Except for the performance implications, there are no functional changes in this PR.
> [receiver/discovery] Simplify config reporting

- internal/receiver/discoveryreceiver/correlation.go
- internal/receiver/discoveryreceiver/correlation_test.go
- internal/receiver/discoveryreceiver/evaluator_test.go
- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/statement_evaluator.go
Update the `correlationStore` methods to take `endpointID` as the first argument.
The most important change is repurposing of the attributes store. After https://github.com/signalfx/splunk-otel-collector/pull/4717, it's not being used anymore, but this will be used to store endpoint-specific attributes. So this change migrates the field from storing receiver's attributes to storing endpoint/correlation attributes.
There are no functional changes in this PR.
> [receiver/discovery] Refactor correlation store to be endpoint-centric

- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
Metric evaluation emits entities with attributes from the first resource in the metric batch regardless of where the matching metrics were found. This change fixes the bug. The resource attributes are now assigned from the resource where the metrics are found.
It doesn't make sense to mention it in the changelog because we don't have any pre-configured receiver to run into this bug.
> [receiver/discovery] Assign correct resource in the metric evaluation

- .github/workflows/vuln-scans.yml
Similar to the linux image scan, fail on `high` severity or greater and ignore unfixed.
> Scan windows image with anchore

- internal/receiver/discoveryreceiver/correlation.go
- internal/receiver/discoveryreceiver/endpoint_tracker.go
- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
- internal/receiver/discoveryreceiver/evaluator.go
- internal/receiver/discoveryreceiver/evaluator_test.go
- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
- internal/receiver/discoveryreceiver/receiver.go
- internal/receiver/discoveryreceiver/statement_evaluator.go
- internal/receiver/discoveryreceiver/statement_evaluator_test.go
- tests/receivers/discovery/testdata/resource_logs/host_observer_simple_prometheus_statuses.yaml
This change consolidates the entity emitting in one place: the endpoint tracker. Once the evaluation succeeds, the endpoint attributes are updated in the correlation store, and the new entity state is emitted immediately. Every subsequent state is emitted with all the added attributes.
Currently, we emit a superset of all the attributes that were previously emitted on a regular basis or during evaluation. Later, we will reduce the set and remove redundant attributes.
The tests are kept with minimal changes to ensure no attributes are lost in the emitted entities.
> [receiver/discovery] Emit evaluation entities by the endpoint tracker

- internal/signalfx-agent/bundle/scripts/security-requirements.txt
Tested locally on a docker image, the proper version of `idna` was installed.
> Bump minimum version of idna to >= 3.7

- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
- internal/receiver/discoveryreceiver/statement_evaluator_test.go
We don't need to parse the entity events in the evaluation tests. They can be simplified. The `entityStateEvents` and `entityDeleteEvents` functions can be tested separately.
Addresses https://github.com/signalfx/splunk-otel-collector/pull/4728#discussion_r1580044053
> [chore] [receiver/discovery] Simplify endpoint evaluation tests

- internal/signalfx-agent/bundle/collectd-plugins.yaml
Remove the `integration-test` directory included in the `collectd-etcd` pip package.
> Remove integration-test from collectd-ectd

- CHANGELOG.md
Update changelog in preparation for `v0.99.0` release.
> Update changelog for v0.99.0

- internal/confmapprovider/discovery/discoverer.go
- internal/receiver/discoveryreceiver/endpoint_tracker.go
- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
- tests/receivers/discovery/testdata/resource_logs/host_observer_endpoints.yaml
- tests/receivers/discovery/testdata/resource_logs/host_observer_simple_prometheus_statuses.yaml
Update entity events ID fields according to the latest contract with the inventory service:
- `discovery.endpoint.id` is moved from identifying to regular attributes
- The following attributes now marked as identifying instead:
- `k8s.pod.uid`
- `k8s.node.uid`
- `container.id`
- `source.port`
- `host.id`
> [receiver/discovery] Update entity events ID fields

- deployments/chef/CHANGELOG.md
- deployments/chef/metadata.rb
- deployments/chef/recipes/default.rb
Only copy the collector configuration file to `ProgramData` if the source exists.
> chef: fix config file for win installs

- internal/receiver/discoveryreceiver/endpoint_tracker.go
- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
- tests/receivers/discovery/testdata/resource_logs/host_observer_endpoints.yaml
- tests/receivers/discovery/testdata/resource_logs/host_observer_simple_prometheus_statuses.yaml
`service.name` and `service.type` attributes are required according to the contract with the inventory service. We deduct `service.name` from several inputs and use receiver type for `service.type`
> [receiver/discovery] Add service attributes

- .github/workflows/win-package-test.yml
Ensure the test fails correctly.  See https://github.com/signalfx/splunk-otel-collector/actions/runs/8915023067/job/24483979058#step:6:50 for latest run from `main`.
> Fix windows image java test

- CHANGELOG.md
- internal/buildscripts/packaging/installer/install.sh
- internal/buildscripts/packaging/tests/installer_test.py
- Install and configure env vars for `splunk-otel-dotnet` (x86_64/amd64 only)
- Refactored handling of installer script options for auto instrumentation
- Removed support for the "original" `libsplunk.so` (requires v0.87.0 or greater)
- Updated tests to verify preload and systemd configs
> Linux installer script: support .NET zero config

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
This adds the Redaction processor to the Splunk distribution of the OpenTelemetry Collector.
> adopt redaction processor into our distro

- .github/workflows/salt-test.yml
- CHANGELOG.md
- deployments/salt/README.md
- deployments/salt/splunk-otel-collector/auto_instrumentation.sls
- internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.debian-bullseye
- internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.debian-buster
- internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.debian-stretch
- internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.ubuntu-bionic
- internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.ubuntu-focal
- internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.ubuntu-jammy
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.amazonlinux-2
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.amazonlinux-2023
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.centos-7
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.centos-8
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.centos-9
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.opensuse-12
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.opensuse-15
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.oraclelinux-7
- internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.oraclelinux-8
- internal/buildscripts/packaging/tests/deployments/salt/salt_test.py
- Activate Node.js and .NET instrumentation by default if `install_auto_instrumentation` is `true` for either preload or systemd.
- Update test to verify env vars for both preload and systemd configs.
> salt: support Node.js and .NET zero config on linux

- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
- internal/receiver/discoveryreceiver/receiver.go
- internal/receiver/discoveryreceiver/statement_evaluator.go
- internal/receiver/discoveryreceiver/statement_evaluator_test.go
- tests/receivers/discovery/testdata/resource_logs/host_observer_simple_prometheus_statuses.yaml
Stop emitting `discovery.event.type` and `metric.name` entity attributes. They are not relevant anymore since the entity events are emitted constantly from the latest state
> [receiver/discovery] Remove discovery.event.type and metric.name attrs

- .gitlab-ci.yml
Instead of relying on `git describe`, override `VERSION` with the `CI_COMMIT_TAG` gitlab env var when building `otelcol` for release tags.  This ensures that `otelcol --version` is consistent with the github release and packages.
> Use CI_COMMIT_TAG for otelcol version

- internal/settings/settings.go
- internal/settings/settings_test.go
This removes an extra validation of the schema in place where it not expected.
Now, if schema isn't set correctly, user still gets a message like:
```
2024/05/20 14:47:39 main.go:78: unsupported scheme on URI "fil:./config.yaml"
```
Before this change, the additional line was reported at the top of the output
```
2024/05/20 14:47:39 settings.go:554: "fil" is an unsupported config provider scheme for this Collector distribution (not in [env file]).
2024/05/20 14:47:39 settings.go:480: Set config to [fil:./config.yaml]
2024/05/20 14:47:39 settings.go:541: Set memory limit to 460 MiB
2024/05/20 14:47:39 settings.go:526: Set soft memory limit set to 460 MiB
2024/05/20 14:47:39 settings.go:416: set "SPLUNK_LISTEN_INTERFACE" to "0.0.0.0"
2024/05/20 14:47:39 main.go:78: unsupported scheme on URI …
```
> [chore] Remove redundant config provider schema validation

- internal/receiver/scriptedinputsreceiver/operator.go
Remove usage of incorrect logger inherited from stanza InputOperator and removed in 0.101.0 as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32177
> [chore] [receiver/scriptedinput] Use correct logger

- go.mod
- go.sum
- tests/general/validate_test.go
Pull fix for the validate sub-command https://github.com/open-telemetry/opentelemetry-collector/pull/10203 and re-enable failing tests
> [chore] Pull fix for validate subcommand

- cmd/otelcol/config/collector/config.d.linux/receivers/mongodb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml.tmpl
`endpoint` is coming from receiver creator when it matches an endpoint provided by an observer extension. The `mongodb` receiver uses the `endpoint` in a slightly different way than expected, as an item in a `hosts` map, rather than directly as an `endpoint` config option. This updates the receiver creator's way of creating `mongodb` as the target receiver, setting the endpoint properly in the `hosts` config option.
I was able to see that the option is being picked up properly, and the MongoDB receiver's config is setup as expected, but discovery didn't succeed due to docker's IP configuration on my local machine. Posting PR as draft while I investigate locally.
> [OTL-2836] Set hosts in MongoDB config from autodiscover endpoint

- tests/receivers/kong/kong_test.go
Fixes a flaky test:
```
2024-05-28T17:56:39.430Z	INFO	testutils/collector_container.go:267	2024-05-28T17:56:39.430Z	info	zapgrpc/zapgrpc.go:176	[core] [Channel #1]Channel Connectivity change to READY	{"grpc_log": true}
golden.go:71: 
Error Trace:	/home/runner/work/splunk-otel-collector/splunk-otel-collector/tests/testutils/golden.go:77
/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/asm_amd64.s:1650
Error:      	Received unexpected error:
the following errors occurred:
-  resource "map[http.scheme:http net.host.port:18001 service.instance.id:localhost:18001 service.name:kong]": scope "otelcol/prometheusreceiver": metric "kong_memory_workers_lua_vms_bytes": missing expected datapoint: map[kong_subsystem:http node_id: pid:2435]
-  resource "map[http.scheme:http net.host.port:18001 …
```
> Ignore pid attribute value

- docker/couchbase/Dockerfile
- docker/haproxy/Dockerfile
- docker/httpd/Dockerfile
- docker/mysql/Dockerfile
- docker/redis_client/Dockerfile
- docker/redis_server/Dockerfile
- docker/solr/Dockerfile
Since the services in the `docker` directory are not currently in sync with the `quay.io/splunko11ytest` images, pin the versions in the dockerfiles to help reduce integration test failures when the the services need to be rebuilt and the latest base images have been updated.
> Pin versions for docker services

- CHANGELOG.md
- cmd/otelcol/config/collector/config.d.linux/receivers/mongodb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml.tmpl
Reduce the connection timeout to 5s seconds. Otherwise, it's the 60s for every Mongodb query, which accumulates to a significant delay and makes the collector killed in k8s.
> [discovery] Fix crashing collector if discovered mongodb isn't reachable

- .github/workflows/integration-test.yml
- .github/workflows/linux-package-test.yml
- Makefile
- cmd/otelcol/Dockerfile
- internal/buildscripts/packaging/docker-otelcol.sh
- Update the `docker-otelcol` makefile target and dockerfile to support multiarch builds, i.e. `make docker-otelcol ARCH=amd64,arm64,ppc64le`.  Requires either the manifest/images to be pushed, or the containerd image store to be enabled to save the manifest/images locally (limitations of buildkit and the docker engine). Otherwise, the images will be built for each platform individually as it previously did.
- Update github CI tests to support multiarch builds.
- The gitlab changes to support this will be in a separate PR.
> Update docker-otelcol for multiarch builds

- .gitlab-ci.yml
- CHANGELOG.md
- internal/buildscripts/packaging/release/gh-release-notes.sh
Requires #4908 
- Build/push the linux multiarch manifest and image
- Include the windows 2019 and 2022 images in the `quay.io/signalfx/splunk-otel-collector` manifest for releases, in addition to the linux images.
- Push manifests for each individual linux and windows images (for backward compatibility until we decide to stop in a future release).
- Push the windows manifests/images to both `quay.io/signalfx/splunk-otel-collector` and `quay.io/signalfx/splunk-otel-collector-windows` (for backward compatibility until we decide to stop in a future release).
- Miscellaneous fixes/improvements to the gitlab pipeline.
> Update gitlab for multiarch manifest builds

- .gitlab-ci.yml
Sign the deprecated `quay.io/signalfx/splunk-otel-collector-windows` 2019 and 2022 manifests.
> Sign old windows 2019 and 2022 manifests

- .github/workflows/auto-instrumentation.yml
- .github/workflows/build-and-test.yml
- .github/workflows/darwin-test.yml
- .github/workflows/gendependabot.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint-examples.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/vuln-scans.yml
- .github/workflows/win-package-test.yml
- .github/workflows/windows-test.yml
- .gitlab-ci.yml
- CHANGELOG.md
- internal/tools/go.mod
- pkg/processor/timestampprocessor/go.mod
For CVE-2024-24790, [GO-2024-2887](https://pkg.go.dev/vuln/GO-2024-2887)
> Upgrade golang to 1.21.11

- go.mod
- go.sum
- tests/go.mod
- tests/go.sum
> Bump github.com/mostynb/go-grpc-compression to v1.2.3

- deployments/chef/recipes/collector_win_config_options.rb
- deployments/chef/recipes/collector_win_install.rb
- deployments/chef/recipes/collector_win_registry.rb
- deployments/chef/recipes/default.rb
Leverage the latest MSI capabilities so we don't rely on custom Chef code to install the collector on Windows. At this point if the user wants to install only the collector on Windows they can directly use https://docs.chef.io/resources/windows_package/
The change itself move the handling of the configuration options (env. vars) to a step before installing the MSI. The MSI properties are passed on all versions since legacy versions would simply ignore the unknown properties. The code to setup the registry is only invoked when installing a MSI version that doesn't support the install properties.
**Testing:** CI
This change is not noticeable to end users, they can keep using the same settings that they used before.
> Use msi capabilities for chef

- deployments/cloudfoundry/bosh/README.md
- deployments/cloudfoundry/buildpack/README.md
- deployments/cloudfoundry/tile/DEVELOPMENT.md
- deployments/cloudfoundry/tile/README.md
Our `linkChecker` CI action [started failing](https://github.com/signalfx/splunk-otel-collector/actions/runs/9468176772/job/26083932834?pr=4969) due to broken Tanzu links. I contacted the Tanzu team and was informed that the URL has been moved from: 
```
https://docs.vmware.com/en/Tile-Developer-Guide/3.0/tile-dev-guide/index.html
```
to
```
https://docs.vmware.com/en/VMware-Tanzu-Operations-Manager/3.0/tile-dev-guide/index.html
```
I've updated all links accordingly.
> Fix broken Tanzu doc links

- .github/workflows/vuln-scans.yml
Run snyk scan jobs only if the token is available. The snyk token secret is unavailable for PRs from external contributors, including dependabot, which causes the workflow to fail.
Also:
- Run the vulnerability scan workflow every weekday at midnight
- Fix snyk scan for arm64 collector images
> Check for token before running snyk scans

- .github/workflows/puppet-test.yml
- deployments/puppet/manifests/collector_win_config_options.pp
- deployments/puppet/manifests/collector_win_install.pp
- deployments/puppet/manifests/collector_win_registry.pp
- deployments/puppet/manifests/init.pp
- deployments/puppet/manifests/params.pp
- internal/buildscripts/packaging/tests/deployments/puppet/puppet_test.py
Leverage the latest MSI capabilities so we don't rely on custom Puppet code to install the collector on Windows. At this point if the user wants to install only the collector on Windows they can directly use https://www.puppet.com/docs/puppet/8/types/package.html
The change itself move the handling of the configuration options (env. vars) to a step before installing the MSI. The MSI properties are passed on all versions since legacy versions would simply ignore the unknown properties. The code to setup the registry is only invoked when installing a MSI version that doesn't support the install properties or additional environment variables were specified for the setup (it is easy to setup everything in the registry than read the registry and merge the additional …
> Use msi capabilities for puppet

- .github/workflows/integration-test.yml
- tests/receivers/scriptedinputs/testdata/resource_logs/iostat.yaml
- Move binary build to a separate job
- Add new `integration-test-binary` job to install and test the otelcol binary and agent-bundle directly on ubuntu 20.04, 22.04, and 24.04 runners, in addition to the existing job that only tests the collector docker image
> integration-test workflow updates

- .github/workflows/windows-test.yml
Ensure that the required port on the Windows dynamic range is available prior to running the collector.
Many of the failures related to starting the collector on CI are due to the fact that a port in the dynamic range is taken by some applications on Windows. This change ensures that the required port is available for the Windows tests that start the collector with the default configuration.
Same was done for other Windows tests, `windows-test` was missed, see #4653
> Reduce CI test flakiness of windows-test job

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
Add upstream [Active Directory DS receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/activedirectorydsreceiver) to the Splunk distro.
> Add Active Directory DS receiver

- .github/workflows/puppet-test.yml
- deployments/puppet/CHANGELOG.md
- deployments/puppet/lib/facter/win_collector_path.rb
- deployments/puppet/lib/facter/win_collector_version.rb
- deployments/puppet/lib/facter/win_programdata.rb
- deployments/puppet/lib/facter/win_programfiles.rb
- deployments/puppet/lib/facter/win_systemdrive.rb
- deployments/puppet/lib/facter/win_temp.rb
- deployments/puppet/manifests/collector_service_owner.pp
- deployments/puppet/manifests/init.pp
- deployments/puppet/manifests/params.pp
- deployments/puppet/metadata.json
- deployments/puppet/spec/classes/init_spec.rb
- internal/buildscripts/packaging/tests/deployments/puppet/images/deb/Dockerfile.debian-bullseye
- internal/buildscripts/packaging/tests/deployments/puppet/images/deb/Dockerfile.debian-buster
- internal/buildscripts/packaging/tests/deployments/puppet/images/deb/Dockerfile.ubuntu-bionic
- internal/buildscripts/packaging/tests/deployments/puppet/images/deb/Dockerfile.ubuntu-focal
- internal/buildscripts/packaging/tests/deployments/puppet/images/deb/Dockerfile.ubuntu-jammy
- internal/buildscripts/packaging/tests/deployments/puppet/puppet_test.py
- Use `$facts['os']['family']` instead of the legacy `$::osfamily` fact
- Add test support for puppet 8
Replaces https://github.com/signalfx/splunk-otel-collector/pull/4996
> puppet: Use structured os.family hash fact

- internal/buildscripts/update-deps
- Remove hacky instructions (no longer needed)
- Just run the following commands to update all matching packages:
- `go get go.opentelemetry.io/collector/...@${CORE_VERSION}`
- `go get github.com/open-telemetry/opentelemetry-collector-contrib/...@${CONTRIB_VERSION}`
> Simplify the update-deps script

- .github/workflows/win-package-test.yml
- tests/zeroconfig/windows/testdata/resource_traces/aspnetcore.yaml
- tests/zeroconfig/windows/testdata/resource_traces/aspnetfx.yaml
- Add `host.id: <ANY>` to golden files to support latest splunk-otel-dotnet version
- Update test to use splunk-otel-dotnet version from `instrumentation/packaging/dotnet-agent-release.txt`
> Fix dotnet-zeroconfig-e2e-test

- .github/workflows/integration-test.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/vuln-scans.yml
- Removes the need for qemu
- Saves over an hour of build time if there is a cache miss
> Build arm64 agent-bundle on otel-arm64 runner

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
Added upstream [Splunk Enterprise](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/splunkenterprisereceiver) receiver to the Splunk-otelcol distro.
> added to components.go

- deployments/chef/kitchen.yml
Chef tests for centos-8 are failing since mirror doesn't have a version 8 anymore (which is already EOL), some removing it to avoid failures.
Failed run: https://github.com/signalfx/splunk-otel-collector/actions/runs/9654110000/job/26687077886#step:4:67
> Remove centos-8 from chef tests

- go.mod
- go.sum
- pkg/processor/timestampprocessor/go.mod
- pkg/processor/timestampprocessor/go.sum
- tests/receivers/kong/testdata/kong_metrics_expected.yaml
Update OpenTelemetry Dependencies to latest
> Bump google.golang.org/genproto/googleapis/rpc to v0.0.0-20240617180043-68d350f18fd4

- cmd/otelcol/config/collector/config.d.linux/receivers/mongodb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml.tmpl
Remove host.transport config option since it's removed upstream.
> [chore] [discovery] Update mongodb default config

- CHANGELOG.md
- internal/settings/settings.go
After the removal of the memory_ballast extension in v0.97.0, the Go garbage collection is running more aggressively, which increases CPU usage and leads to reduced throughput of the collector. This change reduces the frequency of garbage collection cycles to improve the collector's performance for typical workloads. As a result, the collector will report higher memory usage, but it will be bound to the same configured limits. If you want to revert to the previous behavior, set the `GOGC` environment variable to `100`.
> Set Go garbage collection target percentage to 400%

- .github/workflows/ansible.yml
- deployments/ansible/molecule/config/windows.yml
- deployments/ansible/molecule/shared/install_nodejs.yml
- Pre-download the windows vagrant box to allow starting the VM from a local box file instead of relying on the vagrant registry.
- Add retry when downloading nodejs for linux instrumentation tests
> ansible: Fix windows tests

- internal/receiver/discoveryreceiver/correlation.go
- internal/receiver/discoveryreceiver/correlation_test.go
- internal/receiver/discoveryreceiver/endpoint_tracker.go
- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
- internal/receiver/discoveryreceiver/evaluator.go
- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
- internal/receiver/discoveryreceiver/statement_evaluator.go
- internal/receiver/discoveryreceiver/statement_evaluator_test.go
The interface has only one implementation in the same package so it doesn't introduce any value. Following up https://github.com/signalfx/splunk-otel-collector/pull/4728#discussion_r1580027610
> [chore] [receiver/discovery] Remove redundant correlationStore interface

- deployments/chef/kitchen.yml
Chef tests for centos-7 are failing since mirror doesn't exist anymore, although, we could replace the mirror there is no point in doing it since centos-7 just reached EOL so removing it.
* https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve
* https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
* https://github.com/signalfx/splunk-otel-collector/actions/runs/9752697846/job/26950277365#step:4:4228
> Remove centos-7 from chef tests

- internal/buildscripts/packaging/tests/images/rpm/Dockerfile.centos-7
- internal/buildscripts/packaging/tests/images/tar/Dockerfile.tar-centos-7
- internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.centos-7
Replaces yum repo with the archived centos repo (no updates) since centos 7 is officially EOL starting June 30th 2024.
> update centos7 yum repo to use the archive

- .gitlab-ci.yml
xray-instrumentation-[rpm|deb] and xray-collector jobs are running in gitlab on schedule but failing due to dependent jobs not being configured to run on schedule. Not sure if these are intended to run on schedule. Updating the condition to use rules instead of only/except which are deprecated and to not run when trigger is schedule for now.
> [chore] update xray scan jobs with only condition

- .github/workflows/auto-instrumentation.yml
- .github/workflows/build-and-test.yml
- .github/workflows/darwin-test.yml
- .github/workflows/gendependabot.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint-examples.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/vuln-scans.yml
- .github/workflows/win-package-test.yml
- .github/workflows/windows-test.yml
- .gitlab-ci.yml
- CHANGELOG.md
- internal/tools/go.mod
- pkg/processor/timestampprocessor/go.mod
For CVE-2024-24791, [GO-2024-2963](https://pkg.go.dev/vuln/GO-2024-2963)
> Upgrade to golang 1.21.12

- .snyk
- Update snyk to ignore [SNYK-GOLANG-GITHUBCOMJACKCPGXV4-7416900](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJACKCPGXV4-7416900).
- [GO-2024-2567](https://pkg.go.dev/vuln/GO-2024-2567) only affects v5 and we are currently only dependent on v4.
> snyk: ignore GO-2024-2567 false positive

- Makefile
- tests/receivers/smartagent/collectd-activemq/collectd_activemq_test.go
- tests/receivers/smartagent/collectd-cassandra/collectd_cassandra_test.go
- tests/receivers/smartagent/collectd-kafka/collectd_kafka_test.go
- tests/receivers/smartagent/collectd-tomcat/tomcat_test.go
- tests/testutils/README.md
- tests/testutils/collector_container.go
- tests/testutils/collector_container_test.go
- tests/testutils/golden.go
- Change default image for integration tests from `quay.io/signalfx/splunk-otel-collector-dev:latest` to `otelcol:latest`
- Update smartagent and golden file tests to actually test with the image from the `SPLUNK_OTEL_COLLECTOR_IMAGE` env var or skip
> Set default image for integration tests to otelcol:latest

- .gitlab/update-otel-deps.sh
- internal/buildscripts/update-deps
The `update-otel-deps-nightly` gitlab job has been failing due to 60 minute timeouts. This updates the `update-deps` script to bypass the golang proxy when updating core/contrib deps to `main`.
> Fix timeout failure for update-otel-deps-nightly gitlab job

- cmd/otelcol/config/collector/config.d.linux/receivers/kafkametrics.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/kafkametrics.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/kafkametrics.discovery.yaml.tmpl
**Description:** Kafkametrics server cannot communicate to brokers with localhost:9092/ 127.0.0.1:9092 endpoints. 
**Testing:** locally
> fix to kafkametrics k8s issues

- .github/workflows/cla.yml
Whenever I use my branch to test some GH action changes I get the error for this action, by default it should run only on the original repository, not on forks.
There are other GH actions that may deserve the same but this one is a low hanging fruit. I will look at others as I do other GH action tests in my fork.
> Do not run CLA Assistant on repository forks

- .gitlab/common.sh
- .gitlab/update-otel-deps.sh
Enable the `update-otel-deps-nightly` gitlab job to push new commits to an existing PR for nightly github workflow runs.
> Allow commits to open PRs from gitlab

- .github/workflows/vuln-scans.yml
- .gitlab-ci.yml
The image is the same, so no noticeable changes to the collector image.
```
$ docker buildx imagetools inspect mcr.microsoft.com/windows/servercore:1809
Name:      mcr.microsoft.com/windows/servercore:1809
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:41f42aa4ad39d85e4d30642b8111ca6454ca2275f188f012934b9afbaf63a647
Manifests: 
Name:       mcr.microsoft.com/windows/servercore:1809@sha256:f44fdada7eb2e71f80c964b2759421f4f7645a2df97a12aa82f66a8d50410414
MediaType:  application/vnd.docker.distribution.manifest.v2+json
Platform:   windows/amd64
OSVersion:  10.0.17763.6054
OSFeatures: win32k
```
```
$ docker buildx imagetools inspect mcr.microsoft.com/windows/servercore:ltsc2019
Name:      mcr.microsoft.com/windows/servercore:ltsc2019
MediaType: …
```
> Use ltsc2019 tag for windows 2019 base image

- .github/workflows/ansible.yml
Hopefully helps with vagrant/virtualbox flakiness
> ansible: use ubuntu-24.04 runner for windows tests

- tests/testutils/golden.go
`collectorOptionsFunc` passed to `CheckGoldenFileWithCollectorOptions` are only applied only if they mutate the original object, e.g. `WithEnv`. Other options are not applied because the result of the function call is ignored.
> [testutils] Fix collector opts in CheckGoldenFileWithCollectorOptions

- .gitlab-ci.yml
Add vulnerability scanning to the gitlab pipeline for the collector docker image (the `/prodsec/.container-scan.yml` template currently only supports `linux/amd64` images).
> gitlab: scan docker image

- CHANGELOG.md
- internal/configsource/source.go
Deprecate usage of bare environment variables and config sources in configuration files.
- Use `${env:VAR}` or `${VAR}` instead of `$VAR`.
- Use `${uri:selector}` instead of `$uri:selector`, e.g. `${file:/path/to/file}` instead of `$file:/path/to/file`.
Detect such usages and print a deprecation warning. It's ok to not use logger because it's not initiated at this point yet. We use `log.Print` at this stage in other places as well.
> Deprecate usage of bare env vars and config sources

- cmd/otelcol/config/collector/upstream_agent_config.yaml
Jira: [DOCGUILD-26337](https://splunk.atlassian.net/browse/DOCGUILD-26337)
The user docs page [Send telemetry using the OpenTelemetry Collector Contrib project](https://docs.splunk.com/observability/en/gdi/other-ingestion-methods/upstream-collector.html) includes as a sample config the YAML file that this PR edits. The docs link directly to this YAML file, as you can see here: https://github.com/splunk/public-o11y-docs/blob/main/gdi/other-ingestion-methods/upstream-collector.rst#sample-configuration-for-splunk-observability-cloud
The YAML file does not use the `splunk_hec` exporter, as it is not ultimately used in the pipelines. However, I don't know if it is specified for another reason, so let's review this PR carefully.
> Remove splunk_hec exporter from upstream_agent_config

- go.mod
- go.sum
- internal/signalfx-agent/go.mod
- internal/signalfx-agent/go.sum
- pkg/receiver/smartagentreceiver/go.mod
- pkg/receiver/smartagentreceiver/go.sum
- tests/go.mod
- tests/go.sum
For [GO-2024-3005](https://pkg.go.dev/vuln/GO-2024-3005)
> Bump github.com/docker/docker to v26.1.5+incompatible

- internal/buildscripts/packaging/installer/install.sh
After clarification from @pjanotti, remove the dependency between the `--otlp-endpoint` and `--otlp-endpoint-protocol` options for configuring the `OTEL_EXPORTER_OTLP_ENDPOINT` and `OTEL_EXPORTER_OTLP_PROTOCOL` env vars.
> linux installer script: decouple the endpoint and protocol options

- internal/configconverter/config_server.go
- internal/configconverter/config_server_test.go
It seems that some change either on the runner or the actual OS is exposing a race in which the previous test case didn't release the port yet.
> Fix TestConfigServer flakiness on Windows and mac

- CHANGELOG.md
`ElasticSearch` -> `Elasticsearch`
> [chore] Fix changelog capitalization

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/telegraf/monitors/exec/exec.go
- internal/signalfx-agent/pkg/monitors/telegraf/monitors/exec/metadata.yaml
Deprecate the telegraf/exec plugin.
> deprecate telegraf/exec

- internal/configconverter/config_server_test.go
It seems that somehow the `TestConfigServer_RequireEnvVar` is being launched with the environment variable `SPLUNK_DEBUG_CONFIG_SERVER` set to `true`. This seems to happen when `go test -v -cover ./...` is launched on a GH runner. I can't reproduce it locally, in light of that, I'm opting to enforce the condition required by the test at its own status.
> Make TestConfigServer_RequireEnvVar environment consistent

- internal/receiver/discoveryreceiver/factory.go
- internal/receiver/discoveryreceiver/factory_test.go
The `Validate` method is implicitly called by the config resolver, no need to call it in the constructor.
> [recveiver/discovery] [chore] Remove redundant config.Validate() call

- internal/common/sharedcomponent/package_test.go
- internal/common/sharedcomponent/sharedcomponent.go
- internal/common/sharedcomponent/sharedcomponent_test.go
- internal/receiver/discoveryreceiver/factory.go
- internal/receiver/discoveryreceiver/factory_test.go
- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
- internal/receiver/discoveryreceiver/receiver.go
- internal/receiver/discoveryreceiver/receiver_test.go
This change will be used to convert the discovery receiver into long running receiver that would discover services and emit entity events along with the metrics without requiring the restart of the collector
I had to copy the sharedcomponent package from upstream to use the same instance of the discovery receiver work in both logs and metrics pipelines
> [discovery/receiver] Emit metrics from discovered services

- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
This gives the test a little more time to get to the expected state.
[Example test failure](https://github.com/signalfx/splunk-otel-collector/actions/runs/10240393182/job/28327164831?pr=5178)
> [chore] Address flaky test TestEntityEmittingLifecycle

- .github/workflows/integration-test.yml
Intended to resolve out of space errors seen [here](https://github.com/signalfx/splunk-otel-collector/actions/runs/10374366437/job/28723529340?pr=5225). This simply copies what we're currently doing for the `docker-otelcol` action.
[Action reference here.](https://github.com/jlumbroso/free-disk-space)
> [chore] Free GitHub runner space before docker integration tests

- .github/workflows/integration-test.yml
https://github.com/shogo82148/actions-setup-redis/issues/958 is fixed now. Keeping the version pinned since it's tracked by the dependabot anyway. That way, it's easier to pinpoint any issue during explicit upgrades.
> [chore] Remove redundant CI comments

- deployments/ansible/CHANGELOG.md
- deployments/ansible/galaxy.yml
- deployments/ansible/molecule/with_instrumentation_preload_custom/converge.yml
- deployments/ansible/molecule/with_instrumentation_preload_custom/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_default/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_dotnet/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_java/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_nodejs/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_without_npm/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_custom/converge.yml
- deployments/ansible/molecule/with_instrumentation_systemd_custom/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_default/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_dotnet/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_java/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_nodejs/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_without_npm/verify.yml
- deployments/ansible/roles/collector/README.md
- deployments/ansible/roles/collector/defaults/main.yml
- deployments/ansible/roles/collector/templates/00-splunk-otel-auto-instrumentation.conf.j2
- deployments/ansible/roles/collector/templates/dotnet.conf.j2
- deployments/ansible/roles/collector/templates/java.conf.j2
- deployments/ansible/roles/collector/templates/node.conf.j2
Similar to the installer script changes in #5029:
- change the default for `splunk_otel_auto_instrumentation_otlp_endpoint` from `http://127.0.0.1:4317` to empty
- add new `splunk_otel_auto_instrumentation_metrics_exporter` and `splunk_otel_auto_instrumentation_otlp_endpoint_protocol` options
> ansible: Support splunk-otel-java v2

- .github/workflows/build-and-test.yml
- go.mod
When the tidy step fails, the message printed out is actually:
```
One or more Go files are not tidied. Run 'make for-all CMD=make tidy' and push the changes.
```
The `"` around `make tidy` get dropped, which means you can't copy-paste to your local terminal and run.
**Testing:**
I made this PR fail tidy on purpose, output of failure:
```
require (
+	github.com/alecthomas/participle/v2 v2.1.1
github.com/antonmedv/expr v1.15.5
github.com/cenkalti/backoff/v4 v4.3.0
github.com/expr-lang/expr v1.16.9
One or more Go files are not tidied. Run 'make for-all CMD="make tidy"' and push the changes.
```
> [chore] Update tidy comment

- README.md
Fix a doc comment that is invalid. See https://github.com/signalfx/splunk-otel-collector/blob/80c54cdf0e9e7c15cfac0138069af99a5cdcd5bf/internal/configconverter/config_server.go#L134 for the algorithm.
> Fix an invalid doc reference

- .github/workflows/win-package-test.yml
- internal/buildscripts/packaging/choco/splunk-otel-collector/tools/chocolateyinstall.ps1
choco upgrades currently fail:
```
PS C:\Windows\system32> choco upgrade -y splunk-otel-collector
Chocolatey v1.3.1
Upgrading the following packages:
splunk-otel-collector
By upgrading, you accept licenses for the packages.
You have splunk-otel-collector v0.106.0 installed. Version 0.106.1 is available based on your source(s).
Progress: Downloading splunk-otel-collector 0.106.1... 100%
splunk-otel-collector v0.106.1 [Approved]
splunk-otel-collector package files upgrade completed. Performing other installation steps.
Checking configuration parameters ...
Checking for previous installation...
Found a previous installation...
Service registry entry key found: HKLM:\SYSTEM\CurrentControlSet\Services\splunk-otel-collector
Found previous environment variables for the splunk-otel-collector …
```
> fix choco package upgrades

- deployments/chef/CHANGELOG.md
- deployments/chef/README.md
- deployments/chef/attributes/default.rb
- deployments/chef/kitchen.yml
- deployments/chef/metadata.rb
- deployments/chef/templates/00-splunk-otel-auto-instrumentation.conf.erb
- deployments/chef/templates/dotnet.conf.erb
- deployments/chef/templates/java.conf.erb
- deployments/chef/templates/node.conf.erb
- deployments/chef/test/integration/with_custom_preload_dotnet_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_preload_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_preload_java_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_preload_node_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_systemd_dotnet_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_systemd_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_systemd_java_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_systemd_node_instrumentation/test.rb
- deployments/chef/test/integration/with_default_preload_dotnet_instrumentation/test.rb
- deployments/chef/test/integration/with_default_preload_instrumentation/test.rb
- deployments/chef/test/integration/with_default_preload_instrumentation_without_npm/test.rb
- deployments/chef/test/integration/with_default_preload_java_instrumentation/test.rb
- deployments/chef/test/integration/with_default_preload_node_instrumentation/test.rb
- deployments/chef/test/integration/with_default_systemd_dotnet_instrumentation/test.rb
- deployments/chef/test/integration/with_default_systemd_instrumentation/test.rb
- deployments/chef/test/integration/with_default_systemd_instrumentation_without_npm/test.rb
- deployments/chef/test/integration/with_default_systemd_java_instrumentation/test.rb
- deployments/chef/test/integration/with_default_systemd_node_instrumentation/test.rb
Similar to the installer script changes in https://github.com/signalfx/splunk-otel-collector/pull/5029:
- change the default for `auto_instrumentation_otlp_endpoint` from `http://127.0.0.1:4317` to empty
- add new `auto_instrumentation_metrics_exporter` and `auto_instrumentation_otlp_endpoint_protocol` options
> chef: support splunk-otel-java v2

- .golangci.yml
- internal/settings/settings_test.go
- internal/signalfx-agent/pkg/monitors/ecs/ecs_test.go
- internal/signalfx-agent/pkg/monitors/haproxy/monitor.go
- internal/signalfx-agent/pkg/utils/timeutil/duration_test.go
Follow up on linter change as per https://github.com/signalfx/splunk-otel-collector/pull/5268
> Swap linters to use copyloopvar after exitloopref was deprecated

- .github/workflows/vuln-scans.yml
The `govulncheck` job won't fail if vulns are found. Instead, similar to our other vuln scan jobs, the vulns will be added to https://github.com/signalfx/splunk-otel-collector/security/code-scanning and can be manually dismissed when there are false positives.
> govulncheck: generate sarif report

- .golangci.yml
- internal/confmapprovider/discovery/properties/property.go
- internal/receiver/signalfxgatewayprometheusremotewritereceiver/mock_reporter_test.go
- internal/signalfx-agent/pkg/monitors/cadvisor/converter/converter.go
- internal/signalfx-agent/pkg/monitors/collectd/collectd.go
- internal/signalfx-agent/pkg/monitors/diskio/diskio_others.go
- internal/signalfx-agent/pkg/monitors/docker/conversion.go
- internal/signalfx-agent/pkg/monitors/filesystems/filesystems.go
- internal/signalfx-agent/pkg/monitors/filesystems/partitions_windows.go
- internal/signalfx-agent/pkg/monitors/filesystems/partitions_windows_test.go
- internal/signalfx-agent/pkg/monitors/jaegergrpc/jaegerprotobuf/trace_jaeger.go
- internal/signalfx-agent/pkg/monitors/kubernetes/kubeletmetrics/metrics.go
- internal/signalfx-agent/pkg/monitors/kubernetes/kubeletmetrics/monitor.go
- internal/signalfx-agent/pkg/monitors/kubernetes/volumes/volumes.go
- internal/signalfx-agent/pkg/monitors/memory/memory_darwin.go
- internal/signalfx-agent/pkg/monitors/memory/memory_linux.go
- internal/signalfx-agent/pkg/monitors/memory/memory_windows.go
- internal/signalfx-agent/pkg/monitors/netio/netio.go
- internal/signalfx-agent/pkg/monitors/processlist/processlist_windows.go
- internal/signalfx-agent/pkg/monitors/prometheusexporter/conversion.go
- internal/signalfx-agent/pkg/monitors/subproc/messages.go
- tests/testutils/endpoint.go
Removing lint suppression for G115: int overflow.
Fixed or suppressed the 3 locations outside `internal/signalfx-agent/pkg/monitors`, I will call these out via PR comments. For the `internal/signalfx-agent/pkg/monitors` I'm suppressing them line by line per Slack conversation, see https://splunk.slack.com/archives/G01L5S7BKLY/p1724431826011759?thread_ts=1724358192.342099&cid=G01L5S7BKLY
> Remove golang lint suppression for int overflow

- deployments/salt/README.md
- deployments/salt/splunk-otel-collector/auto_instrumentation.sls
- internal/buildscripts/packaging/tests/deployments/salt/salt_test.py
- Change default for `auto_instrumentation_otlp_endpoint` to empty
- Add `auto_instrumentation_otlp_endpoint_protocol`, `auto_instrumentation_metrics_exporter`, and `auto_instrumentation_logs_exporter` options
> salt: support java v2

- deployments/chef/CHANGELOG.md
- deployments/chef/README.md
- deployments/chef/attributes/default.rb
- deployments/chef/kitchen.yml
- deployments/chef/metadata.rb
- deployments/chef/templates/00-splunk-otel-auto-instrumentation.conf.erb
- deployments/chef/templates/dotnet.conf.erb
- deployments/chef/templates/java.conf.erb
- deployments/chef/templates/node.conf.erb
- deployments/chef/test/integration/with_custom_preload_dotnet_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_preload_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_preload_java_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_preload_node_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_systemd_dotnet_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_systemd_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_systemd_java_instrumentation/test.rb
- deployments/chef/test/integration/with_custom_systemd_node_instrumentation/test.rb
- deployments/chef/test/integration/with_default_preload_dotnet_instrumentation/test.rb
- deployments/chef/test/integration/with_default_preload_instrumentation/test.rb
- deployments/chef/test/integration/with_default_preload_instrumentation_without_npm/test.rb
- deployments/chef/test/integration/with_default_preload_java_instrumentation/test.rb
- deployments/chef/test/integration/with_default_preload_node_instrumentation/test.rb
- deployments/chef/test/integration/with_default_systemd_dotnet_instrumentation/test.rb
- deployments/chef/test/integration/with_default_systemd_instrumentation/test.rb
- deployments/chef/test/integration/with_default_systemd_instrumentation_without_npm/test.rb
- deployments/chef/test/integration/with_default_systemd_java_instrumentation/test.rb
- deployments/chef/test/integration/with_default_systemd_node_instrumentation/test.rb
Support configuration of `OTEL_LOGS_EXPORTER`. Follow up to https://github.com/signalfx/splunk-otel-collector/pull/5160.
> chef: add logs exporter option

- deployments/ansible/CHANGELOG.md
- deployments/ansible/galaxy.yml
- deployments/ansible/molecule/with_instrumentation_preload_custom/converge.yml
- deployments/ansible/molecule/with_instrumentation_preload_custom/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_default/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_dotnet/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_java/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_nodejs/verify.yml
- deployments/ansible/molecule/with_instrumentation_preload_without_npm/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_custom/converge.yml
- deployments/ansible/molecule/with_instrumentation_systemd_custom/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_default/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_dotnet/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_java/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_nodejs/verify.yml
- deployments/ansible/molecule/with_instrumentation_systemd_without_npm/verify.yml
- deployments/ansible/roles/collector/README.md
- deployments/ansible/roles/collector/defaults/main.yml
- deployments/ansible/roles/collector/templates/00-splunk-otel-auto-instrumentation.conf.j2
- deployments/ansible/roles/collector/templates/dotnet.conf.j2
- deployments/ansible/roles/collector/templates/java.conf.j2
- deployments/ansible/roles/collector/templates/node.conf.j2
Support configuration of `OTEL_LOGS_EXPORTER`. Follow up to https://github.com/signalfx/splunk-otel-collector/pull/5133.
> ansible: add logs exporter option

- CHANGELOG.md
- internal/confmapprovider/discovery/discoverer.go
- internal/confmapprovider/discovery/discoverer_test.go
In #5202 the discovery code was changed so the collector ended its start up in case any observer failed to start - this behavior was agreed per [conversation](https://splunk.slack.com/archives/C02C8GVHL1Z/p1722025110851139). However, the docker observer had a behavior that if it failed to start on mac and Linux it didn't crash as in Windows. This cemented a behavior on the collector that was changed by #5202: the collector started successfully even if the docker observer failed. This change restores the previous behavior while not adding the risk of crashing in observers that failed to start (that's why it is not a simple reverse).
In the future we may want to consider if having a strict discovery mode is desirable. In this mode the user could enter an option to indicate that discovery …
> Discovery observers Start failures should not stop nor crash the collector

- .github/workflows/integration-test.yml
Tests for mongo 6 and 7 are flaky. Skipping for now. Reported a ticket to fix later
> [chore] Skip flaky mongodb discovery tests

- tests/receivers/apachewebserver/testdata/docker_observer_apachewebserver_config.yaml
This is done by really using the data obtained by the observer instead of hardcoding the endpoint. This makes it more realistic and also an example that we can refer to.
> [chore] Make Apache discovery test more meaningful

- tests/receivers/apachewebserver/testdata/docker_observer_apachewebserver_config.yaml
Using the `endpoint` directly instead of building it from `host` and `port`. Follow-up to #5325
> [chore] Simplify Apache container discovery test config

- go.mod
I'm getting "go: github.com/veraison/go-cose@v1.2.0: invalid version: unknown revision v1.2.0" trying to build the distro locally.
Apparently, github.com/veraison/go-cose v1.2.0 doesn't exist (likely removed) but is required by the latest github.com/Microsoft/hcsshim
> [chore] Add a replace statement for an unavailable module version

- .github/dependabot.yml
- .github/workflows/auto-instrumentation.yml
- .github/workflows/build-and-test.yml
- .github/workflows/darwin-test.yml
- .github/workflows/gendependabot.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint-examples.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/vuln-scans.yml
- .github/workflows/win-package-test.yml
- .github/workflows/windows-test.yml
- .gitlab-ci.yml
- go.mod
- internal/tools/go.mod
- pkg/extension/smartagentextension/go.mod
- pkg/processor/timestampprocessor/go.mod
- pkg/receiver/smartagentreceiver/go.mod
- tests/go.mod
For [GO-2024-3105](https://pkg.go.dev/vuln/GO-2024-3105), [GO-2024-3106](https://pkg.go.dev/vuln/GO-2024-3106), [GO-2024-3107](https://pkg.go.dev/vuln/GO-2024-3107)
> update golang to 1.22.7

- internal/confmapprovider/discovery/provider.go
There is no need to memoize the bundle config because the whole retrieved is memoized. So accessing the `"<bundle>"` key cannot happen twice.
> [chore] [discoverer] Remove redundant memoization

- docker/cassandra/Dockerfile
This reverts commit d8c510c43c3f0f92ca868192ed8bfb00be431b6b.
> Revert "Bump cassandra from 4.1 to 5.0 in /docker/cassandra (#5333)"

- internal/receiver/discoveryreceiver/factory_test.go
- internal/receiver/discoveryreceiver/receiver.go
Also, remove redundant synchronization
> [receiver/discovery] Allow the receiver to run for metrics only

- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/receiver.go
I missed some conditions in the previous PR. If the receiver was configured only on a metrics pipeline with any discovered services, it would block collector shutdown. This change fixes that. It's not a typical use case to enable it on the metrics pipeline only, so we don't need to test it extensively. It'd require an integration test. I'll be covered to some extent in the following PRs.
> [receiver/discovery] Fix metrics-only collection

- cmd/otelcol/config/collector/config.d.linux/receivers/apache.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/apache.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/apache.discovery.yaml.tmpl
- tests/receivers/apache/testdata/docker_observer_apache_config.yaml
On Debian based distros the process is named `apache2` not `httpd` as in other distros. This change just adds `apache2` to the matching expression.
Reference: https://askubuntu.com/a/248412
> Discover Apache web server on Debian based distros

- .github/workflows/win-package-test.yml
- internal/buildscripts/packaging/choco/splunk-otel-collector/tools/chocolateyinstall.ps1
Do not pass custom entries and untraditional env vars, e.g. var names with spaces, from the collector service's reg key as MSI arguments when installing/upgrading the choco package. Instead, just re-add them to the reg key after the MSI is installed.
> [OTL-3017] choco: handle custom env vars from registry

- go.mod
- internal/confmapprovider/discovery/discoverer.go
- internal/confmapprovider/discovery/discoverer_test.go
- internal/confmapprovider/discovery/provider_test.go
This change introduces a new way of how the discovery mechanism works. Instead of observing data for the first 10 seconds and creating a static `receiver_cretor` config from that, it'll be running discovery receiver watching for all supported receivers. Once a new endpoint for any supported service is available, the collector will try to fetch metrics from it. If the collector cannot get metrics from a new service right away, it'll send detailed information about what can be done to enable it to the backend, which will be reflected in the newly discovered services UI. Any services that are successfully discovered will also be reflected in the UI. The collector sends entity events as OTLP logs to deliver information about the discovered services.
The new functionality can be enabled with …
> Continuous service discovery

- deployments/chef/recipes/default.rb
**Description:** Fixing the error message displayed on error
Just changing the attribute to match the one actually expected.
> Fix error message when splunk_access_token is not set

- cmd/otelcol/config/collector/agent_config.yaml
- cmd/otelcol/config/collector/upstream_agent_config.yaml
- internal/configconverter/discovery.go
- internal/configconverter/discovery_test.go
- internal/confmapprovider/discovery/discoverer.go
- internal/confmapprovider/discovery/provider_test.go
- internal/confmapprovider/discovery/testdata/base-config.yaml
- tests/general/default_config_test.go
We cannot assume that ${SPLUNK_ACCESS_TOKEN} and ${SPLUNK_REALM} are aways set. It's not the case for the helm chart. We should move static config part of continuous discovery from discoverer to the config files. Having it in the `agent_config.yaml` has no overhead until the continuous discovery is enabled.
> [discovery] Move continuous discovery config parts to static files

- Makefile
- Makefile.Common
Making my life easier: a few times I ended losing time because I forgot to set the env var while building on Windows and kept testing an old build. While Windows can run executables without the `.exe` extension the terminal/shells don't like that in general and I have to manually rename or copy the result from the build.
Sorry about the link thing the `ln` from bash doesn't work at all on Windows so ...
> [chore] Build .exe files by default on Windows

- CHANGELOG.md
- cmd/otelcol/config/collector/config.d.linux/receivers/mongodb.discovery.yaml
- cmd/otelcol/config/collector/config.d.linux/receivers/mysql.discovery.yaml
- cmd/otelcol/config/collector/config.d.linux/receivers/oracledb.discovery.yaml
- cmd/otelcol/config/collector/config.d.linux/receivers/postgresql.discovery.yaml
- cmd/otelcol/config/collector/config.d.linux/receivers/redis.discovery.yaml
- cmd/otelcol/config/collector/config.d.linux/receivers/smartagent-collectd-mysql.discovery.yaml
- cmd/otelcol/config/collector/config.d.linux/receivers/smartagent-postgresql.discovery.yaml
- cmd/otelcol/config/collector/config.d.linux/receivers/sqlserver.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml.tmpl
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mysql.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mysql.discovery.yaml.tmpl
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/oracledb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/oracledb.discovery.yaml.tmpl
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/postgresql.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/postgresql.discovery.yaml.tmpl
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/redis.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/redis.discovery.yaml.tmpl
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-collectd-mysql.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-collectd-mysql.discovery.yaml.tmpl
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-postgresql.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-postgresql.discovery.yaml.tmpl
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/sqlserver.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/sqlserver.discovery.yaml.tmpl
The new format was suggested by the UI team. It'll be displayed in the Discovered Services UI
> [discovery] update instructions for partial discovery

- internal/receiver/discoveryreceiver/metric_evaluator.go
- internal/receiver/discoveryreceiver/metric_evaluator_test.go
We don't need to send discovery.receiver.type and discovery.receiver.name along with the metrics. They are meant to be used for discovery evaluation only
> [receiver/discovery] Remove redundant resource attributes

- cmd/otelcol/config/collector/agent_config.yaml
- cmd/otelcol/config/collector/ecs_ec2_config.yaml
- cmd/otelcol/config/collector/fargate_config.yaml
- cmd/otelcol/config/collector/full_config_linux.yaml
- cmd/otelcol/config/collector/gateway_config.yaml
- cmd/otelcol/config/collector/logs_config_linux.yaml
- cmd/otelcol/config/collector/otlp_config_linux.yaml
- cmd/otelcol/config/collector/upstream_agent_config.yaml
- tests/general/default_config_test.go
to retrieve access token from request context, add the key to batch processor as default. this is part of a series of changes related to deprecating sapm  in favor of otel
**Description:** add the metadata key to retrieve access token from context as default
> add metadata key to batch processor

- .github/workflows/otelcol-fips.yml
- .gitlab-ci.yml
- CHANGELOG.md
- Makefile
- cmd/otelcol/fips/build/Dockerfile.linux
- cmd/otelcol/fips/build/Dockerfile.windows
- cmd/otelcol/main_fipsonly.go
- Add `otelcol-fips` make target to build the standalone collector binary for linux (amd64/arm64) and windows (amd64).
- Usage:
- linux: `GOOS=linux GOARCH=<amd64|arm64> make otelcol-fips`
- windows: `GOOS=windows GOARCH=amd64 make otelcol-fips`
- Linux binaries are built with [`GOEXPERIMENT=boringcrypto`](https://go.dev/src/crypto/internal/boring/README) and [`crypto/tls/fipsonly`](https://go.dev/src/crypto/tls/fipsonly/fipsonly.go).
- Windows binaries are built  using [Microsoft's golang fork](https://github.com/microsoft/go) with [`GOEXPERIMENT=cngcrypto`](https://github.com/microsoft/go/blob/microsoft/main/eng/doc/fips/README.md) and [`requirefips`](https://github.com/microsoft/go/blob/microsoft/main/eng/doc/fips/README.md#build-option-to-require-fips-mode) (the collector will panic …
> fips: otelcol binaries for linux and windows

- .github/workflows/chef-test.yml
- deployments/chef/test/integration/custom_vars/test.rb
- deployments/chef/test/integration/default/test.rb
The tests were failing but in Windows we need to check the logs and we were not considering if any test was run. This fixes that and update the tests so they are all green (since they drifted from the actual behavior).
https://splunk.atlassian.net/browse/OTL-3063
> [chore] Fix chef/kitchen CI tests

- CHANGELOG.md
**Description:** In preparation for release v0.111.0
> Update changelog for v0.111.0

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/heroku/metadata.yaml
- internal/signalfx-agent/pkg/monitors/heroku/monitor.go
Deprecate the heroku observer. Use the [resource detection observer with heroku detector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor#heroku) instead.
> Deprecate heroku observer

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/cloudfoundry/README.md
- internal/signalfx-agent/pkg/monitors/cloudfoundry/monitor.go
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/cloudfoundryreceiver is now the preferred approach to integrate with Tanzu. See https://docs.splunk.com/observability/en/gdi/opentelemetry/deployments/deployments-pivotal-cloudfoundry.html for more information.
> Deprecate the cloudfoundry monitor in favor of the cloudfoundry receiver

- internal/signalfx-agent/cmd/monitorcodegen/main.go
- internal/signalfx-agent/cmd/monitorcodegen/metadata.go
Simple go refactoring to reduce API exposure.
> move selfdescribe in monitorcodegen, last place it's used

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/mongodb/atlas/metadata.yaml
- internal/signalfx-agent/pkg/monitors/mongodb/atlas/monitor.go
Deprecate mongodb atlas monitor. [Please use the mongodbatlasreceiver instead](https://docs.splunk.com/observability/en/gdi/opentelemetry/components/mongodb-atlas-receiver.html)
> Deprecate mongodb atlas monitor

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/statsd/metadata.yaml
- internal/signalfx-agent/pkg/monitors/statsd/monitor.go
Deprecate the statsd monitor, use statsd receiver
> Deprecate statsd monitor, use statsd receiver

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/windowslegacy/metadata.yaml
- internal/signalfx-agent/pkg/monitors/windowslegacy/windowslegacy_windows.go
Deprecate the windowslegacy monitor. A replacement for the monitor is the windowsperfcounters receiver.
> Deprecate windowslegacy monitor

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/collectd/consul/consul.go
- internal/signalfx-agent/pkg/monitors/collectd/consul/metadata.yaml
Deprecate the collectd/consul monitor. Please use the statsd or prometheus receiver instead. See https://developer.hashicorp.com/consul/docs/agent/monitor/telemetry for more information.
> Deprecate collectd/consul monitor

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
Add chrony receiver to the distribution.
> Add chronyreceiver

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/collectd/chrony/chrony.go
- internal/signalfx-agent/pkg/monitors/collectd/chrony/metadata.yaml
Deprecate the collectd/chrony monitor. Please use the [chronyreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/chronyreceiver) instead.
> Deprecate the collectd/chrony monitor

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/collectd/nginx/metadata.yaml
- internal/signalfx-agent/pkg/monitors/collectd/nginx/nginx.go
Deprecate the collectd/nginx monitor. Please use the [nginx receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/nginxreceiver/) instead.
> Deprecate collectd/nginx monitor

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/collectd/mysql/metadata.yaml
- internal/signalfx-agent/pkg/monitors/collectd/mysql/mysql.go
Deprecate collectd/mysql monitor. Use the [mysql receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mysqlreceiver) instead.
> Deprecate collectd/mysql monitor

- CHANGELOG.md
- cmd/otelcol/config/collector/ecs_ec2_config.yaml
- cmd/otelcol/config/collector/fargate_config.yaml
- cmd/otelcol/fips/config/ecs_ec2_config.yaml
- cmd/otelcol/fips/config/fargate_config.yaml
- deployments/ecs/ec2/README.md
- deployments/ecs/ec2/splunk-otel-collector.json
- deployments/fargate/README.md
- internal/signalfx-agent/pkg/monitors/ecs/ecs.go
- internal/signalfx-agent/pkg/monitors/ecs/metadata.yaml
Deprecate `ecs-metadata` monitor and set `awsecscontainermetrics` as the replacement.
* https://splunk.atlassian.net/browse/OTL-2834
**Testing:**
Deployed to https://app.signalfx.com/#/home `deployment.environment:otel-ecs-ec2-sidecar`
https://github.com/splunk/public-o11y-docs/pull/1576
> Deprecate ecs metadata monitor

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/haproxy/metadata.yaml
- internal/signalfx-agent/pkg/monitors/haproxy/monitor.go
Deprecate the haproxy monitor. Please use the [haproxyreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/haproxyreceiver) instead
> Deprecate haproxy monitor

- .github/workflows/linux-package-test.yml
The `awsecscontainermetrics` requires the env var `ECS_CONTAINER_METADATA_URI_V4` so I'm adding that to the test of the configs.
> Fix docker-otelcol-verify test

- CHANGELOG.md
- internal/signalfx-agent/pkg/monitors/collectd/statsd/metadata.yaml
- internal/signalfx-agent/pkg/monitors/collectd/statsd/statsd.go
Deprecate the collectd/statsd monitor. Use the statsd receiver instead.
> Deprecate the collectd/statsd monitor

- .lychee.toml
**Description:** Ignore `httpsinkexporter` link in CHANGELOG.md from linter since the exporter was deleted.
> Update link checker to ingore deleted exporter links from CHANGELOG.md

- .github/workflows/vuln-scans.yml
We are seeing our trivy scans failing constantly due to github rate limits. This PR updates the trivy github action to run with a newer version of trivy (default in the action is `0.56`) which has a feature to try ECR repo as fallback https://github.com/aquasecurity/trivy/pull/7679
> [chore] use newer trivy version with registry fallback feature

- .github/workflows/auto-instrumentation.yml
- .github/workflows/bosh-release.yml
- .github/workflows/build-and-test.yml
- .github/workflows/cloudfoundry_buildpack.yml
- .github/workflows/gendependabot.yml
- .github/workflows/installer-script-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint-examples.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/lychee.yml
- .github/workflows/puppet-test.yml
- .github/workflows/puppet.yml
- .github/workflows/release-requirements.yml
- .github/workflows/salt-test.yml
- .github/workflows/tanzu-tile.yml
- .github/workflows/vuln-scans.yml
- .github/workflows/win-package-test.yml
Skipping chef and ansible tests for now. They are still failing
> [chore] Upgrade ubuntu CI runners

- CHANGELOG.md
- cmd/otelcol/Dockerfile
- tests/receivers/smartagent/telegraf-exec/testdata/exec/Dockerfile
- tests/receivers/smartagent/telegraf-exec/testdata/exec/config.yaml
Use the latest debian image to build the journald client with the latest libraries. Otherwise, journald receiver doesn't work on nodes with latests OSs like Amazon Linux 2023.
> Upgrade journald client built in the docker image

- tests/receivers/smartagent/telegraf-exec/testdata/exec/Dockerfile
This line was accidentally removed in https://github.com/signalfx/splunk-otel-collector/pull/5664. Fixes https://github.com/signalfx/splunk-otel-collector/actions/runs/12152054403/job/33888059096
> Fix telegraf integration tests

- docs/troubleshooting.md
Documentation from the upstream repo was removed in https://github.com/open-telemetry/opentelemetry-collector/pull/11483
> [docs] Update upstream troubleshooting link

- .github/workflows/lychee.yml
- .lychee.toml
- Exclude checking PRs and issues. There are too many of them in CHANGELOG.md, so we always run into the rate limits.
- Use the latest lychee build that has fixed retries https://github.com/lycheeverse/lychee/pull/1573
- Increase the number of retries and retry timeout to workaround [secondary Github rate limiting](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits)
- Do not consider 429 successful
There is one failing link left which is fixed in https://github.com/signalfx/splunk-otel-collector/pull/5667
> [CI] Stabilize lychee links validation

- internal/settings/settings.go
- internal/settings/settings_test.go
If `SPLUNK_INGEST_URL` env var is set by the user, use it to populate a default value for `SPLUNK_TRACE_URL`.
This is a preliminary step before we can deprecate and stop using `SPLUNK_TRACE_URL`
> Preset default value for SPLUNK_TRACE_URL from SPLUNK_INGEST_URL

- cmd/otelcol/config/collector/agent_config.yaml
- cmd/otelcol/config/collector/gateway_config.yaml
- tests/general/default_config_test.go
To easily filter between agent and gateway deployments of the collector in dashboards a proposed new dimension `otelcol.service.mode` to be added to the `metrics/internal` pipeline.
N/A
**Testing:**
N/A - new PR for verified commits
N/A
> Added new dimension to internal metrics to identify mode

- .gitlab-ci.yml
- CHANGELOG.md
This PR changes the way we build internally to produce a Windows FIPS docker image, signed and combined with the Linux FIPS images with a multiarch tag.
Here is the result of the run:
* Windows FIPS image: https://quay.io/repository/signalfx/splunk-otel-collector-fips-windows-dev/manifest/sha256:fba0c70c4b1fb743ec319cf5d871464d0d8de84b506fd2f646161ff6ebc41cb1
* Linux FIPS image: https://quay.io/repository/signalfx/splunk-otel-collector-fips-dev/manifest/sha256:1f3a69d1dda9de055d8250d6a15e127080f595874a2b3fd311f6d032497be1c8
> Build Windows image for FIPS use cases

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
Picking up the work by @greatestusername-splunk from https://github.com/signalfx/splunk-otel-collector/pull/5722
> Add the snowflake receiver

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
HI!
This PR is to add the purefa receiver from contrib.
Pure Storage is a Splunk Partner with mutual customers who are looking to get their Pure Storage FlashArray Data into Splunk IM using the Splunk OTel Collector.
> Add the purefa receiver from contrib

- pkg/extension/smartagentextension/config_windows_test.go
- tests/internal/discoverytest/discoverytest.go
- tests/msi/msi_test.go
Nothing serious here, but, indication that there is no CI running pkg/extension/smartagentextension tests on Windows. Anyway, just detected issues on test code.
> [chore] Running lint on Windows

- .github/workflows/cla.yml
- .github/workflows/cleanup-closed-pr.yml
- .github/workflows/nomad.yml
- .github/workflows/splunk-ta-otel.yml
- .github/workflows/vuln-scans.yml
For consistency with other jobs where we want to avoid surprises when new ubuntu is released
> [chore] Pin CI runners to ubuntu-24.04

- CHANGELOG.md
- docs/components.md
- go.mod
- go.sum
- internal/components/components.go
- internal/components/components_test.go
This processor has functionality that is required to be able to remove the SignalFx exporter's translation rules
> Add metricsgeneration processor

- tests/general/discoverymode/configd_test.go
- tests/general/discoverymode/testdata/memory-expected.yaml
- tests/general/discoverymode/testdata/resource_metrics/memory.yaml
No op change of a test to use the golden library to compare data.
> move to use golden fixture files for memory metrics asserts

- go.mod
- go.sum
- internal/configsource/includeconfigsource/package_test.go
- internal/configsource/includeconfigsource/source.go
- internal/configsource/includeconfigsource/source_test.go
This was noticed while investigating failures to upgrade fsnotify, see https://splunk.atlassian.net/browse/OTL-3177
The `TestIncludeConfigSource_WatchFileUpdate` was deadlocking because a goroutine that empties the fsnotify event channel was bailing out on first write operation. The test deadlocked on trying to write another file event. The fixes on fsnotify for Windows file watching made surfaced the issue because prior to that it was really not listening to changes on the file.
In practice, the deadlock was an artifact from the test, on production, depending on the config source usage it meant that only the first file change was notified.
Test deadlock, for the record:
```terminal
=== RUN   TestIncludeConfigSource_WatchFileUpdate
panic: test timed out after 30s
running …
```
> Fix includeconfigsource handling of multiple file writes

- .github/workflows/ansible.yml
- deployments/ansible/molecule/config/docker.yml
Migrating CI runners from Ubuntu 20.04 to Ubuntu 24.04 means that the host VM for Ansible tests is switched from cgroups v1 to cgroups v2. This is a significant difference because we use docker containers to run Ansible Molecule tests connected to cgroups on the host VM. Making cgroups v1 OSs work in docker containers on a host with groups v2 appeared to be not possible based on my trials. 
I also tried to migrate to the full VM virtualization, from Docker to Vagrant. This made some particular VM boxes fail and increased test run time by 50%.
Eventually, I kept the old Ubuntu 20.04 workers to test OSs with groups v1 and the latest Ubuntu 24.04 to test OSs with groups v2. Once the old VMs are EOL'd, we can drop Ubuntu 20.04 workers.
> [chore] Upgrade CI workers for ansible tests

- cmd/otelcol/config/collector/fargate_config.yaml
- cmd/otelcol/fips/config/fargate_config.yaml
- deployments/fargate/README.md
> remove unused filter processor

- docker/apachespark/long_running.py
Do not exit running jobs on spark. It is possible the container may exit before the collector collects metrics
> Address apachespark test flakiness

- .github/workflows/chef-test.yml
- .github/workflows/chef.yml
- deployments/chef/kitchen.yml
The tests for old systems (amazonlinux-2, opensuse-12, oraclelinux-7) are removed. Newer versions of Chef v18.x+ come with ruby 3.1, which requires glibc 2.28. The removed systems go with glibc 2.26. We could've tested them with an old Chef version 17.x, but it has reached EOL.
> [draft] [chef] Upgrade CI workers for chef tests

- CHANGELOG.md
- internal/configsource/source.go
There is a deprecation for bare config source calls. `${source:value[?params]}` should be used instead of `$source:value[?params]`. 
It's also applied to multiline config source calls. One-line format like `${source:value?param1=val1,param2=val2}` should be used instead of multiline calls with a bare reference to a config source like the following DEPRECATED call:
```
config_field: |
$source: value
param1: val1
param2: val2
```
However, the deprecation warning is broken. This change fixes that. So instead of 
```
[WARNING] Config source expansion formatted as $uri:selector has been deprecated, use ${uri:selector[?params]} instead. Please replace $include: /Users/danoshin/Projects/otel-configs/memory-limiter.yaml
watch_files: true
with ${include: …
```
> [chore] Fix deprecation warning for multiline config source calls

- docs/components.md
There were two identical entries in the table for the Simple Prometheus receiver, so I've removed one.
> [chore] Remove duplicate receiver entry

- CHANGELOG.md
- README.md
- internal/configsource/includeconfigsource/README.md
- internal/configsource/source.go
- internal/configsource/source_test.go
- internal/configsource/testdata/arrays_and_maps.yaml
- internal/configsource/testdata/cfgsrc_load_use_cfgsrc.yaml
- internal/configsource/testdata/env_var_on_load.yaml
- internal/configsource/testdata/params_handling.yaml
- internal/configsource/testdata/params_handling_expected.yaml
- internal/configsource/testdata/yaml_injection.yaml
- internal/confmapprovider/configsource/testdata/manager_resolve_error.yaml
- tests/general/configsources/testdata/templated.yaml
- tests/general/discoverymode/host_observer_discovery_test.go
- tests/general/testdata/env_config_source_labels.yaml
- tests/general/testdata/env_config_source_labels_expected.yaml
- tests/general/testdata/envvar_labels.yaml
- tests/general/testdata/envvar_labels_expected.yaml
The expansion of bare config sources is no longer supported.
Strings like `$ENV` or `$include:/path/to/file.yaml` will no longer be expanded. Instead, use the `${env:ENV}` or `${include:/path/to/file.yaml}` syntax. Only two symbols are allowed after `$`: `{` and `$`. The collector will log an error and fail to start if it encounters a bare config source expansion.
This syntax has been deprecated since [version 0.105.0](https://github.com/signalfx/splunk-otel-collector/blob/main/CHANGELOG.md#deprecations--6).
The reason for this change is aligning with OpenTelemetry Collector upstream, where this syntax has been removed in [0.104.0 version](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md#v1110v01040). Long term plan is to do not have [the custom config …
> Stop supporting deprecated syntax for config source expansion

- .lychee.toml
Fixes the failing CI job https://github.com/signalfx/splunk-otel-collector/actions/runs/12956357003/job/36179333884?pr=5832
> [chore] Fix lychee test

- CHANGELOG.md
- internal/confmapprovider/discovery/discoverer.go
- tests/general/discoverymode/docker_observer_discovery_test.go
- tests/general/discoverymode/host_observer_discovery_test.go
- tests/receivers/envoy/bundled_k8s_test.go
- tests/receivers/envoy/bundled_test.go
- tests/receivers/mysql/bundled_test.go
- tests/receivers/oracledb/bundled_test.go
- tests/receivers/redis/bundled_test.go
This enables new way to discover third-party components and collect metrics from them:
- It allows discovering services that were not available at the time of the collector startup but were started later.
- Information about discovered services will be sent to Splunk Observability Cloud that can be found in "Discovered services" page. If you want to disable this feature and bring back the old behavior, add `--feature-gates=-splunk.continuousDiscovery` command line flag.
> Turn on `splunk.continuousDiscovery` feature gate by default

- tests/receivers/envoy/bundled_k8s_test.go
- tests/receivers/smartagent/postgresql/postgresql_test.go
- tests/testutils/golden.go
Attempt to make testing catch any intermediate metrics that we may have received instead of the latest metrics in the sink.
> try to match against metric received by the sink

- update-deps
When we run go get... and go tidy in particular modules, it may affect modules that depend on it. If the dependent modules are modified, running `go get ...` there fails with
```
go: updates to go.mod needed; to update it:
go mod tidy
```
In order to fix that, we need to run go tidy in all the modules after updating every module
> [chore] Fix update-deps script to not miss module upgrades

- tests/receivers/smartagent/telegraf-sqlserver/telegraf_sqlserver_test.go
Ignore `sql_version` attribute value since we don't pin the MySQL image version.
The latest go updated, and we are getting the `sql_version` attribute value mismatch errors:
```
-  resource "map[system.type:sqlserver]": scope "": metric "sqlserver_server_properties.cpu_count": missing expected datapoint: map[hardware_type: plugin:telegraf-sqlserver sku:Developer Edition (64-bit) sql_instance: sql_version:15.0.4415.2 telegraf_type:untyped]
-  resource "map[system.type:sqlserver]": scope "": metric "sqlserver_server_properties.cpu_count": unexpected datapoint: map[hardware_type: plugin:telegraf-sqlserver sku:Developer Edition (64-bit) sql_instance: sql_version:15.0.4420.2 telegraf_type:untyped]
```
> [chore] fix TestTelegrafSQLServerReceiverProvidesAllMetrics

- tests/testutils/golden.go
Currently, the test passes if there are no new metrics between the `assert.EventuallyWithT` tries because the for loop isn't executed, and the `err` is left to the initiated `nil.`
> [chore] Fix RunMetricsCollectionTest helper to avoid false positives

- tests/general/internal_metrics_test.go
- tests/general/testdata/internal_metrics_config.yaml
- tests/general/testdata/internal_metrics_expected.yaml
The test is needed for the 0.119.0 upgrade to validate that the output of the internal metrics isn't changed. There was a new unexpected metric added.
> [chore] Add an integration test to validate internal metrics

- Makefile
`compile` is failing on `main` due to the `govulncheck@master` package requiring `>= go 1.23`. Since we're still on `go 1.22` for testing, we can pin this dependency to the latest release instead. This should keep it updated enough to save us from manually updating it, while also preserving us from breaking changes in `master` unexpectedly between releases.
**Testing:**
```
$ go install golang.org/x/vuln/cmd/govulncheck@latest
$ govulncheck --version
Go: go1.22.10
Scanner: govulncheck@v1.1.4
```
> [chore] Pin govuln check to latest released version

- .github/dependabot.yml
- .github/workflows/auto-instrumentation.yml
- .github/workflows/build-and-test.yml
- .github/workflows/darwin-test.yml
- .github/workflows/gendependabot.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint-examples.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/otelcol-fips.yml
- .github/workflows/splunk-ta-otel.yml
- .github/workflows/vuln-scans.yml
- .github/workflows/win-package-test.yml
- .github/workflows/windows-test.yml
- .gitlab-ci.yml
- CHANGELOG.md
- cmd/otelcol/fips/build/Dockerfile.linux
- cmd/otelcol/fips/build/Dockerfile.windows
- examples/prometheus-federation/prom-counter/go.mod
- examples/splunk-hec-traces/tracing/go.mod
- examples/splunk-hec/logging/go.mod
- go.mod
- internal/signalfx-agent/go.mod
- internal/tools/go.mod
- pkg/extension/smartagentextension/go.mod
- pkg/processor/timestampprocessor/go.mod
- pkg/receiver/smartagentreceiver/go.mod
- tests/go.mod
- tests/tools/go.mod
This keeps us up to date with upstream
[Upstream contrib PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37875)
[Previous Splunk PR upgrading golang version](https://github.com/signalfx/splunk-otel-collector/pull/5248)
> Bump minimum go version to 1.23

- packaging/installer/install.ps1
Current `install.ps1` is not showing the exit code of the `msiexec.exe` run - this tiny PR fixes that.
> [tiny]Fix: display msiexec exit code on install.ps1

- .github/workflows/splunk-ta-otel.yml
Makes easier to get a not yet published Splunk_TA_otel by collecting the tgz as an asset of the CI run.
> [tiny] Upload Splunk_TA_otel as asset of splunk-ta-otel workflow

- tests/general/internal_metrics_test.go
- tests/general/testdata/internal_metrics_expected.yaml
Update resource attributes after the prometheus receiver upgrade to Prometheus 3.0 library. The dots in the names are not escaped anymore
> [chore] Update expected metrics for TestDefaultInternalMetrics test

- .github/workflows/integration-test.yml
A recent run of `integration-test-binary` failed due to a `No space left on device` error. This is the same step that's done before other integration tests that has successfully fixed this failure in other tests.
> [chore][integration-test-binary] Free disk space at test start

- tests/general/discoverymode/docker_observer_discovery_test.go
[Flaky test failure](https://github.com/signalfx/splunk-otel-collector/actions/runs/13842229250/job/38732965681), the deadline was hit here. This test failed without any recent relevant changes, so this PR attempts to have a less aggressive timeout to reduce flakiness.
> [chore][CI/CD] Extend docker observer test timeout

- go.mod
- go.sum
- internal/signalfx-agent/go.mod
- internal/signalfx-agent/go.sum
- pkg/extension/smartagentextension/go.mod
- pkg/receiver/smartagentreceiver/go.mod
- pkg/receiver/smartagentreceiver/go.sum
This PR consumes the latest telegraf signalfx fork to release this fix https://github.com/signalfx/telegraf/commit/931557f78bed123ac2f37ed56d083d395db3ee01
> [OTL-3328] Consume latest sfx telegraf fork - fixes winservices permission

- tests/receivers/scriptedinputs/testdata/script_config_cpu.yaml
- tests/receivers/scriptedinputs/testdata/script_config_df.yaml
- tests/receivers/scriptedinputs/testdata/script_config_hardware.yaml
- tests/receivers/scriptedinputs/testdata/script_config_interfaces.yaml
- tests/receivers/scriptedinputs/testdata/script_config_iostat.yaml
- tests/receivers/scriptedinputs/testdata/script_config_lastlog.yaml
- tests/receivers/scriptedinputs/testdata/script_config_lsof.yaml
- tests/receivers/scriptedinputs/testdata/script_config_netstat.yaml
- tests/receivers/scriptedinputs/testdata/script_config_openPorts.yaml
- tests/receivers/scriptedinputs/testdata/script_config_package.yaml
- tests/receivers/scriptedinputs/testdata/script_config_protocol.yaml
- tests/receivers/scriptedinputs/testdata/script_config_ps.yaml
- tests/receivers/scriptedinputs/testdata/script_config_top.yaml
- tests/receivers/scriptedinputs/testdata/script_config_who.yaml
The scripted inputs tests have flaky failures because no data is received within the 10s timeout. The original configuration of the receiver in each of these tests is to scrape [after one second](https://github.com/open-telemetry/opentelemetry-collector/blob/0e9e259750f8bc4485709067246cc869ec149781/scraper/scraperhelper/config.go#L36), then wait for another 10s from then to scrape again. The test waits 10s from starting and fails if no data is received. That means only one scrape occurs, 1 second after starting up. If the collector isn't fully up after 1 second, the test will fail without retrying to scrape.
This change updates the collection interval to scrape more often, hopefully not too frequently. If the collection interval is hit before …
> [chore][CI/CD] Reduce scriptedinputs collection interval

- tests/receivers/apachespark/testdata/all_metrics_config.yaml
[Recent failure](https://github.com/signalfx/splunk-otel-collector/actions/runs/13866560120/job/38807065209?pr=5980)
The test has a timeout of 30 seconds, so which means accounting for the initial delay and collection interval, the test would only scrape twice. 15 seconds should have been enough time to get metrics, but this test is flaky without any changes impacting it. This should at least help as there isn't any obvious bug occurring.
If the collection interval is hit before a previous scrape is complete, the scraper fails and the test fails, resulting in more flakiness. We have to balance it here.
> [chore][CI/CD][Apache Spark] Reduce collection interval in flaky test

- .gitlab-ci.yml
This job is used to update dependabot PRs with by automatically tidying them when necessary. It's currently only running on new PRs. This changes it to run when existing PRs are updated or the relevant branch is pushed.
> [chore][CI/CD] Run tidy action on PR update and push

- deployments/databricks/README.md
If a cluster is long-running, the script may not be able to be deployed as an init script. In this case, the user will manually have to run the script on each node. This PR updates documentation for directions on how to deploy manually.
> [chore][deployments/databricks] Add docs for deploying as standalone script

- .github/workflows/vuln-scans.yml
Running with scan mode `symbol` is preferable to scan mode `package` due to more precise diagnostics. A large runner has enough memory to do that reliably.
Successful runs:
1. https://github.com/signalfx/splunk-otel-collector/actions/runs/14071720581/job/39407165670?pr=6031
2. https://github.com/signalfx/splunk-otel-collector/actions/runs/14071833700/job/39407508906?pr=6031
> govulncheck: safely use scan mode symbol by using a large runner

- .github/workflows/scripts/govulncheck-run.sh
- .github/workflows/vuln-scans.yml
For consistency with other vulnerabilities scan the workflow should fail if vulnerabilites are detected.
Example of other vulnerability scans failing:
- https://github.com/signalfx/splunk-otel-collector/actions/runs/14010129646/job/39228865795
- https://github.com/signalfx/splunk-otel-collector/actions/runs/14010129646/job/39228866006
> Fail govulncheck if vulnerabilities are found

- CHANGELOG.md
- deployments/ansible/CHANGELOG.md
- deployments/chef/CHANGELOG.md
- deployments/chef/README.md
These links are being redirected straight to the preceding link now that SFx.NET is fully retired. Removing the old links that were failing lychee workflow: https://github.com/signalfx/splunk-otel-collector/actions/runs/14088064794/job/39457294595?pr=6034#step:3:3969
> [tiny][chore]Remove old redirected links for SFx.NET

- go.mod
- go.sum
- internal/signalfx-agent/go.mod
- internal/signalfx-agent/go.sum
- pkg/receiver/smartagentreceiver/go.mod
- pkg/receiver/smartagentreceiver/go.sum
- tests/go.mod
- tests/go.sum
Doing a single PR for this upgrade, supersedes two dependabot PRs:
- https://github.com/signalfx/splunk-otel-collector/pull/6005
- https://github.com/signalfx/splunk-otel-collector/pull/6006
> [chore] Upgrade go-sql-driver/mysql

- cmd/otelcol/config/collector/config.d.linux/receivers/mongodb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/mongodb.discovery.yaml.tmpl
With disabled direct connection, the mongodb receiver tries to discover other endpoints by itself. Given that the discovery receiver covers all endpoints on every node, such configuration can end up in cross-nodes scraping, metric duplication and failures. The mongodb receiver 0.121.0 was also changed to actively look for secondary hosts which may result in collector stuck on startup when it cannot reach other endpoints.
> Use direct_connection in mongodb discovery

- CHANGELOG.md
- deployments/databricks/deploy_collector.sh
A customer found that `curl` without the `-L` option was failing to properly download the collector. `-L` fixed it for them.
[More info on `curl -L`](https://curl.se/docs/manpage.html#-L)
Deployment script is working with the redirect in testing.
> [deployment/databricks] Ensure curl commands are properly redirected

- .codecov.yml
This relaxes main's target to be 50% coverage on PRs, and to target 85% for a PR's changed lines coverage. Originally suggested [here](https://github.com/signalfx/splunk-otel-collector/pull/6022#discussion_r2017173964) by @dmitryax
> [chore][codecov] Change coverage targets

- .github/workflows/vuln-scans.yml
I got a report of vulnerability detected by `anchore-scan`, but the scan didn't show any useful information about the scan, see https://github.com/signalfx/splunk-otel-collector/actions/runs/14158623610/job/39661248327?pr=6052#step:5:21
Surprisingly, the scan ended up clean here and on a retry on the original PR, but, reporting the vulnerabilities to GH code scanning is done for the other scans and more importantly ensures that we have some information in case of vulnerability detection.
> [chore][vuln-scan] Workaround anchore-scan not showing vulnerabilities

- .github/workflows/auto-instrumentation.yml
- .github/workflows/integration-test.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/vuln-scans.yml
Replaced qemu usage in the easiest CI jobs. This doesn't help much in reducing test flakiness since various integration tests are still using qemu. Anyway, it reduces the qemu usage in CI.
> [chore][CI] Replace some qemu usage for arm with GH runner

- .github/workflows/vuln-scans.yml
Supersedes #6079
Fixes the Snyk scan on arm: the `snyk/snyk:docker` doesn't have an image for ARM so it requires qemu if scanning an image for any ARM architecture.
Side change: add message with the likely cause in case of missing Snyk token.
> [chore][CI] Fix snyk vulnerability scan on arm

- examples/prometheus-federation/prom-counter/go.mod
- examples/splunk-hec-traces/tracing/go.mod
- examples/splunk-hec/logging/go.mod
- internal/signalfx-agent/go.mod
- internal/tools/go.mod
- packaging/dotnet-instr-deployer-add-on/go.mod
- pkg/extension/smartagentextension/go.mod
- pkg/processor/timestampprocessor/go.mod
- tests/go.mod
- tests/tools/go.mod
It seems that the modules with a version different than the one that we are using are the ones being hit by the toolchain upgrade issue by dependabot. Anyway, I'm not aware of any reason to keep these on older versions.
> [chore] Make go version consistent on all go.mod files

- cmd/otelcol/config/collector/agent_config.yaml
- cmd/otelcol/config/collector/ecs_ec2_config.yaml
- cmd/otelcol/config/collector/fargate_config.yaml
- cmd/otelcol/config/collector/full_config_linux.yaml
- cmd/otelcol/config/collector/otlp_config_linux.yaml
- cmd/otelcol/config/collector/upstream_agent_config.yaml
- cmd/otelcol/fips/config/agent_config.yaml
- cmd/otelcol/fips/config/ecs_ec2_config.yaml
- cmd/otelcol/fips/config/fargate_config.yaml
- cmd/otelcol/fips/config/otlp_config_linux.yaml
- packaging/fpm/etc/otel/collector/splunk-otel-collector.conf.example
- packaging/technical-addon/Splunk_TA_otel/configs/ta-agent-config.yaml
- packaging/technical-addon/Splunk_TA_otel/configs/ta-agent-to-gateway-config.yaml
- tests/general/default_config_test.go
> Update agent config to be otlp token passthrough ready

- Makefile
`|| true` means that any command will be successful and continue to the next step. This would make workflow runs green even if there were failures. This was helpful testing locally when code coverage output could be saved even with unsuccessful tests, but should be not in our branch.
This was introduced in my codecov changes yesterday: https://github.com/signalfx/splunk-otel-collector/pull/6084
> [chore][codecov] Fix muting errors bug in make targets

- .gitlab-ci.yml
Otherwise, we run out of disk due to pulling too many dependencies.  Set it to all jobs relying on go cache
> gitlab-ci: Use large runners for compilation

- .github/workflows/integration-test.yml
- Makefile
This change introduces `with-cover` targets for all integration tests.
Key changes
- Introduce reusable integration test targets in `Makefile`. The original `integration` targets are functionally unchanged, but no longer used in CI/CD.
- Create a directory for cover testing that will be used to hold cover profiles created by integration tests.
**NOTE:** This does not improve code coverage results by itself. A follow up PR will introduce the functional changes enabled by this PR.
> [chore][Makefile] Add with-cover targets for integration tests

- Makefile
Error introduced in https://github.com/signalfx/splunk-otel-collector/pull/6144, this incorrectly sets target.
These targets are not used in CI/CD, that's why it wasn't caught in the original PR.
> [chore][Makefile] Fix make target typo

- .github/workflows/build-and-test.yml
- tests/testutils/golden.go
- tests/testutils/socket_proxy.go
The `gofmt` job in the `build-and-test` workflow is only checking the main module for formatting, rather than every module in the repo. This needs to be updated to check all modules.
**Testing:**
The `gofmt` [action failed](https://github.com/signalfx/splunk-otel-collector/actions/runs/14542033047/job/40801790137?pr=6148) when a formatting error was included in a submodule, when the action passed before.
> [chore] Ensure entire repo is formatted in workflow

- tests/receivers/smartagent/collectd-activemq/collectd_activemq_test.go
- tests/receivers/smartagent/collectd-cassandra/collectd_cassandra_test.go
- tests/receivers/smartagent/collectd-hadoop/collectd_hadoop_test.go
- tests/receivers/smartagent/collectd-kafka/collectd_kafka_test.go
- tests/receivers/smartagent/collectd-tomcat/tomcat_test.go
- tests/receivers/smartagent/jmx/jmx_test.go
- tests/testutils/testcase.go
There are a number of smartagent receiver tests that have duplicate logic. This change moves all duplicate logic to a central method. This was found in my efforts to add codecov support.
`jmx_test.go` is the only added code coverage in this PR.
> [chore][receive/smartagent] Centralize test logic

- docker/kafka/Dockerfile
This reverts commit fe69ebd2b6486f9fa94d86214d8423b14ec27d65. I accidentally merged https://github.com/signalfx/splunk-otel-collector/pull/6057 and it broke `main`. Revert so we can resolve errors in dependabot PR.
> Revert "Bump bitnami/kafka from 3.9.0 to 4.0.0 in /docker/kafka (#6057)"

- CHANGELOG.md
- pkg/receiver/smartagentreceiver/config.go
- pkg/receiver/smartagentreceiver/config_linux_test.go
- pkg/receiver/smartagentreceiver/config_test.go
- pkg/receiver/smartagentreceiver/factory_test.go
- pkg/receiver/smartagentreceiver/receiver_test.go
This fixes receiver_creator failing to start smartagent receivers since 0.124.0 with the following error:
```
2025-05-01T09:35:43.989Z	info	receivercreator@v0.124.1-0.20250415150511-f840bdff19ca/observerhandler.go:201	starting receiver	{"name": "smartagent/coredns", "endpoint": "10.42.0.8", "endpoint_id": "k8s_observer/c7a1646a-969d-4e5d-9bbd-a95574b903b3", "config": {"extraDimensions":{"metric_source":"k8s-coredns"},"port":9153,"type":"coredns"}}
2025-05-01T09:35:43.991Z	error	receivercreator@v0.124.1-0.20250415150511-f840bdff19ca/observerhandler.go:217	failed to start receiver	{"receiver": "smartagent/coredns", "error": "failed creating endpoint-derived receiver: Validation error in field 'Config.host': host is a required field (got '')"} …
```
> Move smart agent config validation from unmarshal

- Makefile
- Makefile.Common
- internal/signalfx-agent/Makefile
- internal/tools/go.mod
- internal/tools/go.sum
- internal/tools/tools.go
This is redundant. We already use `go fmt` and `goimport` linter for the same purpose. Unblocks https://github.com/signalfx/splunk-otel-collector/pull/6189 because impi doesn't support more than one local prefix
> [chore] Remove impi tool

- deployments/ansible/molecule/shared/install_nodejs.yml
This resolves test failures running Ansible tests on Linux. Errors from [previous actions](https://github.com/signalfx/splunk-otel-collector/actions/runs/14961242885/job/42070350592) show the node version must be upgraded to >= 18 to meet requirements.
_All usages of this file that I could find are for tests so I don't believe this requires a changelog._
> [ansible] Upgrade node.js to v18

- packaging/tests/installer_test.py
Test failure output from `linux-installer-script-test`:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@splunk/otel@3.1.2',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
```
[Failure link](https://github.com/signalfx/splunk-otel-collector/actions/runs/14815389621/job/41595172679#step:6:955)
**NOTE:** [`v16` has been EOL since August 2023](https://nodejs.org/en/about/previous-releases). v18 is also EOL, but I think it makes sense to upgrade one major version at a time for now.
> [chore][installer-script-test] Upgrade minimum version of Node.js to v18 in testing

- packaging/tests/deployments/puppet/images/deb/Dockerfile.debian-bullseye
- packaging/tests/deployments/puppet/images/deb/Dockerfile.ubuntu-focal
- packaging/tests/deployments/puppet/images/deb/Dockerfile.ubuntu-jammy
- packaging/tests/deployments/puppet/images/rpm/Dockerfile.amazonlinux-2023
- packaging/tests/deployments/puppet/images/rpm/Dockerfile.centos-8
- packaging/tests/deployments/puppet/images/rpm/Dockerfile.centos-9
- packaging/tests/deployments/puppet/images/rpm/Dockerfile.opensuse-15
- packaging/tests/deployments/puppet/images/rpm/Dockerfile.oraclelinux-8
[Failure link](https://github.com/signalfx/splunk-otel-collector/actions/runs/15079744379/job/42394416205#step:5:1032):
```
Notice: /Stage[main]/Splunk_otel_collector/Exec[Install splunk-otel-js]/returns: npm WARN EBADENGINE Unsupported engine {
Notice: /Stage[main]/Splunk_otel_collector/Exec[Install splunk-otel-js]/returns: npm WARN EBADENGINE   package: '@splunk/otel@3.1.2',
Notice: /Stage[main]/Splunk_otel_collector/Exec[Install splunk-otel-js]/returns: npm WARN EBADENGINE   required: { node: '>=18' },
Notice: /Stage[main]/Splunk_otel_collector/Exec[Install splunk-otel-js]/returns: npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
Notice: /Stage[main]/Splunk_otel_collector/Exec[Install splunk-otel-js]/returns: npm WARN …
```
> [chore][puppet tests] Upgrade minimum Node.js version to v18

- CHANGELOG.md
- cmd/otelcol/config/collector/config.d.linux/receivers/envoy.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/envoy.discovery.yaml
- internal/confmapprovider/discovery/bundle/bundle.d/receivers/envoy.discovery.yaml.tmpl
- tests/receivers/envoy/testdata/expected.yaml
- tests/receivers/envoy/testdata/expected_k8s.yaml
The current config for prometheus receiver for Envoy in discovery mode is not matching with histogram metrics. This PR updates the config to additional keep metrics which match with the histogram suffixes.
Update the tests with histogram metrics received
> keep histograms in envoy prometheus receiver

- .lychee.toml
The max redirects is 5 and tests show failures for "too many redirects", let's double the max redirects to 10.
> [chore] Update .lychee.toml for  docs.splunk.com to help.splunk.com redirects

- go.mod
- go.sum
- internal/receiver/discoveryreceiver/endpoint_tracker.go
- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
- tests/receivers/istio/bundled_k8s_test.go
Send delete entity events once discovered services are removed to keep the "discovered services" view up-to-date.
This change requires pulling the upstream bugfix https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40279.
This also moves service.name and service.type attributes to the set of identifying attributes according to the entity definition in the inventory service.
> [receiver/discovery] Send delete entity events for discovered services

- packaging/fpm/etc/otel/collector/splunk-otel-collector.conf.example
Avoid the following error when just copying the .conf example for quick tests (not worried about the data failing to be ingested)
```
error decoding 'exporters': error reading configuration for "splunk_hec": decoding failed due to the following error
'token' expected type 'configopaque.String', got unconvertible type 'int', value: '12345'
```
> [tiny] Fix HEC error when using conf example

- deployments/ansible/CHANGELOG.md
- deployments/ansible/molecule/custom_vars/converge.yml
- deployments/ansible/molecule/custom_vars/verify.yml
- deployments/ansible/roles/collector/README.md
- deployments/ansible/roles/collector/defaults/main.yml
- deployments/ansible/roles/collector/templates/splunk-otel-collector.conf.j2
Adds a specific option to set the command-line arguments used to launch the collector service on Linux - Windows implementation is coming after #6268 is released.
The test for this new config setting is piggy-backing on the test for custom environment variables due to the similarities and to avoid yet another test for some CI that is already relatively long to run.
> [ansible] Add option to set service CLI args

- deployments/chef/CHANGELOG.md
- deployments/chef/kitchen.windows.yml
- deployments/chef/metadata.rb
- deployments/chef/recipes/collector_win_install.rb
- deployments/chef/recipes/default.rb
- deployments/chef/test/integration/custom_vars/test.rb
This fixes how Chef handles custom variables for the `splunk-otel-collector` on Windows deployments. The MSI doesn't support custom variables, it supports a set of known variables. To properly set custom variables we need to use the registry.
Also, update version of the collector being used in testing.
> [deployment/chef] Fix custom variables handling on Windows

- deployments/ansible/molecule/config/docker.yml
Centos8 is EOL, this reference was missed in https://github.com/signalfx/splunk-otel-collector/pull/6250/. This currently has no impact in CICD as `MOLECULE_DISTRO` is set in the GitHub workflow. It's only hit locally if `MOLECULE_DISTRO` is not set.
> [chore][molecule] Update default image in docker config

- deployments/ansible/galaxy.yml
- deployments/ansible/molecule/custom_vars/verify.yml
- deployments/ansible/molecule/default/verify.yml
- deployments/ansible/roles/collector/templates/splunk-otel-collector.conf.j2
Without the `register` and `failed_when` checks, the test passes with output saying that lines would have been added if values don't match. The goal is to test to see if an env var is set, by matching lines in a file. If the env var is set to the expected value, no lines would be added. So rather than failing the test, there was just a log message saying a line would be added. This change makes it so tests fail if the env var isn't set to the expected value.
This is already being done in other tests, `with_instrumentation` [for example.](https://github.com/signalfx/splunk-otel-collector/blob/be1bce1d7544b25a2f51e5411d5c076af7a195bb/deployments/ansible/molecule/with_instrumentation/verify.yml#L85)
Edit: After adding verification, `custom_vars` …
> [ansible] Fix incorrect environmental variable naming

- .github/workflows/win-package-test.yml
- packaging/installer/install.ps1
- tests/windows-install-script/windows_install_script_test.go
Change the Windows install script to support changing the collector version, without requiring manual uninstall.
**Testing:**
Added a new test to cover the main scenario for this change
> Add version change support to Windows install script

- .github/workflows/chef-test.yml
- deployments/chef/attributes/default.rb
- deployments/chef/kitchen.windows.yml
- deployments/chef/kitchen.yml
- deployments/chef/recipes/collector_deb_repo.rb
- deployments/chef/recipes/collector_win_install.rb
- deployments/chef/recipes/collector_yum_repo.rb
- deployments/chef/recipes/collector_zypper_repo.rb
- deployments/chef/recipes/default.rb
Same idea as https://github.com/signalfx/splunk-otel-collector/pull/6284, updating Chef tests to run against locally built artifacts.
- Introduced a new variable `local_artifact_testing_enabled` that will install the collector from a local artifact when set to true.
- Added workflow build functionality is all copied from other workflows. Once https://github.com/signalfx/splunk-otel-collector/pull/6329 is merged we can reuse the reusable workflows.
> [chore][chef] Run tests against locally built artifact

- .github/workflows/ansible.yml
I believe this was broken by https://github.com/signalfx/splunk-otel-collector/pull/6329 ([failure example](https://github.com/signalfx/splunk-otel-collector/actions/runs/15834169378)), since the workflow wasn't formatted properly it didn't show up in the PR as failed, you have to go to actions to see the faiilure.
1. Compile a windows AMD64 image
2. Can only have one of: `runs-on` or `uses`
3. Download properly named msi package
> [chore][CICD] Fix broken Ansible workflow

- CHANGELOG.md
- packaging/installer/install.ps1
Follow up to https://github.com/signalfx/splunk-otel-collector/pull/6264, for the Windows installer script this time.
```
> Get-Help .\packaging\installer\install.ps1 -detailed
...
-with_fluentd <Boolean>
DEPRECATED: Fluentd support has been deprecated and will be removed in a future release.
Please refer to documentation for more information: https://github.com/signalfx/splunk-ot
el-collector/blob/main/docs/deprecations/fluentd-support.md
(OPTIONAL) Whether to install and configure fluentd to forward log events to the
collector (default: $false)
> .\packaging\installer\install.ps1 -with_fluentd $True
...
WARNING: [DEPRECATED] Fluentd support has been deprecated and will be removed in a future …
```
> [windows installer script] Mark Fluentd support as deprecated

- CHANGELOG.md
The [tag for](https://github.com/signalfx/splunk-otel-collector/releases/tag/v0.128.0) `v0.128.0` was pushed right before the PRs for these changes were merged. The changelog entries should be moved to unreleased, rather than being under `v0.128.0`.
> [chore][CHANGELOG] Move unreleased changes from v0.128.0

- .github/actionlint.yml
- .github/workflows/ansible.yml
- .github/workflows/auto-instrumentation.yml
- .github/workflows/build-and-test.yml
- .github/workflows/chef-test.yml
- .github/workflows/chef.yml
- .github/workflows/cleanup-closed-pr.yml
- .github/workflows/dotnet-instr-deployer-add-on.yml
- .github/workflows/installer-script-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint-examples.yml
- .github/workflows/linux-package-test.yml
- .github/workflows/nomad.yml
- .github/workflows/otelcol-fips.yml
- .github/workflows/puppet-test.yml
- .github/workflows/salt-test.yml
- .github/workflows/splunk-ta-otel.yml
- .github/workflows/tanzu-tile.yml
- .github/workflows/vuln-scans.yml
- .github/workflows/windows-test.yml
The goal is to lint GitHub actions to ensure there are no syntax errors. As seen in #6360, if a workflow has a syntax error the failure is not shown in the PR introducing the error, causing workflows to break silently until after the PR is merged, causing more noise on `main`. As suggested: https://github.com/signalfx/splunk-otel-collector/pull/6360#pullrequestreview-2954822075
**Testing:**
I broke the Ansible workflow in the same way it had broken on `main`, and the `actionlint` [job failed](https://github.com/signalfx/splunk-otel-collector/actions/runs/15888090505/job/44804872103?pr=6363) with the following message:
```
.github/workflows/ansible.yml:36:5: when a reusable workflow is called with "uses", "runs-on" is not available. only …
```
> [chore][CICD] Add GitHub action linter

- .github/workflows/scripts/win-test-services.ps1
- .github/workflows/win-installer-script-test.yml
Adding a test to validate the Windows install script support of customization of the command-line used to launch the collector service. This can be used, for instance, to enable discovery when installing the collector via the install script.
> Test custom cmd line set via Windows install script

- deployments/ansible/molecule/custom_vars/windows-converge.yml
- deployments/ansible/molecule/custom_vars/windows-verify.yml
- deployments/ansible/roles/collector/tasks/otel_win_install.yml
- internal/signalfx-agent/Makefile
Analog implementation done to Linux via #6270 (changes to README and CHANGELOG were made via #6270).
> [ansible][windows] Add option to set service CLI args

- tests/receivers/scriptedinputs/script_test.go
See https://github.com/signalfx/splunk-otel-collector/actions/runs/16271201210/job/45940031815#step:16:1964
> [chore] Increase timeout for TestScriptReceiverPs to reduce flakiness

- CHANGELOG.md
- internal/receiver/discoveryreceiver/endpoint_tracker.go
- internal/receiver/discoveryreceiver/endpoint_tracker_test.go
Use `app.kubernetes.io/instance` pod label for setting `service.name` entity attribute in addition to other sources.
Addressing https://github.com/signalfx/splunk-otel-collector/pull/6419#discussion_r2201364747
> [receiver/discovery]: Update extraction of `service.name` attribute

- CHANGELOG.md
- internal/confmapprovider/discovery/discoverer.go
- internal/confmapprovider/discovery/provider_test.go
- internal/confmapprovider/discovery/testdata/disable-host-observer.properties.yaml
Fixes a bug where observers couldn't be disabled using properties
> [discovery] Fix disabling observers with properties

- .github/workflows/integration-test.yml
Remove the github action to free space from the runner for some of the integration tests, to speed up tests.
> Remove freeing space from some of the tests

- .gitlab-ci.yml
- packaging/release/tag-on-github.sh
Adds a manual pipeline option to start a release. The tag is expected as pipeline input. The github-release stage has been updated to first create the tag and then the github release. Note - I have kept the original option of release being triggered by a manually added tag to github for now.
> [chore] add github tag creation to release pipelines

- CHANGELOG.md
- go.mod
- go.sum
Pulling https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41102 to 0.130.0 release
> Cherry-pick a receiver/sqlserver improvement change

- .gitlab-ci.yml
choco-release when not releasing is broken with error like below
```
$ $ErrorActionPreference = 'Stop' # collapsed multi-line command
DEBUG: 384+ >>>> $msi_file_name = Resolve-Path .\dist\signed\splunk-otel-collector*.msi | Split-Path -leaf
DEBUG: 385+ if ( >>>> $msi_file_name -match '(\d+.\d+.\d+)(.\d+)?') {
DEBUG: 388+ >>>> throw "Failed to get version from $msi_file_name"
Failed to get version from
At line:388 char:3
throw "Failed to get version from $msi_file_name"
```
> [chore] fix dry-run of choco-release in gitlab on main

- .gitlab-ci.yml
Add the missing artifact to the `release-nupkg` job used by `choco-release`.
> Fix choco publication

- packaging/technical-addon/packaging-scripts/update-otel-version.sh
We now have rc releases, but afaik we only want to release the addon on prod releases, so update the "get latest" tag
Note one could always manually update the `Makefile` if needed for an RC release/test, or we could change this to permit RC releases
> fixes script for downloading latest otel version

- packaging/technical-addon/packaging-scripts/cicd-tests/test-utils.sh
`tr` complains with `Illegal byte sequence`
Setting `LC_TYPE=c` helps: https://unix.stackexchange.com/questions/141420/tr-complains-of-illegal-byte-sequence
See https://community.splunk.com/t5/All-Apps-and-Add-ons/Why-am-I-getting-error-quot-archive-contains-more-than-one/m-p/248831 for the rationale of the fix to the tar file. The tar.gz built on my mac is rejected by Splunk otherwise.
> Small fixes to TA testing code to make it work on mac

- CHANGELOG.md
> [chore] v0.131.0 Changelog

- .gitlab-ci.yml
Fixes below error in grep regex - 
```
grep: invalid option -- '('
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
```
> [chore] escape in regex pattern

- .chloggen/deprecate-smartagent-cadvisor-monitor.yaml
- .chloggen/deprecate-smartagent-kubelet-stats-monitor.yaml
- internal/signalfx-agent/pkg/monitors/cadvisor/cadvisor.go
- internal/signalfx-agent/pkg/monitors/cadvisor/kubeletstats.go
- internal/signalfx-agent/pkg/monitors/cadvisor/metadata.yaml
Deprecate `cadvisor` and `kubelet-stats` monitors since they don't have any usage per telemetry data.
> Deprecate cadvisor and kubelet-stats monitors

- .github/workflows/win-package-test.yml
No way to validate, but given the success rate on retry there is reason to think that this test is suffering from noisy neighbor issues. The hope here is that the larger runner won't experience similar issues.
> [chore] Stabilize .NET zeroconfig test by using large runner

- .gitlab-ci.yml
The job fails with `/usr/bin/bash: line 253: ghr: command not found` because the `before_script` from the `.go-cache` extension is overridden by the job's own `before_script`, which misses the required `make install-tools` step. The job's `before_script` appears redundant since `gh` isn't used in the job.
> [chore] Fix github-release gitlab job

- .chloggen/use_default_path_logs_config.yaml
- cmd/otelcol/config/collector/logs_config_linux.yaml
- internal/settings/settings.go
- internal/settings/settings_test.go
Added a new optional environment variable to the default Linux logs configuration file. If not set by the user, it's set by default upon collector startup to `/var/lib/otelcol/filelogs`.
This PR also changes the configuration to enable `create_directory` by default on the file storage extension as it helps new installation startup proceed more smoothly. When running in a new test or production environment without this option being enabled, users have to manually create the directory or the collector will fail on startup.
This is a pre-req to https://github.com/signalfx/splunk-otel-collector/pull/6625
> [logs config] Use env variable for file storage extension path

- .github/workflows/scripts/prepare-changelog.sh
When preparing the changelog notes for v0.133.0 I found the prepare changelog script couldn't properly handle changelog entries with more than one issue. The `grep` and `sed` operations were only looking for `(#NUMBER)`, filtering out valid values such as `(#NUMBER1, #NUMBER2)` and `(#NUMBER1, #NUMBER2, #NUMBER3)`. This fixes the operations to be able to properly link issues when there are more than one.
> [chore][prepare-changelog] Properly handle changelog entries with multiple issues

- .github/workflows/otelcol-fips.yml
I'm hitting a lot of failures in the job `otelcol-fips` for Windows/amd64 running on the `ubuntu-24.04` GitHub runner ([example](https://github.com/signalfx/splunk-otel-collector/actions/runs/17749508115/job/50502480445?pr=6763)):
```
362.5 /usr/bin/x86_64-w64-mingw32-ld: final link failed: No space left on device
362.5 collect2: error: ld returned 1 exit status
```
Cleaning up free space before building should help reduce the frequency of this error.
> [chore] Clean up free space on runner for Windows FIPS build

- .github/workflows/win-package-test.yml
Previously I switched to the larger runner, but after that problems in the test code were fixed. Switching back to the standard GH runner since the original issue was caused by the test code itself.
I will retry a few runs to see if all is good before merging this one.
> [chore] Use GH standard runner for `dotnet-zeroconfig-e2e-test` workflow
