.circleci/config.yml, .gitignore, Makefile, docs/release.md, internal/buildscripts/packaging/release/helpers/util.py, internal/buildscripts/packaging/release/pyproject.toml, internal/buildscripts/packaging/release/requirements.txt, internal/buildscripts/packaging/release/sign_release.py, internal/buildscripts/packaging/release/tests/deb/Dockerfile, internal/buildscripts/packaging/release/tests/rpm/Dockerfile, internal/buildscripts/packaging/release/tests/rpm/splunk-otel-collector.repo
- Requires `GITHUB_TOKEN` env var to be added to circleci in order to publish assets to Github Releases for tags.
- sign_release.py ported from signalfx-agent and currently required to be run manually since it needs to access the Splunk signing service on the corporate network.
=> Sign and release deb/rpm packages

go.mod, go.sum, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/output_test.go, internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go
These changes introduce the main receiver start and shutdown functionality (addressing the second remaining item detailed in https://github.com/signalfx/splunk-otel-collector/pull/53#issue-549208453).  They include dynamic SA monitor creation using the provided config and establish a means of accessing the SFx datapoints reported by the monitors.  These change don't include datapoint conversion, which will be introduced in the next proposed addition.
They also don't include the core collectd process creation, which will also be introduced in a later PR.
=> smartagentreceiver: add Dynamic Monitor creation

internal/receiver/smartagentreceiver/convert.go, internal/receiver/smartagentreceiver/convert_test.go, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go
These changes address the 3rd remaining item detailed in https://github.com/signalfx/splunk-otel-collector/pull/53#issue-549208453 by adding internal SFx datapoint to pdata metric translation and forwarding to the next metric consumer.  They are largely based on the translation that occurs in [Collector Contrib's SFx receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/receiver/signalfxreceiver) but without using SFx's protobuf definitions.
In testing these changes, there is a minor form of end-to-end integration test that uses the native SA cpu monitor without vetting its metric content too heavily, which I deemed out of scope after earlier attempts in light of CI flake and cross-platform concerns.
=>  Smart Agent Receiver: add datapoint conversion

internal/receiver/smartagentreceiver/convert.go, internal/receiver/smartagentreceiver/convert_test.go, internal/receiver/smartagentreceiver/output.go
Many monitors will use `time.Time{}` as a timestamp placeholder, invalidating their points for our purposes.  These changes record the time of `Output.SendDatapoints()` invocation and use that value in these cases.
=> smartagentreceiver: use time of reception if datapoints without timestamp

.circleci/config.yml, README.md, cmd/otelcol/config/collector/agent_config_linux.yaml, internal/buildscripts/packaging/fpm/Dockerfile, internal/buildscripts/packaging/fpm/common.sh, internal/buildscripts/packaging/fpm/deb/build.sh, internal/buildscripts/packaging/fpm/etc/otel/collector/fluentd/README, internal/buildscripts/packaging/fpm/etc/otel/collector/fluentd/conf.d/journald.conf.example, internal/buildscripts/packaging/fpm/etc/otel/collector/fluentd/fluent.conf, internal/buildscripts/packaging/fpm/etc/otel/collector/fluentd/splunk-otel-collector.conf, internal/buildscripts/packaging/fpm/etc/otel/collector/splunk_config_linux.yaml, internal/buildscripts/packaging/fpm/etc/otel/collector/splunk_env.example, internal/buildscripts/packaging/fpm/postinstall.sh, internal/buildscripts/packaging/fpm/preinstall.sh, internal/buildscripts/packaging/fpm/preuninstall.sh, internal/buildscripts/packaging/fpm/rpm/build.sh, internal/buildscripts/packaging/installer/install.sh, internal/buildscripts/packaging/tests/installer_test.py
*Dependent on fixes for the `fluentfoward` receiver upstream*
- Add `fluentforward` receiver, `splunk_hec` exporter, and custom endpoint URL env vars to the default linux config
- Add default fluentd config to forward `@SPLUNK` labeled events to the collector
- Add sample fluentd source for journald (currently not enabled by default since it requires dependencies and permissions that we may not want to perform on the system)
- Update installer script to install/configure fluentd and add options for custom endpoint URLs
- Update deb/rpm packaging for new fluentd config files and set ownership/permissions
=> Update deb/rpm and installer script for fluentd

examples/splunk-hec-metrics/README.md, examples/splunk-hec-metrics/docker-compose.yml, examples/splunk-hec-metrics/otel-collector-config.yml, examples/splunk-hec-metrics/splunk.yml, examples/splunk-hec-metrics/telegraf.conf
Simple example showing how to surface Telegraf CPU metrics into Splunk Enterprise via the Otel collector.
=> Add Splunk HEC metrics example, taking metrics from telegraf

internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/output_test.go, internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go
These changes add `extraDimensions` config and output support to the Smart Agent receiver.  Also including `Output.Copy()` support to allow adopting monitors to manage multiple Output instances with different extra dimensions.
=> smart agent: add extraDimensions support

README.md, cmd/otelcol/main.go, cmd/otelcol/main_test.go
Today, SPLUNK_BALLAST_SIZE_MIB needs to be computed and manually
configured by a user. Most users do not know or care about the ballast
and under normal circumstances they should not need to. Users will
understand the total amount of memory allocated to the Collector. As
such, introduce a SPLUNK_MEMORY_TOTAL_MIB env var that can be used
instead of or in addition to SPLUNK_BALLAST_SIZE_MIB. This has the added
bonus that now memory spike and limit env vars are no longer required
for non-linux systems. This change is backwards compatible.
A few other minor enhancements:
- Memory spike/limit env vars are now applied even if SPLUNK_CONFIG is
passed
- Add logging for custom behavior so configuration is clear
- Add accessible endpoints to README
- Add tests
=> Add SPLUNK_MEMORY_TOTAL_MIB

cmd/otelcol/main.go, cmd/otelcol/main_test.go
Addresses #77
A behavior change was introduced such that either total memory or
limit/spike environment variables had to be set even if the config
parameter was passed. This fails for Windows as you cannot pass env vars
to the service.
To address, total or limit/spike are no longer required if config
parameter is passed. Added a test to ensure this issue is not
reintroduced in the future.
=> Fix Windows build failure

internal/receiver/smartagentreceiver/config.go, internal/receiver/smartagentreceiver/config_test.go, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go, internal/receiver/smartagentreceiver/reflect.go, internal/receiver/smartagentreceiver/reflect_test.go, internal/receiver/smartagentreceiver/testdata/endpoints_config.yaml, internal/receiver/smartagentreceiver/testdata/invalid_endpoint.yaml, internal/receiver/smartagentreceiver/testdata/unsupported_endpoint.yaml
These changes add a new Endpoint field to the Smart Agent receiver Config to make them compatible with the receiver creator and observer endpoint targets.  They will apply to corresponding host and port monitor config fields.
Also includes some refactoring since both these changes and the reflective Output value setting follow the same pattern.
=> Smart Agent: Add Endpoint Config field for receiver creator

README.md, internal/buildscripts/packaging/installer/install.sh, internal/buildscripts/packaging/tests/installer_test.py
Sets the `SPLUNK_MEMORY_TOTAL_MIB` env var for the collector systemd service unless the `--ballast` option is specified.
=> Add --memory option to linux installer script

README.md, docs/getting-started/linux-installer.md, docs/getting-started/linux-standalone.md, docs/getting-started/windows-standalone.md
We continue to add getting started documentation as support for
different platforms increases and as installation scripts are
introduced. Instead of continuing to grow the main README, create
getting started docs and link to them.
Also add supported component information to main README.
=> Clean up getting started docs

tests/README.md, tests/go.mod, tests/go.sum, tests/testutils/README.md, tests/testutils/collector_process.go, tests/testutils/collector_process_integration_test.go, tests/testutils/collector_process_test.go, tests/testutils/testdata/collector_process_config.yaml, tests/testutils/testdata/expected_host_metrics.yaml
These changes introduce the last basic helper for the integration testing module - a runner for the Collector.  It uses the subprocess manager from the JMX receiver, a specified or detected Collector binary path, and provided config to launch the collector process for the lifetime of a test or suite.
Also introduces the first `integration` tagged test file, but as with the previous changes I'm holding off on sourcing/running these in CI until a future PR.
=> tests: CollectorProcess helper

tests/testutils/README.md, tests/testutils/pdata_to_resource_metrics.go, tests/testutils/pdata_to_resource_metrics_test.go, tests/testutils/resource_metrics.go, tests/testutils/resource_metrics_test.go, tests/testutils/testdata/emptyLabelsRequired.yaml, tests/testutils/testdata/labelValueResourceMetrics.yaml, tests/testutils/testdata/unspecifiedLabelsAllowed.yaml
These changes adjust the `ResourceMetrics` test format to have labels as a pointer to a map, allowing selectively not specifying the field to match with any value in `RelaxedEquals()`.
=> tests: relax label equality in RelaxedEquals

tests/go.mod, tests/go.sum, tests/testutils/container.go, tests/testutils/container_test.go
These changes allow adding test containers to networks and specifying their name via builder methods.  If a network is determined not to exist, it will be created beforehand.
Also bumps the testcontainers dep to the most recent psuedoversion since there have been unreleased fixes in these paths.
=> tests: add container names and network support

go.mod, go.sum, tests/receivers/smartagent/postgresql/postgresql_test.go, tests/receivers/smartagent/postgresql/testdata/all_metrics_config.yaml, tests/receivers/smartagent/postgresql/testdata/client/Dockerfile, tests/receivers/smartagent/postgresql/testdata/client/requests.sh, tests/receivers/smartagent/postgresql/testdata/resource_metrics/all.yaml, tests/receivers/smartagent/postgresql/testdata/server/Dockerfile, tests/receivers/smartagent/postgresql/testdata/server/init.sh, tests/receivers/smartagent/postgresql/testdata/server/initdb.d/db.sql
These changes introduce the first integration test case for the tests module, and exercises the [native postgresql monitor](https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/postgresql.md).  Since output filtering is yet to be implemented it confirms that all metrics are received, though in the near future more restricted configs/tests could be added (@pmcollins).
requires: https://github.com/signalfx/splunk-otel-collector/pull/103 and https://github.com/signalfx/signalfx-agent/pull/1607
I will update the desired agent version once the PG13 support fix lands.
=> Smart Agent receiver: Postgresql integration test

internal/components/components.go, internal/components/components_test.go, internal/extension/smartagentextension/README.md, internal/extension/smartagentextension/config.go, internal/extension/smartagentextension/config_test.go, internal/extension/smartagentextension/extension.go, internal/extension/smartagentextension/extension_test.go, internal/extension/smartagentextension/factory.go, internal/extension/smartagentextension/factory_test.go, internal/extension/smartagentextension/testdata/config.yaml, internal/extension/smartagentextension/testdata/invalid_config.yaml
This extension provides a centralized mechanism to configure things collectd that are common to all instances of the smartagent receiver. To begin with, this extension will enable users to override default config options such as "config_dir" and "bundle_dir" that are applicable for all collectd based monitors.
Also, note that it is not a requirement to configure this extension for collectd monitors to work. In such cases, the default collectd config will be applied.
=> Add smartagent extension

internal/receiver/smartagentreceiver/README.md, internal/receiver/smartagentreceiver/config.go, internal/receiver/smartagentreceiver/config_test.go, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/output_test.go, internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/testdata/config.yaml, internal/receiver/smartagentreceiver/testdata/invalid_float_metadata_clients.yaml, internal/receiver/smartagentreceiver/testdata/invalid_nonarray_metadata_clients.yaml
These changes build upon https://github.com/signalfx/splunk-otel-collector/pull/120 but add a `metadataClients` config field to denote the SFx exporter to use to send dimension updates.  If a client array is isn't provided the current behavior of defaulting to the nextConsumer if possible remains.
Camelcasing is inherited by the Agent config conventions to avoid mixing it w/ snake case.
I am not happy with the configuration experience here and hope something comes out of https://github.com/open-telemetry/opentelemetry-collector/issues/2536 or the existing sdk has features that can improve it I wasn't able to find.  It's unfortunate that we'd need to require the user to specify the exporter they're using without otherwise having to make the assumption that all SFx exporters are desired and …
=> WIP: smartagent: Allow specifying metadata exporters for dimension updates

internal/receiver/smartagentreceiver/log.go, internal/receiver/smartagentreceiver/log_test.go, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/receiver.go
Currently the receiver logs a warning whenever `monitorType` is not present as a field on the underlying logrus logs. Use the default logger instead.
=> receiver/smartagent: Use default logger when monitorType field does not exist

internal/buildscripts/packaging/installer/install.sh
The Linux installer script has a check to see whether otelcol is
installed. td-agent should also be checked and now is. Also make echo
cleaner.
=> Make ensure_not_installed more robust

internal/receiver/smartagentreceiver/event.go, internal/receiver/smartagentreceiver/event_test.go
These changes introduce a conversion helper that will be later adopted by the Smart Agent receiver's Output `SendEvent` method to provide the configured SFx exporter monitor-created events as log records.  They are based on the logic in the SFx receiver, but are unable to source it directly since it isn't exported and operates on the protobuf-generated types instead of the type defined in SFx golib as used by the agent.
=> translate Smart Agent events into log records

internal/receiver/smartagentreceiver/README.md, internal/receiver/smartagentreceiver/config.go, internal/receiver/smartagentreceiver/config_test.go, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/output_test.go, internal/receiver/smartagentreceiver/testdata/config.yaml, internal/receiver/smartagentreceiver/testdata/invalid_float_dimension_clients.yaml, internal/receiver/smartagentreceiver/testdata/invalid_nonarray_event_clients.yaml
These changes adopt SignalFx Event support using the same `MetadataClients` mechanism provided by https://github.com/signalfx/splunk-otel-collector/pull/124 but with the conversion provided by https://github.com/signalfx/splunk-otel-collector/pull/130.  The consumer selection logic is effectively the same as that of the metadata exporter path, but checking for `LogsConsumer` implementors and still defaulting to the next consumer if applicable.  **edit: Now these changes split dimension clients from event clients, but have the same functionality as described**
Not included, but associated with these changes will be a future PR proposing to default to any lone SignalFx exporter if no MetadataClients are specified to avoid the edge cases with processor usage and not requiring users specify …
=> Smart Agent: send SignalFx events to event clients

Makefile, tests/receivers/smartagent/postgresql/postgresql_test.go, tests/receivers/smartagent/postgresql/testdata/all_metrics_config.yaml, tests/testutils/README.md, tests/testutils/collector_process.go, tests/testutils/collector_process_test.go, tests/testutils/container_test.go, tests/testutils/otlp_receiver_sink.go, tests/testutils/testcase.go
These changes introduce and source a new `testutils.AssertAllMetricsReceived()` helper to remove unnecessary boilerplate in integration tests, which is largely relocated from the existing postgresql monitor test.  The major change is that they enable a random OTLP receiver address to be used for each case and disable internal telemetry to avoid port conflicts.
Also adds a new `integration-test` make target to be utilized in future Circle CI change.
=> Add and adopt unified integration test helper

internal/receiver/smartagentreceiver/config_test.go, internal/receiver/smartagentreceiver/filtering.go, internal/receiver/smartagentreceiver/filtering_test.go, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/output_test.go, internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go, internal/receiver/smartagentreceiver/testdata/filtering_config.yaml, internal/receiver/smartagentreceiver/testdata/invalid_filtering_config.yaml
The following files ported mostly as is from signalfx-agent:
- internal/receiver/smartagentreceiver/filtering.go 
- internal/receiver/smartagentreceiver/filtering.go
=> Port monitor-level filtering functionality from signalfx-agent

cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, examples/kubernetes-yaml/splunk-otel-collector-agent.yaml, examples/kubernetes-yaml/splunk-otel-collector-gateway.yaml
Specifically don't need process scraper which doesn't collect default metrics.
=> Use same scrapers as OCK

cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, cmd/otelcol/config/collector/otlp_config_linux.yaml, cmd/otelcol/config/collector/splunk_config_linux.yaml
"deployment.environment" supposed to be set by OTel instrumentation libraries, but when it's missing we want to provide an easy option to specify a default value in collector.
=> Add comments on how to setup optional "environment" attribute

internal/receiver/smartagentreceiver/README.md, internal/receiver/smartagentreceiver/config.go, internal/receiver/smartagentreceiver/config_test.go, internal/receiver/smartagentreceiver/factory.go, internal/receiver/smartagentreceiver/factory_test.go, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/output_test.go, internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go, internal/receiver/smartagentreceiver/testdata/config.yaml, internal/receiver/smartagentreceiver/testdata/invalid_nonarray_dimension_clients.yaml
(In lieu of https://github.com/signalfx/splunk-otel-collector/pull/149)
These changes allow the Smart Agent receiver to act as both a metrics and logs receiver, as well as removing the notion of an event client in config and Output functionality.  Instead they use standard log pipelines after I discovered that the main user of events in the agent, the processlist monitor, requires a host dimension that must be added via processor in a log pipeline unless hardcoded in agent config (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2631 is necessary in SFx exporter for this to take effect).
Also includes the basic SFx exporter dimension client defaulting logic, which is simpler without event clients.
=> Smart Agent log receiver

tests/receivers/smartagent/collectd-activemq/collectd_activemq_test.go, tests/receivers/smartagent/collectd-activemq/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-activemq/testdata/default_metrics_config.yaml, tests/receivers/smartagent/collectd-activemq/testdata/resource_metrics/default.yaml, tests/receivers/smartagent/collectd-apache/collectd_apache_test.go, tests/receivers/smartagent/collectd-apache/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-apache/testdata/default_metrics_config.yaml, tests/receivers/smartagent/collectd-apache/testdata/resource_metrics/default.yaml, tests/receivers/smartagent/collectd-cassandra/collectd_cassandra_test.go, tests/receivers/smartagent/collectd-cassandra/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-cassandra/testdata/default_metrics_config.yaml, tests/receivers/smartagent/collectd-cassandra/testdata/resource_metrics/default.yaml, tests/receivers/smartagent/collectd-couchbase/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-elasticsearch/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-hadoop/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-kafka/testdata/all_broker_metrics_config.yaml, tests/receivers/smartagent/collectd-kafka/testdata/all_consumer_metrics_config.yaml, tests/receivers/smartagent/collectd-kafka/testdata/all_producer_metrics_config.yaml, tests/receivers/smartagent/collectd-postgresql/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-solr/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-spark/testdata/all_master_metrics_config.yaml, tests/receivers/smartagent/collectd-spark/testdata/all_worker_metrics_config.yaml, tests/receivers/smartagent/haproxy/testdata/all_metrics_config.yaml, tests/receivers/smartagent/postgresql/testdata/all_metrics_config.yaml
These changes adopt `extraMetrics: ["*"]` usage now that https://github.com/signalfx/splunk-otel-collector/pull/151 enabled default monitor metrics and causes the integration tests to fail.  Also adding a few default metric tests based on SA metadata.yaml files for collectd ActiveMQ, apache, and Cassandra to validate its basic behavior.
A robust set of default metric tests is now possible but on brief examination would required robust test client interaction to generate otherwise latent metrics that I'm deferring for now.
=> Adopt SA receiver filtering and add some default metric integration tests

internal/extension/smartagentextension/config.go, internal/extension/smartagentextension/config_test.go
These changes fix a bug in the SA Extension that leaves* the default collectd config partially populated and doesn't* respect the desired executable location, which is what the agent [actually uses](https://github.com/signalfx/signalfx-agent/blob/c295133b4a52b2fff071c8070536183a48e403fc/pkg/monitors/collectd/collectd.go#L469).
I've corrected the relevant unit test with the desired value.  The integration tests missed this since they set a temporary collectd configDir option, which I'm not able to bypass at this time due to resulting permission errors w/ the default.
=> smartagent extension: ensure propagation of collectd bundle dir

go.mod, internal/receiver/smartagentreceiver/converter/converter.go, internal/receiver/smartagentreceiver/converter/converter_test.go, internal/receiver/smartagentreceiver/converter/event.go, internal/receiver/smartagentreceiver/converter/event_test.go, internal/receiver/smartagentreceiver/converter/metrics.go, internal/receiver/smartagentreceiver/converter/metrics_test.go, internal/receiver/smartagentreceiver/converter/traces.go, internal/receiver/smartagentreceiver/converter/traces_test.go, internal/receiver/smartagentreceiver/output.go
These change provide some minor refactoring of the conversion functions by breaking out to a new `converter` subpackage and add SFx->pdata trace conversion.
SFx trace format is an implementation of Zipkin v2, so I coerce to its json representation before using the existing Collector's zipkin v2 to pdata translator.  If performance issues become a concern we can optimize as needed.
This PR doesn't adopt any of this translation, which will be done shortly after.
=> Smart Agent: translate SFx traces to pdata

internal/receiver/smartagentreceiver/factory.go, internal/receiver/smartagentreceiver/factory_test.go, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/output_test.go, internal/receiver/smartagentreceiver/output_traces_test.go, internal/receiver/smartagentreceiver/receiver.go
These changes adopt the converter introduced in https://github.com/signalfx/splunk-otel-collector/pull/178 and add trace receiver support to the Smart Agent Receiver.  They also port the extra and default span tags functionality from the SA codebase.
This is largely done to support the signalfx-forwarder monitor, whose documentation I will add in a subsequent PR once https://github.com/signalfx/splunk-otel-collector/pull/167 has landed.
=> Add Trace support to SA Receiver

internal/buildscripts/packaging/msi/splunk-otel-collector.wxs
- Workaround for #153 
- The registry key is created on MSI installation and removed on uninstall
- Adding the registry key changes the events to:
=> Create registry key for collector service events

docs/signalfx-smart-agent-migration.md, internal/receiver/smartagentreceiver/README.md
These changes fix a broken link and provide an example of using the signalfx-forwarder monitor in a traces pipeline.  They also update the receiver creator rule expression and use the desired `matches` expvar operator.
=> Update Smart Agent docs for signalfx-forwarder and discovery rule changes

README.md
Clarify that this is the only distribution that will receive paid Splunk support, but that we'll still assist with the OSS version on a best-effort basis
=> Clarify support

.circleci/config.yml, .gitignore, internal/buildscripts/packaging/msi/msi-builder/Dockerfile, internal/buildscripts/packaging/msi/msi-builder/build.sh, internal/buildscripts/packaging/release/helpers/util.py
requires: https://github.com/signalfx/splunk-otel-collector/pull/202
These changes migrate the circle ci and release job msi builders to a shared docker image, with build script based on the currently unused local development script and the python `build_msi()` helper.  This way any required changes to the msi build process (like SA bundling support) only need to be made once*, as opposed to in 3 places* (circle's make.ps1, utils.py, build.sh).
Given the restrictions and requirements for the `felfert/wix` image's wix user, the msi-builder image is intended to be run as user root.  This way only wix user read access to the `/project` directory is required, and any desired `OUTPUT_DIR`** writes are guaranteed to be the resulting msi.
=> Adopt single msi-builder in circle and release script

docs/sizing.md
Existing tests in the [testbed](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/testbed/tests) were used to validate/determine sizing information. The specific tests used -
1. SAPM for traces
2. SignalFx for metrics
3. FluentForward-SplunkHEC for logs (yet to be merged https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2924)
Each of these tests were run separately. Slight code modifications were made to testbed code to test various loads and also include default processors included by this distribution. For example, for the logs test, the used config was the following - 
```yaml
receivers:
prometheus:
config:
scrape_configs:
- job_name: 'otel-collector'
scrape_interval: 10s
static_configs:
- targets: [ '0.0.0.0:8888' ] …
```
=> Update sizing guidelines

docs/getting-started/windows-installer.md, docs/getting-started/windows-standalone.md, internal/buildscripts/packaging/installer/install.ps1, internal/buildscripts/packaging/msi/make.ps1, internal/buildscripts/packaging/msi/msi-builder/Dockerfile, internal/buildscripts/packaging/msi/msi-builder/build.sh
requires https://github.com/signalfx/splunk-otel-collector/pull/210
These changes add a slightly modified Smart Agent bundle to msi installations.  There is a path length limitation w/ WiX and Wine that prevents copying it completely that I wasn't able to find a workaround to while preserving signed builds in linux.
=> Include SA bundle in msi

.circleci/config.yml, cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, cmd/otelcol/config/collector/otlp_config_linux.yaml, docs/signalfx-smart-agent-migration.md, internal/receiver/smartagentreceiver/README.md
This will allow existing tracing library users to not need to update their instrumented deployments' configurations when using the Collector.
Also pork-barrelling layer caching on fpm image builds.
=> Add SignalFx forwarder to default configs

internal/buildscripts/packaging/msi/msi-builder/Dockerfile, internal/buildscripts/packaging/msi/msi-builder/docker-entrypoint.sh, internal/buildscripts/packaging/release/helpers/util.py
- Move Dockerfile entrypoint command to `docker-entrypoint.sh`
- Copy the signed exe before the MSI release build to the staging directory and pass the `--otelcol` option to the build script
=> Fix MSI release build for signed exe

internal/buildscripts/packaging/fpm/common.sh, internal/buildscripts/packaging/fpm/deb/build.sh, internal/buildscripts/packaging/fpm/rpm/build.sh, internal/buildscripts/packaging/installer/install.sh, internal/buildscripts/packaging/tests/installer_test.py, internal/buildscripts/packaging/tests/package_test.py
- Updated installer script for the `--mode <agent|gateway>` option (defaults to agent)
- Sets the `SPLUNK_CONFIG` env var for the collector service to `agent_config.yaml` if running the installer script with `--mode agent`, or `gateway_config.yaml` if `--mode gateway`
- Updated the installer test for the `--mode` and `--without-fluentd` options
=> Support gateway mode for linux installer

.circleci/config.yml, docs/getting-started/windows-installer.md, docs/getting-started/windows-standalone.md, internal/buildscripts/packaging/installer/install.ps1, internal/buildscripts/packaging/msi/msi-builder/build.sh, internal/buildscripts/packaging/msi/splunk-otel-collector.wxs
- Add `gateway_config.yaml` to the MSI
- Add `--mode <agent|gateway>` option to the installer script (defaults to `agent`)
- Set and use the `SPLUNK_CONFIG` env var in the registry instead of the `--config` argument for the collector service
- Update msi/installer test in circleci for agent and gateway modes
=> Support gateway mode for windows installer

cmd/otelcol/config/collector/agent_config.yaml
Any `host.name` and `os.type` resource attributes that have been set should be respected instead of overridden by our provided resource detection processor instance.  Otherwise there is the potential for masking the actual data source.
=> Don't override system resource attrs in default config

.circleci/config.yml, internal/extension/smartagentextension/config_linux_test.go, internal/extension/smartagentextension/config_windows_test.go, internal/extension/smartagentextension/factory.go
These changes use saner defaults for the agent bundle path, which should match standard installation paths.  For windows, since the bundle is adjacent to the executable in standard installation we check for it and source it if found.
edit: I've also added uploading a windows run coverage report, but don't think I'll be hitting the requirement for this PR since one diff path requires running from an installed msi's perspective.
The significant drop in project coverage w/ these changes results from the windows build files now revealing they are without coverage.  The actual missing coverage from the diff is from a runtime only path, and one where a critical env var has been cleared (both relative edge cases).
=> SA Extension: Set platform specific bundleDir default

docs/signalfx-smart-agent-migration.md, internal/extension/smartagentextension/README.md, internal/extension/smartagentextension/config_test.go, internal/extension/smartagentextension/testdata/config.yaml, internal/receiver/smartagentreceiver/README.md
These changes update the supported global/collectd config fields and descriptions and add a reference to the extension from the receiver readme.  Also includes a minor unit test update to vet fs fields.
These changes also expand the beta disclaimer for the SA receiver.
=> Better document and test SA Extension config

internal/buildscripts/packaging/fpm/etc/otel/collector/fluentd/conf.d/journald.conf, internal/buildscripts/packaging/msi/fluentd/conf.d/eventlog.conf
No longer required with the latest collector release.
=> Remove host mapping in fluentd configs

internal/buildscripts/packaging/fpm/etc/otel/collector/splunk-support-bundle.sh, internal/buildscripts/packaging/tests/images/deb/Dockerfile.debian-buster, internal/buildscripts/packaging/tests/images/deb/Dockerfile.debian-jessie, internal/buildscripts/packaging/tests/images/deb/Dockerfile.debian-stretch, internal/buildscripts/packaging/tests/images/deb/Dockerfile.ubuntu-bionic, internal/buildscripts/packaging/tests/images/deb/Dockerfile.ubuntu-focal, internal/buildscripts/packaging/tests/images/deb/Dockerfile.ubuntu-xenial, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.amazonlinux-2, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.centos-7, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.centos-8, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.oraclelinux-7, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.oraclelinux-8, internal/buildscripts/packaging/tests/installer_test.py
- The support bundle script currently exits with non-zero code because `TMPDIR` does not exist before `tee -a "$TMPDIR"/stdout.log`
- Need to temporarily skip bundle support script tests until these changes are included in the next release, otherwise CI tests will continue to fail
- Install wget in the test images as a requirement for the support bundle script
=> Fix support bundle script and tests

cmd/otelcol/main_windows.go
This is a copy of the main repo PR: open-telemetry/opentelemetry-collector#2272 that enables running the collector inside Windows Docker containers.
Main repo PR description:
> Adding a feature - adds a check for NO_WINDOWS_SERVICE environment variable on Windows to allow forcing interactive mode instead of running as a service.
>
> This is required for using the collector in Windows Docker containers, as at least some of the Windows base images do not support services (fails with "The service process could not connect to the service controller"). Environment variable is used instead of automatic detection of Docker as it is uncertain if images that support services are possible and/or desired.
>
>Running collector in Windows Docker containers is required to perform containerized …
=> Env variable NO_WINDOWS_SERVICE to force interactive mode on Windows

.gitignore, internal/components/componenttest/assert_no_error_host.go, internal/extension/smartagentextension/extension_test.go, internal/receiver/smartagentreceiver/receiver_test.go
In the near future components need to support the cycle of creation/start/stop multiple times inside the same process.
Adding minimal tests to ensure that the components defined on the repo are at least supporting the most trivial lifecycle. Ideally, the testing code for components will be provided by packages from the core repo until that happens these minimal tests ensure the basic behavior is not broken. The tests don't cover the case when the components are actively receiving or sending data that will be added later when the collector can recycle components.
=> Add minimal lifecycle tests for distro components

Makefile, cmd/otelcol/Dockerfile
- Install smart agent bundle in image.
- Set environment variables:
- SPLUNK_BUNDLE_DIR="/usr/lib/splunk-otel-collector/agent-bundle"
- SPLUNK_COLLECTD_DIR="/usr/lib/splunk-otel-collector/agent-bundle/run/collectd
=> Include smart agent bundle in docker image

.circleci/config.yml, Makefile
- Add `docker-otelcol` job to build and run the image before publishing
- Add `msi` make target
- Add `SKIP_COMPILE` Makefile var so that we can use the make targets to build the deb, rpm, msi, and docker image in circleci without recompiling the otelcol binaries
=> docker-otelcol circleci job and Makefile updates

internal/extension/smartagentextension/config.go, internal/extension/smartagentextension/config_test.go, internal/extension/smartagentextension/testdata/config.yaml
Instead of using the [Smart Agent default](https://github.com/signalfx/signalfx-agent/blob/master/pkg/core/config/config.go#L387) for the collectd config directory setting value, these changes introduce an agent-bundle relative location (~`${bundleDir}/run/collectd`) for more intuitive organization.
Thanks to @bjsignalfx for initial leg work in https://github.com/signalfx/splunk-otel-collector/pull/241
=> Use agent bundle-relative Collectd ConfigDir default

cmd/otelcol/Dockerfile, tests/go.sum, tests/testutils/otlp_receiver_sink_test.go, tests/testutils/pdata_to_resource_metrics.go
Also exposes port 9080 for signalfx-forwarder monitor in docker image.
=> Adopt 0.24.0 changes in tests

internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go
Receiver creator instantiated names have quotes in them, which breaks collectd instance templating:
```<Instance "[monitorID=receiver_creatorsmartagentnginx{endpoint="172.17.0.2:8080"}]">```
These changes url encode the monitor name for monitor id usage instead of simply removing forward slashes.
=> url encode monitor IDs in SA receiver

cmd/otelcol/Dockerfile, internal/extension/smartagentextension/factory.go, internal/receiver/smartagentreceiver/receiver_test.go, internal/receiver/smartagentreceiver/testdata/extension_config.yaml
These changes ensure that if the SA extension isn't used, a bundleDir-relative configDir is still used.  Also corrects a typo in the dockerfile for this config field.
=> Fully adopt default collectd config directory

internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go
https://github.com/signalfx/splunk-otel-collector/pull/266 introduced a regression where monitor ids with unsupported characters are not used as monitorID dimension values, causing the collectd write server to drop points.  Instead of url encoding these changes strip all non-word characters.
=> Correct invalid monitor ID encoding

docs/security.md
Related to Splunk Support ticket 00016757, Kevin R indicated that the Jaeger Thrift HTTP URL is /api/traces. Local execution suggests this is correct.
=> Correct Jaeger Thrift HTTP Receiver URL to /api/traces

internal/configprovider/manager.go, internal/configprovider/manager_test.go
A follow-up to #295 that superseded #277.
This brings the config source manager from the core repository that is not publicly exposed. The manager will be used to implement a provider that uses config sources to inject data in configuration. This code was originally reviewed on the collector core repository.
/cc @owais
=> Add the config source manager

cmd/otelcol/main.go, internal/configprovider/config_source_provider.go, internal/configprovider/config_source_provider_test.go, internal/configprovider/testdata/manager_resolve_error.yaml
Adds a parser provider that can understand config sources. At this moment no config sources were added yet so none can be used but it works as the default parser provider in this case - manually verified.
=> Add a parser provider that allows config sources

internal/configprovider/parser.go, internal/configprovider/parser_test.go, internal/configprovider/testdata/cfgsrc_load_use_cfgsrc.yaml, internal/configprovider/testdata/env_var_on_load.yaml
The YAML section config_sources was missing the environment variables. This PR adds that support by processing the config.Parser passed to load.
/cc @Owais
=> Add support of env vars on config_sources section

cmd/otelcol/main.go, internal/configsources/configsources.go, internal/configsources/configsources_test.go
Similar to components a set of default config sources needs to be defined. Since config sources are still experimental they are not being added to the components package. To avoid circular dependencies a dedicated package, configsources, was created since config source implementations depend on the configprovider package for configuration load and related interfaces.
=> Create default config sources

internal/configprovider/manager.go, internal/configprovider/manager_test.go
Named config sources were not being handled correct: the code was relying on getShellName from os package and that stopped at the first '/'. Fixed the code and separate the logic to handled ${<expression>} from $<expression>.
=> Fix named config sources

docs/components.md, go.mod, go.sum, internal/components/components.go, internal/components/components_test.go
Adding the kafkametricsreceiver which should allow us to ingest kafka consumer lag
=> added kafkametricsreceiver

internal/configsources/configsources.go, internal/configsources/configsources_test.go
Enabling two more config sources: etcd2 and zookeeper.
=> Enable etcd2 and zookeeper config sources

.circleci/config.yml
I am disabling until an audit is done and we are certain there
is nothing wrong with it.
We should decide how we prevent this from happening in the future.
=> Disable codecov until the script is audited

cmd/otelcol/config/collector/agent_config.yaml
This is important to create the unique cloud dimensions,
such as `AWSUniqueId`, `gcp_id`, or `azure_resource_id`,
which our built-in content heavily relies on.
Ordering taken from https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor#ordering
=> Enable primary cloud resource detection

internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go
=> Remove premature protection for Start/Stop, trust Service to start/stop once

internal/extension/smartagentextension/config.go, internal/receiver/smartagentreceiver/config.go, internal/receiver/smartagentreceiver/config_test.go, internal/receiver/smartagentreceiver/testdata/nested_monitor_config.yaml, internal/utils/config.go
Addresses the following -
- Currently yamlTags from pointers to structs aren't accounted for
- Capitalized yaml tags aren't applied recursively on structs
=> Fix config parsing for structs and pointers to structs

cmd/otelcol/config/collector/gateway_config.yaml
In our other default agent config, we are recommending sending
to the gateway via OTLP. If agents are sending OTLP to the gateway,
we need to do exclusions and translations at the gateway, as these
would only occur if they were using the signalfx exporter.
=> Unset exclusion and translations by default in gateway config

.circleci/config.yml
- Remove ghr from circleci and save the packages as artifacts instead of publishing them to github (temporary workaround until the release workflow is migrated to github actions)
- Also save artifacts from the main branch builds
=> Remove ghr and save release artifacts

internal/extension/smartagentextension/config.go, internal/extension/smartagentextension/config_linux_test.go, internal/extension/smartagentextension/config_test.go, internal/extension/smartagentextension/config_windows_test.go, internal/extension/smartagentextension/extension.go, internal/extension/smartagentextension/factory.go, internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go
OpenTelemetry collector core in the Host interface does not guarantee access to the Config as a Key in the map (which is NamedInstance and not config.Extension).
=> Avoid using type casting on Config, otel core guarantees access to instances

internal/configprovider/manager.go, internal/configprovider/manager_test.go, internal/extension/smartagentextension/config.go, internal/receiver/smartagentreceiver/config.go
=> Avoid using removed functionality (Parser.Viper) from otel core

internal/configprovider/config_server.go, internal/configprovider/config_server_test.go, internal/configprovider/config_source_provider.go
Exposes config via an HTTP server at localhost if explicitly requested. Expose the config by setting the environment variable "SPLUNK_DEBUG_CONFIG_SERVER" to "true" (it won't work for any other value). By default it exposes the HTTP server at localhost:55555 with the following paths:
- /debug/configz/initial
- /debug/configz/effective
The first shows the initial configuration used by the collector the second the configuration actually in use by the collector. If the configuration is reloaded due to some update triggered by a config source the endpoint is briefly unavailable until the updated configuration is reloaded.
The exposed port is controlled by the env var "SPLUNK_CONFIG_SERVER_PORT" - if it is explicitly set to the empty string, e.g. SPLUNK_DEBUG_CONFIG_SERVER_PORT="" it disables …
=> Expose initial and effective config for debugging purposes

internal/configsource/envvarconfigsource/README.md, internal/configsource/envvarconfigsource/config.go, internal/configsource/envvarconfigsource/config_test.go, internal/configsource/envvarconfigsource/configsource.go, internal/configsource/envvarconfigsource/configsource_test.go, internal/configsource/envvarconfigsource/factory.go, internal/configsource/envvarconfigsource/factory_test.go, internal/configsource/envvarconfigsource/session.go, internal/configsource/envvarconfigsource/session_test.go, internal/configsource/envvarconfigsource/testdata/config.yaml, internal/configsource/envvarconfigsource/testdata/env_config_source_end_2_end.yaml, internal/configsource/envvarconfigsource/testdata/env_config_source_end_2_end_expected.yaml, internal/configsources/configsources.go
Although the OTel collector already supports env variables on the config for feature parity with SA we need to add a full config source for env vars. Having env vars as a config source allows injection of YAML fragments, like SA, via environment variables. Added also the following:
- Possibility to define defaults/fallbacks when environment variables used in the config are undefined in the environment.
- A retrieve parameter to indicate that the configuration load should fail if the environment variable is not defined.
=> Add a config source for env vars

internal/configprovider/manager.go, internal/configprovider/manager_test.go, internal/configprovider/testdata/yaml_injection.yaml, internal/configprovider/testdata/yaml_injection_expected.yaml
This keeps parity with SA functionality: config sources can return fragments of YAML to be injected in the configuration. Usage of it will appear on the README for env var config sources.
/cc @owais
=> Config sources: handle strings and byte slices as YAML

docs/signalfx-smart-agent-migration.md
These changes correct a config typo (`receivor_creator`) and also demonstrate the `processlist` monitor's logs pipeline requirements, which is also documented in the receiver readme but potentially not clearly enough.
=> Fix SA migration typo and expand example

cmd/otelcol/main.go
Use a strict greater than so folks can set ballast as exactly 2x the memory limit.
Right now, we get this message:
```
2021/05/06 00:44:51 main.go:276: Memory limit (512) is less than 2x ballast (256). Increase memory limit or decrease ballast size.
```
=> nit: >, not >=

cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, cmd/otelcol/config/collector/gateway_config.yaml, cmd/otelcol/config/collector/otlp_config_linux.yaml, examples/kubernetes-yaml/splunk-otel-collector-agent.yaml, examples/kubernetes-yaml/splunk-otel-collector-gateway.yaml, examples/prometheus-federation/otel-collector-config.yml, examples/splunk-hec-metrics/otel-collector-config.yml, examples/splunk-hec/otel-collector-config.yml
For better user experience, we want to have default endpoint values always to be explicitly set in the configs, so user don't have to check receiver docs in order to find out which port data should be sent to.
=> Explicitly define receivers endpoints

internal/buildscripts/packaging/fpm/deb/build.sh, internal/buildscripts/packaging/fpm/postinstall.sh, internal/buildscripts/packaging/fpm/rpm/build.sh, internal/buildscripts/packaging/tests/package_test.py
- Set the `CAP_SYS_PTRACE` and `CAP_DAC_READ_SEARCH` capabilities for `/usr/bin/otelcol` during deb/rpm postinstall (similar to the smart agent)
- Add the `setcap` package dependency
=> Enable capabilities in deb/rpm postinstall

internal/buildscripts/packaging/tests/requirements.txt
Explicitly add `six` as a requirement for pytest dependencies as a workaround for https://github.com/docker/docker-py/issues/2807.
=> Add six to pip requirements for tests

deployments/ansible/roles/collector/tasks/apt_install_otel_collector.yml
`ansible.builtin.apt_key` module has a know bug in ansible v4.0.0 https://github.com/ansible/ansible/issues/74424 which is fixed in the version 4.0.1 that will be released on May 24. Until that use `ansible.builtin.get_url` module instead
=> Workaround ansible.builtin.apt_key module bug in ansible 4.0.0

Makefile, tests/README.md, tests/receivers/smartagent/collectd-activemq/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-activemq/testdata/default_metrics_config.yaml, tests/receivers/smartagent/collectd-apache/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-apache/testdata/default_metrics_config.yaml, tests/receivers/smartagent/collectd-cassandra/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-cassandra/testdata/default_metrics_config.yaml, tests/receivers/smartagent/collectd-couchbase/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-elasticsearch/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-hadoop/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-kafka/testdata/all_broker_metrics_config.yaml, tests/receivers/smartagent/collectd-kafka/testdata/all_consumer_metrics_config.yaml, tests/receivers/smartagent/collectd-kafka/testdata/all_producer_metrics_config.yaml, tests/receivers/smartagent/collectd-nginx/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-postgresql/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-solr/testdata/all_metrics_config.yaml, tests/receivers/smartagent/collectd-spark/testdata/all_master_metrics_config.yaml, tests/receivers/smartagent/collectd-spark/testdata/all_worker_metrics_config.yaml, tests/testutils/README.md, tests/testutils/collector.go, tests/testutils/collector_container.go, tests/testutils/collector_container_test.go, tests/testutils/collector_process.go, tests/testutils/collector_process_test.go, tests/testutils/container.go, tests/testutils/otlp_receiver_sink_test.go, tests/testutils/testcase.go
These changes allow running the existing integration tests against* an arbitrary collector container.  They add a new `CollectorContainer` type that implements the now unified `Collector` interface broken out from the previously lone `CollectorProcess`.   The `make integration-test` target uses this collector type by default to run against `quay.io/signalfx/splunk-otel-collector-dev:latest`.
Also updates the integration test configs to not use the agent extension.  These are breaking changes that require running against a collector binary with a properly configured agent bundle.  An easy way to avoid this and still test local changes is to run:
```bash
SPLUNK_OTEL_COLLECTOR_IMAGE='otelcol:latest' make -e docker-otelcol integration-test
```
Running Collector containers with command line …
=> Allow running integration tests against Collector images

internal/configprovider/manager.go, internal/configprovider/manager_test.go, internal/configsource/envvarconfigsource/session.go, internal/configsource/envvarconfigsource/session_test.go
Handling of nil retrieved values by the config provider manager was causing the string "<nil>" to be used. Fixed the handling on the manager and removed the special case on the env variable.
=> Correctly handle nil value on the config provider

cmd/otelcol/main.go, tests/endtoend/doc.go, tests/general/container_test.go, tests/general/testdata/logged_hostmetrics.yaml, tests/testutils/collector.go, tests/testutils/collector_container.go, tests/testutils/collector_container_test.go, tests/testutils/collector_process.go
Currently it's forbidden to set both `SPLUNK_CONFIG` and provide the `--config` cmdline options for our distribution.  This is a little unexpected given cli tools generally allow redundant options while giving priority to command line options and falling back to environment variables.  The current system makes it relatively inconvenient to update startup arguments as changing or clearing the environment variable is also required, which can sometimes be more difficult than updating the cmdline args.
These changes ease the restriction and give priority to the `--config` option with clear logging of which config will be used.  They also provide more context when default config locations are used and required env vars aren't set.
Also including necessary testutils changes for added …
=> Allow setting both SPLUNK_CONFIG and --config with priority given to --config

cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, cmd/otelcol/config/collector/gateway_config.yaml, cmd/otelcol/config/collector/otlp_config_linux.yaml
These changes add a new metrics pipeline w/ internal prometheus scraper and a resource detector that overrides attributes (since the `host.name` is 0.0.0.0 as reported by prometheus).
=> Use internal pipelines for collector prometheus metrics

cmd/translatesfx/translatesfx/directive.go, cmd/translatesfx/translatesfx/otel.go, cmd/translatesfx/translatesfx/otel_test.go, cmd/translatesfx/translatesfx/testdata/sa-collectd.yaml, cmd/translatesfx/translatesfx/testdata/sa-discoveryrules.yaml, cmd/translatesfx/translatesfx/translate.go
Manually end-to-end tested using a collectd/redis Smart Agent config. Also now deleting any discovery rules -- will translate them in a subsequent PR.
=> Add support for translating collectd monitors

README.md, cmd/otelcol/main.go, docs/troubleshooting.md, internal/buildscripts/packaging/fpm/etc/otel/collector/splunk-support-bundle.sh
Configured main.go to enable in memory config gathering locally. In
addition, updated support bundle to capture this information.
=> Enable collecting in memory config locally by default

docs/troubleshooting.md, internal/buildscripts/packaging/fpm/etc/otel/collector/fluentd/conf.d/journald.conf
Journald can either persist data in /var/log/journald or temporarily
store in /run/log/journald. A clean Ubuntun 20.04 Docker container will
NOT persist journald by default -- as a result, Fluentd will NOT pick up
the data. Update the Fluentd default configuration to ensure this data
is collected.
Note: the tail plugin supports a comma-separate list of paths, it does
not appear the journald plugin does.
Tested locally.
Also update the troubleshooting guide as the example provided does not
work with the syslog parser.
=> Add support for non-persisted journald

internal/configsource/zookeeperconfigsource/README.md, internal/configsource/zookeeperconfigsource/factory.go, internal/configsource/zookeeperconfigsource/factory_test.go
Previous ZK endpoint validation required endpoints to be valid URLs, but URLs don't appear
to be valid ZK endpoints. ZK needs a bare hostname or a hostname:port. This change removes
the endpoint validation altogether and leaves it to ZK. Change manually tested on Linux
against the latest ZK.
=> zk config source: remove config validation for zk endpoints

cmd/otelcol/main.go, cmd/otelcol/main_test.go, docs/getting-started/linux-manual.md, internal/configprovider/config_source_provider.go, internal/configprovider/config_source_provider_test.go, tests/general/container_test.go
Supplying Splunk Otel Collector configuration yaml via environment variable SPLUNK_CONFIG_YAML. 
One advantage is that this allows for having the config YAML as a parameter value in AWS Systems Manager Parameter Store and thus removing the need to have a volume mounted to a Fargate task to hold the configuration file.
=> Add env var SPLUNK_CONFIG_YAML for storing configuration YAML

examples/prometheus-federation/docker-compose.yml, examples/splunk-hec-metrics/docker-compose.yml, examples/splunk-hec/docker-compose.yml
The example projects fail to run, the otel-collector-config health_check extension contains an endpoint entry which didn't exist when docker image 0.5.0 was built, it was added with https://github.com/open-telemetry/opentelemetry-collector/pull/2782
=> Update the splunk-otel-collector docker image to fix broken examples

cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, cmd/otelcol/config/collector/gateway_config.yaml, cmd/otelcol/config/collector/otlp_config_linux.yaml, cmd/otelcol/config/collector/upstream_agent_config.yaml, cmd/otelcol/main.go, cmd/otelcol/main_test.go, examples/kubernetes-yaml/splunk-otel-collector-agent.yaml, examples/kubernetes-yaml/splunk-otel-collector-gateway.yaml
Bug: If `SPLUNK_MEMORY_TOTAL_MIB` set to more than 20480, the calculated memory limit drops from 90% to 2048 and collector is failing to start with 
```
main.go:283: Memory limit (2048) is less than 2x ballast (6761). Increase memory limit or decrease ballast size.
```
This change fixes the bug and removes the unnecessary complication for default memory limit calculation. If user wants to adjust memory allocation for a 20Gb+ deployment they can always use `SPLUNK_MEMORY_LIMIT_MIB` env var.
=> Fix memory limit calculation for deployments with 20Gi+ of total memory

cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, cmd/otelcol/config/collector/gateway_config.yaml, cmd/otelcol/config/collector/otlp_config_linux.yaml, cmd/otelcol/config/collector/upstream_agent_config.yaml, cmd/otelcol/main.go, cmd/otelcol/main_test.go, internal/components/components.go, internal/components/components_test.go
* The memory_ballast extension is the only way to configure ballast starting with v0.31.0 of the collector;
* The memory_limiter processor accesses the ballast directly from the config, no need to set ballast_memory_size anymore;
=> Update to use the ballast memory instead of the flag

.gitignore, README.md, deployments/heroku/README.md, deployments/heroku/bin/compile, deployments/heroku/bin/detect, deployments/heroku/bin/release, deployments/heroku/setup/agent.sh, deployments/heroku/setup/config.yaml, deployments/heroku/test/Procfile, deployments/heroku/test/README.md, deployments/heroku/test/config.yaml, deployments/heroku/test/package.json, deployments/heroku/test/send_metrics.js
The SignalFx Smart Agent has a Heroku buildpack. Create the same
packaging for Splunk OpenTelemetry Connector adding the Smart Agent
bundle. Includes complete feature parity with Smart Agent buildpack.
Changes from Smart Agent buildpack:
- Default to latest releases instead of hard-coding an old version
- More exposed configuration options
- Example application to make it easier to get started (modified from
signalfx-nodejs)
- Included in same repository instead of dedicated
=> Add Heroku buildpack

Makefile, tests/testutils/container_test.go, tests/testutils/testcase.go
These changes slightly update the method of finding test files, reaching the host via [`host.docker.internal`](https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds), and accounting for ipv6* in docker port maps on mac.
=> Allow running integration tests on mac os

cmd/translatesfx/translatesfx/cli.go, cmd/translatesfx/translatesfx/directive.go, cmd/translatesfx/translatesfx/directive_test.go, cmd/translatesfx/translatesfx/otel.go, cmd/translatesfx/translatesfx/otel_test.go, cmd/translatesfx/translatesfx/sa.go, cmd/translatesfx/translatesfx/sa_test.go, cmd/translatesfx/translatesfx/testdata/otel-e2e-expected.yaml, cmd/translatesfx/translatesfx/testdata/sa-e2e-input.yaml, cmd/translatesfx/translatesfx/testdata/sa-vault.yaml, cmd/translatesfx/translatesfx/translate_test.go
This change converts Vault remote configs in Smart Agent to Otel Config Sources.
For example, the following partial Smart Agent config:
```
configSources:
vault:
vaultAddr: http://127.0.0.1:8200
vaultToken: abc123
monitors:
- type: vsphere
username: bob
password: {"#from": "vault:/secret/sfx[password]"}
```
is translated into
```
config_sources:
vault/0:
endpoint: http://127.0.0.1:8200
path: /secret/sfx
auth:
token: abc123
receivers:
smartagent/vsphere:
username: bob
password: ${vault/0:password}
```
=> translatesfx: add support for vault remote config

docs/security.md, docs/troubleshooting.md, internal/buildscripts/packaging/fpm/etc/otel/collector/splunk-support-bundle.sh, internal/configprovider/config_server.go
It appears Mac OS Big Sur uses port 55555:
https://developer.apple.com/forums/thread/671197. To ease user
experience, change the default port of the config server.
While this is a breaking change, the port is only exposed locally and
used by the support bundle script. As a result, this should not have
user impact beyond education of the updated port.
=> Change default config server port to 55554

cmd/otelcol/main.go, cmd/otelcol/main_test.go
If you deploy Splunk OTel Connector outside of installer script then the
gateway configuration is used. If the agent configuration was desired,
it was really hard to switch:
```
$ > SPLUNK_ACCESS_TOKEN=1234 SPLUNK_REALM=us0 SPLUNK_CONFIG=../cmd/otelcol/config/collector/agent_config.yaml ./otelcol_darwin_amd64
2021/07/23 11:30:17 main.go:198: Set config to ../cmd/otelcol/config/collector/agent_config.yaml
2021/07/23 11:30:17 main.go:283: Set ballast to 168 MiB
2021/07/23 11:30:17 main.go:307: Set memory limit to 460 MiB
2021-07-23T11:30:17.907-0400	info	service/collector.go:283	Starting otelcol...	{"Version": "v0.29.0-43-g491b2f0", "NumCPU": 12}
2021-07-23T11:30:17.910-0400	info	service/collector.go:343	Using memory ballast	{"MiBs": 168}
2021-07-23T11:30:17.910-0400	info …
```
=> Set required URL and TOKEN env vars for agent config

internal/buildscripts/packaging/fpm/postinstall.sh
Ensures that the paths are accessible by the `splunk-otel-collector` service user/group if the deb/rpm package is not installed by the installer script.
=> Set path ownership on deb/rpm postinstall

.circleci/config.yml
No need to run circleci jobs for tags anymore since tags are built in gitlab now.
=> Disable circleci jobs for tags

internal/receiver/smartagentreceiver/log.go, internal/receiver/smartagentreceiver/log_test.go
The target logrus standard logger used by the agent monitors will only have its level set to the config-specified value in the agent main, which we do not use.  These changes set the logger from the equivalent receiver zap logger's core.
=> smart agent receiver: set redirected logrus logger level

cmd/translatesfx/translatesfx/otel.go, cmd/translatesfx/translatesfx/otel_test.go, cmd/translatesfx/translatesfx/testdata/otel-e2e-expected.yaml, cmd/translatesfx/translatesfx/testdata/sa-dp-to-exclude-simple.yaml, cmd/translatesfx/translatesfx/testdata/sa-dp-to-exclude.yaml, cmd/translatesfx/translatesfx/testdata/sa-e2e-input.yaml, cmd/translatesfx/translatesfx/translate.go, go.mod, go.sum
This change translates a Smart Agent config's metricsToExclude globs to an equivalent Otel filter processor.
Given the following metricsToExclude in a SmartAgent config:
```
metricsToExclude:
- metricNames:
- node_filesystem_*
- '!node_filesystem_free_bytes'
- '!node_filesystem_readonly'
- metricName: node_network_*
dimensions:
interface: [ '*', '!eth0' ]
- metricName: node_disk_*
dimensions:
device: sr*
```
the following filter processor will be generated:
```
filter:
metrics:
exclude:
match_type: expr
expressions:
- MetricName matches "^node_filesystem_.*$" and not (MetricName
matches "^node_filesystem_free_bytes$") and not (MetricName matches
"^node_filesystem_readonly$")
- MetricName matches "^node_network_.*$" and (Label("interface")
matches "^.*$" and not (Label("interface") matches …
```
=> translatesfx: translate metricsToExclude

cmd/translatesfx/translatesfx/cli.go, cmd/translatesfx/translatesfx/otel.go, cmd/translatesfx/translatesfx/otel_test.go, cmd/translatesfx/translatesfx/testdata/sa-e2e-input.yaml, cmd/translatesfx/translatesfx/translate.go, cmd/translatesfx/translatesfx/translate_test.go
Previous version extracted the realm from the SA config's apiURL (which may not even have been specified). This change just translates apiURL, ingestURL, and realm directly from SA config to the SFx exporter config.
=> translatesfx: directly translate realm and urls from SA to SFx exporter

cmd/translatesfx/translatesfx/otel.go, cmd/translatesfx/translatesfx/otel_test.go
Also, don't build a metrics pipeline if there are no metrics receivers.
=> translatesfx: only put processlist in logs pipeline if it's specified in SA

docs/release.md, internal/buildscripts/packaging/release/helpers/release_args.py, internal/buildscripts/packaging/release/helpers/util.py, internal/buildscripts/packaging/release/sign_release.py
Remove the AWS key requirement for S3 releases since it is now replaced by the new okta auth process.  This is temporary until we can automate from gitlab.
=> Update S3 release process

.github/release-drafter.yaml
This change adds a paragraph at the top of the draft of release notes for new versions of the Splunk OpenTelemetry Collector that links to the Quay page showing releases of the Splunk OpenTelemetry Collector, and text of the Docker image URL one can use to take advantage of the release.
It has not been tested.
=> Add text linking the new release to its Docker image URL

deployments/fargate/README.md
In the Fargate task definition JSON, adding a JSON array value to the environment field of a container definition causes an error. Stringifying the JSON array resolves the error.
=> Stringify JSON array value of a container definition in Fargate

cmd/translatesfx/translatesfx/otel.go, cmd/translatesfx/translatesfx/otel_test.go, cmd/translatesfx/translatesfx/testdata/otel-e2e-expected.yaml, cmd/translatesfx/translatesfx/testdata/sa-e2e-input.yaml, cmd/translatesfx/translatesfx/translate.go
SA's `metricsToInclude` overrides any matching `metricsToExclude`. This change
translates SmartAgent metricsToInclude filters and appends them to filter
processor expr expressions.
For example, the following SA filters:
```
metricsToExclude:
- metricNames:
- node_filesystem_*
metricsToInclude:
- metricNames:
- node_filesystem_readonly
```
should translate to:
```
filter:
metrics:
exclude:
match_type: expr
expressions:
- MetricName matches "^node_filesystem_.*$" and
(not (MetricName matches "^node_filesystem_readonly$"))
```
=> translatesfx: translate metricsToInclude filters to expr

internal/buildscripts/packaging/msi/msi-builder/Dockerfile
Workaround for `apt` failures when building the MSI due to move of `stable` sources to `buster`:
```
Err:4 http://security.debian.org/debian-security stable/updates Release
404  Not Found [IP: 151.101.130.132 80]
Get:5 http://deb.debian.org/debian stable/main i386 Packages [8117 kB]
Reading package lists...
E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
```
=> Update apt sources for buster in wix dockerfile

.github/workflows/ansible.yml
To avoid triggering when release tags are pushed
=> Ignore tags in ansible github action

.gitlab-ci.yml
- Fix syntax errors
- Rename `test` stage to `cve-scan`
- Move `cve-scan` stage/job to after `build-image` job to avoid redundant image builds
- Remove `notify-cve-scan-failure` job and move slack message post to `cve-scan:after_script`
- Move cron schedule from the file to the gitlab pipeline Schedules page
=> Update cve-scan in gitlab CI

.gitlab-ci.yml
Exclude unnecessary build/release jobs when running scheduled security scans
=> Only run security scan jobs for scheduled pipelines

docs/getting-started/linux-manual.md, internal/buildscripts/packaging/fpm/postinstall.sh, internal/buildscripts/packaging/fpm/rpm/build.sh
- Initial step to support suse since the automatic dependency on `libcap` prevents the installation of the collector rpm on suse
- Next steps: Add suse/zypper support to installer script, ansible, puppet, and docs (need to wait for the rpm with this change to be released to artifactory)
=> Remove libcap dependency from rpm

deployments/ansible/galaxy.yml
Depends on https://github.com/signalfx/splunk-otel-collector/pull/683
=> Add an Ansible Galaxy tag to trigger missed release

deployments/ansible/CHANGELOG.md, deployments/ansible/roles/collector/tasks/apt_install_otel_collector.yml
Hello,
Currently, the ansible role is not usable with proxy set from environment because of a long time and known bug in ansible for apt key module.
I found and tested this workaround here: https://github.com/ansible/ansible/issues/31691#issuecomment-396973282
Here is the underlying relevant code: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt_key.py#L210
Now it is possible to use a playbook like the following:
```yaml
---
- name: "Example of proxy usage with splunk otel"
hosts: all
become: true
tasks:
- name: "Include splunk_otel_collector"
import_role:
name: "signalfx.splunk_otel_collector.collector"
vars:
splunk_access_token: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/signalfx:token') }}"
splunk_realm: eu0
install_fluentd: false …
```
=> avoid using deprecated apt-key

deployments/ansible/CHANGELOG.md, deployments/ansible/roles/collector/README.md, deployments/ansible/roles/collector/defaults/main.yml, deployments/ansible/roles/collector/tasks/linux_install.yml, deployments/ansible/roles/collector/templates/collector-service-proxy.conf.j2
Hello,
It is possible to easily use a proxy during ansible deployment by setting right environment variable at playbook level like:
```yaml
---
- name: "Example of proxy usage with splunk otel"
hosts: all
become: true
tasks:
- name: "Include splunk_otel_collector"
import_role:
name: "signalfx.splunk_otel_collector.collector"
vars:
splunk_access_token: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/signalfx:token') }}"
splunk_realm: eu0
install_fluentd: false
environment:
https_proxy: "{{ https_proxy }}"
http_proxy: "{{ https_proxy }}"
no_proxy: "localhost,127.0.0.1,::1"
```
but it is not possible to configure a proxy to be used by the collector itself.
of course we can add a task after the role import but it seems useful to support this upstream.
=> add collector service level proxy for ansible

internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go
Add `system.type` dimension to all datapoints, where `system.type` == "smartagent-&lt;monitor-name&gt;" in support of pivot sidebar. Not sure about "smartagent-&lt;monitor-name&gt;" -- open to other possibilities.
=> auto add system.type dimension to all sa receiver datapoints

internal/receiver/smartagentreceiver/config.go, internal/receiver/smartagentreceiver/config_test.go, internal/receiver/smartagentreceiver/testdata/endpoints_config.yaml
The current endpoint parser was implemented naively and should accept ipv6 addresses.
=> properly parse receiver creator endpoints in SA receiver

cmd/translatesfx/translatesfx/otel.go, cmd/translatesfx/translatesfx/otel_test.go, cmd/translatesfx/translatesfx/testdata/sa-processlist.yaml
These changes add the `kubernetes-events` monitor to the logs pipeline cases that are* only currently applicable to the processlist monitor.
=> translatesfx: kubernetes-events as logs receiver

.circleci/config.yml
Not sure what changed, but the `windows-test` job recently started failing due to:
```
go: GOPATH entry cannot start with shell metacharacter '~': "~/go"
```
=> Fix GOPATH for windows-test in circleci config

cmd/translatesfx/translatesfx/otel.go, cmd/translatesfx/translatesfx/otel_test.go, cmd/translatesfx/translatesfx/testdata/sa-metrics-to-exclude-monitor.yaml, cmd/translatesfx/translatesfx/translate.go
If metricsToExclude is specified for a monitor (not the agent -- this is
apparently an invalid configuration according to the docs, but it actually
works and some customers are using it) rename it to the supported
datapointsToExclude.
=> translatesfx: rename metricsToExclude to datapointsToExclude on SA monitors

CONTRIBUTING.md, docs/README.md, docs/agent-vs-gateway.md, docs/architecture.md, docs/components.md, docs/experimental/splunk-forwarder-integration.md, docs/experimental/using-fluentd-only.md, docs/faq.md, docs/getting-started/kubernetes-yaml.md, docs/getting-started/linux-installer.md, docs/getting-started/linux-manual.md, docs/getting-started/windows-installer.md, docs/getting-started/windows-manual.md, docs/monitoring.md, docs/security.md, docs/sizing.md, docs/troubleshooting.md
- Adding the docs paragraph to CONTRIBUTING.md, as per GDI Specs PR https://github.com/signalfx/gdi-specification/pull/129
- Adding callouts that point to equivalent official docs (when applicable)
- Adding README file in docs folder 
These changes were discussed and approved by @flands and Traci Morrison.
=> Edit contributing and add callouts to docs

internal/buildscripts/packaging/fpm/rpm/build.sh
For #767.  Resolves installation conflicts for `/usr/lib/.build-id` links if the signalfx-agent rpm is already installed.
=> Exclude build-id links from rpm

README.md
The example directory has an `agent_config.yaml`, there is no `agent_config_linux.yaml`.
=> Use the correct agent config filename

.github/workflows/lychee-push.yml, .github/workflows/lychee-weekly.yml
Ignores 429 status codes from github due to rate limiting without a github token.
=> Allow 200 and 429 codes for lychee

docs/getting-started/linux-installer.md, internal/buildscripts/packaging/installer/install.sh
Allows installation of the collector and/or fluentd packages from preconfigured non-default sources, e.g. private mirrors.
=> Add installer script options to skip repo config

go.mod, internal/components/components.go, internal/components/components_test.go, internal/exporter/httpsinkexporter/README.md, internal/exporter/httpsinkexporter/client.go, internal/exporter/httpsinkexporter/config.go, internal/exporter/httpsinkexporter/config_test.go, internal/exporter/httpsinkexporter/factory.go, internal/exporter/httpsinkexporter/factory_test.go, internal/exporter/httpsinkexporter/httpsink_exporter.go, internal/exporter/httpsinkexporter/testdata/config.yaml
This is a test exporter that allows clients to "watch" for spans they might be interested in. This is very useful for end-to-end tests where we want to test real world applications and ensure data reaches the collector as expected.
The exporter exposes a HTTP endpoint. Clients can make GET requests to this endpoint and specify the characteristics of spans they are interested in using URL query params. Collector will then block the request until it detects the specified spans. Once the spans are detected, they are serialized to JSON (using jaeger proto) and returned back to the client. Multiple clients can watch for the same spans at the same time. The export does not hold anything in memory before a watch is started or after a watch ends. Clients must start the watch first, generate spans …
=> Initial version of HTTP sink exporter

deployments/ansible/roles/collector/tasks/linux_install.yml
waiting for feature or answer addressing https://github.com/signalfx/splunk-otel-collector/issues/700, using `template` module instead of `copy` will, at least, allow user to inject some variables from ansible to the otel collector config file.
For example if we need to define secret values in otel collector file, the only way is to hardcode them in the static file.
another way could be to provide variable to change src of `splunk-otel-collector.conf.j2`. this will allow users to define his own custom variable and use them in the otel collector yaml config file which could so remain static but this way seems less powerful.
=> custom configuration file templating support

cmd/otelcol/config/collector/full_config_linux.yaml
The processor is not being used in any of the pipelines, and it was renamed to k8sattributes processor in contrib
=> Remove k8s_tagger processor from full_config_linux.yaml

cmd/otelcol/config/collector/ecs_ec2_config.yaml
We need this double evaluation to expand the lists, otherwise it is interpreted as a string and doesn't work. The `METRICS_TO_EXCLUDE` is described but isn't present in any of the pipelines, so I'll submit a follow up PR to enable that.
=> Fix evaluating env variables in ecs ec2 config

cmd/otelcol/Dockerfile, cmd/otelcol/Dockerfile.windows, internal/buildscripts/packaging/fpm/common.sh, internal/buildscripts/packaging/msi/msi-builder/build.sh
Relaxes cert removal from https://github.com/signalfx/splunk-otel-collector/pull/861.  Requests uses the certifi bundle by default and this doesn't appear configurable, so sfxcollectd plugins are experiencing errors:
```
Could not find a suitable TLS CA certificate bundle, invalid path: /usr/lib/splunk-otel-collector/agent-bundle/lib/python3.8/site-packages/certifi/cacert.pem
```
=> Ensure only test certs are stripped from agent bundle

CHANGELOG.md, cmd/otelcol/config/collector/fargate_config.yaml, cmd/otelcol/main.go
We need this double evaluation to expand the lists, otherwise it is interpreted as a string and doesn't work.
=> Fix evaluating env variables in fargate config

cmd/otelcol/main.go, docs/getting-started/linux-manual.md, docs/getting-started/windows-manual.md, examples/prometheus-federation/docker-compose.yml, examples/splunk-hec-metrics/docker-compose.yml, examples/splunk-hec-traces/docker-compose.yml, examples/splunk-hec/docker-compose.yml, tests/testutils/collector_process.go, tests/testutils/collector_process_test.go
https://github.com/open-telemetry/opentelemetry-collector/commit/a51bf5a2753263aa0284f76548847bea46e75d07 broke `--set` support for our distribution and https://github.com/open-telemetry/opentelemetry-collector/commit/48a2e01652fa679c89259866210473fc0d42ca95 removed `--log-level` support from the collector so that setting non-info log level requires manual config changes (read: inconvenient).
These changes ~port the `--set` properties parser and use it in our default config provider.  Also updates `--log-level` usage throughout project to the required `--set service.telemetry.logs.level` value.
=> Support set flag and update log-level example usage

.circleci/config.yml, .github/workflows/build-and-test.yml
Migrate lint, test, and coverage jobs
Ticket: [OTL-1257.](https://signalfuse.atlassian.net/browse/OTL-1257)
Adding GitHub Action jobs of `lint`, `test`, and `coverage`.
Removing CircleCi jobs of `lint`, `test`, and `coverage`.
=> Migrate lint, coverage, and unit-test jobs from CircleCi to GitHub Action.

go.mod, go.sum, tests/go.mod
Include https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/87408fd66556302f90741242e95b444707d0d4a6 for v0.39.0 release.
=> Update splunkhec exporter/receiver

.gitlab-ci.yml
The splunk semgrep policy was recently updated and now fails if Dockerfiles do not define or run as `USER` .  This change excludes the windows and ansible test Dockerfiles from semgrep scans.
=> Update exclude list for semgrep

CHANGELOG.md, cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/ecs_ec2_config.yaml, cmd/otelcol/config/collector/fargate_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, cmd/otelcol/config/collector/gateway_config.yaml, cmd/otelcol/config/collector/otlp_config_linux.yaml, cmd/otelcol/config/collector/upstream_agent_config.yaml, deployments/nomad/otel-agent.nomad, deployments/nomad/otel-gateway.nomad, examples/kubernetes-yaml/splunk-otel-collector-agent.yaml, examples/kubernetes-yaml/splunk-otel-collector-gateway.yaml, examples/nomad/otel-demo.nomad
Migrate from legacy endpoint. The migration must be smooth because setting up default OTLP HTTP endpoint also enables the legacy one https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/otlp.go#L146-L157. 
With this change, the collector will be listening on both 0.0.0.0:4318 and 0.0.0.0:55681 endpoints.
Warning for configured legacy endpoint added here: https://github.com/open-telemetry/opentelemetry-collector/pull/4519
=> Update OTLP HTTP receiver endpoint to use port 4318 in default configuration files

.gitlab-ci.yml
Workaround for `github.com/hashicorp/vault/sdk/framework` false positive to unblock the gitlab pipeline
=> Only fail docker scan for high severity

deployments/ansible/molecule/default/Dockerfile.j2, internal/buildscripts/packaging/tests/deployments/puppet/images/rpm/Dockerfile.opensuse-12, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.opensuse-12
`opensuse-12` tests have been failing due to mirror resolution issues.  Pin the repo to a mirror that is known to work.
=> Update opensuse repo mirror for tests

.github/workflows/build-and-test.yml, .github/workflows/deps-test.yml, .github/workflows/integration-test.yml, .github/workflows/windows-test.yml, .gitlab-ci.yml
Upgrade Golang to the latest 1.17.x (1.17.6) to address the following vulnerabilities 
- [CVE-2021-41772](https://nvd.nist.gov/vuln/detail/CVE-2021-41772)
- [CVE-2021-41771](https://nvd.nist.gov/vuln/detail/CVE-2021-41771)
This fixes https://github.com/signalfx/splunk-otel-collector/issues/1063
=> Upgrade golang to 1.17.6 

go.mod, go.sum
The newest version of vault has invalid deps and is breaking `go mod tidy`: https://github.com/hashicorp/vault/pull/13321.
We should probably have `go mod tidy` checks in CI, which I'll try in another PR.
=> fix invalid vault api deps

CHANGELOG.md, internal/receiver/smartagentreceiver/config.go, internal/receiver/smartagentreceiver/config_linux_test.go, internal/receiver/smartagentreceiver/config_test.go, internal/receiver/smartagentreceiver/receiver.go
Only select smart-agent monitors can be created via endpoints. This is
defined as a struct tag on the monitor configs "acceptsEndpoints". In
the case where we attempt to set Host/Port on a monitor that has it's
"acceptsEndpoints" value set to false, an error occurs and we do not
create the monitor.
This change would create the monitor but avoid setting the
Host/Port fields. This allows the receiver creator to
create any smart-agent monitor with receiver creator.
=> check if monitor accepts endpoints before setting host/port

CHANGELOG.md, cmd/otelcol/config/collector/ecs_ec2_config.yaml, cmd/otelcol/config/collector/fargate_config.yaml
This is no longer required and would now lead to warnings during config parsing.
=> Remove double dollar ecs config escaping

tests/general/testdata/envvar_labels.yaml, tests/general/testdata/resource_metrics/envvar_labels.yaml
These changes better demonstrate `$` escaping requirements when using non-envvar symbols.
=> update env var expansion test with non env var usage

CHANGELOG.md, internal/receiver/smartagentreceiver/config.go, internal/receiver/smartagentreceiver/config_windows_test.go, internal/receiver/smartagentreceiver/testdata/collectd_apache.yaml
The existing error is vague for windows users who aren't aware that existing platform support is enforced in SA receiver. These changes provide more detail instead of saying the monitor isn't known.
=> Provide informative unsupported monitor error on windows

.github/workflows/build-and-test.yml, .github/workflows/scripts/win-test-services.ps1, .github/workflows/scripts/win-test-support-bundle.ps1, .github/workflows/windows-test.yml
- For https://github.com/actions/virtual-environments/issues/4856: Pin the docker and choco build jobs to `windows-2019` since that is what we use for release builds from gitlab
- Update the msi, choco, and windows test jobs to run for both `windows-2019` and `windows-2022`
- Update choco test job to run with and without fluentd
- Move powershell test steps to scripts
=> Run windows tests on 2019 and 2022

.github/workflows/auto-instrumentation.yml, .gitignore, instrumentation/Dockerfile, instrumentation/Makefile
- Initial CI job to build `libsplunk.so` for amd64 and arm64
- Add basic dockerfile with build dependencies
- Add `dist` makefile target to build docker image and test/compile for `$ARCH`
=> Add CI job to build libsplunk.so

deployments/puppet/manifests/params.pp, deployments/puppet/metadata.json
For https://signalfuse.atlassian.net/browse/OTL-1227
=> puppet: Bump default td-agent version to 4.3.0

deployments/ansible/roles/collector/tasks/linux_install_fluentd.yml
For https://signalfuse.atlassian.net/browse/OTL-1227
=> ansible: Bump default td-agent version to 4.3.0

cmd/otelcol/config/collector/ecs_ec2_config.yaml, cmd/otelcol/config/collector/fargate_config.yaml
Since the pipeline for logs and profiling is the same, this is a PR to enable it for ec2/ecs and fargate by default to avoid any configuration changes to do so.  
Context: https://docs.google.com/document/d/1KABqbnRCi--JGc6ZHIADMeyccTlTrUJZnPVQZk7F4Cs/edit?disco=AAAATAk4C5Y
=> Enabling shared pipeline for profiling by default

go.mod, go.sum, tests/go.mod, tests/go.sum
For dependabot alert [GHSA-qq97-vm5h-rrhg](https://github.com/advisories/GHSA-qq97-vm5h-rrhg)
=> Bump github.com/docker/distribution to v2.8.0

docs/signalfx-smart-agent-migration.md, internal/receiver/smartagentreceiver/README.md
As a result of https://github.com/signalfx/splunk-otel-collector/issues/1246
=> add notes to readme clarifying signalfx exporter required for events

CHANGELOG.md, internal/receiver/smartagentreceiver/config.go
`collectd/hadoop` is python based and functional on windows.
=> smartagent: correct collectd/hadoopjmx type for windows validation

.gitlab-ci.yml
Reduces cache sizes since they have been accumulating with old packages.
=> Use file hash for cache in gitlab

go.mod, go.sum, internal/components/components.go, internal/components/components_test.go
Include the TCP log receiver in our distribution
=> Include the TCP log receiver in our distribution

Makefile
During build we need to also update the core version file, otherwise, the internal metrics show "latest" instead of the real version.
=> Update core version during build

.github/workflows/deps-test.yml
Upgrading core/contrib deps to `main` has been too unstable, so just try testing with the latest release instead (only if there are changes).
Sample run: https://github.com/signalfx/splunk-otel-collector/runs/5605814999?check_suite_focus=true
=> Upgrade to latest instead of main for deps test

internal/receiver/smartagentreceiver/converter/event.go, internal/receiver/smartagentreceiver/converter/event_test.go, internal/receiver/smartagentreceiver/output_test.go
After this change https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/e794616815bd9a145503f87078a623d6e2908e2d the SA processlist monitor stopped working.
This PR uses the new event type attribute in the event to log conversion .
=> Update SA event type to fix processlist

.github/workflows/build-and-test.yml, .github/workflows/windows-test.yml
- Only run the `build-and-test` and `windows-test` workflows if there are changes to relevant paths.
- Skip these workflows if only `**.md` files are changed.
=> Restrict workflow runs for relevant paths

CHANGELOG.md, cmd/otelcol/config/collector/gateway_config.yaml
Remove `signalfx` exporter from traces pipeline. `signalfx` exporter in the traces pipeline is used only for correlation when the Collector runs as an agent. It shouldn't be enabled for a Collector running as the gateway.
=> gateway config: Remove signalfx exporter from traces pipeline

.gitlab-ci.yml
Restrict concurrent deb/rpm release jobs with `resource_group` to prevent artifactory repo conflicts when multiple pipelines are running at the same time.
=> Add resource_group to gitlab pipeline

.github/workflows/integration-test.yml
Similar to our other workflows, auto-cancel in-progress integration test jobs for the same PR or branch.
=> Restrict concurrent integration test jobs

.github/workflows/ansible.yml, deployments/ansible/molecule/default/Dockerfile.j2, internal/buildscripts/packaging/tests/deployments/puppet/images/rpm/Dockerfile.opensuse-15, internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.opensuse-15, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.opensuse-15
- opensuse:15 tests have been timing out due to mirrorbrain choosing slow mirrors
- ansible-lint >= 6 no longer supports ansible 2.9
=> Fix CI test issues

.github/workflows/build-and-test.yml, examples/splunk-hec-traces/tracing/main.go
For some reason, `golangci-lint` doesn't always catch `gofmt` issues.
Example of failed job with file not currently formatted: https://github.com/signalfx/splunk-otel-collector/runs/5778977909?check_suite_focus=true
=> Add gofmt check to CI

.github/workflows/cloudfoundry_buildpack.yml, .github/workflows/lychee.yml, deployments/cloudfoundry/README.md, deployments/cloudfoundry/buildpack/README.md, deployments/cloudfoundry/buildpack/bin/detect, deployments/cloudfoundry/buildpack/bin/release, deployments/cloudfoundry/buildpack/bin/supply, deployments/cloudfoundry/buildpack/otelconfig.yaml
This is a deployment of the OpenTelemetry Collecter in the format of a
Cloud Foundry buildpack. This buildpack supplies the Collector to the
app it is used for. When the app is deployed it can run and configure
the Collector as a sidecar (as described in the README). This will allow
the Collector to observe the given app as well as the whole environment's
metrics.
=> Cloud Foundry Buildpack for Collector

.github/workflows/installer-script-test.yml, docs/getting-started/linux-installer.md, docs/getting-started/linux-manual.md, internal/buildscripts/packaging/installer/install.sh, internal/buildscripts/packaging/tests/installer_test.py, internal/buildscripts/packaging/tests/pytest.ini
- Add `--with-instrumentation` option to install the `splunk-otel-auto-instrumentation` deb/rpm package from artifactory (disabled by default)
- Add `--deployment-environment VALUE` option to define the `deployment.environment=VALUE` resource attribute in  the instrumentation config file
=> Add auto instrumentation to installer script

tests/receivers/smartagent/collectd-solr/testdata/server/Dockerfile
The `quay.io/bitnami/solr:latest` image is no longer accessible.
=> Update solr repo in dockerfile

examples/otel-logs-routing/docker-compose.yml, examples/otel-logs-sanitization-splunk/docker-compose.yml, examples/otel-logs-splunk/docker-compose.yml
Fixes examples that used curly brackets instead of parens to call out to the date function.
=> Fix use of parens vs curly brackets in bash

tests/receivers/smartagent/collectd-solr/testdata/resource_metrics/all.yaml, tests/receivers/smartagent/collectd-solr/testdata/server/Dockerfile
The `latest` image was recently updated and breaks integration tests.
=> Fix solr integration test

examples/otel-logs-processor-splunk/docker-compose.yml, examples/otel-logs-processor-splunk/otel-collector-config.yml
* Remove bad comment
* Use proper bash syntax to print dates
* Remove logging exporter
=> Clean up example:

CHANGELOG.md, go.mod, go.sum
The kubeletstatsreceiver introduced a regression in version v0.52.0 that can break metrics for Kubernetes pods and containers, pinning this receiver's version to v0.51.0 until the regression is resolved.
=> kubeletstatsreceiver introduced a regression in version v0.52.0

go.mod
Need to ignore `kubletstatsreceiver` from the update-deps script until the issues are resolved upstream.
=> Ignore kubeletstats for update-deps

instrumentation/packaging/fpm/rpm/build.sh
Similar to https://github.com/signalfx/splunk-otel-collector/pull/805/files#diff-1e18523d1853d221c59c60282863f5d50de31e7152dfa51a8b3fd115fdecaec1L65, need to use `--rpm-posttrans` to ensure that the postinstall script runs correctly on upgrade.
=> Fix auto-instrumentation rpm upgrade

go.mod, go.sum
Use newer version of `sapm` exporter to pick up: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11425.
Creating a PR against `update-deps-v0.54.0` as it appears I may not have permissions to push to it.
=> Update sapm exporter

README.md, cmd/otelcol/main.go
We currently force the config server to be enabled despite this not being always desirable. These changes document the feature and enable the server if its env var is unset.
=> Only use config server if env var unset

CHANGELOG.md, cmd/otelcol/config/collector/ecs_ec2_config.yaml, deployments/ecs/ec2/README.md, deployments/ecs/ec2/splunk-otel-collector.json
The existing ecs on ec2 config relies on environment variables being evaluated twice, which is only now possible by deferring the second execution with the env config source. These changes use this method and also include the previously unused filter processor.
Also includes doc updates for more helpful information.
=> Correct ecs ec2 metadata endpoints, filter processor, and docs

instrumentation/packaging/fpm/install-deps.sh, internal/buildscripts/packaging/fpm/install-deps.sh
Workaround for compatibility issue with latest dotenv release causing fpm to fail when building deb/rpm packages: https://github.com/signalfx/splunk-otel-collector/runs/7527424773?check_suite_focus=true
=> Pin dotenv to 2.7.6 for fpm

tests/receivers/smartagent/jmx/jmx_test.go, tests/receivers/smartagent/jmx/testdata/all_metrics_config.yaml, tests/receivers/smartagent/jmx/testdata/resource_metrics/all.yaml, tests/receivers/smartagent/jmx/testdata/server/Dockerfile
Basic test (without TLS) ported from https://github.com/signalfx/signalfx-agent/tree/main/tests/monitors/jmx
=> Add jmx monitor integration test

go.mod, go.sum
=> Bump github.com/emicklei/go-restful to v2.16.0

.github/workflows/trivy-scans.yml, .trivyignore
https://github.com/aquasecurity/trivy
- Run vulnerability scans for the repo and the collector image (currently only on pushes to main)
- Fail for high and critical vulnerabilities
- Example of failed jobs for detected vulnerability before it was updated: https://github.com/signalfx/splunk-otel-collector/actions/runs/2755673358
=> Add trivy security scan jobs

internal/receiver/discoveryreceiver/README.md
This readme describes the initial desired functionality of the proposed discovery receiver. The actual receiver implementation will be added in a series of commits, ideally based on some feedback from this doc content. There are a few limitations to unified log record content based on reported telemetry and I'd be happy to describe or attempt to reconcile them w/ suggestions/requests.
=> Initial discovery receiver readme

.github/workflows/build-and-test.yml, .gitlab-ci.yml, Makefile, docs/getting-started/linux-manual.md, internal/buildscripts/packaging/fpm/tar/README.md, internal/buildscripts/packaging/fpm/tar/build.sh, internal/buildscripts/packaging/tests/helpers/util.py, internal/buildscripts/packaging/tests/images/tar/Dockerfile.tar-centos-7, internal/buildscripts/packaging/tests/package_test.py, internal/buildscripts/packaging/tests/pytest.ini
Adds a tar distro of the Splunk Otel Collector. It doesn't interact with pytest much, as there is no path to upgrade and install is a `tar xzf`.
=> Add tar.gz distribution of the Splunk Otel Collector

go.mod, internal/receiver/discoveryreceiver/README.md, internal/receiver/discoveryreceiver/config.go, internal/receiver/discoveryreceiver/config_test.go, internal/receiver/discoveryreceiver/factory.go, internal/receiver/discoveryreceiver/factory_test.go, internal/receiver/discoveryreceiver/receiver.go, internal/receiver/discoveryreceiver/receiver_test.go, internal/receiver/discoveryreceiver/testdata/config.yaml, internal/receiver/discoveryreceiver/testdata/invalid_status_types.yaml, internal/receiver/discoveryreceiver/testdata/missing_status.yaml, internal/receiver/discoveryreceiver/testdata/missing_status_metrics_and_statements.yaml, internal/receiver/discoveryreceiver/testdata/multiple_status_match_types.yaml, internal/receiver/discoveryreceiver/testdata/no_watch_observers.yaml
These changes introduce the initial Discovery receiver component methods and config validation (proposed readme: https://github.com/signalfx/splunk-otel-collector/pull/1812).
=> Initial discovery receiver skeleton

cmd/otelcol/config/collector/gateway_config.yaml
The current GW config does not sync host metadata by default, which created confusion when users enable hostmetrics (and other GW metrics) and not seeing the host metadata in the backend.
=> sync host metadata for internal metrics

cmd/otelcol/config/collector/agent_config.yaml
The current comment suggests to switch all exporters to OTLP when sending to GW, which breaks the metadata updates.
At least one `signalfx` exporter should exists to update the host metadata properties.
=> hostmetadata when sending to GW

cmd/otelcol/config/collector/agent_config.yaml
The OOTB content in IMM uses the data emitted from processlist monitor, it makes sense to add this by default.
If we agreed to add processlist to the default config, then I will make the same update to the remaining OOTB configs we ship with the splunk distro
=> add processlist to default config

cmd/otelcol/config/collector/agent_config.yaml
This is related to https://github.com/signalfx/splunk-otel-collector/pull/1937
Without resourcedetection, the event will be missing the `host.name` label which is used to store the event in the memcache, if host.name is missing then the event is dropped.
=> Add resourcedetection to make the processlist events register with the backend

internal/configsource/envvarconfigsource/README.md, tests/general/envvar_expansion_test.go, tests/general/testdata/resource_metrics/yaml_from_env.yaml, tests/general/testdata/yaml_from_env.yaml
These changes validate documented yaml from env var config source functionality and refer to the installer guides for setting service environment variables.
=> add yaml from env config source test

go.mod, go.sum, internal/receiver/discoveryreceiver/config.go, internal/receiver/discoveryreceiver/config_test.go, internal/receiver/discoveryreceiver/correlation.go, internal/receiver/discoveryreceiver/correlation_test.go, internal/receiver/discoveryreceiver/endpoint_tracker.go, internal/receiver/discoveryreceiver/evaluator.go, internal/receiver/discoveryreceiver/evaluator_test.go, internal/receiver/discoveryreceiver/factory.go, internal/receiver/discoveryreceiver/factory_test.go, internal/receiver/discoveryreceiver/receiver.go, internal/receiver/discoveryreceiver/statussources/common.go, internal/receiver/discoveryreceiver/testdata/config.yaml
These changes introduce a basic evaluator to be later used in metric and statement evaluation, and a correlation system for ensuring that all receiver/endpoint/observer activity is accessible by any one applicable element of the component. This is in preparation for a future PR that actually evaluates metrics and statements for the purposes of emitting log records.
=> discovery receiver: add base evaluator and correlations

internal/receiver/discoveryreceiver/metric_evaluator.go, internal/receiver/discoveryreceiver/metric_evaluator_test.go, internal/receiver/discoveryreceiver/receiver.go, internal/receiver/discoveryreceiver/statussources/metrics.go, internal/receiver/discoveryreceiver/statussources/metrics_test.go
These changes add metric consumption, evaluation, and log record emission to the discovery receiver. They require https://github.com/signalfx/splunk-otel-collector/pull/1971.
=> discovery receiver: add metrics evaluation

internal/receiver/discoveryreceiver/receiver.go, internal/receiver/discoveryreceiver/statement_evaluator.go, internal/receiver/discoveryreceiver/statement_evaluator_test.go, internal/receiver/discoveryreceiver/statussources/statements.go, internal/receiver/discoveryreceiver/statussources/statements_test.go
These changes add component log statement evaluation with an intercepting `zapcore.Core` to the discovery receiver. Current target will be updated to main when https://github.com/signalfx/splunk-otel-collector/pull/1980 lands.
=> discovery receiver: add statement evaluation

Makefile, Makefile.Common
Remove a constant that is not used in Makefile.Common and inline it in Makefile to avoid computing the list of tests every time we run make.
=> simplify Makefile further, load lazily tests list

internal/receiver/smartagentreceiver/config.go, internal/receiver/smartagentreceiver/converter/event.go, internal/receiver/smartagentreceiver/factory.go, internal/receiver/smartagentreceiver/factory_test.go, internal/receiver/smartagentreceiver/output.go, internal/receiver/smartagentreceiver/output_test.go, internal/receiver/smartagentreceiver/output_traces_test.go, internal/receiver/smartagentreceiver/receiver.go, internal/receiver/smartagentreceiver/receiver_test.go, internal/receiver/smartagentreceiver/reflect.go, internal/receiver/smartagentreceiver/reflect_test.go
Unexport all types that can be made package private for the smart agent receiver.
This is a change that should not affect any logic in the code.
=> remove some exports from the smartagent receiver

tests/README.md, tests/endtoend/authscope_test.go, tests/general/envvar_expansion_test.go, tests/receivers/filelog/filelog_test.go, tests/receivers/filelog/testdata/resource_logs/syslog.yaml, tests/receivers/filelog/testdata/syslog, tests/receivers/filelog/testdata/syslog_config.yaml, tests/receivers/smartagent/collectd-kafka/collectd_kafka_test.go, tests/receivers/smartagent/collectd-spark/collectd_spark_test.go, tests/testutils/README.md, tests/testutils/collector_process_integration_test.go, tests/testutils/container.go, tests/testutils/otlp_receiver_sink.go, tests/testutils/otlp_receiver_sink_test.go, tests/testutils/telemetry/common_test.go, tests/testutils/telemetry/logs.go, tests/testutils/telemetry/logs_test.go, tests/testutils/telemetry/metrics_test.go, tests/testutils/telemetry/pdata_logs.go, tests/testutils/telemetry/pdata_logs_test.go, tests/testutils/telemetry/testdata/logs/attribute-value-resource-logs.yaml, tests/testutils/telemetry/testdata/logs/empty-attributes-required.yaml, tests/testutils/telemetry/testdata/logs/expected-logs.yaml, tests/testutils/telemetry/testdata/logs/invalid-resource-logs.yaml, tests/testutils/telemetry/testdata/logs/never-received-instrumentation-scope.yaml, tests/testutils/telemetry/testdata/logs/never-received-logs.yaml, tests/testutils/telemetry/testdata/logs/never-received-resource.yaml, tests/testutils/telemetry/testdata/logs/resource-logs.yaml, tests/testutils/telemetry/testdata/logs/unspecified-attributes-allowed.yaml, tests/testutils/testcase.go
In preparation of adding the discovery receiver these changes add a new ResourceLogs test format and associate an otlp logs receiver with the testsuite sink.
Also adding a `WithMount` container helper and `CollectorBuilder` pattern to be able to arbitrarily update the tested collector, which is required for mounting files without adding a more strict signature.
Requires https://github.com/signalfx/splunk-otel-collector/pull/2069
=> Add ResourceLogs and filelog receiver integration test

docs/components.md, internal/components/components.go, internal/components/components_test.go, internal/receiver/discoveryreceiver/README.md, internal/receiver/discoveryreceiver/evaluator.go, internal/receiver/discoveryreceiver/evaluator_test.go, tests/receivers/discovery/discovery_test.go, tests/receivers/discovery/testdata/host_observer_endpoints_config.yaml, tests/receivers/discovery/testdata/host_observer_simple_prometheus_config.yaml, tests/receivers/discovery/testdata/resource_logs/host_observer_endpoints.yaml, tests/receivers/discovery/testdata/resource_logs/host_observer_simple_prometheus_statuses.yaml
These changes include the discovery receiver in the Splunk distribution and include new integration tests. Also corrected the example yaml in the readme and updated to fix a race condition the tests uncovered where empty observer IDs are used in the embedded config.
=> Adopt discovery receiver

tests/general/discoverymode/testdata/resource_metrics/memory.yaml, tests/general/testdata/resource_metrics/cpu.yaml, tests/general/testdata/resource_metrics/env_config_source_labels.yaml, tests/general/testdata/resource_metrics/envvar_labels.yaml, tests/general/testdata/resource_metrics/incompat_env_config_source_labels.yaml, tests/general/testdata/resource_metrics/yaml_from_env.yaml, tests/receivers/oracledb/oracledb_test.go, tests/receivers/oracledb/testdata/resource_metrics/all.yaml, tests/testutils/collector_container.go, tests/testutils/otlp_receiver_sink.go, tests/testutils/telemetry/common.go, tests/testutils/telemetry/common_test.go, tests/testutils/telemetry/logs.go, tests/testutils/telemetry/logs_test.go, tests/testutils/telemetry/metrics.go, tests/testutils/telemetry/metrics_test.go, tests/testutils/telemetry/pdata_logs.go, tests/testutils/telemetry/pdata_logs_test.go, tests/testutils/telemetry/pdata_metrics.go, tests/testutils/telemetry/pdata_metrics_test.go, tests/testutils/testdata/expected_host_metrics.yaml
These changes introduce a central attribute equality helper used by ResourceLogs and ResourceMetrics. They also update resource attributes to be a `*map[string]any` to conform with the resource item attributes and update associated helpers and integration tests as necessary to expand the functionality provided by the `<ANY>` token value from https://github.com/signalfx/splunk-otel-collector/pull/2011
Also including a minor collector container change to respect specified wait conditions.
=> testutils: unify <ANY> and <VERSION_FROM_BUILD> values and checks

internal/exporter/pulsarexporter/testdata/config.yaml
- setting `partitions_auto_discovery_interval` to `1` causes a flood of `CommandPartitionedTopicMetadata` requests to brokers. The broker doesn't log these requests with info level, and it's hard to detect the issue. 
- [The default value in pulsar-client-go is 1 minute](https://github.com/apache/pulsar-client-go/blob/v0.8.1/pulsar/producer_impl.go#L47) which is 60*10^9. Set the example value to the default.
- setting `batching_max_publish_delay` to `10` will make batching ineffective since the unit is nanoseconds. 
- [The default value in pulsar-client-go is 10 milliseconds](https://github.com/apache/pulsar-client-go/blob/v0.8.1/pulsar/producer_impl.go#L38) which is 10^7. Set the example value to the default.
=> Fix example config for Pulsar exporter, units are nanoseconds

tests/testutils/telemetry/metrics.go, tests/testutils/telemetry/pdata_metrics.go, tests/testutils/telemetry/pdata_metrics_test.go
These changes add very rudimentary summary, histogram, and exponential histogram metric support to the integration test utils. They don't account for for any bucket/quantile/exemplar values but do add basic reception capabilities from the otlp metric receiver sink where panics* currently occur.
=> testutils: add missing resource metric types

docs/docker.md, tests/general/container_test.go, tests/general/testdata/activemq_config.yaml, tests/general/testdata/resource_metrics/activemq.yaml, tests/general/testdata/resource_metrics/solr.yaml, tests/general/testdata/solr_config.yaml
These changes add a short doc for docker daemon connectivity permissions for linux and containers and two integration tests to make sure that the agent bundle can be interacted with when the container user isn't in the default group.
=> Document Docker usage and add bundle integration tests

internal/buildscripts/packaging/installer/install.ps1
This change adds a `with_dotnet_tracing` parameter to the collector install script for windows. When set, the script downloads and installs the dotnet tracing library, and it sets environment variables so that dotnet applications that run on the local machine will be auto-instrumented.
=> add support for installing dotnet instrumentation

tests/receivers/prometheus/internal_prometheus_test.go, tests/receivers/prometheus/testdata/internal_metrics_config.yaml, tests/receivers/prometheus/testdata/resource_metrics/internal.yaml
We rely on these for our content and in the helm chart so best to have a test for them.
=> Add internal prometheus metrics integration test

internal/configprovider/builder.go, internal/configprovider/builder_test.go, internal/configprovider/component.go, internal/configprovider/config_source_provider.go, internal/configprovider/config_source_provider_test.go, internal/configprovider/manager.go, internal/configprovider/manager_test.go, internal/configprovider/parser.go, internal/configprovider/parser_test.go
Before, the WatchForChanges was not called, now we pass the same WatcherFunc down to the ConfigSources.
=> [BUG_FIX] Watch for changes in the configsource implementations

internal/buildscripts/packaging/tests/deployments/puppet/puppet_test.py
Temporarily skipping these tests to unblock builds since we aren't pushing puppet changes in immediate future.
=> skip puppet focal for github.com/puppetlabs/puppetlabs-release/issues/271

deployments/ansible/roles/collector/README.md, deployments/ansible/roles/collector/defaults/main.yml, deployments/ansible/roles/collector/tasks/apt_install_otel_collector.yml, deployments/ansible/roles/collector/tasks/yum_install_otel_collector.yml
Hello team,
Can you please review PR for skipping use of Splunk repo for installing otel package.
We would like to utilize your role, though we can't rely on external repo and would like to keep rpm locally.
Since we are using RH satellite, we can't just provide splunk_repo_base_url var as url is different.
As a reference there is a parity of this in Smart Agent role: https://github.com/signalfx/signalfx-agent/issues/1628
Thanks.
=> Add splunk_skip_repo option to ansible

tests/general/configsources/include_test.go, tests/general/configsources/vault_test.go, tests/general/container_test.go, tests/general/discoverymode/configd_test.go, tests/general/discoverymode/docker_observer_discovery_test.go, tests/general/discoverymode/host_observer_discovery_test.go, tests/general/envvar_expansion_test.go, tests/general/process_test.go, tests/receivers/filelog/filelog_test.go, tests/receivers/oracledb/oracledb_test.go, tests/testutils/assert_no_error_host.go, tests/testutils/collector.go, tests/testutils/collector_container.go, tests/testutils/collector_process.go, tests/testutils/endpoint.go, tests/testutils/otlp_receiver_sink.go, tests/testutils/testcase.go
The current pattern of `Testcase.SkipIfNotContainer()` and then type asserting the resulting collector from `SplunkOtelCollector` or `SplunkOtelCollectorWithEnv` to a `*CollectorContainer` is a little unintuitive. These changes add new helper methods that incorporate this logic and remove `SplunkOtelCollectorWithEnv`, opting for the builder options.
These changes also promote the initial and effective config helpers to testutils.Collector interface by adding the method to `CollectorProcess`, incorporating existing test logic that was repeated.
=> testutils: add Testcase.SplunkOtelCollector(Container|Process)

.gitlab-ci.yml
The Windows 2022 runner is now working correctly and I have used this branch  to push a Windows 2022 docker image out:
https://quay.io/repository/signalfx/splunk-otel-collector-windows-dev?tab=tags&tag=d15a9d9722240111885ab24761c240483eef35e0-2022
=> Use windows 2022 runner

.github/workflows/build-and-test.yml, .gitlab-ci.yml, Makefile, go.mod, go.sum, internal/buildscripts/packaging/release/gh-release-notes.sh, pkg/receiver/smartagent/go.mod, pkg/receiver/smartagent/go.sum
This has been tested against the gitlab pipeline, the CI passes.
Ready for review.
=> PPC support

cmd/otelcol/config/collector/upstream_agent_config.yaml, internal/settings/settings.go, internal/settings/settings_test.go
The argument was removed from the core collector in v0.36.0. We kept supporting it in our distro but the support is broken. We never remove that argument as we do for others and it's being passed to the core collector in https://github.com/signalfx/splunk-otel-collector/blob/main/cmd/otelcol/main.go#L105 where it fails with the following error:
```
2022/12/08 16:25:34 main.go:106: application run finished with error: unknown flag: --mem-ballast-size-mib
```
So I don't think it makes sense to bring back support of it.
=> Remove handling of unsupported --mem-ballast-size-mib command line argument

deployments/fargate/README.md
OTEL agent task is not filtering out OTEL container metrics when using this example https://github.com/signalfx/splunk-otel-collector/blame/main/deployments/fargate/README.md#L35
the string we are trying to match against is 
```
quay.io/signalfx/splunk-otel-collector:0.36.0
```
based on https://github.com/signalfx/signalfx-agent/blob/c295133b4a52b2fff071c8070536183a48e403fc/pkg/utils/filter/overridable.go#L14 and running it through the unit test, a * is needed to get a match.
```
"value": "[\"quay.io/signalfx/splunk-otel-collector:*\"]"
```
=> fix image filter to regex match the tag

cmd/otelcol/main.go, internal/settings/settings.go, internal/settings/settings_test.go
This PR solves two problems:
1. In the current implementation, command flags specific to the Splunk distro are dropped from the arguments list passed to the collector core service by their names. It means that all the flag values are unintentionally passed downstream. Also, flags with `=` are not removed from the list and cause failures downstream. For example, `./bin/otelcol --config-dir=/tmp/conf ...` fails with:
```
2022/12/10 19:15:52 main.go:106: application run finished with error: unknown flag: --config-dir
```
And `removeFlag` function is called from methods that are not expected to be mutating by their definition like `ResolverURIs`.
2. Currently, we rely on the downstream collector core service to display `--help` flag output and get the following:
```
Usage:
otelcol [flags] …
```
=> Rework command line arguments parsing

internal/settings/settings.go
This attribute is temporarily required to be set to make Splunk OTel Collector Helm chart to work on GKE/Autopilot.
=> Temporarily add a no-op flag --metrics-addr

tests/go.mod, tests/go.sum
bug fix PR has landed so fork is no longer required.
=> use upstream kind for k8s testing

README.md
Migrate to the new endpoint. See https://github.com/badges/shields/issues/8671
=> Update build badge link

deployments/salt/templates/agent_config.yaml
This fixes a warning showing that setting the ballast memory size must happen under an extension memory_ballast rather than under the memory_limiter processor.
=> Use memory ballast extension

instrumentation/packaging/fpm/common.sh, internal/buildscripts/packaging/fpm/common.sh, internal/buildscripts/packaging/fpm/tar/build.sh, internal/buildscripts/packaging/installer/install.ps1
We are being throttled by Github because we call in various places its API from public workers. Instead, use the `latest` release link.
=> Remove github api calls, use github's latest link

.gitlab-ci.yml, internal/buildscripts/packaging/release/release.py
Remove the confusion that the python script has anything to do with signing, which is now handled elsewhere.
=> rename sign_release.py to release.py

examples/otel-logs-splunk/docker-compose.yml, examples/otel-logs-splunk/otel-collector-config.yml
Add the file_storage extension to the example to show how checkpointing works.
=> Add storage to filelog example

cmd/otelcol/main.go, internal/configconverter/config_server.go, internal/configconverter/config_server_test.go, internal/configconverter/dry_run.go, internal/configconverter/dry_run_test.go, internal/configprovider/config_source_provider.go, internal/configprovider/config_source_provider_test.go, pkg/extension/smartagentextension/config_windows_test.go, pkg/receiver/smartagent/config_windows_test.go, tests/general/dry_run_test.go, tests/testutils/container.go, tests/testutils/container_test.go
Currently `--dry-run` will provide the final config values with all config source and environment variables having been resolved/expanded. This is not desirable for dynamic* content. These changes add a new `configprovider.Hook` mechanism to provide additional components access of pre-resolving config content like* the config server currently does. The config server converter is updated to conform to the new interface.
These also pick up existing missing imports and add an integration test with an additional testutil container helper.
=> ensure --dry-run doesn't report expanded config values

CHANGELOG.md
A CHANGELOG update for a given release is required to properly create the release. We will add a more detailed release description after the release is created.
=> Add empty CHANGELOG update for v0.68.0 release

internal/confmapprovider/discovery/discoverer.go, tests/general/discoverymode/configd_test.go, tests/general/discoverymode/docker_observer_discovery_test.go, tests/general/discoverymode/host_observer_discovery_test.go, tests/general/discoverymode/k8s_observer_discovery_test.go, tests/general/discoverymode/testdata/docker-observer-config.d/extensions/docker-observer.discovery.yaml, tests/general/discoverymode/testdata/docker-observer-config.d/receivers/internal-prometheus.discovery.yaml, tests/general/discoverymode/testdata/host-observer-config.d/receivers/internal-prometheus.discovery.yaml, tests/general/discoverymode/testdata/k8s-observer-config.d/extensions/k8s-observer.discovery.yaml, tests/general/discoverymode/testdata/k8s-observer-config.d/receivers/smart-agent-redis.discovery.yaml, tests/general/discoverymode/testdata/otlp-exporter-no-internal-prometheus.yaml, tests/general/discoverymode/testdata/resource_metrics/host-observer-internal-prometheus.yaml, tests/general/discoverymode/testdata/resource_metrics/k8s-observer-smart-agent-redis.yaml, tests/general/dry_run_test.go, tests/testutils/container.go, tests/testutils/container_test.go, tests/testutils/kubeutils/kind_cluster.go
In the same vein as https://github.com/signalfx/splunk-otel-collector/pull/2439 these changes ensure that successfully discovered target entities don't report their expanded config values from the discovery confmap provider* (and by extension `--dry-run`), which would make any configs using env vars only valid for running on a matching environment.
They also update all discovery mode integration tests to vet this w/ a new docker exec helper and add a new k8s integration test (the bulk of the changes).
=> Provide unexpanded configs in discovery mode

instrumentation/packaging/fpm/common.sh
The collector downloads the Java agent for instrumentation. The java agent download link is incorrect when a specific tag is provided. This fixes the link.
I tested both the `latest` and `$tag` URLs manually, they're both working now (`latest` wasn't broken).
=> Fix broken Java Agent GitHub download link

.gitlab-ci.yml
The `.submit-request` job has been renamed to `.submit-signing-request`. The job fails when referring to the old name, so this updates the GitLab CI yaml file to use the new name.
=> Use updated signing service name in GitLab CI

instrumentation/packaging/fpm/common.sh, internal/buildscripts/packaging/fpm/common.sh, internal/buildscripts/packaging/fpm/tar/build.sh, internal/buildscripts/packaging/msi/msi-builder/build.sh
Add the -f flag to curl downloads in our packaging scripts, so failure to download a component fails the script.
=> Add -f to curl downloads

.gitlab-ci.yml, instrumentation/Dockerfile, instrumentation/Makefile
Helps avoid docker rate limiting failures in gitlab.
=> Use DOCKER_HUB for libsplunk builds

deployments/ansible/roles/collector/README.md, deployments/ansible/roles/collector/defaults/main.yml, deployments/ansible/roles/collector/templates/collector-service-proxy.conf.j2
IFAIK when you need to monitor an https vhost on localhost on a proxied environment you need to add the vhost on the NO_PROXY environment variable (event if localhost is used).
```
smartagent/http_toto:
type: http
host: 127.0.0.1
port: 443
useHTTPS: true
noRedirects: true
sniServerName: www.toto.com
httpHeaders:
Host: www.toto.com
path: /up.php
desiredCode: 200
regex: '^OK$'
```
will not worked on a proxied environment if `NO_PROXY=localhost,127.0.0.1,::1` ; for it to work we need `NO_PROXY=localhost,127.0.0.1,::1,www.toto.com`
So we need a way to set NO_PROXY.
=> ansible: add splunk_otel_collector_no_proxy variable

.github/workflows/auto-instrumentation.yml, .github/workflows/build-and-test.yml, instrumentation/Makefile, instrumentation/packaging/fpm/Dockerfile, instrumentation/packaging/fpm/common.sh, internal/buildscripts/packaging/fpm/Dockerfile, internal/buildscripts/packaging/fpm/common.sh, internal/buildscripts/packaging/msi/build.sh
Workaround for https://github.com/actions/checkout/issues/766 when using `git describe` to get the latest tag for deb/rpm versioning.
=> Fix deb/rpm versioning in github workflows

internal/configconverter/k8s_tagger.go
Fixes #2465
Somehow the value of a k8s attribute is nil, and we panic on this. The fix is to check for nil before we look for the type of the attribute.
=> nil check when looking for the type of a value

internal/buildscripts/packaging/release/helpers/release_args.py, internal/buildscripts/packaging/release/helpers/util.py
In case we need to upload an older version of the MSI.
=> Add --not-latest option to release script

.github/workflows/chef.yml, .github/workflows/deps-test.yml
`set-output` is being deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Use GITHUB_OUTPUT instead of set-output

internal/configsource/vaultconfigsource/README.md
This fixes a typo in the vault config source sample documentation, renaming `jwp_ext` to `jwt_ext` and moving the value to an integer from `10m` to `10`.
See description of the field here: https://github.com/hashicorp/vault-plugin-auth-gcp/blob/e1f6784b379d277038ca0661606aa8d23791e392/plugin/cli.go#L151
=> [internal/configsource] Fix vault configsource typo in README

.github/workflows/ansible.yml, deployments/ansible/README.md, deployments/ansible/contributing/README.md, deployments/ansible/contributing/requirements-dev-macos.txt, deployments/ansible/molecule/config/windows.yml, deployments/ansible/molecule/custom_vars/converge.yml, deployments/ansible/molecule/custom_vars/verify.yml, deployments/ansible/molecule/custom_vars/windows-converge.yml, deployments/ansible/molecule/custom_vars/windows-verify.yml, deployments/ansible/molecule/default/windows-converge.yml, deployments/ansible/molecule/default/windows-prepare.yml, deployments/ansible/molecule/default/windows-verify.yml, deployments/ansible/molecule/without_fluentd/windows-converge.yml, deployments/ansible/molecule/without_fluentd/windows-verify.yml
- Update molecule for vagrant/virtualbox to support windows
- Add test scenarios for windows based on existing linux scenarios, excluding `with_instrumentation`
- Add github matrix job to run on `macos-12` since it has vagrant/virtualbox support
Issues/Limitations:
- New github test jobs could take up to 1 hour to complete a single scenario per Windows version (mostly to download, boot, and provision the vagrant boxes)
- Windows vagrant boxes are too big to cache in github (10GB cache limit per repo)
- Molecule/vagrant/virtualbox flakiness and system load may cause timeouts/failures
=> Add windows support to ansible tests

pkg/extension/smartagentextension/go.mod, pkg/extension/smartagentextension/go.sum
=> Bump github.com/emicklei/go-restful to v2.16.0+incompatible

tests/exporters/signalfx/signalfx_translation_test.go, tests/general/container_test.go, tests/general/discoverymode/configd_test.go, tests/general/envvar_expansion_test.go, tests/receivers/discovery/host_observer_test.go, tests/receivers/filelog/filelog_test.go, tests/receivers/oracledb/oracledb_test.go, tests/receivers/postgresql/postgresql_test.go, tests/receivers/prometheus/internal_prometheus_test.go, tests/receivers/redis/redisreceiver_test.go, tests/receivers/smartagent/collectd-activemq/collectd_activemq_test.go, tests/receivers/smartagent/collectd-apache/collectd_apache_test.go, tests/receivers/smartagent/collectd-cassandra/collectd_cassandra_test.go, tests/receivers/smartagent/collectd-couchbase/collectd_couchbase_test.go, tests/receivers/smartagent/collectd-elasticsearch/collectd_elasticsearch_test.go, tests/receivers/smartagent/collectd-hadoop/collectd_hadoop_test.go, tests/receivers/smartagent/collectd-kafka/collectd_kafka_test.go, tests/receivers/smartagent/collectd-nginx/collectd_nginx_test.go, tests/receivers/smartagent/collectd-postgresql/collectd_postgresql_test.go, tests/receivers/smartagent/collectd-solr/collectd_solr_test.go, tests/receivers/smartagent/collectd-spark/collectd_spark_test.go, tests/receivers/smartagent/collectd-tomcat/tomcat_test.go, tests/receivers/smartagent/haproxy/haproxy_test.go, tests/receivers/smartagent/jmx/jmx_test.go, tests/receivers/smartagent/postgresql/postgresql_test.go, tests/receivers/smartagent/telegraf-procstat/telegraf_procstat_test.go, tests/receivers/smartagent/telegraf-sqlserver/telegraf_sqlserver_test.go, tests/testutils/README.md, tests/testutils/testcase.go
Forcing us to reimplement the core helpers to specify collector builders is a nuisance, so best not to do that imo.
=> testutils: add []CollectorBuilder to assertion helpers to reduce boilerplate

.github/workflows/integration-test.yml
Avoid unnecessary rebuilds when re-running failed tests.
=> Split build and integration test into separate jobs

tests/testutils/collector_process_integration_test.go, tests/testutils/testdata/collector_process_config.yaml
The current process integration test doesn't specify a logger so exec errors aren't surfaced and deducing the failure is left as an exercise to the user. Updating the test so that issues are clearer:
>{{debug 2023-02-16 15:32:18.284052751 -0500 EST m=+0.011909859  subprocess changed state undefined } [{state 15 0 Errored <nil>}]}
{{error 2023-02-16 15:32:18.284054307 -0500 EST m=+0.011911407  subprocess died undefined } [{error 26 0  fork/exec /splunk-otel-collector/bin/otelcol: permission denied}]}
{{debug 2023-02-16 15:32:18.284061454 -0500 EST m=+0.011918562  subprocess changed state undefined } [{state 15 0 ShuttingDown <nil>}]}
{{debug 2023-02-16 15:32:18.284137259 -0500 EST m=+0.011994373  subprocess changed state undefined } [{state 15 0 Stopped <nil>}]}
Thanks to @jeffreyc-splunk …
=> Use testcase helper for process integration test

internal/receiver/discoveryreceiver/statement_evaluator_test.go
The current output is way too verbose.
=> discovery: Don't use zaptest logger for statement evaluation tests

cmd/otelcol/config/collector/agent_config.yaml, tests/general/default_config_test.go
Existing agent config doesn't source the SA extension, leading to its env vars not being used if deviating from defaults. Also added two integration tests to confirm default configs successfully start.
=> add smartagent extension to default agent config and test config contents

tests/general/discoverymode/docker_observer_discovery_test.go, tests/general/discoverymode/host_observer_discovery_test.go, tests/general/set_properties_test.go, tests/testutils/testcase.go
Changing the expected values to use `host.docker.internal` in effective config with* a newly exported helper field. Also skipping a docker observer test that requires significant workarounds for now.
=> Update more recent test changes to support docker for mac

.github/workflows/build-and-test.yml, .github/workflows/deps-test.yml, .github/workflows/integration-test.yml, .github/workflows/trivy-scans.yml, .github/workflows/windows-test.yml, .gitlab-ci.yml
For CVE-2022-41723 (https://pkg.go.dev/vuln/GO-2023-1571)
=> Update golang to 1.19.6

.github/workflows/nomad.yml, deployments/nomad/README.md, deployments/nomad/otel-agent.nomad, deployments/nomad/otel-gateway.nomad
Current tests fail because our sample job files are incompatible with nomad versions >= 1.3.0.
- Update tests for nomad versions 1.1.0 and 1.2.0
- Add validation checks for the sample job files
- Add constraint for nomad version < 1.3.0 to the sample job files
=> Update nomad tests

docs/apm-infra-correlation.md, examples/nomad/otel-demo.nomad, tests/general/container_test.go, tests/general/discoverymode/testdata/standalone-config.d/exporters/otlp.yaml, tests/general/dry_run_test.go, tests/general/testdata/env_config_source_labels.yaml, tests/general/testdata/envvar_labels.yaml, tests/general/testdata/hostmetrics_cpu.yaml, tests/general/testdata/yaml_from_env.yaml, tests/receivers/redis/testdata/all_metrics_config.yaml
Configuration for the OTLP exporter "insecure" option changed a long time ago to move under the "tls" map item. We have a lot of tests using the old format, so this updates them to match the new.
=> Update OTLP TLS insecure config option formatting

tests/general/container_test.go
This config option was misconfigured in a test on purpose for the sake of testing the config converts to make sure they properly catch it.
=> Revert an OTLP exporter config change

.gitignore, internal/receiver/databricksreceiver/internal/metadata/generated_metrics.go
It's helpful to have local dev/test content without needing to filter git commands. Also updating fieldalignment -fix changes that haven't been merged yet.
=> add .local to .gitignore and run make fmt

tests/receivers/smartagent/prometheus-exporter/prometheus_exporter_test.go, tests/receivers/smartagent/prometheus-exporter/testdata/internal_metrics_config.yaml, tests/receivers/smartagent/prometheus-exporter/testdata/resource_metrics/internal.yaml
As we continue updating prometheus deps it would be good to ensure the SA monitor functions as expected.
=> add SA prometheus-exporter integration test

internal/exporter/pulsarexporter/config.go, internal/exporter/pulsarexporter/pulsar_exporter.go, internal/exporter/pulsarexporter/testdata/config.yaml
These configuration changes sync the options with what is offered by the upstream pulsar exporter offered by the contrib project. Along with the changes from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19184, these changes will allow down the road to move to the upstream exporter.
=> Changes to the pulsarexporter configuration to prepare with using upstream

examples/prometheus-federation/prom-counter/go.mod, examples/splunk-hec-traces/tracing/go.mod, examples/splunk-hec/logging/go.mod
This is required for "multimod" tool utility to stop complaining about incorrectly named modules.
Moreover, it's just better practice to name the module after the git repo + module subpath
=> Correct module names for directory locations in examples

.github/workflows/release-requirements.yml
Simple pip installation test to verify changes to `internal/buildscripts/packaging/release/requirements.txt` (e.g. dependabot PRs).
=> Add workflow to test changes to release requirements

.github/workflows/build-and-test.yml, .github/workflows/deps-test.yml, .github/workflows/installer-script-test.yml, .github/workflows/integration-test.yml, .github/workflows/trivy-scans.yml, .github/workflows/windows-test.yml
Clean up workflow caches to reduce redundancy and reclaim some storage space.
=> Update github workflow caches for consistency

.github/workflows/cache-cleanup.yml
Copied from https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries to delete branch caches when the PR is closed.
=> Add cache cleanup workflow

tests/receivers/custom_upstat/custom_upstat_test.go, tests/receivers/custom_upstat/testdata/custom/collectd-upstat.py, tests/receivers/custom_upstat/testdata/custom/upstat_types.db, tests/receivers/custom_upstat/testdata/custom_upstat.yaml, tests/receivers/custom_upstat/testdata/resource_metrics/all.yaml, tests/testutils/collector.go, tests/testutils/collector_container.go, tests/testutils/collector_process.go
This adds a new integration test that checks explicitly that the smart agent receiver can work with custom collectd plugins.
=> Add test for custom collectd plugin

.github/CODEOWNERS
The property guidance these files (will) contain is user-facing content and should be verified by our writers.
=> add gdi-docs to discovery config yaml owners

internal/buildscripts/packaging/installer/install.sh, internal/buildscripts/packaging/tests/installer_test.py
Follow-up to #2718.
Add option to configure `generate_service_name` instead of inferring based on `service_name`.
=> Update installer script for generate_service_name option

deployments/salt/README.md, deployments/salt/splunk-otel-collector/auto_instrumentation.sls, internal/buildscripts/packaging/tests/deployments/salt/salt_test.py
For https://signalfuse.atlassian.net/browse/OTL-1886
=> Add java zc options to salt

tests/receivers/smartagent/jmx/jmx_test.go, tests/receivers/smartagent/jmx/testdata/all_metrics_config.yaml, tests/receivers/smartagent/jmx/testdata/script.groovy
These changes exercise the more likely invocation instead of using an embedded script.
=> Use include config source with jmx monitor test

.github/workflows/chef-test.yml
Ensures all platforms/suites defined in [kitchen.yml](https://github.com/signalfx/splunk-otel-collector/blob/main/deployments/chef/kitchen.yml) and [kitchen.windows.yml](https://github.com/signalfx/splunk-otel-collector/blob/main/deployments/chef/kitchen.windows.yml) are tested without manually updating the workflow file.
=> Dynamically create test matrix for chef tests

.github/workflows/build-and-test.yml, .github/workflows/integration-test.yml, .github/workflows/trivy-scans.yml, .github/workflows/update-deps.yml, .github/workflows/windows-test.yml
After #2749, separately caching go deps is no longer necessary since the updated `actions/setup-go@v4` caches by default.
=> Remove redundant go cache from workflows

.github/workflows/darwin-test.yml, Makefile
Similar to [windows-test.yml](https://github.com/signalfx/splunk-otel-collector/blob/main/.github/workflows/windows-test.yml), but for `macos-11` and `macos-12`.
Also, not sure what changed or when, but the `test-with-cover` make target has not been running tests or producing any coverage results. See latest [run](https://github.com/signalfx/splunk-otel-collector/actions/runs/4468999844/jobs/7850537586) for main, compared to the [run](https://github.com/signalfx/splunk-otel-collector/actions/runs/4469517243/jobs/7851783470) from this PR.
=> Add workflow for go tests on darwin

go.mod, go.sum, tests/exporters/signalfx/testdata/cpu_translations_config.yaml, tests/exporters/signalfx/testdata/resource_metrics/cpu_translations.yaml
These changes pick up https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/6b0c2cca999c0ab87491049b57769dfdaca591e7 and update the integration test to ensure we can include the `system.cpu.time` metric with default translation rules.
=> adopt signalfx exporter system.cpu.time fix

.github/workflows/darwin-test.yml
=> Bump actions/setup-go to v4 in darwin-test.yml

.github/workflows/build-and-test.yml, .github/workflows/darwin-test.yml, .github/workflows/integration-test.yml, .github/workflows/trivy-scans.yml, .github/workflows/update-deps.yml, .github/workflows/windows-test.yml
The default cache key is the hash for only the go.sum in the project root dir.
=> Update actions/setup-go cache key for hash of all go.sum

.github/workflows/update-openjdk.yml
Check https://github.com/adoptium/temurin11-binaries for the latest release, update the `JDK_VERSION` arg in the agent bundle [Dockerfile](https://github.com/signalfx/splunk-otel-collector/blob/main/pkg/signalfx-agent/bundle/Dockerfile), and create a draft PR if there are changes.
=> Add workflow to create PR for new openjdk release

internal/confmapprovider/discovery/README.md, internal/confmapprovider/discovery/config.go, internal/confmapprovider/discovery/config_test.go, internal/confmapprovider/discovery/discoverer.go, internal/confmapprovider/discovery/testdata/config.d/properties.discovery.yaml, internal/confmapprovider/discovery/testdata/invalid-properties.d/properties.discovery.yaml, tests/general/discoverymode/docker_observer_discovery_test.go, tests/general/discoverymode/testdata/docker-observer-config.d/properties.discovery.yaml, tests/general/discoverymode/testdata/docker-observer-config.d/receivers/internal-prometheus.discovery.yaml
These changes add the ability to specify discovery properties in a single `config.d/properties.discovery.yaml` file that are merged w/ env/cli set properties.
edit: these changes also fix a [bug I introduced](https://github.com/signalfx/splunk-otel-collector/blob/cb4e27e2dc4010d93ed3e8abbe1d5e9e790ace7e/internal/confmapprovider/discovery/config.go#L497) where `configDirRootRegex` was using a group in a range exclusion.
=> add properties.discovery.yaml support

.github/dependabot.yml, Makefile
We usually need to handle these manually or with the `update-deps` script/workflow.
=> dependabot: Ignore otel dependencies

.github/workflows/installer-script-test.yml, docs/getting-started/linux-installer.md, internal/buildscripts/packaging/installer/install.sh, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.amazonlinux-2, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.amazonlinux-2023, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.centos-9, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.oraclelinux-9, internal/buildscripts/packaging/tests/installer_test.py
Note: Fluentd is not yet supported for Amazon Linux 2023 since there are currently [no packages available](https://td-agent-package-browser.herokuapp.com/4/amazon) (the packages for Amazon Linux 2 are incompatible on 2023).
=> Update installer script for amazonlinux 2023 and rhel 9

deployments/cloudfoundry/bosh/example/deployment.yaml, deployments/cloudfoundry/tile/DEVELOPMENT.md, deployments/cloudfoundry/tile/tile.yml
The shard ID should be filled in automatically with the default collector value to make it easier on the user. This will result in one less variable to fill in for most use-cases.
Use default value as defined in the cloud foundry [receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/cloudfoundryreceiver#configuration).
=> Add default shard ID for Tanzu Tile configuration

Makefile, tests/Makefile, tests/general/configsources/testdata/vault_config.yaml, tests/general/configsources/vault_test.go, tests/testutils/collector_container.go, tests/testutils/collector_container_integration_test.go, tests/testutils/collector_container_test.go, tests/testutils/collector_process.go, tests/testutils/collector_process_integration_test.go, tests/testutils/collector_process_test.go, tests/testutils/container_test.go, tests/testutils/kubeutils/kind_cluster_integration_test.go, tests/testutils/testcase.go
These tests add a new `testutilsintegration` build tag for integration-vet and relocate* the collector container image helpers to the collector container package.
Also updating the vault integration test to use a new `CollectorImageIsSet()` helper and fix subprocess target validation in preparation of https://github.com/signalfx/splunk-otel-collector/pull/2893.
=> minor integration test helper improvements

.golangci.yml, docs/components.md, internal/components/components.go, internal/exporter/pulsarexporter/README.md, internal/exporter/pulsarexporter/doc.go, internal/exporter/pulsarexporter/factory.go
This PR updates the component status of the pulsar exporter we host in this repository as deprecated in favor of using the upstream pulsar exporter.
=> Mark our internal pulsar exporter as deprecated

go.mod, go.sum, pkg/extension/smartagentextension/go.mod, pkg/extension/smartagentextension/go.sum, pkg/receiver/smartagentreceiver/go.mod, pkg/receiver/smartagentreceiver/go.sum, pkg/signalfx-agent/go.mod, pkg/signalfx-agent/go.sum, tests/go.mod, tests/go.sum
For CVE-2023-25809, CVE-2023-27561, and CVE-2023-28642
=> Bump github.com/opencontainers/runc to v1.1.5

.github/workflows/build-and-test.yml, .github/workflows/darwin-test.yml, .github/workflows/integration-test.yml, Makefile.Common, pkg/signalfx-agent/Makefile
Try to reduce CI failures due to lint timeouts.
=> Increase timeout to 10m for golangci-lint

.github/workflows/tidy-dependabot-pr.yml
Runs `make for-all CMD='make tidy'` and commits/pushes the changes to dependabot branches.
=> Add workflow to tidy dependabot PRs

.github/workflows/cleanup-closed-pr.yml
No longer necessary, and avoid unexpectedly canceling workflows from automated PRs.
=> Remove workflow cleanup for closed PRs

internal/buildscripts/packaging/tests/images/rpm/Dockerfile.centos-9
Workaround for our test failures (e.g. https://github.com/signalfx/splunk-otel-collector/actions/runs/4619591339 and https://github.com/signalfx/splunk-otel-collector/actions/runs/4619591335) until the centos9 image and/or yum repo is updated.
=> Import gpg key for centos9 test image

go.mod, go.sum, pkg/extension/smartagentextension/go.mod, pkg/extension/smartagentextension/go.sum, pkg/receiver/smartagentreceiver/go.mod, pkg/receiver/smartagentreceiver/go.sum, pkg/signalfx-agent/go.mod, pkg/signalfx-agent/go.sum, tests/go.mod, tests/go.sum
For CVE-2023-28840, CVE-2023-28841, CVE-2023-28842
=> Bump github.com/docker/docker to v23.0.3+incompatible

deployments/salt/Dockerfile, internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.debian-bullseye, internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.debian-buster, internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.debian-stretch, internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.ubuntu-bionic, internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.ubuntu-focal, internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.ubuntu-jammy
Saltstack recently updated their apt repos to https and deprecated http.  Fixes salt test failures (e.g. https://github.com/signalfx/splunk-otel-collector/actions/runs/4625524016).
=> Use https apt repos for salt tests

CHANGELOG.md, go.mod, go.sum
This needs to be included in the next release of our distro since we rely on this receiver for the logs collection. It will be released upstream only in 0.76.0
=> Cherry-pick fluentforward receiver performance regression fix

pkg/receiver/smartagentreceiver/log.go, pkg/receiver/smartagentreceiver/log_test.go, pkg/signalfx-agent/pkg/core/config/config.go, pkg/signalfx-agent/pkg/core/config/monitor.go, pkg/signalfx-agent/pkg/monitors/collectd/collectd.go, pkg/signalfx-agent/pkg/monitors/collectd/custom/custom.go, pkg/signalfx-agent/pkg/monitors/collectd/logging.go, pkg/signalfx-agent/pkg/monitors/collectd/monitorcore.go, tests/go.mod, tests/go.sum, tests/receivers/smartagent/collectd-custom/custom_upstat_test.go, tests/receivers/smartagent/collectd-mysql/collectd_mysql_test.go, tests/receivers/smartagent/collectd-mysql/testdata/isolated_config.yaml, tests/receivers/smartagent/collectd-mysql/testdata/not_isolated_config.yaml, tests/receivers/smartagent/collectd-mysql/testdata/resource_metrics/all.yaml
An inherent limitation w/ native collectd monitors is that the [logfile plugin](https://collectd.org/wiki/index.php/Plugin:LogFile)* output is routed to a single logrus instance, which means that all monitors running in a collectd process cannot claim ownership of their respective plugin's messages. This prevents the discovery receiver from working w/ these monitors since its statement evaluator hijacks the core of the underlying receiver's* zap logger: https://github.com/signalfx/splunk-otel-collector/blob/95279eae1b85ce0e0ae17d932ee1c9bd6ac8be15/internal/receiver/discoveryreceiver/statement_evaluator.go#L74
These changes add a new `isolatedCollectd` option that will use the existing collectd/custom logic of starting an isolated subprocess such that the SA receiver's logger identity is …
=> Provide `isolatedCollectd` option for native collectd SA monitors

deployments/ansible/roles/collector/tasks/otel_win_install.yml
This fixes the Ansible task needed to template the OTEL configuration for Windows.  
Like for the Linux part, this should be a `template` task.
https://github.com/signalfx/splunk-otel-collector/blob/00a9165ffaac9665e3d00b94bb8790e82a0164ad/deployments/ansible/roles/collector/tasks/linux_install.yml#L51-L59
=> Ansible fix Windows templating

pkg/signalfx-agent/go.mod
For GHSA-2qjp-425j-52j9, GHSA-259w-8hf6-59c2, and GHSA-hmfx-3pcx-653p
=> Update github.com/containerd/containerd to v1.5.18

pkg/signalfx-agent/Makefile
Our lint action routinely times out, so removing a redundant generate call to help reduce build requirements.
=> Remove generate call from agent lint target

internal/common/discovery/discovery.go, internal/configconverter/discovery.go, internal/configconverter/discovery_test.go, internal/configconverter/dry_run.go, internal/confmapprovider/discovery/README.md, internal/confmapprovider/discovery/discoverer.go, internal/settings/settings.go, internal/settings/settings_test.go, tests/general/discoverymode/docker_observer_discovery_test.go, tests/general/discoverymode/host_observer_discovery_test.go
The initial behavior of discovery mode for receiver and extension suggestions was destructive to existing service config* components. These changes add a new discovery config converter to append the components by way of temporary `service::extensions/splunk.discovery` and `service::receivers/splunk.discovery` intermediaries.
=> add discovery config converter to respect existing service config

.github/workflows/build-and-test.yml, .golangci.yml, Makefile, Makefile.Common, pkg/signalfx-agent/Makefile
The `lint` github job usually takes over 20m and frequently fails due to `golangci-lint` timeouts
- Increase `golangci-lint` timeout to 15m
- Use `-j$(NUM_CORES)` for concurrency
- Add `impi` to `lint` make target
- Remove redundant calls to `checklicense`, `impi`, and `misspell` targets in the job
- Cache `${HOME}/.cache/golangci-lint` in the job to help reduce run time (~25% faster)
=> Update lint target and job

deployments/ansible/contributing/README.md
`https://molecule.readthedocs.io/en/latest/` -> `https://molecule.readthedocs.io/`
=> [chore] Fix dead link

pkg/signalfx-agent/pkg/monitors/sql/monitor.go
The sql monitor is wrapped by a number of other monitors, and their type isn't used in underlying query statements (causing issues w/ logrus->zap agent receiver shim). These changes take the type value from the user config instead of hardcoded "sql".
=> set sql monitor logger type from config

.github/workflows/build-and-test.yml, Makefile
For #3005:
- Add job to run `make generate-metrics` and fail if there are changes
- Update Makefile to run `make fmt` after mdatagen to ensure changes are formatted
- Change the `gofmt` job to run `make fmt` instead of only `gofmt -s -w .`
=> Add generate-metrics job

internal/buildscripts/packaging/tests/deployments/puppet/images/deb/Dockerfile.debian-stretch, internal/buildscripts/packaging/tests/deployments/puppet/images/rpm/Dockerfile.centos-7, internal/buildscripts/packaging/tests/deployments/salt/images/deb/Dockerfile.debian-stretch, internal/buildscripts/packaging/tests/images/deb/Dockerfile.debian-stretch, tests/receivers/smartagent/collectd-spark/testdata/server/Dockerfile
Updating spark image since stretch packages appear to have been pulled from http://deb.debian.org/debian/dists
=> collectd/spark test: use working image

internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-postgresql.discovery.yaml, internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-postgresql.discovery.yaml.tmpl, internal/confmapprovider/discovery/bundle/templatefunctions.go, internal/confmapprovider/discovery/bundle/templatefunctions_test.go
The default auth and service field values for bundled discovery config should be transparent and uniform. These changes add a `{{ defaultValue }}` template function resolving to `"splunk.discovery"` so that the origin of requests is more clear than one-offs would allow.
=> add defaultValue bundle.d helper

internal/receiver/discoveryreceiver/README.md, internal/receiver/discoveryreceiver/evaluator.go, internal/receiver/discoveryreceiver/evaluator_test.go, internal/receiver/discoveryreceiver/metric_evaluator.go, internal/receiver/discoveryreceiver/metric_evaluator_test.go, internal/receiver/discoveryreceiver/receiver.go, internal/receiver/discoveryreceiver/statement_evaluator.go, internal/receiver/discoveryreceiver/statement_evaluator_test.go, tests/general/discoverymode/testdata/k8s-observer-config.d/receivers/smart-agent-redis.discovery.yaml, tests/receivers/discovery/testdata/host_observer_simple_prometheus_config.yaml, tests/receivers/discovery/testdata/resource_logs/host_observer_simple_prometheus_statuses.yaml
In some cases the most helpful information from a logged statement is in its zap fields, which are currently unavailable to the statement evaluator. These changes add all fields not including `name`, `caller`, and `stacktrace` to the matched pattern for regexp and expr match types. Also includes adding an `ExprEnv` object for accessing fields that make invalid identifiers.
These changes are breaking for both regexp and expr. It's my opinion that these are ok to land without transitional guidance as the component is still in development.
regexp: Since the pattern is no longer just the message, `^$` start and end identifiers will likely no longer lead to matches. `message: ` prefixes can reasonably* replace `^`, and `$` will persist where no fields are logged.
expr: The env has been updated …
=> discovery receiver: provide zap fields to regexp and expr

internal/exporter/httpsinkexporter/README.md, internal/exporter/httpsinkexporter/client.go, internal/exporter/httpsinkexporter/factory.go, internal/exporter/httpsinkexporter/httpsink_exporter.go, internal/exporter/httpsinkexporter/httpsink_exporter_test.go, internal/exporter/httpsinkexporter/metrics.go, internal/exporter/httpsinkexporter/options.go, internal/exporter/httpsinkexporter/sink.go
- now supports metrics datatype.
- also supports filtering by name and attributes (metrics only)
- query URL has changed from `/` to `/spans` and `/metrics`
- fixed some other subtle bugs/issues
=> httpsinkexporter: add support for metrics and filtering

.github/workflows/build-and-test.yml
- Dynamically create the matrix for the `test-package` job for supported distros and archs
- Reduce workflow run times and failures due to job timeouts
=> Update matrix for test-package job

pkg/receiver/smartagentreceiver/converter/metrics.go, pkg/receiver/smartagentreceiver/converter/metrics_test.go, tests/receivers/smartagent/collectd-mysql/testdata/resource_metrics/all.yaml
These changes ensure that datapoints with `monitorID` dimension values matching the monitor id in the meta map aren't translated to dp attributes for cardinality concerns.
=> SA receiver: don't use monitorID dimension if matching meta value

internal/confmapprovider/discovery/bundle/cmd/discoverybundler/main.go, internal/receiver/discoveryreceiver/statement_evaluator.go, internal/receiver/discoveryreceiver/statement_evaluator_test.go, tests/general/discoverymode/testdata/k8s-observer-config.d/receivers/smart-agent-redis.discovery.yaml, tests/receivers/discovery/testdata/host_observer_simple_prometheus_config.yaml
These changes improve https://github.com/signalfx/splunk-otel-collector/pull/3004 by using json encoding instead of yaml as multiline and apostrophe containing strings were encoded in unintuitive ways that required odd escaping in discovery rules.
Also adding discovery bundler file paths in render errors for easier debugging.
=> json encode statement maps and more informative bundler errors

internal/receiver/lightprometheusreceiver/config.go, internal/receiver/lightprometheusreceiver/scraper.go, internal/receiver/lightprometheusreceiver/scraper_test.go, internal/receiver/lightprometheusreceiver/testdata/scraper/expected.json, tests/receivers/lightprometheus/testdata/resource_metrics/internal.yaml
Limit resource attributes added by the lightprometheus receiver by default and make them configurable. 
Make enabling/disabling particular attributes possible and disable the following attributes by default:
- net.host.name:
- net.host.port:
- http.scheme:
To enable them back the attributes add the following configuration:
```yaml
resource_attributes:
net.host.name:
enabled: true
net.host.port:
enabled: true
http.scheme:
enabled: true
```
The configuration interface is aligned with receivers created by the mdatagen tool
=> [receiver/lightprometheus] OTL-2117: Limit resource attributes

.github/workflows/build-and-test.yml, .github/workflows/scripts/win-test-services.ps1, .github/workflows/win-installer-script-test.yml, internal/buildscripts/packaging/choco/splunk-otel-collector/tools/chocolateyinstall.ps1, internal/buildscripts/packaging/choco/splunk-otel-collector/tools/common.ps1, internal/buildscripts/packaging/choco/splunk-otel-collector/tools/fluentd.ps1, internal/buildscripts/packaging/installer/install.ps1
For the windows installer script and chocolatey installer:
- Add retries (max of 3) when starting/stopping the collector and fluentd services
- Check the exit code when installing MSI's
- Move service starts to the end, after all components have been installed
- Update failure messages
- Add new workflow to test windows installer script
- Update installation tests
Known issue:
- CI tests may occasionally fail when the installers try to start the collector service with our default configs, e.g. https://github.com/signalfx/splunk-otel-collector/actions/runs/4872776707/jobs/8691911641
```
failed to start service: failed to start extensions: listen tcp 0.0.0.0:55679: bind: An attempt was made to 
access a socket in a way forbidden by its access permissions.; failed to shutdown pipelines: no …
```
=> Improve error handling for windows installers

internal/buildscripts/packaging/tests/requirements.txt
Latest [requests release](https://github.com/psf/requests/releases/tag/v2.30.0) breaks compatibility with the `docker` module.
=> Pin requests<2.30.0 for tests

README.md
We show a warning with a link to upgrade guidelines, but the actual section in the guidelines is missing.
```
2023/05/04 00:49:20 normalize_gcp.go:67: [WARNING] `processors` -> `resourcedetection` -> `detectors` parameter contains a deprecated configuration. Please update the config according to the guideline: https://github.com/signalfx/splunk-otel-collector#from-0680-to-0690.
```
=> [chore] [docs] Add missing upgrade guideline

tests/testutils/README.md, tests/testutils/otlp_receiver_sink.go, tests/testutils/otlp_receiver_sink_test.go, tests/testutils/telemetry/helpers_test.go, tests/testutils/telemetry/logs_test.go, tests/testutils/telemetry/metrics_test.go, tests/testutils/telemetry/pdata_traces.go, tests/testutils/telemetry/pdata_traces_test.go, tests/testutils/telemetry/testdata/traces/expected-traces.yaml, tests/testutils/telemetry/testdata/traces/invalid-resource-traces.yaml, tests/testutils/telemetry/testdata/traces/never-received-instrumentation-scope.yaml, tests/testutils/telemetry/testdata/traces/never-received-resource.yaml, tests/testutils/telemetry/testdata/traces/never-received-spans.yaml, tests/testutils/telemetry/testdata/traces/resource-traces.yaml, tests/testutils/telemetry/traces.go, tests/testutils/telemetry/traces_test.go, tests/zeroconfig/windows/run-tests.ps1, tests/zeroconfig/windows/testdata/Dockerfile.iis.server, tests/zeroconfig/windows/testdata/Dockerfile.pipeline.collector, tests/zeroconfig/windows/testdata/expected_resource_metrics.yaml, tests/zeroconfig/windows/testdata/expected_resource_traces.yaml, tests/zeroconfig/windows/testdata/pipeline-collector.yaml, tests/zeroconfig/windows/windows_iis_test.go
Stop using indirect metrics to validate the Windows IIS zero-config deployment for .NET Framework applications. Now the test checks for the expected spans instead, see [expected spans file](https://github.com/signalfx/splunk-otel-collector/pull/3051/files#diff-721729486953b4987e7865221feabbbcb1ba055349169c999929bc238bc4283b).
This PR adds a `ResourceTraces` to `testutils\telemetry`. This type has a few differences from the other o11y signals (`metrics` and `logs`):
- It doesn't have a "relaxed match" mode: the use of `<ANY>` on the attributes suffices. This can become an issue if spans expected by the tests change frequently; if that happens, adding a relaxed matching for the span attributes can be useful.
- Spans have IDs that should be ignored by integration tests; as such, they were …
=> Switch Windows IIS zero-config test to check for traces instead of metrics

internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-postgresql.discovery.yaml, internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-postgresql.discovery.yaml.tmpl, internal/confmapprovider/discovery/bundle/templatefunctions.go, internal/confmapprovider/discovery/bundle/templatefunctions_test.go, internal/receiver/discoveryreceiver/README.md, internal/receiver/discoveryreceiver/config.go, internal/receiver/discoveryreceiver/statement_evaluator.go, internal/receiver/discoveryreceiver/statement_evaluator_test.go, tests/receivers/smartagent/postgresql/bundled_test.go
These changes provide a new `append_pattern` option for discovery receiver statement evaluation to not require debug logging to see the originating statements and source them in the smartagent/postgres rules, with a couple of corrections that the feature led to.
They also update the default placeholder value to "splunk.discovery.default" to provide a bit more clarity.
=> Discovery receiver and smartagent/postgres rule improvements

.github/workflows/ansible.yml, deployments/ansible/CHANGELOG.md, deployments/ansible/README.md, deployments/ansible/contributing/requirements-dev-linux.txt, deployments/ansible/galaxy.yml, deployments/ansible/molecule/config/docker.yml, deployments/ansible/molecule/custom_vars/verify.yml, deployments/ansible/molecule/default/Dockerfile.j2, deployments/ansible/molecule/shared/verify_tasks.yml, deployments/ansible/roles/collector/handlers/main.yml, deployments/ansible/roles/collector/meta/main.yml, deployments/ansible/roles/collector/tasks/linux_install.yml, deployments/ansible/roles/collector/tasks/linux_install_fluentd.yml, deployments/ansible/roles/collector/tasks/vars.yml
- Skip fluentd installation on Amazon 2023 since the td-agent package currently unavailable
- Update molecule tests and dependencies
- Update test matrix for ansible 6 and 7 (drop 3 and 4)
=> ansible: Support RHEL9 and Amazon 2023

internal/receiver/signalfxgatewayprometheusremotewritereceiver/client_test.go
~~while we investigate why we get issues with ipv6~~
Well [there's the problem](https://github.com/actions/runner-images/issues/668) lol
=> use ipv4 explicitly to fix flakiness 

docs/components.md, go.mod, go.sum, internal/components/components.go, internal/components/components_test.go
Adds support for the upstream forward connector
=> [connector/forward] Add forward connector support

.github/workflows/auto-instrumentation.yml, .github/workflows/build-and-test.yml, .github/workflows/installer-script-test.yml, .github/workflows/integration-test.yml, .github/workflows/vuln-scans.yml
Updates the `tonistiigi/binfmt` image for `docker/setup-qemu-action` from the default (latest, 6.2.0) to 7.0.0 to help with stability and performance for arm64 builds and tests in github workflows.
=> Update qemu to 7.0.0 for github workflows

CHANGELOG.md
Update changelog for v0.77.0 release of the Splunk OpenTelemetry collector.
=> Prepare release v0.77.0

.github/workflows/lint-examples.yml
Run `make lint` for PRs with go-related changes in `examples`.
=> Add workflow to lint examples

deployments/ansible/molecule/config/windows.yml
The windows 2019 and 2022 box versions currently in the test config no longer exist.
=> ansible: Update vagrant box versions

CHANGELOG.md, internal/configconverter/overwrite_properties.go, internal/configconverter/overwrite_properties_test.go, tests/general/set_properties_test.go
These changes will unmarshal `--set` property values as yaml. This is to match the existing core service functionality of converting `--set` flags to yaml, though without the yaml confmap provider directives we don't currently include.
=> evaluate --set property values as yaml

CHANGELOG.md, cmd/otelcol/main.go, internal/configconverter/discovery.go, internal/configconverter/dry_run.go, internal/configconverter/dry_run_test.go, tests/general/discoverymode/configd_test.go
These changes fix a bug where config converter updates aren't propagated to* `--dry-run` content such that the reported config doesn't match that provided to the actual collector service.
~requires https://github.com/signalfx/splunk-otel-collector/pull/3175~
=> Apply config converters to `--dry-run` content.

internal/buildscripts/packaging/tests/images/rpm/Dockerfile.centos-7, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.centos-8, internal/buildscripts/packaging/tests/images/rpm/Dockerfile.centos-9
Try to reduce test timeouts due to slow mirrors.
=> Enable fastestmirror for centos test images

CHANGELOG.md, internal/settings/settings.go, internal/settings/settings_test.go, tests/general/configproviders/env_test.go
These changes add support for* using resolver* uri's for `--config` option values as documented generally by https://github.com/open-telemetry/opentelemetry-collector/tree/main/service#single-config-source
=> support uris as --config args

.github/workflows/build-and-test.yml, .github/workflows/darwin-test.yml, .gitlab-ci.yml, Makefile
- Build, sign, and include the `otelcol_darwin_arm64` and `translatesfx_darwin_arm64` standalone binaries in github releases from the gitlab pipeline
- Add the `macos-11-arm64` self-hosted runner to the `darwin-test` workflow
=> Add binaries-darwin_arm64 make target

tests/receivers/smartagent/telegraf-exec/telegraf_exec_test.go, tests/receivers/smartagent/telegraf-exec/testdata/exec/Dockerfile, tests/receivers/smartagent/telegraf-exec/testdata/exec/config.yaml, tests/receivers/smartagent/telegraf-exec/testdata/exec/telegraf-exec.go, tests/receivers/smartagent/telegraf-exec/testdata/resource_metrics/all.yaml, tests/testutils/collector_container.go, tests/testutils/container.go, tests/testutils/container_test.go
Also allows setting the build context (and build args) for the target collector to make embedding go into the collector image possible.
=> Add smartagent/telegraf-exec integration test

tests/receivers/smartagent/prometheus-exporter/testdata/internal_metrics_config.yaml, tests/receivers/smartagent/prometheus-exporter/testdata/resource_metrics/internal.yaml
Adds extraDimensions in testing the smart agent receiver prometheus-exporter monitor. This is a test change with no change to the functionality offered by the collector, to ensure backwards compatibility.
=> Use extraDimensions in testing

CHANGELOG.md, pkg/receiver/smartagentreceiver/config.go, pkg/receiver/smartagentreceiver/config_test.go, pkg/receiver/smartagentreceiver/testdata/endpoints_config.yaml
Currently the `acceptsEndpoints` value is used to determine if `endpoint`-derived host and port values should be used in monitor configs. This logic is invalid where endpoints are accepted but `host` and `port` don't exist or are of unexpected string values. These changes ensure the field exists before attempting to set them, and also tries port strings since changing the config field type could be a breaking one.
Resolves https://github.com/signalfx/splunk-otel-collector/issues/2264.
=> Prevent setting SA monitor configs with invalid endpoint fields

internal/receiver/discoveryreceiver/statement_evaluator_test.go
Attempting to reduce flake in darwin and windows tests, though I've not been able to reproduce locally.
=> increase statement evaluation log submission timeout

cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, cmd/otelcol/config/collector/gateway_config.yaml, cmd/otelcol/config/collector/otlp_config_linux.yaml, cmd/otelcol/config/collector/upstream_agent_config.yaml, deployments/ansible/molecule/custom_vars/custom_collector_config.yml, deployments/nomad/README.md, deployments/nomad/otel-agent.nomad, deployments/nomad/otel-gateway.nomad, deployments/salt/templates/agent_config.yaml, docs/getting-started/linux-manual.md, examples/nomad/otel-demo.nomad, examples/redis/otel-collector-config.yaml, examples/splunk-hec-traces/otel-collector-config.yml, internal/receiver/discoveryreceiver/README.md, internal/receiver/signalfxgatewayprometheusremotewritereceiver/internal/testdata/otel-collector-config.yaml, internal/settings/settings_test.go, tests/general/default_config_test.go, tests/general/discoverymode/testdata/logging-exporter-internal-prometheus-config.d/exporters/logging.yaml, tests/receivers/discovery/testdata/k8s_observer_smart_agent_redis_config.yaml
The config files in the repo are still using the deprecated `loglevel: debug` for the `logging` exporter. This setting should now be `verbosity: detailed` as per https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/loggingexporter/README.md
=> Replace deprecated logging exporter parameter

deployments/puppet/lib/facter/local_groups.rb, deployments/puppet/lib/facter/local_users.rb, deployments/puppet/lib/facter/win_collector_path.rb
See #3147 - this should help support new versions of Puppet which use versions of Ruby where this deprecated method was removed.
=> Remove use of File.exists?, prefer File.exist? instead

CHANGELOG.md, go.mod, go.sum
Cherry-pick https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23229
Set `pkg.translator.prometheus.NormalizeName` feature gate back to Alpha state since it was enabled prematurely. Metrics coming from Prometheus receiver will not be normalized by default, specifically `_total` suffix will not be removed from metric names. To maintain the current behavior (drop the `_total` suffix), you can enable the feature gate using the `--feature-gates=pkg.translator.prometheus.NormalizeName` command argument. However, note that the translation in the prometheus receiver is a subject to possible future changes.  See [issue #23208](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23208) for more details.
=> Cherry-pick disabling of `pkg.translator.prometheus.NormalizeName` FG

internal/signalfx-agent/pkg/monitors/http/http.go
Adding this monitorID to the logger was missed in https://github.com/signalfx/signalfx-agent/pull/2334
=> http monitor: add missing monitorID logger field

internal/signalfx-agent/pkg/monitors/kubernetes/cluster/metrics/dimensions.go, internal/signalfx-agent/pkg/monitors/kubernetes/cluster/metrics/node.go, internal/signalfx-agent/pkg/monitors/kubernetes/cluster/monitor.go
Adds a configuration to the smartagent/kubernetes-cluster receiver to optional sync node labels as properties on the kubernetes_node dimension.
=> kubernetes-cluster: sync node labels as properties on node name dimension

tests/general/discoverymode/docker_observer_discovery_test.go, tests/general/discoverymode/host_observer_discovery_test.go, tests/general/discoverymode/k8s_observer_discovery_test.go, tests/general/discoverymode/testdata/docker-otlp-exporter-no-internal-prometheus.yaml, tests/general/discoverymode/testdata/host-otlp-exporter-no-internal-prometheus.yaml, tests/general/discoverymode/testdata/k8s-otlp-exporter-no-internal-prometheus.yaml, tests/general/testdata/activemq_config.yaml, tests/general/testdata/solr_config.yaml, tests/receivers/lightprometheus/testdata/resource_metrics/internal.yaml, tests/receivers/prometheus/testdata/resource_metrics/internal.yaml, tests/receivers/redis/redisreceiver_test.go, tests/receivers/redis/testdata/resource_metrics/all_server.yaml, tests/receivers/smartagent/collectd-kafka/testdata/resource_metrics/all_broker.yaml, tests/receivers/smartagent/collectd-postgresql/testdata/resource_metrics/all.yaml, tests/receivers/smartagent/collectd-tomcat/testdata/resource_metrics/default.yaml, tests/receivers/smartagent/telegraf-procstat/testdata/resource_metrics/all.yaml, tests/receivers/smartagent/telegraf-sqlserver/testdata/resource_metrics/all.yaml, tests/testutils/otlp_receiver_sink.go, tests/testutils/telemetry/metrics.go, tests/testutils/telemetry/metrics_test.go
These changes make sure that all emitted metrics have an expected entry in the case's resource metrics in order for `AssertAllMetricsReceived()` to be successful.
=> Update integration tests to detect unexpected metrics

cmd/translatesfx/translatesfx/translate.go, cmd/translatesfx/translatesfx/translate_test.go
A customer referenced an empty file in their SA config and translatesfx panicked because that resulted in a nil being coerced to string.  This change tests the unmarshaled variable for nil before attempting to coerce it to a string.
=> check for nil before coercing to string

.gitlab-ci.yml, .gitlab/update-javaagent.sh
Similar to the other gitlab jobs for automated PR creation:
1. Get the latest release tag from https://github.com/signalfx/splunk-otel-java
2. Update `instrumentation/packaging/java-agent-release.txt` with the tag
3. Create a PR if there are changes and no other PRs are open for the `create-pull-request/update-javaagent` branch
=> Add update-javaagent gitlab job

tests/testutils/telemetry/common.go, tests/testutils/telemetry/common_test.go, tests/testutils/telemetry/logs.go, tests/testutils/telemetry/logs_test.go, tests/testutils/telemetry/metrics.go, tests/testutils/telemetry/metrics_test.go, tests/testutils/telemetry/testdata/logs/resource-logs.yaml, tests/testutils/telemetry/testdata/metrics/resource-metrics.yaml, tests/testutils/telemetry/testdata/traces/resource-traces.yaml, tests/testutils/telemetry/traces.go, tests/testutils/telemetry/traces_test.go
The failure output for integration tests is suboptimal, to say the least. These changes adopt yaml representation to the telemetry helpers to help make* debugging and updating resource telemetry content easier.
=> Add yaml representation to testutils/telemetry

internal/tools/go.sum, tests/README.md, tests/general/container_test.go, tests/general/discoverymode/configd_test.go, tests/general/discoverymode/docker_observer_discovery_test.go, tests/general/discoverymode/host_observer_discovery_test.go, tests/general/discoverymode/k8s_observer_discovery_test.go, tests/receivers/discovery/host_observer_test.go, tests/receivers/discovery/k8s_observer_test.go, tests/receivers/filelog/filelog_test.go, tests/receivers/filelog/testdata/syslog_config.yaml, tests/receivers/lightprometheus/internal_prometheus_test.go, tests/receivers/prometheus/internal_prometheus_test.go, tests/receivers/smartagent/collectd-mysql/bundled_test.go, tests/receivers/smartagent/jmx/jmx_test.go, tests/receivers/smartagent/postgresql/bundled_test.go, tests/receivers/smartagent/prometheus-exporter/prometheus_exporter_test.go, tests/receivers/smartagent/telegraf-procstat/telegraf_procstat_test.go, tests/testutils/collector.go, tests/testutils/collector_container.go, tests/testutils/collector_process.go, tests/testutils/collector_process_test.go
The subprocess target runs have drifted as ci only adopts the container target. These changes align the auto-config loading to match the container builder logic and update tests to be more intuitively skipped or work w/ the subprocess.
=> tests: fix CollectorProcess failures

CHANGELOG.md, cmd/otelcol/config/collector/config.d.linux/extensions/k8s-observer.discovery.yaml, internal/confmapprovider/discovery/README.md, internal/confmapprovider/discovery/bundle/README.md, internal/confmapprovider/discovery/bundle/bundle.d/extensions/k8s-observer.discovery.yaml, internal/confmapprovider/discovery/bundle/bundle.d/extensions/k8s-observer.discovery.yaml.tmpl, internal/confmapprovider/discovery/config.go, internal/confmapprovider/discovery/config_test.go, internal/confmapprovider/discovery/discoverer.go, internal/confmapprovider/discovery/properties/conf_test.go, internal/confmapprovider/discovery/properties/env_var_test.go, internal/confmapprovider/discovery/properties/property.go, internal/confmapprovider/discovery/properties/property_test.go, internal/confmapprovider/discovery/testdata/config.d/extensions/docker-observer.discovery.yaml, tests/general/discoverymode/testdata/docker-observer-config.d/extensions/docker-observer.discovery.yaml, tests/general/discoverymode/testdata/host-observer-config.d/extensions/host-observer.discovery.yaml, tests/general/discoverymode/testdata/k8s-observer-config.d/extensions/k8s-observer.discovery.yaml
These changes embed observer configuration in a `config` mapping like is done with receivers. This will allow the addition of future discovery mode fields (though none planned atm) without interfering with the underlying component config.
=> use parent `config` field in discovery observer configuration and properties

tests/general/configsources/vault_test.go
Hashicorp has stopped publishing new images directly to dockerhub ([deprecation notice](https://hub.docker.com/_/vault)). This PR updates tests to use vault image from [Hashicorp publisher](https://hub.docker.com/r/hashicorp/vault).
=> use hashicorp/vault docker repo for vault images

internal/receiver/discoveryreceiver/receiver.go, internal/receiver/discoveryreceiver/receiver_test.go
Fixes a bug where invalid receiver creator rules lead to partial setup and panic on shutdown.
=> discovery: allow out of order shutdown

cmd/otelcol/config/collector/config.d.linux/receivers/smartagent-collectd-mysql.discovery.yaml, internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-collectd-mysql.discovery.yaml, internal/confmapprovider/discovery/bundle/bundle.d/receivers/smartagent-collectd-mysql.discovery.yaml.tmpl
Similar to https://github.com/signalfx/splunk-otel-collector/pull/3329 these changes don't rely on mysql's default port and expand discovery rules to support more options.
=> expand collectd/mysql discovery rules

CHANGELOG.md, internal/confmapprovider/discovery/README.md, internal/confmapprovider/discovery/config.go, internal/confmapprovider/discovery/discoverer.go, internal/confmapprovider/discovery/provider.go, internal/settings/settings.go, internal/settings/settings_test.go, tests/general/discoverymode/docker_observer_discovery_test.go, tests/general/discoverymode/testdata/docker-observer-config.d/properties.discovery.yaml, tests/general/discoverymode/testdata/docker-observer-properties.yaml, tests/general/discoverymode/testdata/resource_metrics/docker-observer-internal-prometheus.yaml
These changes add a new startup option to take priority over the `<config-dir>/properties.discovery.yaml` file so that multiple collector services can use the same discovery configurations but with different property values.
=> support custom --discovery-properties file

CHANGELOG.md, docs/getting-started/linux-installer.md, internal/buildscripts/packaging/installer/install.sh
These changes add and document a `--discovery` option for the linux install script.
=> add --discovery to install.sh

CHANGELOG.md, cmd/otelcol/config/collector/agent_config.yaml, cmd/otelcol/config/collector/ecs_ec2_config.yaml, cmd/otelcol/config/collector/fargate_config.yaml, cmd/otelcol/config/collector/full_config_linux.yaml, cmd/otelcol/config/collector/gateway_config.yaml, cmd/otelcol/config/collector/upstream_agent_config.yaml, tests/general/default_config_test.go
Split the logs pipeline in the default configuration in a way that profiling data is always sent to Splunk Observability endpoint while other logs can be sent to another hec endpoint configured with `SPLUNK_HEC_URL` and `SPLUNK_HEC_TOKEN` environment variables.
=> Split the logs pipeline in the default configuration

internal/buildscripts/packaging/release/gh-release-notes.sh
I think if we've made it this far we should be ok to release w/ partial notes.
=> don't fail ghr for missing changelog

deployments/cloudfoundry/tile/tile.yml
To allow the Tanzu Tile to work in TAS v3+ environments, the stemcell version must be explicitly set, or it won't run. [Reference for context.](https://docs.vmware.com/en/Tile-Developer-Guide/3.0/tile-dev-guide/tile-generator.html#stemcells-13)
Tested on TAS v2.13, v3.0, and v4.0
=> Set explicit stemcell requirement for Tanzu Tile

internal/receiver/databricksreceiver/factory.go, internal/receiver/databricksreceiver/internal/databricks/raw_client.go, internal/receiver/databricksreceiver/internal/databricks/raw_client_test.go, internal/receiver/databricksreceiver/internal/httpauth/client.go, internal/receiver/databricksreceiver/internal/httpauth/client_test.go, internal/receiver/databricksreceiver/internal/spark/client.go, internal/receiver/databricksreceiver/internal/spark/service.go
A customer with a presumably large Databricks deployment encountered rate limit errors (HTTP 429) while using the Databricks receiver. This change adds retry/backoff logic for when a 429 is encountered.
=> [receiver/databricks] add retry/backoff on http 429s

CHANGELOG.md, internal/confmapprovider/discovery/discoverer.go, tests/general/discoverymode/host_observer_discovery_test.go, tests/general/discoverymode/testdata/host-observer-config.d/extensions/host-observer-with-name.discovery.yaml, tests/general/discoverymode/testdata/host-observer-config.d/receivers/internal-prometheus.discovery.yaml, tests/go.mod, tests/go.sum
These changes fix a bug in discovery mode where multiple observer-discovered receiver instances don't end up using all the applicable observers in the receiver creator `watch_observers` sequence.
=> discovery: add all utilized observers to receiver creator

.github/workflows/integration-test.yml, .github/workflows/linux-package-test.yml, .github/workflows/vuln-scans.yml, .gitlab-ci.yml, internal/signalfx-agent/bundle/scripts/build.sh
- Build and push inline cache images for each agent bundle stage to `quay.io/signalfx/agent-bundle-stage-cache` from gitlab, and use these images as caches for builds
- Allow using previous CI caches (if available) without snowballing
- Reduces agent bundle build time by at least 50% if there is a local cache miss in CI
=> Update caching for agent bundle builds

.github/workflows/ansible.yml, deployments/ansible/CHANGELOG.md, deployments/ansible/galaxy.yml, deployments/ansible/molecule/config/windows.yml, deployments/ansible/molecule/custom_vars/windows-converge.yml, deployments/ansible/molecule/custom_vars/windows-verify.yml, deployments/ansible/molecule/default/windows-verify.yml, deployments/ansible/molecule/shared/verify_registry_key.yml, deployments/ansible/molecule/with_instrumentation/windows-converge.yml, deployments/ansible/molecule/with_instrumentation/windows-verify.yml, deployments/ansible/roles/collector/README.md, deployments/ansible/roles/collector/defaults/main.yml, deployments/ansible/roles/collector/handlers/main.yml, deployments/ansible/roles/collector/tasks/vars.yml, deployments/ansible/roles/collector/tasks/win_install.yml, deployments/ansible/roles/collector/tasks/win_install_dotnet_auto_instrumentation.yml
- Download and install the `signalfx-dotnet-tracing` MSI from https://github.com/signalfx/signalfx-dotnet-tracing/releases, and configure the environment variables in the windows registry. 
- Update tests to verify installation and configuration of env vars
- See the changes in `README.md` for details about the new options.
=> ansible: Add support for dotnet auto instrumentation

.github/workflows/ansible.yml, .github/workflows/chef-test.yml, .github/workflows/puppet-test.yml, .github/workflows/salt-test.yml
No need to run the entire test suite for PRs with only doc changes.
=> Ignore doc-only changes for deployment workflows

CHANGELOG.md, docs/components.md, go.mod, go.sum, internal/components/components.go, internal/components/components_test.go, tests/receivers/lightprometheus/internal_prometheus_test.go, tests/receivers/lightprometheus/testdata/httpd_basic_auth.yaml, tests/receivers/lightprometheus/testdata/resource_metrics/basic_auth_metrics.yaml, tests/receivers/lightprometheus/testdata/server/Dockerfile, tests/receivers/lightprometheus/testdata/server/content/metrics, tests/receivers/lightprometheus/testdata/server/htpasswd, tests/receivers/lightprometheus/testdata/server/httpd.conf
This adds the basicauth extension to our distribution of the collector. This addition is supported by an integration test checking that we can scrape a Prometheus endpoint protected by basic authentication.
=> Add basicauth extension

tests/zeroconfig/windows/testdata/resource_traces/aspnetcore.yaml, tests/zeroconfig/windows/testdata/resource_traces/aspnetfx.yaml
After pulling contrib changes making `host.id` resource attribute optional
=> Fix .NET Zero Config tests

CHANGELOG.md, docs/getting-started/linux-installer.md, docs/getting-started/windows-installer.md, internal/buildscripts/packaging/installer/install.ps1, internal/buildscripts/packaging/installer/install.sh, internal/buildscripts/packaging/tests/installer_test.py
Just for the patch release. This will be applied on 0.82.0
=> Revert OTL-2195: Disable fluentd by default in installer scripts

go.mod, go.sum
Pull https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24670 from contrib, which was merged right after 0.82.0
=> Cherry-pick a fix for resource detection processor

.github/workflows/salt-test.yml, CHANGELOG.md, deployments/salt/README.md, deployments/salt/splunk-otel-collector/fluentd.sls, deployments/salt/splunk-otel-collector/init.sls, internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.amazonlinux-2023, internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.centos-9, internal/buildscripts/packaging/tests/deployments/salt/salt_test.py
- Update tests and workflow
- Include RHEL 9 and Amazon Linux 2023 to supported distros
=> OTL-2195: Fluentd disabled by default for salt

internal/signalfx-agent/bundle/Dockerfile
Disable ipv6 when importing mysql key.  Workaround for agent bundle build failure:
```
gpg: keyserver receive failed: Cannot assign requested address
```
=> Workaround for apt-key failure in agent bundle

go.mod, go.sum
should resolve recent failures (and ones demonstrated in https://github.com/signalfx/splunk-otel-collector/pull/3454)
=> pin testcontainers 0.20.1

.github/ISSUE_TEMPLATE/config.yml
This will redirect users to open support tickets and ideas instead of Github issues.
=> Add a github issue template to send folks to support and splunk ideas

tests/installation/testdata/tree
This change corrects the expected `tree` output that was invalid from local config.d content. These tests aren't hooked into CI yet so failures aren't raised without manual runs.
=> correct installation test tree output

deployments/cloudfoundry/bosh/jobs/splunk-otel-collector/templates/otel-collector-config.yaml.erb
The BOSH release and Tanzu Tile config file for the collector were missing the system detector in the resource detection processor. This meant that metrics coming from Cloud Foundry environments were unable to be filtered based on host. This fix allows metrics to be filtered by host. This is tested and works in TAS v2+.
=> [deployment/cloudfoundry] Add missing system resource detection

internal/signalfx-agent/pkg/monitors/elasticsearch/stats/metadata.yaml
Add a note clarifying the usage of `clusterHealthStatsMasterOnly` when running in failover mode.
=> ElasticSearch monitor configuration note

examples/splunk-hec-traces/docker-compose.yml, examples/splunk-hec-traces/otel-collector-config.yml, examples/splunk-hec-traces/tracing/Dockerfile, examples/splunk-hec-traces/tracing/go.mod, examples/splunk-hec-traces/tracing/go.sum
- Bump `gopkg.in/yaml.v3` to v3.0.1 for CVE-2022-28948
- Bump collector image to 0.83.0
- Use `tls/insecure_skip_verify` in config
- Fix app name
=> Update splunk-hec-traces example

.github/workflows/integration-test.yml, .github/workflows/linux-package-test.yml, .github/workflows/vuln-scans.yml, internal/signalfx-agent/bundle/scripts/build.sh
- Reduce disk usage on github runners when building the agent-bundle by only exporting a new local cache when there are changes to agent-bundle files
- Only download and use registry cache images if the CI cache was not restored
=> Reduce agent-bundle cache in github workflows

.github/workflows/auto-instrumentation.yml, internal/buildscripts/packaging/tests/instrumentation/images/deb/Dockerfile.debian-bullseye, internal/buildscripts/packaging/tests/instrumentation/images/deb/Dockerfile.debian-buster, internal/buildscripts/packaging/tests/instrumentation/images/deb/Dockerfile.debian-stretch, internal/buildscripts/packaging/tests/instrumentation/images/deb/Dockerfile.ubuntu-bionic, internal/buildscripts/packaging/tests/instrumentation/images/deb/Dockerfile.ubuntu-focal, internal/buildscripts/packaging/tests/instrumentation/images/deb/Dockerfile.ubuntu-jammy, internal/buildscripts/packaging/tests/instrumentation/images/deb/Dockerfile.ubuntu-xenial, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.amazonlinux-2, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.amazonlinux-2023, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.centos-7, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.centos-8, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.centos-9, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.opensuse-12, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.opensuse-15, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.oraclelinux-7, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.oraclelinux-8, internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.oraclelinux-9, internal/buildscripts/packaging/tests/instrumentation/instrumentation_test.py, internal/buildscripts/packaging/tests/instrumentation/libsplunk-java-test.conf, internal/buildscripts/packaging/tests/instrumentation/libsplunk-node-test.conf, internal/buildscripts/packaging/tests/instrumentation/setup-express.sh, internal/buildscripts/packaging/tests/instrumentation/systemd-java-test.conf, internal/buildscripts/packaging/tests/instrumentation/systemd-node-test.conf, internal/buildscripts/packaging/tests/instrumentation/systemd-test.conf
- Distro images updated to install node, express, and sample app
- Added test to simulate manual installation of the `splunk-otel-auto-instrumentation` package for both amd64 and arm64:
- Install python3 and development package dependencies required for `splunk-otel-js`:
- suse: devel_basis, devel_C_C++
- amazon/rhel: Development Tools
- debian/ubuntu: build-essential
- Install `splunk-otel-js` with npm
- Test preload and systemd-only instrumentation methods for the sample express app, with default and custom configs
=> Add tests for express instrumentation

examples/signalfxgatewayprometheusremotewritereceiver/go.mod
Give newly created module its fully qualified name.
Necessary for go-multimod to be able to correctly "discard" this module from versioned modules. Needed for third parties who are trying to build their own versions of the collector using these modules.
=> Give module its correct full name
