README.md
examples/README.md

Followup to #64, requires #65 and #57 to be merged beforehand.

Add examples README

---

examples/prometheus-federation/docker-compose.yml
examples/prometheus-federation/otel-collector-config.yml
examples/splunk-hec-metrics/docker-compose.yml
examples/splunk-hec-metrics/otel-collector-config.yml
examples/splunk-hec/docker-compose.yml
examples/splunk-hec/otel-collector-config.yml

Update to latest image
Remove queued_retry processor
Clean up some splunk metadata parameters

Update examples to use official distro

---

.github/no-response.yaml
.github/release-drafter.yaml
.github/stale.yaml

* Enable auto-close of issues with no response from issue author
* Enable auto-close of stale issues
* Enable release notes to be automatically drafted

Add bot configuration

---

cmd/otelcol/main.go

Addresses #97
Also add a helper function to keep main simple.
TODO: Add more tests

Ensure help CLI parameter can be passed

---

README.md
docs/getting-started/linux-installer.md
internal/components/components.go
internal/components/components_test.go

Addresses #100
Also fix broken link

Remove fluentbit extension

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Add CONTRIBUTING documentation

---

cmd/otelcol/config/collector/full_config_linux.yaml
examples/kubernetes-yaml/splunk-otel-collector-agent.yaml
examples/kubernetes-yaml/splunk-otel-collector-gateway.yaml

Also add fully commented config for the field

Update k8s config

---

internal/receiver/smartagentreceiver/output.go
internal/receiver/smartagentreceiver/output_test.go
internal/receiver/smartagentreceiver/receiver_test.go

These changes adopt the dimension to MetadataUpdate converter introduced in https://github.com/signalfx/splunk-otel-collector/pull/120 and send the resulting updates to an applicable metadata exporter if the provided exporter component implements its interface.  This presumes the next consumer is an SFx exporter and will not work w/ intermediary processors.  More robust exporter selection like that in the k8s cluster receiver will be proposed in a subsequent PR.
Also updates a required test case and another to allow `-count` flag (previously tested extension has single usage limit that leads to panic).

Smart Agent: Send dimension updates

---

internal/buildscripts/packaging/fpm/etc/otel/collector/splunk_config_linux.yaml

SFx events and fluent to hec need to be separate pipelines

Update logging config

---

internal/buildscripts/packaging/installer/install.sh

No changes to functionality
- Alphabetize variable declaration and parameter usage
- Use proper name for package

Clean up installer

---

docs/getting-started/linux-installer.md

- Add uninstall information
- Other minor cleanup

Update linux installer README

---

cmd/otelcol/config/collector/agent_config.yaml
cmd/otelcol/config/collector/gateway_config.yaml
cmd/otelcol/config/collector/otlp_config_linux.yaml

Add debug logging option to agent config

---

docs/release.md
internal/buildscripts/packaging/release/helpers/release_args.py

Defaulting to release may have undesired consequences.

Default to test stage for sign_release.py

---

docs/troubleshooting.md

Fix command issue in troubleshooting guide

---

.github/dependabot.yml
Makefile

Add Python dependencies to dependabot

---

CONTRIBUTING.md
README.md
docs/security.md

- Move security issues from CONTRIBUTING.md to security.md
- Move upstream security link to security.md
- Add dependency information to security.md

Update security documentation

---

README.md
cmd/otelcol/config/collector/full_config_linux.yaml
cmd/otelcol/config/collector/otlp_config_linux.yaml

- Update README
- Update config

Add otlphttp information

---

.github/workflows/assign-one-project.yml

Reverts signalfx/splunk-otel-collector#285

Revert "Switch to repo token for action"

---

Makefile

`go test` will also run a build command, which intermittently runs out of memory in CI runs due to the executor container misreporting its cpu count (16 instead of the limited 2).  These changes ensure that we aren't blindly trusting the reported count where the `CIRLCE_JOB` env var is set.  I wasn't able to find a way to get the granted cpu count with limited searching.
Thanks to @jrcamp

Ensure circle test runs use restricted cpu count for test runs

---

docs/getting-started/linux-installer.md
internal/buildscripts/packaging/installer/install.sh
internal/buildscripts/packaging/tests/installer_test.py

- Update doc for fluentd dependencies and uninstall info
- Update uninstall to stop services before removing packages and for `apt-get purge` to remove unmodified managed config files
- Re-enable support-bundle tests

Linux installer updates

---

.circleci/config.yml
docs/release.md
internal/buildscripts/packaging/release/helpers/constants.py
internal/buildscripts/packaging/release/helpers/util.py
internal/buildscripts/packaging/release/sign_release.py

- Update circleci to create a github draft release instead of a pre-release
- Update release script to push the installer scripts to S3 and to publish the github draft release after the assets are signed

Release process updates

---

README.md

Added link about exposed ports to "Getting started"... because its part of getting started...

Update README.md with Exposed Port check as part of "getting started"

---

docs/components.md

Add links to components in core/contrib.

Add links to component READMEs

---

go.mod

Remove what seems to be unsued dependency

---

cmd/otelcol/Dockerfile

Replaced by 4317 so not needed

Remove 55680 port from Docker

---

examples/kubernetes-yaml/splunk-otel-collector-gateway.yaml
internal/receiver/smartagentreceiver/README.md

- open gateway service ports for defined receivers
- add required fields in example exporters

Fix config examples

---

cmd/otelcol/config/collector/agent_config.yaml

Update comments on how to send traces data to a gateway with correlation enabled

Update comments in agent_config.yaml

---

internal/buildscripts/packaging/installer/install.ps1
internal/buildscripts/packaging/installer/install.sh

Don't check for td-agent when installing without fluentd

---

.github/workflows/ansible-push-release-tag.yml
deployments/ansible/galaxy.yml

- add a change to galaxy.yml to trigger the workflow

Fix script in Push Ansible Release Tag github workflow

---

.github/workflows/ansible-push-release-tag.yml
deployments/ansible/galaxy.yml

- Add change to galaxy.yml to trigger the release

Fix "Push Ansible Release Tag" Github workflow

---

deployments/ansible/roles/collector/tasks/linux_install.yml
deployments/ansible/roles/collector/tasks/linux_install_fluentd.yml
deployments/ansible/roles/collector/tasks/main.yml

- Remove redundant import_tasks 
- Fill fully qualified name where missed
- Fix conditions to avoid warning

Cleanup Ansible tasks

---

.github/workflows/ansible-role-test.yml
deployments/ansible/README.md
deployments/ansible/galaxy.yml

Also:
- secure other packages version in the test
- add a small change to collection description to trigger the tests

Test ansible collection on all supported ansible versions

---

.golangci.yml
cmd/otelcol/main_test.go
internal/configsource/envvarconfigsource/configsource.go
internal/configsource/envvarconfigsource/configsource_test.go
internal/configsource/envvarconfigsource/factory.go
internal/configsource/envvarconfigsource/session.go
internal/configsource/envvarconfigsource/session_test.go
internal/configsource/includeconfigsource/configsource.go
internal/configsource/includeconfigsource/session.go
internal/configsource/includeconfigsource/session_test.go
internal/configsource/zookeeperconfigsource/session.go
internal/receiver/smartagentreceiver/converter/event.go
internal/receiver/smartagentreceiver/reflect.go

Fix golangci linters warnings, golint replaced revive, scopelint replaced exportloopref

---

.circleci/config.yml
.golangci.yml
Makefile
cmd/otelcol/main_test.go
internal/configsource/envvarconfigsource/configsource.go
internal/configsource/envvarconfigsource/configsource_test.go
internal/configsource/envvarconfigsource/factory.go
internal/configsource/envvarconfigsource/session.go
internal/configsource/envvarconfigsource/session_test.go
internal/configsource/includeconfigsource/configsource.go
internal/configsource/includeconfigsource/session.go
internal/configsource/includeconfigsource/session_test.go
internal/configsource/zookeeperconfigsource/session.go
internal/receiver/smartagentreceiver/converter/event.go
internal/receiver/smartagentreceiver/reflect.go

Update golangci, remove duplicate checks with golangci

---

deployments/ansible/CHANGELOG.md
deployments/ansible/galaxy.yml

There are some small fixes/improvements to ansible collection that were not released.

Bump ansible collection version with added changelog

---

.gitlab-ci.yml

- Fix regex for quay.io/signalfx/splunk-otel-collector:latest tag/push
- Always tag/push quay.io/signalfx/splunk-otel-collector-dev:latest for main branch
- Prepend $GOPATH/bin to $PATH

Fix gitlab release issues

---

CHANGELOG.md

* Update bundled Smart Agent to v5.11.0.
* Document APM infra correlation.
* Alpha translatesfx feature additions.

Release v0.28.1

---

README.md
cmd/otelcol/config/collector/upstream_agent_config.yaml
docs/security.md

- Add config sources
- Add Smart Agent
- Add upstream configuration

Add more documentation to readme

---

Makefile

Upgrade tools version in Makefile

---

internal/receiver/smartagentreceiver/output.go

Avoid passing pointers to the interfaces and return them

---

internal/receiver/smartagentreceiver/converter/event_test.go
internal/receiver/smartagentreceiver/converter/metrics.go
internal/receiver/smartagentreceiver/converter/metrics_test.go
internal/receiver/smartagentreceiver/converter/traces.go
internal/receiver/smartagentreceiver/converter/traces_test.go
internal/receiver/smartagentreceiver/converter/translator.go
internal/receiver/smartagentreceiver/converter/translator_test.go
internal/receiver/smartagentreceiver/output.go

Change converter to translator, preparation to extract module

---

cmd/translatesfx/translatesfx/otel.go
cmd/translatesfx/translatesfx/otel_test.go

This change puts any Smart Agent `metricsToExclude` filters that have the `negated` flag set to true in a filter processor `include` block (otherwise they go into an `exclude` block).
For example
```
metricsToExclude:
- metricNames:
- vsphere.cpu_usage_percent
- vsphere.mem_usage_percent
negated: true
- metricNames:
- vsphere.*usage*
```
gets translated to
```
processors:
filter:
metrics:
exclude:
expressions:
- MetricName matches "^vsphere\\..*usage.*$"
match_type: expr
include:
expressions:
- MetricName matches "^vsphere\\.cpu_usage_percent$" or MetricName matches
"^vsphere\\.mem_usage_percent$"
match_type: expr
```

translatesfx: translate SA filter negation

---

internal/buildscripts/packaging/release/helpers/util.py

API service was recently changed to be case-sensitive.

Update signing service api url

---

internal/buildscripts/packaging/installer/install.sh

Update linux installer script to install libcap

---

deployments/puppet/manifests/init.pp
deployments/puppet/metadata.json

Update puppet to install libcap

---

deployments/ansible/galaxy.yml
deployments/ansible/roles/collector/tasks/yum_install_otel_collector.yml

Update ansible to install libcap

---

cmd/otelcol/config/collector/fargate_config.yaml
cmd/otelcol/config/collector/full_config_linux.yaml

Most of these components got migrated to contrib.
Fixes https://github.com/signalfx/splunk-otel-collector/issues/709

Fix several links in full_agent_config.yaml

---

.github/workflows/ansible.yml
deployments/ansible/CHANGELOG.md
deployments/ansible/README.md
deployments/ansible/molecule/config/docker.yml
deployments/ansible/molecule/custom_vars/Dockerfile.j2
deployments/ansible/molecule/custom_vars/converge.yml
deployments/ansible/molecule/custom_vars/verify.yml
deployments/ansible/molecule/default/Dockerfile.j2
deployments/ansible/molecule/default/verify.yml
deployments/ansible/molecule/shared/verify_tasks.yml
deployments/ansible/molecule/without_fluentd/Dockerfile.j2
deployments/ansible/roles/collector/tasks/linux_install.yml
deployments/ansible/roles/collector/tasks/main.yml
deployments/ansible/roles/collector/tasks/zypper_install_otel_collector.yml
deployments/ansible/roles/collector/templates/collector-zypper.repo.j2

Also updated molecule tests for custom opensuse images and to skip fluentd tests when running on suse.

Add suse support to ansible (collector only)

---

cmd/translatesfx/translatesfx/otel.go
cmd/translatesfx/translatesfx/otel_test.go
cmd/translatesfx/translatesfx/testdata/otel-e2e-expected.yaml
cmd/translatesfx/translatesfx/testdata/sa-no-trace-correlation.yaml
cmd/translatesfx/translatesfx/translate.go

... unless `sendTraceHostCorrelationMetrics` is false

Add sfx exporter to traces pipeline

---

cmd/otelcol/main.go

Allow the version flag without envvars

---

.github/workflows/lychee-push.yml
.github/workflows/lychee-weekly.yml
docs/getting-started/windows-installer.md
internal/buildscripts/packaging/installer/install.ps1

Allows MSI downloads from custom hosts.

Add MSI URL options to windows installer script

---

.gitlab-ci.yml
internal/buildscripts/packaging/release/helpers/util.py

- Sign the translatesfx exe and darwin binaries
- Include the translatesfx binaries as assets for the github release

Add translatesfx to gitlab pipeline

---

CONTRIBUTING.md

- Provide information on Makefile
- Provide local build information
- Provide information on adding/removing components

Add local development information to contributing.md

---

CHANGELOG.md
cmd/otelcol/config/collector/agent_config.yaml
cmd/otelcol/config/collector/full_config_linux.yaml
cmd/otelcol/config/collector/gateway_config.yaml
cmd/otelcol/config/collector/otlp_config_linux.yaml
cmd/otelcol/config/collector/upstream_agent_config.yaml

Addresses https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5313

Put system detector last so cloud detectors can win

---

docs/troubleshooting.md

This PR fixes a typo in the Troubleshooting.md file.

Fix a typo in troubleshooting.md

---

.github/workflows/installer-script-test.yml
.github/workflows/puppet-test.yml
.github/workflows/windows-test.yml

- Fix backwards triggers for puppet and installer tests.
- Reduce duplicate triggers for the windows-test job.

Update triggers for github actions

---

.gitlab-ci.yml
docs/getting-started/windows-manual.md
internal/buildscripts/packaging/choco/splunk-otel-collector/splunk-otel-collector.nuspec
internal/buildscripts/packaging/choco/splunk-otel-collector/tools/chocolateybeforemodify.ps1

- Build the choco package with the signed msi for main and tags
- Push the choco package for release tags
- Include the choco package as an asset in the github release
- Update metadata and removed unused `chocolateybeforemodify.ps1` per suggestions from chocolatey maintainers
- Update docs

Add choco build/release to gitlab

---

deployments/ansible/roles/collector/README.md
deployments/ansible/roles/collector/defaults/main.yml
deployments/ansible/roles/collector/tasks/config_override.yml
deployments/ansible/roles/collector/tasks/linux_install.yml
deployments/ansible/roles/collector/tasks/otel_win_install.yml

1. Added splunk_config_override variable to add components to the default config.
2. Done changes for both Linux and Windows.
3. Updated Readme.md

[Ansible] Add splunk_config_override variable.

---

.github/workflows/ansible.yml
.github/workflows/puppet.yml

And update the usage according to [breaking changes in v5](https://github.com/actions/github-script#breaking-changes-in-v5)

Upgrade github-script github action

---

docs/getting-started/windows-manual.md
internal/buildscripts/packaging/choco/splunk-otel-collector/splunk-otel-collector.nuspec

Trim description in choco package spec since chocolatey.org limits the description to 4000 chars.

Update description in choco package

---

deployments/puppet/Gemfile.lock

- CVE-2021-27025
- CVE-2021-27023
- CVE-2021-32740

puppet security updates

---

.github/workflows/build-and-test.yml
Makefile
cmd/otelcol/Dockerfile
internal/buildscripts/packaging/collect-libs.sh

`collect-libs.sh` is based on https://github.com/signalfx/signalfx-agent/blob/main/scripts/collect-libs which we use for bundling collectd dependencies in the smart agent.

Add journalctl to docker image

---

README.md

This PR updates links to old docs with fresh ones.

Edit links to old docs

---

instrumentation/Makefile
instrumentation/README.md
instrumentation/src/logger.c
instrumentation/src/logger.h
instrumentation/src/logger_test.c
instrumentation/src/splunk.c
instrumentation/src/splunk.h
instrumentation/src/test_main.c
instrumentation/src/test_main.h

Going to use this repo instead of https://github.com/signalfx/linux-autoinstrumentation/ which I will close.
This change has been partially reviewed here:
https://github.com/signalfx/linux-autoinstrumentation/pull/1
before I moved it into this repo.

instrumentation: initial revision of libsplunk.so

---

.github/workflows/build-and-test.yml
internal/buildscripts/packaging/msi/splunk-support-bundle.ps1

Fix support bundle script if fluentd is not installed

---

tests/go.mod
tests/go.sum
tests/testutils/subprocess/integration_test.go

Upgrade to use gopsutil/v3 in tests

---

.gitlab-ci.yml

Remove internal domains from .gitlab-ci.yml

---

deployments/ansible/molecule/custom_vars/converge.yml
deployments/ansible/molecule/custom_vars/verify.yml
deployments/ansible/molecule/default/Dockerfile.j2
deployments/ansible/molecule/default/verify.yml
deployments/ansible/roles/collector/README.md
deployments/ansible/roles/collector/templates/splunk-otel-collector.conf.j2

Fix SPLUNK_TRACE_URL and SPLUNK_HEC_URL env vars

---

docs/getting-started/windows-installer.md

For https://signalfuse.atlassian.net/browse/DOCS-3800

Add manual steps for starting the collector on windows

---

internal/buildscripts/packaging/installer/install.sh

- Fail immediately if distro is not in the supported list from https://github.com/signalfx/splunk-otel-collector/blob/main/docs/getting-started/linux-installer.md 
- Fail immediately if `systemctl` is not found

Add distro and systemctl checks to installer script

---

.github/workflows/build-and-test.yml
tests/go.sum

Missed with the previous changes.

go mod tidy tests

---

.github/workflows/installer-script-test.yml
.github/workflows/puppet-test.yml
.github/workflows/salt-test.yml

Reduce unnecessary CI runs for irrelevant changes.

Add more paths for installer CI tests

---

.github/workflows/build-and-test.yml
.github/workflows/deps-test.yml
.github/workflows/integration-test.yml
.github/workflows/windows-test.yml
.gitlab-ci.yml
CHANGELOG.md
examples/prometheus-federation/prom-counter/Dockerfile
examples/splunk-hec-traces/tracing/Dockerfile
examples/splunk-hec/logging/Dockerfile

https://go.dev/doc/devel/release#go1.18.minor

Upgrade to golang 1.18.1

---

deployments/ansible/CHANGELOG.md
deployments/ansible/galaxy.yml

Ansible release v0.7.0

---

.github/workflows/puppet.yml

Only run puppet release workflow for main branch.

Update puppet release workflow

---

cmd/translatesfx/README.md

Add a link to the migration document as requested.

translatesfx: update readme

---

instrumentation/Makefile
instrumentation/src/args.c
instrumentation/src/args.h
instrumentation/src/config.c
instrumentation/src/config.h
instrumentation/src/metrics_client.c
instrumentation/src/metrics_client.h
instrumentation/src/splunk.c
instrumentation/src/splunk.h
instrumentation/src/test_main.c
instrumentation/src/test_main.h
instrumentation/testdata/instrumentation.conf

This change causes the zero config .so to send a metric to the local collector each time it runs.

zc: add telemetry/metrics

---

deployments/ansible/CHANGELOG.md
deployments/ansible/galaxy.yml

ansible release v0.8.0

---

.github/workflows/build-and-test.yml
.github/workflows/deps-test.yml
.github/workflows/integration-test.yml
.github/workflows/windows-test.yml
.gitlab-ci.yml
examples/prometheus-federation/prom-counter/Dockerfile
examples/splunk-hec-traces/tracing/Dockerfile
examples/splunk-hec/logging/Dockerfile

https://go.dev/doc/devel/release#go1.18.minor

Upgrade Go to 1.18.3

---

.fossa.yml
.gitlab-ci.yml
.whitesource.conf

Migrate oss scan to fossa since whitesource has been retired.

Enable fossa scan in gitlab

---

go.mod
go.sum
tests/go.mod
tests/go.sum
tests/testutils/collector_container.go
tests/testutils/collector_container_test.go
tests/testutils/container.go
tests/testutils/container_test.go
tests/testutils/testcase.go

picking up from https://github.com/signalfx/splunk-otel-collector/pull/1833

Update testcontainers to 0.13.0

---

tests/receivers/smartagent/collectd-hadoop/testdata/server/Dockerfile
tests/receivers/smartagent/collectd-hadoop/testdata/server/config/hadoop-env.sh

Should help with test timeout flake.

use openjdk image for collectd-hadoop test

---

deployments/ansible/CHANGELOG.md
deployments/ansible/roles/collector/README.md
deployments/ansible/roles/collector/tasks/otel_win_install.yml
deployments/ansible/roles/collector/tasks/vars.yml
deployments/ansible/roles/collector/tasks/win_fluentd_install.yml

Ansible: Add proxy configuration for Windows downloads

---

deployments/ansible/galaxy.yml

Bump the version of the Ansible playbook

---

.github/workflows/build-and-test.yml
.gitlab-ci.yml
internal/buildscripts/packaging/release/helpers/util.py

Refactor gitlab pipeline to use the new `.submit-request` template for signing debs and rpms.

Update deb/rpm signing

---

.gitlab-ci.yml

- Cleanup gitlab yaml with anchors/extensions for job trigger configuration
- Add check for the tar.gz signature file

Update gitlab pipeline trigger

---

README.md
internal/buildscripts/packaging/installer/install.sh

For #1876.  Also add link to chef cookbook.

Update recommended installation methods

---

docs/release.md

Added more information for specific steps to clarify.

Update release document

---

docs/release.md
go.mod
go.sum

Relaxing the dep conditional and providing suggested path. Future PR should include some automation adoption.

Update release guide and agent dep

---

deployments/ansible/molecule/custom_vars/converge.yml
deployments/ansible/molecule/custom_vars/verify.yml
deployments/ansible/molecule/default/converge.yml
deployments/ansible/molecule/default/verify.yml
deployments/ansible/roles/collector/README.md
deployments/ansible/roles/collector/defaults/main.yml
deployments/ansible/roles/collector/handlers/main.yml

Support installing with ansible and skipping restart of services

---

.gitlab-ci.yml

supersedes https://github.com/signalfx/splunk-otel-collector/pull/1956

Update windows artifact signing

---

docs/release.md

Added more information around requirements for the release process.

Update release process document

---

go.mod
go.sum

update golang.org/x/net v0.0.0-20220906165146-f3363e06e74c

fix vulnerability reported by trivy

---

tests/testutils/container.go

Add a new test setup method to wait for container is ready based on its health.

Container health check method

---

Makefile
Makefile.Common

Create a common makefile for components to be added.
Use the same approach as taken by otel contrib for the main Makefile to identify sources to avoid touching component code

Component Makefile changes

---

CHANGELOG.md
cmd/otelcol/config/collector/gateway_config.yaml

Resolves https://github.com/signalfx/splunk-otel-collector/issues/2082

Increase number of queue consumers in gateway default configuration

---

internal/configsource/includeconfigsource/README.md

This PR updates to include config source to beta from alpha. (This should have been updated with https://github.com/signalfx/splunk-otel-collector/pull/1972.)

update include config source to beta

---

examples/kubernetes-yaml/splunk-otel-collector-agent.yaml
examples/kubernetes-yaml/splunk-otel-collector-gateway.yaml

fix kubernetes example, set the ballast size in the config file

---

.github/workflows/bosh-release.yml
deployments/cloudfoundry/bosh/.gitignore
deployments/cloudfoundry/bosh/example/deployment.yaml
deployments/cloudfoundry/bosh/jobs/splunk-otel-collector/spec
deployments/cloudfoundry/bosh/jobs/splunk-otel-collector/templates/ctl.erb
deployments/cloudfoundry/bosh/jobs/splunk-otel-collector/templates/splunk-otel-collector.conf.erb

This adds support for setting proxy servers values as environment variables.

add support for proxy as part of bosh deployment

---

Makefile
tests/endtoend/authscope_test.go
tests/general/discoverymode/host_observer_discovery_test.go

+Change property name to reflect generalization

Change type of sendEvents in endtoend test from *testing.T to testing.TB

---

.github/workflows/build-and-test.yml
internal/buildscripts/packaging/choco/make.ps1
internal/buildscripts/packaging/msi/make.ps1

Determine latest version available using the github api to pull the latest release made.

use latest release info as exposed by github api

---

examples/otel-logs-with-sourcetypes-splunk/otel-collector-config.yml

Partial revert #2011.  Returns state to #2053.

Fix different sourcetype examples.  

---

CHANGELOG.md

This PR adds the release notes for v0.68.0. Feel free to add comments or provide feedback. Thanks!

Update CHANGELOG.md for v0.68.0 release

---

examples/log-enrichment/docker-compose.yml
examples/otel-logs-internal-monitoring/docker-compose.yml
examples/otel-logs-processor-splunk/docker-compose.yml
examples/otel-logs-routing/docker-compose.yml
examples/otel-logs-sanitization-splunk/docker-compose.yml
examples/otel-logs-severity-splunk/docker-compose.yml
examples/otel-logs-splunk-raw-hec/docker-compose.yml
examples/otel-logs-splunk/docker-compose.yml
examples/otel-logs-with-sourcetypes-splunk/docker-compose.yml
examples/prometheus-federation/docker-compose.yml
examples/splunk-hec-metrics/docker-compose.yml
examples/splunk-hec-prometheus/docker-compose.yml
examples/splunk-hec-traces/docker-compose.yml
examples/splunk-hec/docker-compose.yml
examples/tomcat-mysql/docker-compose.yml

Updated the docker-compose.yaml files to wait for splunk to become healthy by using the depends_on condition that works off the splunk containers healthcheck

updated docker compose dependencies

---

pkg/receiver/smartagent/README.md

Updated some stale links in this document. Also, made the language a bit more in line with ELI5 (explain like I'm five), which I happen to like for technical documentation. Would like to do more of these, but if folks don't like this style, please feel free to revise, extend, or revert!

update sa receiver readme

---

README.md

The current note has a typo and is a little vague.

doc: clarify upstream contrib config requirements

---

deployments/ansible/CHANGELOG.md
deployments/ansible/galaxy.yml
deployments/ansible/molecule/custom_vars/converge.yml
deployments/ansible/molecule/custom_vars/verify.yml
deployments/ansible/molecule/custom_vars/windows-converge.yml
deployments/ansible/molecule/custom_vars/windows-verify.yml
deployments/ansible/roles/collector/README.md
deployments/ansible/roles/collector/defaults/main.yml
deployments/ansible/roles/collector/tasks/otel_win_reg.yml
deployments/ansible/roles/collector/templates/splunk-otel-collector.conf.j2

https://signalfuse.atlassian.net/browse/OTL-1390

ansible: Add option to allow additional env vars

---

.github/workflows/chef-test.yml
deployments/chef/CHANGELOG.md
deployments/chef/README.md
deployments/chef/attributes/default.rb
deployments/chef/kitchen.windows.yml
deployments/chef/kitchen.yml
deployments/chef/metadata.rb
deployments/chef/recipes/collector_win_registry.rb
deployments/chef/templates/splunk-otel-collector.conf.erb
deployments/chef/test/integration/custom_vars/serverspec/custom_vars_spec.rb
deployments/chef/test/integration/custom_vars/serverspec/spec_helper.rb
deployments/chef/test/windows/Dockerfile.windows-2019
deployments/chef/test/windows/Dockerfile.windows-2022

For https://signalfuse.atlassian.net/browse/OTL-1390

chef: Add option to allow additional env vars

---

.github/workflows/salt-test.yml
deployments/salt/README.md
deployments/salt/splunk-otel-collector/collector_config.sls
internal/buildscripts/packaging/tests/deployments/salt/salt_test.py

For https://signalfuse.atlassian.net/browse/OTL-1390

salt: Add option to allow additional env vars

---

tests/receivers/smartagent/collectd-nginx/testdata/resource_metrics/all.yaml

Show that we are sending specific attributes when using the smart agent receiver.

Add an attribute value check

---

.gitlab-ci.yml
Makefile
internal/buildscripts/packaging/msi/build.sh
internal/buildscripts/packaging/msi/msi-builder/Dockerfile
internal/buildscripts/packaging/msi/msi-builder/make-aliases.sh

Follow up to https://github.com/signalfx/splunk-otel-collector/pull/2603#discussion_r1116319813

Update msi-builder dockerfile

---

docs/getting-started/linux-installer.md

For https://signalfuse.atlassian.net/browse/OTL-1390

Update linux installer doc for custom env vars

---

tests/testutils/container.go

Return err on error

---

.github/dependabot.yml
pkg/signalfx-agent/bundle/scripts/requirements.txt
pkg/signalfx-agent/bundle/scripts/windows/bundle.ps1
pkg/signalfx-agent/bundle/scripts/windows/requirements.txt

- Consolidate linux and windows requirements.txt
- Revert #2694 since installation fails on windows

Update bundle pip requirements

---

.github/workflows/build-and-test.yml
.gitlab-ci.yml

Update path to requirements.txt for windows bundle pip cache

---

docs/getting-started/linux-installer.md
internal/buildscripts/packaging/installer/install.sh
internal/buildscripts/packaging/tests/installer_test.py

For https://signalfuse.atlassian.net/browse/OTL-1886

Add java zc options to linux installer script

---

deployments/ansible/CHANGELOG.md
deployments/ansible/galaxy.yml
deployments/ansible/molecule/with_instrumentation/converge.yml
deployments/ansible/molecule/with_instrumentation/verify.yml
deployments/ansible/roles/collector/README.md
deployments/ansible/roles/collector/defaults/main.yml
deployments/ansible/roles/collector/templates/splunk-otel-auto-instrumentation.conf.j2

For https://signalfuse.atlassian.net/browse/OTL-1886

Add java zc options to ansible

---

deployments/chef/CHANGELOG.md
deployments/chef/README.md
deployments/chef/attributes/default.rb
deployments/chef/kitchen.yml
deployments/chef/metadata.rb
deployments/chef/templates/instrumentation.conf.erb
deployments/chef/test/integration/with_instrumentation/serverspec/with_instrumentation_spec.rb

For https://signalfuse.atlassian.net/browse/OTL-1886

Add java zc options to chef

---

internal/buildscripts/packaging/installer/install.sh
internal/buildscripts/packaging/tests/installer_test.py

For SWAT-5713
- Delete the default `splunk-otel-collector` user/group if using a custom service owner.
- Ensure the parent directory for the bundle (`/usr/lib/splunk-otel-collector/agent-bundle`) and config (`/etc/otel/collector`) directories are owned by the service owner.

installer script: Custom service owner updates

---

internal/tools/go.mod
internal/tools/go.sum

Bump github.com/gorilla/websocket to v1.4.1

---

go.mod
go.sum
pkg/extension/smartagentextension/go.mod
pkg/extension/smartagentextension/go.sum
pkg/receiver/smartagentreceiver/go.mod
pkg/receiver/smartagentreceiver/go.sum
pkg/signalfx-agent/go.mod
pkg/signalfx-agent/go.sum
pkg/signalfx-agent/pkg/core/config/config.go

This PR removes the gopkg.in/fatih/set.v0 library in favor of a switch statement.

remove set library

---

.github/workflows/build-and-test.yml

Fix job failures, e.g. https://github.com/signalfx/splunk-otel-collector/actions/runs/4669425310

Checkout code for windows-zeroconfig-sources

---

deployments/ansible/CHANGELOG.md
deployments/ansible/galaxy.yml

For https://github.com/signalfx/splunk-otel-collector/pull/2960

Bump ansible role to 0.17.0 for release

---

internal/confmapprovider/discovery/discoverer.go
tests/general/discoverymode/docker_observer_discovery_test.go
tests/general/discoverymode/host_observer_discovery_test.go
tests/general/discoverymode/k8s_observer_discovery_test.go

These changes add the observer provided endpoint ids to discovery status logs. Also including a minor discovery mode observer creation setting change* to make sure the ID is set where the host observer expects* it.

Log endpoint id w/ discovery status

---

internal/buildscripts/packaging/installer/install.ps1

Edited exception messages for style and clarity.

Update exception messages in install.ps1

---

pkg/signalfx-agent/bundle/Dockerfile
pkg/signalfx-agent/bundle/collectd-plugins.yaml
pkg/signalfx-agent/bundle/scripts/windows/bundle.ps1

For CVE-2023-24329.
Also, run dockerfile commands quietly to reduce noisy console output.

Update bundled python to 3.11.3

---

.gitlab-ci.yml

Updates the gitlab pipeline to sign and release the windows powershell installer script.

Sign windows installer script

---

go.mod
go.sum
internal/signalfx-agent/go.mod
internal/signalfx-agent/go.sum
pkg/extension/smartagentextension/go.mod
pkg/extension/smartagentextension/go.sum
pkg/receiver/smartagentreceiver/go.mod
pkg/receiver/smartagentreceiver/go.sum
tests/go.mod
tests/go.sum

Update github.com/docker/distribution to v2.8.2

---

internal/signalfx-agent/pkg/monitors/elasticsearch/query/metadata.yaml

Update ES query monitor metadata.yaml

---

.github/workflows/build-and-test.yml
internal/signalfx-agent/pkg/core/writer/splunk/splunk.go

Also adds pipefail to avoid false negatives: https://github.com/signalfx/splunk-otel-collector/actions/runs/5247407672/jobs/9477595540#step:4:2289

Update signalfx-go in used in agent generate call

---

internal/receiver/signalfxgatewayprometheusremotewritereceiver/mock_reporter_test.go
internal/receiver/signalfxgatewayprometheusremotewritereceiver/prometheus_to_otel.go
internal/receiver/signalfxgatewayprometheusremotewritereceiver/prometheus_to_otel_test.go
internal/receiver/signalfxgatewayprometheusremotewritereceiver/receiver.go
internal/receiver/signalfxgatewayprometheusremotewritereceiver/server_test.go

Thanks @rmfitzpatrick for the catch, going to see if this fixes it.
Still would love to know why this doesn't reproduce for me locally....

Use pointers to atomic ints instead of atomic ints

---

cmd/otelcol/config/collector/upstream_agent_config.yaml

As discussed, this PR adds some comments to the upstream configuration example.

Add comments to upstream config example

---

cmd/otelcol/config/collector/full_config_linux.yaml

Remove fluentbit extension from config yaml

---

internal/receiver/signalfxgatewayprometheusremotewritereceiver/receiver_test.go

Fixes the flaky test TestSuccessfulSend:
```
--- FAIL: TestSuccessfulSend (0.05s)
receiver_test.go:133: 
Error Trace:	/home/runner/work/splunk-otel-collector/splunk-otel-collector/internal/receiver/signalfxgatewayprometheusremotewritereceiver/receiver_test.go:133
Error:      	"0" is not greater than or equal to "4"
Test:       	TestSuccessfulSend
```

make sure we wait until the events are reported by the reporter before asserting on metrics received

---

internal/receiver/discoveryreceiver/statement_evaluator_test.go

See TestStatementEvaluation/expr/append_true/successful/debug/FirstOnly:false
Reference test run failing: https://github.com/signalfx/splunk-otel-collector/actions/runs/5523091905/jobs/10078279319?pr=3330

fix test failing on slower runners: 

---

cmd/otelcol/config/collector/agent_config.yaml

Updating links to documentation

Update links in agent_config.yaml

---

.github/workflows/build-and-test.yml
.github/workflows/darwin-test.yml
.github/workflows/gendependabot.yml
.github/workflows/integration-test.yml
.github/workflows/lint-examples.yml
.github/workflows/linux-package-test.yml
.github/workflows/vuln-scans.yml
.github/workflows/win-package-test.yml
.github/workflows/windows-test.yml
.gitlab-ci.yml

https://go.dev/doc/devel/release#go1.20.6

Upgrade go to 1.20.6

---

CHANGELOG.md
docs/getting-started/linux-installer.md
docs/getting-started/windows-installer.md
internal/buildscripts/packaging/installer/install.ps1
internal/buildscripts/packaging/installer/install.sh
internal/buildscripts/packaging/tests/installer_test.py

This reverts commit f6dc932544b394f09635685afb57d66ec0069d1a.

Revert "Revert "OTL-2195: Disable fluentd by default in installer scripts (#3369)" (#3420)"

---

deployments/chef/metadata.rb

Bump chef release version to 0.6.0

---

go.mod
go.sum
internal/signalfx-agent/go.mod
internal/signalfx-agent/go.sum
pkg/extension/smartagentextension/go.mod
pkg/extension/smartagentextension/go.sum
pkg/receiver/smartagentreceiver/go.mod
pkg/receiver/smartagentreceiver/go.sum

Bump github.com/hashicorp/vault to v1.14.1

---

README.md

Document SPLUNK_LISTEN_INTERFACE in README

---

internal/signalfx-agent/bundle/scripts/security-requirements.txt
internal/signalfx-agent/bundle/scripts/windows/bundle.ps1

Update requests>=2.31.0 for agent bundle

---

internal/signalfx-agent/bundle/Dockerfile
internal/signalfx-agent/bundle/scripts/build.sh

- Update agent bundle dockerfile to help reduce cache misses
- Don't use cache when building/pushing stage cache images to avoid missing dependency updates

Update agent bundle stage caching

---

.github/workflows/chef-test.yml
.github/workflows/installer-script-test.yml
.github/workflows/linux-package-test.yml
.github/workflows/puppet-test.yml
.github/workflows/salt-test.yml

- Re-run flaky pytest tests
- Bump python to 3.11 for pytest
- Update workflow triggers

Update package and installer test workflows

---

internal/signalfx-agent/pkg/apm/go.sum

Update OpenTelemetry Dependencies to latest

Update OpenTelemetry Dependencies to latest

---

.github/workflows/installer-script-test.yml
.github/workflows/linux-package-test.yml
.github/workflows/puppet-test.yml
.github/workflows/salt-test.yml

Update workflows to not fail if pytest rerun was successful

---

CHANGELOG.md

In preparation of the 0.84.0 release, we are updating the changelog with notes from upstream and our own changes.

Changelog for 0.84.0

---

cmd/otelcol/Dockerfile.windows

Update Bundled OpenJDK to latest

Update Bundled OpenJDK to latest

---

.github/workflows/build-and-test.yml
Makefile
Makefile.Common
examples/prometheus-federation/prom-counter/go.mod
examples/signalfxgatewayprometheusremotewritereceiver/go.mod
examples/splunk-hec-traces/tracing/go.mod
examples/splunk-hec/logging/go.mod
go.mod
internal/buildscripts/update-deps
internal/signalfx-agent/Makefile
internal/signalfx-agent/go.mod
internal/signalfx-agent/pkg/apm/go.mod
internal/tools/go.mod
pkg/extension/smartagentextension/go.mod
pkg/processor/timestampprocessor/go.mod
pkg/receiver/smartagentreceiver/go.mod
tests/go.mod
tests/tools/go.mod

- Update `tidy` commands
- Add `tidy` github job

Bump go modules to 1.20

---

docs/components.md
go.mod
go.sum
internal/components/components.go
internal/components/components_test.go

**Description:** Adopt Wavefront receiver into Splunk distro
**Link to Splunk idea:** 

Adopt Wavefront receiver into Splunk distro

---

examples/one-histogram/README.md
examples/one-histogram/content/metrics
examples/one-histogram/docker-compose.yml
examples/one-histogram/otel-collector-config.yml
examples/traces-with-telemetrygen/README.md
examples/traces-with-telemetrygen/docker-compose.yml
examples/traces-with-telemetrygen/otel-collector-config.yml

Add 2 new examples to show how histograms are represented as metrics, and how to use telemetrygen to export traces.

New examples

---

.gitlab-ci.yml

Add retries for signing jobs

---

cmd/otelcol/config/collector/full_config_linux.yaml

**Description:** Added section for scripted_inputs into linux config

feat: add scripted_inputs into config

---

deployments/cloudfoundry/tile/tile.yml

Cloud Foundry has the concept of users and clients. Documentation had incorrectly been using the word `user` when it should have been `client`.
**Link to Splunk idea:** 

Update Tanzu Tile variable descriptions

---

deployments/ansible/CHANGELOG.md
deployments/ansible/galaxy.yml

ansible: Release v0.22.0

---

internal/signalfx-agent/bundle/scripts/security-requirements.txt

Update bundled urllib3 to 1.26.17

---

docs/components.md
go.mod
go.sum
internal/components/components.go
internal/components/components_test.go

Required for https://github.com/signalfx/splunk-otel-collector/pull/3709

include debug exporter

---

deployments/cloudfoundry/tile/DEVELOPMENT.md

This is just more documentation for resolving possible errors hit by users.

[Tanzu Tile] Add another debugging tip for Tanzu Tile errors

---

cmd/otelcol/config/collector/full_config_linux.yaml

**Description:** Add all scripts to pipeline

feat: add all scripts to pipeline

---

internal/receiver/scriptedinputsreceiver/config.go

**Description:** script name should be logged instead of script content

fix: script name should be logged instead of script content

---

CHANGELOG.md
docs/components.md
go.mod
go.sum
internal/components/components.go
internal/components/components_test.go

Adds UDP log receiver. This receiver can receive log data over UDP.

Add UDP log receiver

---

.github/workflows/installer-script-test.yml
internal/buildscripts/packaging/tests/installer_test.py

- Test new options
- Verify new config files
- Verify installation of the splunk-otel-js package

Update installer script tests for new zero config

---

go.mod
go.sum
internal/signalfx-agent/go.mod
internal/signalfx-agent/go.sum
pkg/extension/smartagentextension/go.mod
pkg/extension/smartagentextension/go.sum
pkg/receiver/smartagentreceiver/go.mod
pkg/receiver/smartagentreceiver/go.sum

Update github.com/hashicorp/vault to v1.14.6

---

internal/signalfx-agent/bundle/scripts/security-requirements.txt

Update urllib3 >= 1.26.18

---

instrumentation/packaging/fpm/common.sh

Add execute permissions to the ZC config directory and files

Update perms for ZC config files

---

internal/buildscripts/packaging/tests/helpers/util.py
internal/buildscripts/packaging/tests/instrumentation/instrumentation_test.py

Adding cli confirmation of https://github.com/signalfx/splunk-otel-collector/commit/07c6b85fe2918391711714cb477cd34ae2085fb0

run app as non-root in zc tests

---

tests/receivers/smartagent/collectd-hadoop/testdata/server/Dockerfile

The current version has been removed from the apache cdn.

update collectd/hadoop tested version

---

internal/signalfx-agent/.golangci.yml
internal/tools/go.mod
internal/tools/go.sum

This updates the unparam linter to the latest commit.

update unparam to latest commit

---

go.mod
go.sum

update vault to 1.14.8

---

deployments/chef/kitchen.yml
deployments/chef/recipes/default.rb
deployments/chef/test/integration/custom_vars/inspec/custom_vars_spec.rb

Add testing for debian 12 to the test matrix of our chef recipes.

[chef] add debian 12 testing

---

docs/components.md
go.mod
go.sum
internal/components/components.go
internal/components/components_test.go

Adds vCenter receiver to the Splunk distribution.

add vCenter receiver to the distribution

---

go.mod
go.sum
internal/signalfx-agent/go.mod
internal/signalfx-agent/go.sum
pkg/receiver/smartagentreceiver/go.mod
pkg/receiver/smartagentreceiver/go.sum

Update github.com/dvsekhvalnov/jose2go to v1.6.0

---

.lychee.toml
deployments/ansible/CHANGELOG.md
deployments/ansible/galaxy.yml

ansible release v0.25.0

---

.gitlab-ci.yml

Add flow to sign the docker artifacts during CI

add artifact-ci sign docker

---

.gitlab/update-openjdk.sh

Prevents gitlab job from opening PRs like [this](https://github.com/signalfx/splunk-otel-collector/pull/4195) when the new version does not have linux/windows patch available.

Fix: do not update jdk if no assets found for OS

---

internal/signalfx-agent/bundle/Dockerfile
internal/signalfx-agent/bundle/scripts/collect-libs

Upgrade the bundle image to Ubuntu 22.04.

Upgrade bundle image to Ubuntu 22.04

---

.gitlab-ci.yml
deployments/chef/CHANGELOG.md
deployments/chef/metadata.rb

Fixes to chef-release job and bumps the version for chef to 0.11.0

Chef release v0.11.0

---

.gitlab-ci.yml

Makes signing a separate job in order to make it platform-agnostic

introduce signing job

---

deployments/puppet/CHANGELOG.md
deployments/puppet/metadata.json

Release v0.13.0 for puppet deployment.

Puppet v0.13.0

---

.gitlab-ci.yml

support multiple tags + explicit artifact path

support multiple tags + explicit artifact path

---

deployments/ansible/README.md
deployments/ansible/roles/collector/README.md
docs/getting-started/windows-manual.md

I had to fix an incorrect info and opportunistically fixed a typo and some non-visible issues.
N/A
**Testing:**
N/A
N/A

Docs: fix collector environment location on registry

---

.gitlab-ci.yml

Replace crlf with lf in windows artifacts

crlf to lf in windows build image

---

internal/signalfx-agent/pkg/core/config/filters.go
internal/signalfx-agent/pkg/core/config/monitor.go

Delete unused code and fix a couple typos.

Delete more unused code

---

.gitlab-ci.yml

Move quay login from jobs to template, what fixes windows2022 access issue

inherited quay login

---

internal/signalfx-agent/go.mod

Update runc version for security updates

update pinned runc version

---

tests/general/default_config_test.go
tests/installation/discovery_test.go

[chore] Fix default config integration tests

---

.lychee.toml
CHANGELOG.md

Prepare release v0.93.0

---

CHANGELOG.md
internal/configconverter/discovery.go
internal/configconverter/discovery_test.go
tests/general/discoverymode/docker_observer_discovery_test.go
tests/general/discoverymode/host_observer_discovery_test.go
tests/general/discoverymode/k8s_observer_discovery_test.go

Add a resource attribute to internal metrics to track discovery usage

---

.gitlab-ci.yml

add multiarch manifest to signing list

---

CHANGELOG.md
docs/components.md

Fix spanmetrics processor link to the last tag shipping it

---

CHANGELOG.md

Update CHANGELOG.md for release v0.94.0

Prepare v0.94.0

---

CHANGELOG.md
internal/buildscripts/packaging/msi/splunk-otel-collector.wxs

remove extra quote from msi config

---

.github/workflows/vuln-scans.yml

Add snyk code and docker scanning to the project.

Add snyk scanning with github

---

deployments/puppet/Gemfile.lock

Patch to address CVE-2024-27285

Patch yard dependency to remediate CVE-2024-27285

---

internal/settings/settings.go
internal/settings/settings_test.go
tests/general/default_config_test.go

Reverts signalfx/splunk-otel-collector#4392

Revert "Removed memory balast and setting soft limit "

---

CHANGELOG.md

Update changelog with changes from core and contrib.
**Also, moved the go version update to a breaking change instead of enhancement.**

Update changelog for v0.95.0

---

internal/configconverter/config_server_test.go

Add coverage support for the `simpleRedact` function.

Add a test to check what we choose to redact

---

deployments/cloudfoundry/tile/DEVELOPMENT.md

Added another case for debugging when the Tanzu Tile doesn't work as expected.

[chore][Tanzu Tile] Update debugging docs with another possible error

---

pkg/receiver/smartagentreceiver/dimension_test.go

Remove a test that has been skipped for 3 years.

Remove skipped test

---

tests/receivers/smartagent/collectd-tomcat/testdata/server/Dockerfile

See https://github.com/signalfx/splunk-otel-collector/pull/4411/files

Remove definition of tomcat dockerfile, it was migrated to github action services

---

CHANGELOG.md
cmd/otelcol/config/collector/full_config_linux.yaml
docs/components.md
go.mod
go.sum
internal/components/components.go

Renamed upstream, this will rename in our distro to make sure we keep up to date with dependencies.

Rename http forwarder extension

---

.gitlab-ci.yml

Another attempt to fix the latest manifest creation with the windows multiarch image.

Multiarch manifest latest tag

---

tests/zeroconfig/windows/testdata/resource_traces/aspnetcore.yaml

Fixes a failing test by relaxing the match required.

update dotnet version

---

tests/receivers/smartagent/collectd-kafka/collectd_kafka_test.go
tests/receivers/smartagent/collectd-kafka/testdata/resource_metrics/all_broker.yaml
tests/receivers/smartagent/jmx/jmx_test.go

skip jmxreceivercassandra and fixed Kafka receiver test

---

tests/receivers/smartagent/collectd-kafka/collectd_kafka_test.go

fixed kafka tests

---

.github/workflows/integration-test.yml
docker/mysql/Dockerfile
docker/mysql/init.sql
tests/receivers/mysql/bundled_test.go
tests/receivers/mysql/mysql_test.go
tests/receivers/mysql/testdata/server/Dockerfile
tests/receivers/smartagent/collectd-mysql/collectd_mysql_test.go

Move MySQL to github action services.

move mysql to github action services

---

.gitlab-ci.yml
.gitlab/update-otel-deps.sh

Add a nightly update build to update the otel dependencies to the latest on the main branch.

Add a job to update with nightly dependencies

---

internal/settings/settings.go
internal/settings/settings_test.go

**Description:** Removing ineffective code which used to be used for` memory_ballast`
**Link to Splunk idea:** #4548

remove small remnants of memory_ballast. OTL-2703

---

internal/signalfx-agent/pkg/monitors/cadvisor/converter/converter.go
internal/signalfx-agent/pkg/monitors/http/http.go
internal/signalfx-agent/pkg/monitors/kubernetes/cluster/clusterstate.go
internal/signalfx-agent/pkg/monitors/telegraf/common/accumulator/accumulator_test.go
internal/signalfx-agent/pkg/monitors/vsphere/model/model.go
internal/signalfx-agent/pkg/monitors/vsphere/service/gateway.go
internal/signalfx-agent/pkg/monitors/vsphere/service/metrics.go
internal/signalfx-agent/pkg/monitors/vsphere/service/metrics_test.go

Reported in https://github.com/signalfx/splunk-otel-collector/pull/4571

[chore] Fix linter issues

---

pkg/processor/timestampprocessor/log_processor.go
pkg/processor/timestampprocessor/metric_processor.go
pkg/processor/timestampprocessor/span_processor.go

Fix a few lint issues reported with latest golancilint-run.

Fix a few lint issues

---

CHANGELOG.md

I could've updated it but I don't think doc updates are valuable in the changelog

[chore] Remove broken link from the changelog

---

internal/buildscripts/packaging/msi/SplunkCustomActions/src/SplunkCustomActions.csproj

Mitigation fix to unblock gitlab.

Emergencial fix for MSI custom action build on gitlab

---

.github/dependabot.yml
.github/workflows/scripts/gendependabot.sh
internal/buildscripts/packaging/msi/SplunkCustomActions/src/SplunkCustomActions.csproj

Add dependabot for MSI custom action projects. The package system in this case is NuGet.

Add dependabot check for MSI custom action

---

tests/zeroconfig/windows/testdata/apps/AspNet.WebApi.NetFramework/AspNet.WebApi.NetFramework.csproj
tests/zeroconfig/windows/testdata/apps/AspNet.WebApi.NetFramework/Web.config
tests/zeroconfig/windows/testdata/apps/AspNet.WebApi.NetFramework/packages.config

This takes care of changes that can't be made directly by dependabot. Replaces #4627

Upgrade dependencies via VS

---

tests/receivers/kong/testdata/resource_metrics/kong_metrics.yaml

**Description:** fixing kong tests.
https://github.com/signalfx/splunk-otel-collector/pull/4637/commits
Bumped up version is making integration test failures by dependentbot.

fixing integration test

---

deployments/ansible/CHANGELOG.md

The changelog was not updated in https://github.com/signalfx/splunk-otel-collector/pull/4127

ansible: Update CHANGELOG.md for 0.26.0

---

deployments/chef/CHANGELOG.md
deployments/chef/README.md
deployments/chef/attributes/default.rb
deployments/chef/metadata.rb
deployments/chef/recipes/collector_win_registry.rb
deployments/chef/templates/splunk-otel-collector.conf.erb

**Description:** Removed `memory_ballast`  from chef and introduced GOMEMLIMIT env var

removed memory_ballast

---

deployments/salt/README.md
deployments/salt/splunk-otel-collector/collector_config.sls

**Description:** deprecation of memory_ballast

removed memory_ballast from salt deployment

---

CHANGELOG.md

Add a missing changelog entry related to Kong support.

Fix changelog entry for kong

---

CHANGELOG.md

Changelog updates for release v0.98.0

Changelog for release v0.98.0

---

CHANGELOG.md
go.mod
internal/receiver/discoveryreceiver/correlation.go
internal/receiver/discoveryreceiver/endpoint_tracker.go
internal/receiver/discoveryreceiver/endpoint_tracker_test.go
internal/receiver/discoveryreceiver/package_test.go

Only applicable if log_endpoints: true

[receiver/discovery] Emit active endpoints as entity events periodically

---

internal/buildscripts/packaging/msi/splunk-support-bundle.ps1

The 2 pieces of information being collected help to investigate any problems with MSI uninstall.
See, https://splunk.atlassian.net/browse/SWAT-7073 and https://splunk.atlassian.net/browse/SWAT-7342

Support bundle: collect MSI info on Windows

---

docs/components.md

Missed this in the original PR. Also added brackets to the stability of the `sshcheck` receiver so that it's rendered properly in the markdown.

[chore] Add sqlserver to components.md

---

internal/receiver/discoveryreceiver/endpoint_tracker_test.go

Added in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32540

[chore] [receiver/discovery] Adopt plogtest.IgnoreTimestamp

---

internal/common/discovery/discovery.go
internal/receiver/discoveryreceiver/endpoint_tracker.go
internal/receiver/discoveryreceiver/endpoint_tracker_test.go
tests/receivers/discovery/testdata/resource_logs/host_observer_endpoints.yaml
tests/receivers/discovery/testdata/resource_logs/host_observer_simple_prometheus_statuses.yaml

The entity state events are missing required entity type field which is expected to be "service"

[receiver/discovery] Record entity type

---

.github/dependabot.yml
.github/workflows/auto-instrumentation.yml
.github/workflows/build-and-test.yml
.github/workflows/darwin-test.yml
.github/workflows/gendependabot.yml
.github/workflows/integration-test.yml
.github/workflows/lint-examples.yml
.github/workflows/linux-package-test.yml
.github/workflows/vuln-scans.yml
.github/workflows/win-package-test.yml
.github/workflows/windows-test.yml
.gitlab-ci.yml

For https://pkg.go.dev/vuln/GO-2024-2824 (CVE-2024-24788)

Upgrade golang to 1.21.10

---

.github/workflows/vuln-scans.yml
.snyk

Ignore https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMOPENCONTAINERSRUNCLIBCONTAINER-6672882

Update snyk to ignore runc false positive

---

deployments/cloudfoundry/README.md

This updates the README to match the [Tanzu Tile supported versions.](https://network.pivotal.io/products/splunk-opentelemetry-collector-for-vmware-tanzu#/releases/1485749)

Update Tanzu supported versions

---

go.mod
go.sum

Pulling https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33096

[chore] Bring another fix for the HEC receiver

---

tests/receivers/mongodb/mongodb_discovery_test.go
tests/receivers/mongodb/testdata/docker_observer_with_ssl_mongodb_config.yaml
tests/receivers/mongodb/testdata/docker_observer_without_ssl_mongodb_config.yaml
tests/receivers/mongodb/testdata/docker_observer_without_ssl_with_wrong_authentication_mongodb_config.yaml

**Description:** Using otlp sink to test mongodb discovery integration test.

working integration tests for discovery

---

.gitlab-ci.yml
.gitlab/update-jmx-metrics-gatherer.sh

This adds a periodical job to pick up new releases of the JMX metrics gatherer.

Add jmx metrics gatherer update job

---

internal/signalfx-agent/bundle/scripts/security-requirements.txt

Update requests to 2.32.0

---

CHANGELOG.md

Changelog for the next release v0.101.0.

Prepare CHANGELOG for 0.101.0

---

tests/receivers/jmxreceiver/jmxreceiver_test.go

**Description:** short fix for jmxreceiver integration test.
https://splunk.slack.com/archives/G01L5S7BKLY/p1717022302897519

fixing jmx receiver integration test failures

---

cmd/otelcol/config/collector/config.d.linux/receivers/redis.discovery.yaml
internal/confmapprovider/discovery/bundle/bundle.d/receivers/redis.discovery.yaml
internal/confmapprovider/discovery/bundle/bundle.d/receivers/redis.discovery.yaml.tmpl

Remove duplicate password field from the instructions

[discovery] Update redis discovery instructions

---

CHANGELOG.md

**Description:** Changelogs associated with the latest release .

Added new Changelogs for v0.102.0

---

internal/buildscripts/packaging/tests/deployments/puppet/images/rpm/Dockerfile.centos-8
internal/buildscripts/packaging/tests/deployments/salt/images/rpm/Dockerfile.centos-8
internal/buildscripts/packaging/tests/images/rpm/Dockerfile.centos-8
internal/buildscripts/packaging/tests/instrumentation/images/rpm/Dockerfile.centos-8

Update yum config files for the Centos 8 dockerfiles since it has reached EOS and the yum repos have moved to vault.

Update centos8 dockerfiles for tests

---

CHANGELOG.md

**Description:** update changelog
**Link to Splunk idea:** Updated changelog for a release patch

updating CHANGELOG for patch release

---

internal/buildscripts/packaging/installer/install.sh
internal/buildscripts/packaging/tests/images/deb/Dockerfile.ubuntu-noble
internal/buildscripts/packaging/tests/installer_test.py
internal/buildscripts/packaging/tests/instrumentation/images/deb/Dockerfile.ubuntu-noble

**Description:** added ubuntu-24.04

adding ubuntu 24.04 LTS

---

internal/signalfx-agent/bundle/scripts/requirements.txt
internal/signalfx-agent/bundle/scripts/security-requirements.txt

Bump urllib3 >= 1.26.19

---

CHANGELOG.md

Some existing releases were missing a summary, so this PR adds them. This is a no-op. I can add these summaries to existing release notes as well, if it's helpful.

Add release summaries to existing releases

---

CHANGELOG.md

prepare for v0.104.0

---

CHANGELOG.md

update changelog for v0.104.0

---

tests/receivers/mongodb/mongodb_discovery_test.go

made certain assertions in the mongodb discovery tests to use the correct test state.

[chore]fixed test state for some mongodb assertions

---

.lychee.toml
CHANGELOG.md

prepare for v0.105.0

---

CHANGELOG.md

Update CHANGELOG.md for v0.105.0 patches

---

CHANGELOG.md
internal/signalfx-agent/pkg/monitors/collectd/healthchecker/healthchecker.go
internal/signalfx-agent/pkg/monitors/collectd/healthchecker/metadata.yaml

Deprecate the collectd/health-checker plugin.

Deprecate the collectd/health-checker plugin

---

internal/configconverter/config_server.go
internal/configconverter/config_server_test.go

The test flakiness is due to the release of the port used by the ConfigServer not being deterministic since it happens in a goroutine, not during the calls to OnShutdown.
Made the test reliable by actually checking if the port is available.

Fix config_server_test flakiness

---

.github/workflows/integration-test.yml

Try downgrading to see if this is a degradation of shogo82148/actions-setup-redis@v1.35.0

Downgrade shogo82148/actions-setup-redis to fix CI

---

CHANGELOG.md

This will be a patch release to include the contents of https://github.com/signalfx/splunk-otel-collector/pull/5203.

Update changelog for v0.106.1

---

internal/configsource/includeconfigsource/README.md

This configuration example was confusing for me, as well as other users internally. Added a note to hopefully clarify that the values were meant to be placeholders.

[chore][includeconfigsource] Add docs note for clarity

---

CHANGELOG.md

`make fmt` is complaining about this typo.

[chore][CHANGELOG.md] Fix typo

---

internal/signalfx-agent/bundle/scripts/requirements.txt

This reverts commit 7e8600443de6d0f20e82dbdc770ef189c04068eb.

Revert "Update pyyaml requirement in /internal/signalfx-agent/bundle/scripts (#5180)"

---

internal/receiver/discoveryreceiver/config.go

Fix one of the issues reported in https://github.com/signalfx/splunk-otel-collector/pull/5268

Remove redundant check

---

internal/confmapprovider/discovery/provider.go

[chore] Remove dead code path

---

tests/general/default_config_test.go

Fixes issues seen in [build](https://github.com/signalfx/splunk-otel-collector/actions/runs/11040867278/job/30670375937)
```
Diff:
--- Expected
+++ Actual
@@ -52,3 +52,3 @@
(string) (len=5) "batch": (map[string]interface {}) (len=1) {
-   (string) (len=13) "metadata_keys": ([]string) (len=1) {
+   (string) (len=13) "metadata_keys": ([]interface {}) (len=1) {
(string) (len=10) "X-SF-Token"
Test:       	TestDefaultGatewayConfig/127.2.3.4
```

[chore] getting error for this in integ tests..

---

deployments/cloudfoundry/tile/DEVELOPMENT.md
deployments/cloudfoundry/tile/README.md

Docs only change, add information around Tanzu Tile generator version requirements.

[chore][Tanzu] Add MacOS development information for Tile Generator tool

---

CHANGELOG.md
internal/signalfx-agent/pkg/monitors/jaegergrpc/metadata.yaml
internal/signalfx-agent/pkg/monitors/jaegergrpc/monitor.go

Deprecates the jaegergrpc monitor

deprecate jaegergrpc

---

deployments/cloudfoundry/tile/scripts/README.md

Some information about the `generate_osdf.py` script needed to be added to ensure it can be run successfully.

[chore][Tanzu Tile] Update helper scripts README

---

deployments/cloudfoundry/tile/scripts/generate_osdf.py

The printed message is not an error and the script will still succeed with all necessary information. The log message should make this more clear.

[chore][Tanzu] Clarify warning message from script

---

deployments/cloudfoundry/tile/DEVELOPMENT.md

Update link to be to the README rather than the script itself.

[chore] Update DEVELOPMENT.md

---

.github/workflows/nomad.yml
deployments/nomad/README.md
deployments/nomad/otel-agent.nomad
deployments/nomad/otel-gateway.nomad

Fix the healthcheck endpoint to bind to 0.0.0.0.

Fix nomad tests

---

tests/receivers/scriptedinputs/script_test.go
tests/receivers/scriptedinputs/testdata/resource_logs/cpu.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/df.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/hardware.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/interfaces.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/iostat.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/lastlog.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/lsof.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/netstat.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/openPorts.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/package.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/protocol.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/ps.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/top.yaml
tests/receivers/scriptedinputs/testdata/resource_logs/who.yaml
tests/testutils/otlp_receiver_sink.go
tests/testutils/testcase.go

Remove indirection and just test the log for its contents.

Inline script tests

---

deployments/cloudfoundry/tile/scripts/install_cli_depencies.sh

Add links to the source of each tool being installed for more context

[chore][Tanzu Tile] Add URLs for install_cli_depencies.sh

---

.gitlab-ci.yml
Makefile

Adds a docker build and signature for linux images only.

Add linux fips docker build

---

docker/nginx/Dockerfile

Validating latest NGINX on CI.

Upgrade nginx to 1.27.2

---

.github/workflows/build-and-test.yml
.github/workflows/integration-test.yml

Make sure tests trigger for any changes to the bundle.

run the build when changes occur in packaging

---

.github/workflows/build-and-test.yml
.github/workflows/integration-test.yml
packaging/bundle/Dockerfile

This will update dependencies being pulled in when we build python, resolving vulnerabilities.

update base image of the bundle builder to ubuntu 24.04

---

.github/dependabot.yml
.github/workflows/scripts/gendependabot.sh

[chore] dependabot ignore rule for prometheus v3

---

internal/signalfx-agent/pkg/core/common/docker/containerlist.go
internal/signalfx-agent/pkg/monitors/docker/docker.go
internal/signalfx-agent/pkg/monitors/telegraf/common/accumulator/accumulator.go
internal/signalfx-agent/pkg/monitors/vmem/vmem_linux.go
pkg/extension/smartagentextension/config_windows_test.go

Fixes `redefines-builtin-id` linting issues

[chore] fix linting issue - redefines-builtin-id

---

.github/workflows/ansible.yml

Disable opensuse15 temporarily

disable opensuse15 temporarily

---

go.mod
go.sum
internal/receiver/discoveryreceiver/correlation_test.go
internal/signalfx-agent/go.mod
internal/signalfx-agent/go.sum
pkg/extension/smartagentextension/go.mod
pkg/extension/smartagentextension/go.sum
pkg/processor/timestampprocessor/go.mod
pkg/processor/timestampprocessor/go.sum
pkg/receiver/smartagentreceiver/go.mod
pkg/receiver/smartagentreceiver/go.sum
tests/go.mod
tests/go.sum
tests/testutils/container_test.go

It requires changes in tests to avoid calling `assert.NotSame` on not pointers

[chore] Upgrade github.com/stretchr/testify

---

Makefile

Fix `all-tidy` target. Add `for-all-target` and `all-modules` targets

[chore] Fix make targets

---

.github/workflows/linux-package-test.yml

To close https://github.com/signalfx/splunk-otel-collector/pull/5679

Update crazy-max/ghaction-setup-docker gh action

---

CHANGELOG.md
docs/components.md
go.mod
go.sum
internal/components/components.go
internal/components/components_test.go

Add the `iis` receiver from contrib.

Add the OTel IIS receiver

---

CHANGELOG.md

Changelog changes for release v0.115.0

Update changelog for release v0.115.0 

---

CHANGELOG.md
docs/components.md
go.mod
go.sum
internal/components/components.go
internal/components/components_test.go

This PR replaces https://github.com/signalfx/splunk-otel-collector/pull/5730 due to signature requirements for merges.
cc @greatestusername-splunk

Add sumconnector

---

examples/collectd/README.md
examples/collectd/collectd/Dockerfile
examples/collectd/collectd/http.conf
examples/collectd/collectd/metrics.conf
examples/collectd/docker-compose.yml
examples/collectd/otel-collector-config.yml

Add an example showing how to use the collector with collectd. This example may be moving elsewhere as part of our docs.

Add an example showing how to use the collector with collectd

---

.github/workflows/auto-instrumentation.yml
.github/workflows/build-and-test.yml
.github/workflows/darwin-test.yml
.github/workflows/gendependabot.yml
.github/workflows/integration-test.yml
.github/workflows/lint-examples.yml
.github/workflows/linux-package-test.yml
.github/workflows/otelcol-fips.yml
.github/workflows/splunk-ta-otel.yml
.github/workflows/vuln-scans.yml
.github/workflows/win-package-test.yml
.github/workflows/windows-test.yml
.gitlab-ci.yml
cmd/otelcol/fips/build/Dockerfile.linux
cmd/otelcol/fips/build/Dockerfile.windows

Update the version of Go used for testing and packaging.

Update go version to 1.22.10

---

.github/workflows/win-installer-script-test.yml
.github/workflows/win-package-test.yml
.github/workflows/windows-test.yml
tests/zeroconfig/windows/windows_iis_test.go

Test code, packaging and instrumentation on Windows 2025.

Test on Windows 2025

---

CHANGELOG.md

Add changelog for release v0.117.0

---

packaging/msi/SplunkCustomActions/test/GlobalUsings.cs
packaging/msi/SplunkCustomActions/test/MultiStringEnvironmentTests.cs
packaging/msi/SplunkCustomActions/test/SplunkCustomActionsTests.csproj

Reason: the "fluent" package changed the license terms.

[chore] Refactor MSI code tests to use only Xunit

---

CHANGELOG.md

https://github.com/signalfx/splunk-otel-collector/pull/5886 required for this to be merged

Prepare changelog for 0.119.0 release

---

instrumentation/README.md

Make sure to fix the title to match the name of the feature

Update README.md title

---

CHANGELOG.md

Pull https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38290

[chore] Update 0.120.0 changelog

---

.github/workflows/dotnet-instr-deployer-add-on.yml
packaging/dotnet-instr-deployer-add-on/Makefile
packaging/dotnet-instr-deployer-add-on/README.md
packaging/dotnet-instr-deployer-add-on/assets/windows_x86_64/bin/installer-wrapper.ps1

- Add a workflow for the Splunk OTel .NET Deployer
- Set the .NET Framework LoaderOptimizations to `SingleDomain`'
- Clean environment variables under IIS during uninstall
**Testing:**
~~Pending~~ manual validation done by deploying it using `splunkd`
N/A

Add workflow for the deployer

---

packaging/technical-addon/Makefile
packaging/technical-addon/Splunk_TA_otel/default/app.conf
packaging/technical-addon/packaging-scripts/cicd-tests/happypath-test.sh
packaging/technical-addon/packaging-scripts/release-ta-version.sh

- Mostly changes for the TA release.
- Added a couple improvements to improve a related make action.

Prepare TA release v1.4.1

---

.github/workflows/lychee.yml
.lychee.toml

Pin lychee version to avoid upstream issue: https://github.com/lycheeverse/lychee-action/issues/281

[chore][deps] Pin lychee version to v0.18.1

---

.github/workflows/dotnet-instr-deployer-add-on.yml

CI change to allow testing against different versions of Splunk UF.

[.NET Deployer] Make UF version used in CI customizable

---

tests/zeroconfig/windows/windows_iis_test.go

This test has a flaky failure that occurs intermittently, even on the same commit, when attempting to connect to the target machine. This PR is adding a retry to try to resolve the flakiness.

[chore][TestWindowsIISInstrumentation] Retry connecting to target

---

deployments/databricks/README.md
deployments/databricks/deploy_collector.sh

This adds support for an init script in Databricks environments that will deploy the collector on every node of a cluster.
The added README should provide necessary context and deployment requirements.

[Databricks] Add support for Databricks deployments

---

.gitlab-ci.yml

Caused by https://github.com/signalfx/splunk-otel-collector/pull/5991, validated it's correct syntax in GitLab CI configuration validation

[chore][CI/CD] Add missing quote

---

packaging/bundle/scripts/security-requirements.txt

Upgrading to the latest release of the package.

Upgrade python requests to 2.32.3

---

README.md

This means the header of the README will be:
`Build Status`, `Go Report Card`, `Codecov Status`, `Github Release`

[chore][README] Add coverage badge in README header

---

CHANGELOG.md

Filtered changelogs for upcoming release v0.122.0

Changelog-for-v0.122.0

---

.github/workflows/build-and-test.yml
.github/workflows/darwin-test.yml
Makefile
Makefile.Common
internal/signalfx-agent/Makefile

- Update codecov github action for more information and clarity in test results
- Update make targets to be consistent

[chore][codecov] Clean up make targets

---

.github/workflows/integration-test.yml

Removing ubuntu-20.04 GH runner.

[chore][ci]integration-test: remove ubuntu-20.04 GH runner

---

.github/workflows/otelcol-fips.yml

Removing ubuntu-20.04 GH runner.

[chore][ci]otelcol-fips: remove ubuntu-20.04 GH runner

---

.github/workflows/salt-test.yml
packaging/tests/deployments/salt/images/distro_docker_opts.yaml

Removing ubuntu-20.04 GH runner.

[chore][ci]salt-test: remove ubuntu-20.04 GH runner

---

.github/workflows/ansible.yml

Removing ubuntu-20.04 GH runner.

[chore][ci]ansible: remove ubuntu-20.04 GH runner

---

.github/workflows/linux-package-test.yml
.github/workflows/puppet-test.yml
deployments/ansible/molecule/config/vagrant.yml

Removing leftovers of Amazon Linux 2 in CI

[chore][ci] Removing leftovers of Amazon Linux 2 in CI

---

docker/kong/Dockerfile
tests/receivers/kong/kong_test.go

Bump docker/kong/kong-gateway 3.7.1.1. to 3.10.0.0

---

.codecov.yml

As a result of https://github.com/signalfx/splunk-otel-collector/pull/6146 code coverage is now higher, so we can raise the minimum bar.

[chore][codecov] Update minimum project coverage

---

go.mod
go.sum
internal/signalfx-agent/go.mod
internal/signalfx-agent/go.sum
pkg/receiver/smartagentreceiver/go.mod
pkg/receiver/smartagentreceiver/go.sum

Upgrade github.com/snowflakedb/gosnowflake to v1.13.3 to clean 
- https://github.com/signalfx/splunk-otel-collector/security/code-scanning/51
- https://github.com/signalfx/splunk-otel-collector/security/code-scanning/50
Supersedes https://github.com/signalfx/splunk-otel-collector/pull/6175

[chore][code-scanning] Upgrade github.com/snowflakedb/gosnowflake

---

pkg/receiver/smartagentreceiver/config.go
pkg/receiver/smartagentreceiver/receiver_test.go

broken in https://github.com/signalfx/splunk-otel-collector/pull/6187

[chore] Fix linter

---

CHANGELOG.md
cmd/otelcol/config/collector/config.d.linux/receivers/sqlserver.discovery.yaml
internal/confmapprovider/discovery/bundle/bundle.d/receivers/sqlserver.discovery.yaml
internal/confmapprovider/discovery/bundle/bundle.d/receivers/sqlserver.discovery.yaml.tmpl

This is to match out of the box content.

[discovery] Enable more metrics by default for SQL Server receiver

---

.github/dependabot.yml
.github/workflows/ansible.yml
.github/workflows/auto-instrumentation.yml
.github/workflows/build-and-test.yml
.github/workflows/darwin-test.yml
.github/workflows/dotnet-instr-deployer-add-on.yml
.github/workflows/gendependabot.yml
.github/workflows/integration-test.yml
.github/workflows/lint-examples.yml
.github/workflows/linux-package-test.yml
.github/workflows/otelcol-fips.yml
.github/workflows/splunk-ta-otel.yml
.github/workflows/vuln-scans.yml
.github/workflows/win-package-test.yml
.github/workflows/windows-test.yml
.gitlab-ci.yml
examples/prometheus-federation/prom-counter/go.mod
examples/splunk-hec-traces/tracing/go.mod
examples/splunk-hec/logging/go.mod
go.mod
internal/signalfx-agent/go.mod
internal/tools/go.mod
packaging/dotnet-instr-deployer-add-on/go.mod
pkg/extension/smartagentextension/go.mod
pkg/processor/timestampprocessor/go.mod
pkg/receiver/smartagentreceiver/go.mod
tests/go.mod
tests/tools/go.mod

Upgrade golang to 1.23.10
Replaces #6323

[chore] Upgrade-golang-to-1.23.10

---

go.mod
go.sum
tests/go.mod
tests/go.sum

Supersedes #6321, #6320, and #6317

[chore] Bump expr, vault/api, mysql on main and tests

---

tests/testutils/container.go

Remove nolint from testcontainers upgrade

[chore] Fix nolint due to testcontainers deprecations

---

CHANGELOG.md

We're retagging with the bumped timeout, might as well release these as well.

[chore] More changelog for 129 release

---

deployments/chef/CHANGELOG.md
deployments/chef/README.md
deployments/chef/kitchen.windows.yml
deployments/chef/kitchen.yml
deployments/chef/recipes/collector_win_install.rb
deployments/chef/test/integration/custom_vars/test.rb

Analog to implementation done for Linux via #6290.

[chef][windows] Support option to set service CLI args

---

.github/workflows/integration-test.yml

Adds a docker caching github action to save on build time downloading docker images.

add docker caching

---

.github/workflows/integration-test.yml

Reverts signalfx/splunk-otel-collector#6442

Revert "Remove freeing space from some of the tests"

---

.github/workflows/integration-test.yml

This reverts commit e37b687562a048a9def57148fedfa4d2924f6c7d.

Revert "add docker caching (#6441)"

---

.gitlab-ci.yml

Allowing failures for this test so the other stages can run

[chore] allow test-collectd-ta to fail in gitlab

---

.gitlab-ci.yml

Trying to get a clean run in gitlab for release preparation but orca-test failures are holding up next stages. Temporarily allow failing these.

[chore] allow failures for orca tests

---

.gitlab-ci.yml
packaging/release/create-github-tag.sh

Adds tag creation after release

[chore] Update gitlab ci tags

---

CHANGELOG.md
internal/signalfx-agent/pkg/monitors/collectd/spark/metadata.yaml
internal/signalfx-agent/pkg/monitors/collectd/spark/spark.go

Deprecate the collectd/spark plugin.

Deprecate the collectd/spark plugin

---

README.md

[chore] fix gomemlimit frequency notes

---

packaging/bundle/scripts/get-collectd-plugins.py

[chore] Add retry/backoff to get-collectd-plugins

---

.gitlab-ci.yml

Reverts the image tag to original logic. I added the branch while testing and it got merged in one of my other gitlab-ci prs

[chore] fix image tag for dev builds

---

.gitlab-ci.yml

The change in PR makes choco-release run after github-release

[chore] run choco-release after github-release

---

packaging/technical-addon/Makefile
packaging/technical-addon/Splunk_TA_otel/CHANGELOG.md
packaging/technical-addon/Splunk_TA_otel/default/app.conf
packaging/technical-addon/packaging-scripts/cicd-tests/happypath-test.sh

[chore] Undo TA 1.4.5

---

README.md

Adds a deprecation notice to the README example of fluentd configuration.

[chore][README] Mark fluentd configuration as deprecated

---

packaging/technical-addon/packaging-scripts/cicd-tests/agent-bundle/orca-collectd-test.sh

[chore] fix TA Orca script

---

packaging/technical-addon/packaging-scripts/update-ta-version.sh

[chore] Switch to minor TA version

---

packaging/technical-addon/packaging-scripts/release-ta-version.sh

[chore] Skip Changelog for TA release branch

---

.github/workflows/vuln-scans.yml

To fix errors like https://github.com/signalfx/splunk-otel-collector/actions/runs/16948578104/job/48036379853

[chore] Exclude app scanning from docker scan runs

---

tests/testutils/testcase.go

This helper isn't being used at this time

[chore][testutils] Remove unused test helper

---

Makefile

This variable wasn't used anywhere

[chore][Makefile] Remove unused variable

---

.github/workflows/scripts/prepare-changelog.sh
CONTRIBUTING.md
Makefile

Address @crobert-1's feedback in https://github.com/signalfx/splunk-otel-collector/pull/6628

[chore] Update prepare-changelog make target

---

.chloggen/addawscloudwatchreceiver.yaml
docs/components.md
go.mod
go.sum
internal/components/components.go
internal/components/components_test.go

Adds a new log receiver for AWS CloudWatch.

[collector] add AWS CloudWatch receiver

---

internal/configconverter/config_server_test.go

This change is to ensure the test is not impacted by previous tests or changes on the host machine by waiting until the config server isn't responding. This should help narrow down potential causes of flakiness.

[chore][config server test] Address flakiness

---

.gitlab-ci.yml

wait for s3 upload jobs when applicable before starting the github release

[chore] wait for s3 release jobs

---

internal/receiver/discoveryreceiver/README.md

The readme was pretty outdated

[chore] Update Readme for the discovery receiver
